### ISSUE TITLE
Add div to a container div

### ISSUE THREAD

**Issue by IvoPereira** [limonte/sweetalert2#10]
Hello,

My layout does have a navigation menu and a content area, however sweetalert2 does by default add the alert in the body, not giving me the option to centering it relative to the content area.

Is there a chance you could add something like this?

Thanks

**Comment by limonte** [comment]
I'm not sure how to implement this. Which bahaviour of gray overlay you're expecting - to fill only parent element?

**Comment by IvoPereira** [comment]
That's a good question, and that's another problem I've came up with, and I've not yet solved.

Well, it could be even more flexible and we could be able to specify which element we want the gray overlay to be, as in my case I would like to have the navigation menu overlayed, however it the alert should be centered to the content area.

**Comment by limonte** [comment]
Sorry, but your case is pretty custom. You can fork SA2 and add that functionality to forked version of SA2.

**Comment by IvoPereira** [comment]
Thanks a lot anyway.

By the way, could you tell me how would you pass the extended params variable to the init function?

AFAIK init function is responsible for creating the main div in body, and it will be there that, according the params I would change the destination div, however, as init() is called once the page is loaded, I am not able to pass parameters to it.

What are your suggestions in this case?

Thanks!

**Comment by limonte** [comment]
@IvoPereira take a look at https://github.com/limonte/sweetalert2/commit/e141f58c230d70552886267a01b86ed0033a76ac

There's you can find the simple example of adding new params to SA2 and processing them in `setParameters()` method.

**Comment by IvoPereira** [comment]
I've successfully added some additional params and I am totally able to process them in modalDependant function.

However, as you in see here https://github.com/limonte/sweetalert2/blob/master/lib/sweetalert2.js#L491 - init function appends the sweet wrapper in body, however at this time I don't have the params defined, as they are just defined when swal() function is called in code.

Once document is ready, init function is called, and I am not able to pass any additional params - https://github.com/limonte/sweetalert2/blob/master/lib/sweetalert2.js#L763

**Comment by limonte** [comment]
Yeah, you're right. You will need to refactor plugin to accept parameters before initialization. Not simple task, as I sensed :)

**Comment by IvoPereira** [comment]
Exactly what I tought!

Thanks a lot for your support @limonte!
