### ISSUE TITLE
Modal can't be closed in Internet Explorer 11

### ISSUE THREAD

**Issue by chrisnoden** [limonte/sweetalert2#100]
Open any sweetalert2 modal in IE11 (tested on Windows 10) and you are unable to close it. Buttons, Esc, Enter or click away all fail to work.

**Comment by dylanh724** [comment]
You shouldn't expect too much from IE11 - it's very unsupportive of quite a lot of things. I'm actually surprised SWAL2 or anything dynamic works at all in IE11 ;)

**Comment by limonte** [comment]
Thank you @chrisnoden for reporting this issue!

Fixed in [v1.3.1](https://github.com/limonte/sweetalert2/releases/tag/v1.3.1)
