### ISSUE TITLE
Enter does not confirm modal when buttons are reversed

### ISSUE THREAD

**Issue by fracz** [limonte/sweetalert2#101]
By default, when a sweetalert2 with two buttons (confirm & cancel) is opened, pressing <kbd>Enter</kbd> confirms the action.

However, when you use `reverseButtons: true`, pressing <kbd>Enter</kbd> cancels it.

It should be consistent regardless of order of buttons. It should always confirm the dialog.

**Comment by dylanh724** [comment]
Careful, I opened something similar earlier and it was immediately closed without explanation

**Comment by limonte** [comment]
Thank you @fracz for reporting this issue!

Fixed in [v1.3.1](https://github.com/limonte/sweetalert2/releases/tag/v1.3.1)
