### ISSUE TITLE
icon support for button

### ISSUE THREAD

**Issue by holmes1491** [limonte/sweetalert2#103]
i tried to button with font awesome icon...

please help me 

how to do it 

and not find any param relate to it

**Comment by limonte** [comment]
Thank you @holmes1491 for suggesting this!

Done in [v1.3.2](https://github.com/limonte/sweetalert2/releases/tag/v1.3.2)

Take a look at the "Custom HTML description and buttons" example here https://limonte.github.io/sweetalert2/

**Comment by holmes1491** [comment]
thanks !

**Comment by natsu90** [comment]
how do i do the same for customized icon for the modal?
