### ISSUE TITLE
[bug + fix] Incorrect marginTop calculation on FF

### ISSUE THREAD

**Issue by bozma88** [limonte/sweetalert2#106]
When displaying large popups, they get positioned wrongly in Firefox.
This is caused by `getTopMargin` function returning wrong values.

@see http://stackoverflow.com/questions/9364367/why-does-getpropertyvalue-return-an-empty-string-instead-of-the-elements-style

**FIX:**
Replace
`var padding = parseInt(getComputedStyle(elem).getPropertyValue('padding'), 10);`
With
`var padding = parseInt(getComputedStyle(elem).getPropertyValue('padding-top'), 10);`

**Comment by johanwilfer** [comment]
I can confirm this issue in Firefox and the provided fix. I've applied it both to 0.4.5 and the latest version, but as I ran into the same issue as #111 I can't use version 1 for now.
