### ISSUE TITLE
Spacebar triggering sweetalert submit (latest CDN build)

### ISSUE THREAD

**Issue by rubencodes** [limonte/sweetalert2#108]
When I press the spacebar on an input field in the sweetalert modal, the form seems to submit. You can see a barebones [demo here](https://jsfiddle.net/aLpyn8jp/2/). This makes typing strings with spaces impossible.

(Updated title because a bug on my end led me down the wrong train of thought for a possible cause).

**Comment by Ascariel** [comment]
Any updates for this issue, seems critical

**Comment by limonte** [comment]
Good news everyone!

Swal2 now supports input and select types, you example: https://jsfiddle.net/47L0mf97/2/

Input example: http://limonte.github.io/sweetalert2/#input-field
Select box example: http://limonte.github.io/sweetalert2/#select-box

**Comment by esetnik** [comment]
unfortunately if you use custom html there's no way to disable afaik to disable the spacebar triggering

**Comment by esetnik** [comment]
@rubencodes I just opened #178 to address this behavior as a configurable option

**Comment by limonte** [comment]
@esetnik this issue is related to the modal **with input** (JS `prompt()` alternative). You are trying to disable submitting of JS `alert()` alternative which is different from native `alert()` behaviour.
