### ISSUE TITLE
CustomClass for buttons in Sweet Alert

### ISSUE THREAD

**Issue by NitinMaaraj** [limonte/sweetalert2#11]
Hi very nice alert replacement for old style javascript alerts etc but if we can have customclass for buttons in alerts as we have customClass for alert itself it would be great and may increase flexibility for design tweaks..

Thanks in advance

**Comment by limonte** [comment]
@NitinMaaraj done in v0.2.1

**Comment by NitinMaaraj** [comment]
Thanks ;)
