### ISSUE TITLE
Unable to repeat Confirm when closeOnConfirm: false

### ISSUE THREAD

**Issue by cormip** [limonte/sweetalert2#111]
I have a sweetalert2 with an input field that I wish to validate before performing an AJAX submit. Because of the THEN promise being returned, the Confirm button only works the first time. i.e. If I show the user a validation error and he corrects the input, he cannot Confirm a second time. Nothing happens because the THEN only runs the first time.

Please provide an example of using sweetalert2 using a callback in the Promise to allow repeated Confirms in case of validation fail, AJAX fail, etc.

**Comment by limonte** [comment]
Thank you @cormip for reporting this. I released [v2.0.0](https://github.com/limonte/sweetalert2/releases/tag/v2.0.0) which solves your issue. Take a look on the [AJAX request example](http://limonte.github.io/sweetalert2/#ajax-request), it should help in your case.

**Comment by cormip** [comment]
Awesome job! Thanks.
