### ISSUE TITLE
Tabbing is broken for forms now

### ISSUE THREAD

**Issue by johanwilfer** [limonte/sweetalert2#112]
Functionality merged in v0.3.0 - tabbing support for forms - is broken since v.1.3.1
https://github.com/limonte/sweetalert2/compare/v1.3.0...v1.3.1

Previously that first input was focused, but it isn't now.
Forward tab doesn't cycle through the input elements (but backwards tabs do for some reason).

Restoring the row that sets $modalElements fixes the issue in v1.3.1
```js
var $modalElements = modal.querySelectorAll('button, input:not([type=hidden]), textarea, select');
```

**Comment by limonte** [comment]
Fixed now, please update swal2 to latest.

Thanks @johanwilfer  for submitting this issue and sorry for the delayed response.

**Comment by johanwilfer** [comment]
Thanks @limonte !
