### ISSUE TITLE
sweetalert2.scss any variables?

### ISSUE THREAD

**Issue by huglester** [limonte/sweetalert2#115]
Hello,

I see there is a scss file. I can't seem to find any variables? For example I would like to change default blue color, or green to something different?

Thank you!

**Comment by limonte** [comment]
default color of which element you want to change?

**Comment by huglester** [comment]
Well as for now, if I understand correct, those colors are inherited from Bootstrap, no?
I am using this inside Foundation6.

I would like to change color, of default buttton (blue) for example.

I know I can kae it via customization via params, or so. But wondered, if maybe I could change some defaults.

**Comment by limonte** [comment]
No, it's not a Bootstrap.

To use styling from Foundation6 you can do this:

```js
confirmButtonClass: '<Foundation6 classes>',
buttonsStyling: false,
``

Realted issue: https://github.com/limonte/sweetalert2/issues/59
