### ISSUE TITLE
sweetalert2 not in center inside iframe bootstrap 3 modal

### ISSUE THREAD

**Issue by holmes1491** [limonte/sweetalert2#117]
OK here i am using iframe inside bs3 modal 

but when i am using sweetalert2 confirm it not centered

what i want say is this
![capture](https://cloud.githubusercontent.com/assets/17147242/15014320/fefc5e52-1222-11e6-9c9f-15b866d95860.PNG)

**Comment by limonte** [comment]
IMHO not related to this issue: modal inside modal - what a hell of UI :)

All modal on the attached screenshot are centered. Can you please specify what exactly isn't centered. JSfillde with example will be nice.

**Comment by limonte** [comment]
reopen if needed

**Comment by holmes1491** [comment]
modal inside modal - what a hell of UI :) 
thanks for this kind word....
i want confirmation inside modal than i have to go through  this

see screenshot top properties not working

not element whole sweetalert2 dialog centered in modal

if we have option like position:center which work according screen size that's it!

jsfiddle  not possible because  i am working on localhost 

any way thanks for reply......
