### ISSUE TITLE
Autofocus confim button on modal open?

### ISSUE THREAD

**Issue by CreativelyCloudy** [limonte/sweetalert2#12]
Hi,

I've tried sweetalert, bootstrap-sweetalert and now sweetalert2 - when the modal opens, the focus seems to remain on the link/button that triggered it instead of being set to the modal's confirm button.  Once I press the tab key, the modal's button is focused but many people won't try the tab key and will reach for their mouse instead.

Is this by design, or am I missing a setting, etc?

Thanks.  Jeff.

**Comment by limonte** [comment]
Yes, that's how SA and SA2 working, won't be changed.
