### ISSUE TITLE
Multiple inputs?

### ISSUE THREAD

**Issue by seiyria** [limonte/sweetalert2#121]
As per https://github.com/t4t5/sweetalert/issues/415 - is it possible in this fork to do multiple inputs? If not, is it possible to do so? Perhaps the syntax would be to pass in an array of config objects, and they would display top to bottom, and the promise would return an array instead of a singular value.

**Comment by limonte** [comment]
Currently I don't know how to implement multiple inputs and not to complicate plugin source code too much. So, my answer is: this feature most probably won't be added in swal2.

For now you can make multiple inputs by using `html` parameter and custom JS code in `preConfirm` parameters for validating and getting value of all inputs.

I the example with multiple inputs, take a look: https://limonte.github.io/sweetalert2/#multiple-inputs


PS. update swal2 to latest on your project before testing multiple inputs.

**Comment by seiyria** [comment]
Interesting. At the very least, it's possible, which is good to know. Thanks for the demo! Feel free to close this if it's your long term solution.

**Comment by th-m** [comment]
Hi, Thanks for adding the demo. Unfortunately, this doesn't work for me. I am getting a ` Cannot read property 'then' of undefined`. I literally copied the code exactly as is from the demo...
