### ISSUE TITLE
Option to not focus previous element

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [limonte/sweetalert2#122]
Hi there!

I'm having a problem after changing from sweetalert to sweetalert2, regarding the access to the previousActiveElement variable.

The sweetalert version set this var in the window object (window.previousActiveElement), which enables me to access it and erase it, in order to not focus the previows element when I close the popup.

But in sweetalert2, this previousActiveElement was made private, and I didn't find any option to disable this feature.

How do I prevent sweetalert2 from focusing the previous selected element?

Thanks!

**Comment by limonte** [comment]
Hi @rafael-renan-pacheco! Thanks for suggesting this!

Done in [v2.2.10](https://github.com/limonte/sweetalert2/releases/tag/v2.2.10)

**Comment by rafael-renan-pacheco** [comment]
Hi @limonte 

Thanks for the fast feedback and commit.

But even after unloading the previousActiveElement, sweetalert2 stills focus on previous element.

I think the following codes are doing that from resetPrevState():

```js
window.onkeydown = previousWindowKeyDown;
document.onclick = previousDocumentClick;
```

I didn't find this on sweetalert legacy.

Would be possible to disable those 3 resets via an option? Something like:

```js
if (some_config.reset_previous_state == true) {
    window.onkeydown = previousWindowKeyDown;
    document.onclick = previousDocumentClick;
    window.previousActiveElement.focus();
}
```

Where "reset_previous_state" is true by default.

After the popup is closed, I must not touch the previous element at all.

Thanks.
