### ISSUE TITLE
Typescript Definition

### ISSUE THREAD

**Issue by ninjaonsafari** [limonte/sweetalert2#124]
Could you create the definition file?
https://github.com/typings/typings

**Comment by limonte** [comment]
https://github.com/typings/registry/issues/404

**Comment by limonte** [comment]
![mq97mzs](https://cloud.githubusercontent.com/assets/6059356/15185812/e1dea654-179a-11e6-9233-d9b2d7c45e04.png)

Thank you @ninjaonsafari for suggesting this!
