### ISSUE TITLE
Alert queues

### ISSUE THREAD

**Issue by KHam0425** [limonte/sweetalert2#125]
Is there any way to incorporate a similar strategy that was used here (https://github.com/t4t5/sweetalert/issues/457) in SweetAlert2?  If I use the basic forms of swal2, everything works with the code those folks have contributed in that thread.  However, it seems to get tied up when I try to use strategies that incorporate a form in the callback function.  I think that SwalService doesn't know how to handle the promise resolution, or maybe it's how I'm calling it, I'm not sure.

I'll continue to try to walk through different ways of making the swal() calls, but it would be great if an alert queue was built into this package without having to resort to outside plugins copied from an issue thread.

If there's anything I can do myself, or if there is a workaround that someone else sees, I'd be glad to do it another way.

**Comment by limonte** [comment]
I personally don't like the idea of multiple alerts one after another. Can you please give me a real example where do you need multiple alerts?

**Comment by KHam0425** [comment]
I'm currently working on an extension that parses user selections in a drop down menu.  Some of those selections have properties in their object that warn the user that one of the selections they have in the multi-select should be removed from the selected options, and includes the reason why they should be removed.  So, if you select 3 items from the drop down, the extension parses the selections, and returns an object with each item's properties within.  On object 1, there is 1 warning that the selected option is not allowed, and on object 3 there are 2 different warnings for the selected option.  Additionally, the warning allows the user to submit an override request that will enable selection, but will send a report that they have overriden the warning. 

So, I need to queue an alert with the warning content so it goes through each object's warnings sequentially, instead of them randomly popping up when the next object construction completes, ie. 
`warnings.forEach(function(warning){swal(warning).then(function(isConfirm){if(isConfirm){swal({title: 'Override Request', html:$requestForm, preConfirm: function(result){return new Promise(blahblah){stuff; resolve(stuff)}}}).then(function(result){$processResult});`

I hope this helps to explain one scenario where it makes sense to queue alerts and to process the queue one at a time until all are resolved.

**Comment by limonte** [comment]
I'm still not happy with the idea of multiple alerts one after another. This behaviour looks spammy for me and I don't want it in this plugin. Feel free to fork swal2 and implement it by yourself :)

**Comment by KHam0425** [comment]
To be fair, when using it with the original swal, it puts a small line of
text at the top letting you know how many alerts are pending in your queue,
and then the content of the next alert just replaces the current alert.
But, it's fine. I'll find a work around.

**Comment by limonte** [comment]
Good news @KHam0425! :)

SWAL2 now supports modals queue: https://limonte.github.io/sweetalert2/#chaining-modals

**Comment by KHam0425** [comment]
Wonderful.

**Comment by synth** [comment]
Is it possible to conditionally advance to steps in the queue? For my use, I simply only want to present step 2 if a condition is met in step 1, otherwise, just close the modal. However, I can see it being useful to be able to move to any step based upon certain conditions. This would make swal2 an awesome way to make a form wizard!
