### ISSUE TITLE
Input text filed now showing

### ISSUE THREAD

**Issue by manojsinghrwt** [limonte/sweetalert2#128]
![screenshot_4](https://cloud.githubusercontent.com/assets/1546185/15246361/eb94771a-1929-11e6-9690-5afc42f9ed5c.png)
I am using below code
`swal({
					
					input: 'textarea',
					showCancelButton: true
				}).then(function(result) {
					if (result) {
					swal(result);
					}
				});`
but when execute code  'input' filed missing.

**Comment by limonte** [comment]
It's working: https://jsfiddle.net/limon/n4evc7jv/

**Comment by manojsinghrwt** [comment]
Thanks Limonte for your reply,
I am using it with wordpress (in admin section).
May be other issue or conflict, If I found something I will update here.

**Comment by limonte** [comment]
@manojsinghrwt any luck?

**Comment by manojsinghrwt** [comment]
not yet, neither error show in browser

**Comment by violetzie** [comment]
Having the same issue in meteor.js

**Comment by birjolaxew** [comment]
@violetzie Could you provide a JSFiddle so we can reproduce the problem on our end?
