### ISSUE TITLE
option to be able to scroll alert on mobile phones (and not background)

### ISSUE THREAD

**Issue by levequej** [limonte/sweetalert2#13]
On mobile phones (small screens) with big alert text, sometime you are simply not able to reach confirm or cancel buttons because you can't scroll the alert, only the background scrolls (FYI I have this problem using bootstrap )
I feel like it would be a great enhancement to have this options, because sometimes you simply can't close the alert, or confirm an action(which in my case prevent normal use of the application)

**Comment by limonte** [comment]
Just pushed https://github.com/limonte/sweetalert2/commit/1d3521e639ef1577c25688d9a24b2ebf46856965, take a look :)

**Comment by levequej** [comment]
awesome, thanks !
