### ISSUE TITLE
Looking for sweetalert2 collaborator(s)

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#130]
Open-source plugins often have just one person (repo owner) who can manage PRs, issues, releases.

This is a huge problem, as dependency on 1 human is a weakness. If I die suddenly, this plugin will die with me and your PRs and issue will have no sense.

If you want to became a collaborator of this repo, let me know. Users with one or more merged PRs to this repo will become collaborators immediately after comment here. Other users are welcome too :)

More details about colaborators permissions: https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account

**Comment by Tonkpils** [comment]
I am definitely open to being a collaborator. I am still fairly new to Javascript but getting better and I figured since I'm making an addon for this package on ember I could help improve it if you're interested.

**Comment by limonte** [comment]
@Tonkpils you are very welcome!

**Comment by KHam0425** [comment]
What sort of features/enhancements are in the pipeline, or what bugs need fixed?  In short, what are you looking for from collaborators in the short term?

**Comment by limonte** [comment]
Thank for good questions @KHam0425! 

> What sort of features/enhancements are in the pipeline, or what bugs need fixed?

All issues to be fixed, features to be discussed/implemented are here: https://github.com/limonte/sweetalert2/issues

> In short, what are you looking for from collaborators in the short term?

- taking part in issues/features discussion
- if I'm inactive for month or more, publishing new releases after adding new features or fixing bugs.

**Comment by shaktisri** [comment]
Been using sweet alert for a bit now. Probably can help with adding features or bug fixes

**Comment by samturrell** [comment]
Happy to help! I have a few features i'm keen to add myself and a few issues i've spotted that I'd like to fix.

**Comment by limonte** [comment]
@samturrell 
![](https://s-media-cache-ak0.pinimg.com/736x/55/5f/cb/555fcbb88d4984908e82f4fe3934c366.jpg)

**Comment by yeomann** [comment]
Can i join as well? :smirk_cat:

**Comment by jdcrensh** [comment]
I'd be happy to help out whenever possible!

**Comment by limonte** [comment]
@jdcrensh hello old contributor and welcome aboard! :)

**Comment by KHam0425** [comment]
Oh, I'd also like to help, if you can add me.  Even though you hate the idea of queueing the modals, I did implement it in my environment.  I'm working on building it into a PR that will allow developers to choose to allow pending alerts (default false).

**Comment by limonte** [comment]
@KHam0425 let me see that PR, then I'll make a decision :)

**Comment by acupajoe** [comment]
@limonte I'd love to help out with the project as a contributor if I can!

**Comment by limonte** [comment]
you're very welcome @acupajoe!

**Comment by limonte** [comment]
thank you all guys, swal2 is now totally safe if I suddenly disappear :)

**Comment by taxpayer** [comment]
Just a small thank-you message, @limonte: don't disappear. You had a very
impressive will power to take a good project that was not properly managed
and changed the game completely. As a Swal user since the very beginning, I
thank you for all you did and is still doing. And I hope to see other
projects of you also. :-)


Atenciosamente,
=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

*Rodrigo de Vasconcellos Rodrigues*


*Tel.*: +55-021-98181-2978

*Skype* rodrigo.vasconcellos.rodrigues
*Facebook* http://www.facebook.com/rodrigo.vasconcellos.rodrigues
*G+*
*https://plus.google.com/u/0/104841391047383868474
<https://plus.google.com/u/0/104841391047383868474>=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*


2016-06-21 16:07 GMT-03:00 Limon Monte <notifications@github.com>:

**Comment by toverux** [comment]
@limonte I'm also quite impressed by the energy you have put in the project. I use Swal on a regular basis, and Swal2 saved me from using another mediocre library that displays alerts, once Swal(1) got too old.

So yes, following your invitation, I would be very happy to help from time to time, on any kind of issues!

**Comment by limonte** [comment]
Welcome to the team @toverux!

**Comment by limonte** [comment]
Dear @Tonkpils, @acupajoe, @birjolaxew, and @toverux!

Could you please make accounts on npmjs.com so I can add you to sweetalert2 collaborators there. After this you will be able to update sweetalert2 package there.

**Comment by limonte** [comment]
BTW, I made [the commit](https://github.com/limonte/sweetalert2/commit/78a4cfb290b672ca030de36614efc513aff15017) with mentioning all your names in `package.json` and `bower.json`.

Thank you so much for helping on SweetAlert2 development, we are so ahead of the original plugin now :rocket:  

Happy holidays to you :christmas_tree: :santa: and all the best in New Year!

**Comment by toverux** [comment]
Thanks @limonte!
I've just created my account on npm (under the username *toverux*).

**Comment by birjolaxew** [comment]
Created [*birjolaxew*](https://www.npmjs.com/~birjolaxew) on NPM

**Comment by limonte** [comment]
> I've just created my account on npm (under the username toverux).

Added :+1: 

> Created birjolaxew on NPM

Added :+1: 

> I presume it's not sorcery (based on my experience with Packagist), but could you eventually write a little development guide for the contributors? Conventions about code, git, how you're publishing, etc.

Not much actually to say :)

- Coding style: I just added https://github.com/limonte/sweetalert2/commit/8c5a8f1292a3d8a71eb4d5fec4384268aab3d3f1 which covers it automatically.
- Contributing guide is in the README: https://github.com/limonte/sweetalert2#contributing
- Publishing
  - **Bower** grabs new versions automatically from Git tags (releases) 
  - for **npm** there's an automatic releasing: https://github.com/limonte/sweetalert2/commit/c9a027c465b42c2335e353f0f2cde555c149def2 so if I suddenly disappear it will continue to work. And if something will happen to my npm account you will need to generate a new key and put it to the Travis config. Read more about npm releasing: https://docs.travis-ci.com/user/deployment/npm/
