### ISSUE TITLE
Option to not focus previous element

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [limonte/sweetalert2#133]
Hi there!

This issue is a continuation of #122.

My last post on that issue suggested an option to prevent focusing on the previous element, since just nulling window.previousActiveElement was not enough in sweetalert2 (it was in sweetalert1).

For example, I have a custom combobox that when the user changes an option, sweetalert2 is fired to confirm that option. If the user cancel it, the option is reverted to the previous value, and must focus out to close the dropdown list. In sweetalert1 this was achieved by nulling window.previousActiveElement, but in sweetalert2, there are more actions to focus the previous element besides window.previousActiveElement.

Thanks :+1:

**Comment by limonte** [comment]
Hi @raf! I'm trying to make sense of your request, could you please make the jsfiddle with your case?

**Comment by rafael-renan-pacheco** [comment]
Hi @limonte!

I can't make a jsfiddle at this moment, but I'll try to explain better with some printscreens.

![01](https://cloud.githubusercontent.com/assets/12160864/15321145/0a5cd35c-1c0b-11e6-92a9-572bc0178b18.png)

In the print above, I have the default option "Wheat" selected. If the user tries to change that option, a swal will popup asking the user to confirm the change. If the user cancel that, the option "Wheat" will be selected back again automatically.

![02](https://cloud.githubusercontent.com/assets/12160864/15321190/4abdfbba-1c0b-11e6-9869-8946f36a1537.png)

The print above is the swal alert I said before, asking the user to confirm the option change to "Beige" value. Note that the select box **has lost focus**, but, if the user hits cancel, look what happens:

![03](https://cloud.githubusercontent.com/assets/12160864/15321220/7597b5c4-1c0b-11e6-80d3-47ed8e5020b5.png)

The value "Wheat" as reseted as expected, but the select box received focus again, and this must not happen, because the user just canceled this action. In sweetalert-1, I managed to avoid focusing the previous element by nulling **window.previousActiveElement**. But in sweetalert-2, there are others things to focus the previous element, like:

```js
window.onkeydown = previousWindowKeyDown;
document.onclick = previousDocumentClick;
```

I think those are as well focusing the previous element.

If they are indeed doing that, I suggest an option to avoid this behavior, something like:

```js
if (some_config.reset_previous_state == true) {
    window.onkeydown = previousWindowKeyDown;
    document.onclick = previousDocumentClick;
    window.previousActiveElement.focus();
}
```

Thanks!

**Comment by limonte** [comment]
This request is too custom to be a parameter. Your case could be done with this piece of code: 

```js
swal({
  ...
}).then(function(isConfirm) {
  if (!isConfirm) {
    document.activeElement.blur();
  }
});
```

http://stackoverflow.com/a/21551843/1331425

**Comment by Tonkpils** [comment]
@limonte I think what he means is he doesn't want the dropdown box to be selected again when the alert is canceled.

**Comment by limonte** [comment]
@Tonkpils 

> I think what he means is he doesn't want the dropdown box to be selected again when the alert is canceled.

Yes, that dropdown box is selected after closing swal2 because of it got focus. If we remove focus from it by using `document.activeElement.blur()`, dropdown won't be visible (untested, but I believe it works so).

**Comment by limonte** [comment]
I just checked Bootstrap modal http://getbootstrap.com/javascript/#modals and it behaves the same way as swal2, i.e. focus modal returns focus to the launching element and there's no option to change this behavior.

**Comment by rafael-renan-pacheco** [comment]
Hi @limonte 

Blur() the element was the first thing I tried in sweet-1. Then I realized that it would not work, because I fire the blur inside the swal feedback. After swal runs all feedback, it runs those focus commands by itself...

So, something like this:

```js
swal({
    text: "Are you sure?",
    title: "Warning",
    type: "warning",
    showCancelButton: true,
    confirmButtonText: "Yes",
}).then(function(isConfirm) {
    window.previousActiveElement = null; /* This was enough in sweet-1 */

    if (isConfirm == true) {
        /* Do something with the new selected option */
    } else {
        /* Revert the selected option back */
        /* .... */

        my_dropdown.blur(); /* This works until swal is closed. After it is closed, it fires focus events. */
    }
});
```

Does not work, because the blur only works during the feedback. When swal is closed, swal itself focus the element using those 3 commands I said before. In sweet-1 it was only 1 command (window.previousActiveElement), which I was able to null it before closing the popup, as you can see in the code above.

**Comment by limonte** [comment]
Piece of code which I provided should work. Let's stop with discussion. Reopen with jsfiddle please :)

**Comment by rafael-renan-pacheco** [comment]
Hi there!

Your code worked as expected! The problem was that I was calling blur() inside the Promise, because that was the sweet-1 way to solve this. In sweet-2, calling blur() before calling swal({}) worked perfectly as you said :+1: 

```js
document.activeElement.blur();

swal({
    text: "Some text"
}).then(function(isConfirm) {
    if (isConfirm == true) {
        // save the new option
    } else {
        // rollback the old selected option
    }
});
```

Thanks!

**Comment by OmikronTheta** [comment]
I was having this same problem because I attached a sweet alert to an SVG button and SVGs do not support the blur or focus method.  My solution was to edit the sweetalert.js to add this check to the focus setting.

`if (window.previousActiveElement && typeof window.previousActiveElement.focus == "function") {`

Couldn't we just get this added to the base library?  Seems like a pretty simple change and I can't see how if would cause any problems.

**Comment by alex-drocks** [comment]
I tried previous solutions and it always focuses the previous element no matter what. 
Adding a "debugger" statement to watch execution steps shows there's a setTimeout involved which makes it hard to prevent.

**Comment by PawelGIX** [comment]
It would be great if this autofocus feature could be turned off.
I have an endless loop:
onFocus is calling swal, and swal is calling onFocus on input after closing. Over and over again ;)
