### ISSUE TITLE
Multiple Buttons?

### ISSUE THREAD

**Issue by blazeworx** [limonte/sweetalert2#134]
I am so glad I found this repo. I was struggling to make the original sweetalert work in a project of mine because it did not make use of promises and I was using an alternative non official merge request branch because I needed an input type of checkbox. So thank you for creating your sweetalert version and moving it in that direction. 

One thing I would like to suggest would be to support having a dialog type that has more than just a confirm true/false (aka 2 button) solution. I currently have a use case in my application where I need to provide 2 confirm buttons, for example, one button is a confirm with `foo`, the other is confirm without `bar`, and the third is cancel/close.

I have previously seen bootbox.js that does this. Here is the example from their site that gives you an idea of how they approach it:
![image](https://cloud.githubusercontent.com/assets/4718238/15305535/8f4eff60-1b91-11e6-9aca-b7dcaec09139.png)

I would use bootbox if this was a brand new project (given the requirements). However, I do not want to replace it with another library at this point because I want to keep the look consistent throughout this existing project 

Is there any chance something like this might be possible with SA2?? If not, any chance it could be implemented?

**Comment by limonte** [comment]
Thank you @blazeworx for nice words. Swal2 is An awesome replacement for JavaScript's popup boxes. Your feature request doesn't seem link JavaScript's popup box so my answer is: no, this most probably won't be implemented.

All custom functionality like additional buttons could be done by using `html` parameter and custom JS handlers.
