### ISSUE TITLE
Background overlay missing on first load

### ISSUE THREAD

**Issue by mumairali** [limonte/sweetalert2#135]
I found this behaviour very strange. Upon first page load it totally disappear background overlay. screenshot attached see whole white background; environment chrome

![image](https://cloud.githubusercontent.com/assets/6498132/15314824/98a76506-1c2d-11e6-95a8-737950b874bd.png)
 
Expected behaviour: there should dark gray overlay on background of swal modal is popup

**Comment by limonte** [comment]
@mumairali could you please make jsfiddle which shows this issue?

**Comment by mumairali** [comment]
@limonte Thank you for quick response. Unfortunately I wouldn't able to do this on fiddle but problem which I found is here

highlighted div with styles are automatically generated `display: none` One thing more if I try once more time then overlay works

![image](https://cloud.githubusercontent.com/assets/6498132/15319395/0ded3fd2-1c44-11e6-9d3a-3354399e5a68.png)

**Comment by limonte** [comment]
I can't reproduce this issue, most probably it's up to your project-related code.

**Comment by mumairali** [comment]
I think you'r right. I am digging into my project :+1:

**Comment by ilaif** [comment]
@mumairali Did you figure out the source of this bug? I'm also experiencing it atm.

Thanks!

**Comment by limonte** [comment]
Shalom @mumairali ! Can you please make jsfiddle (here's [an example](https://jsfiddle.net/limon/ad3quksn/)) with code you're using so I can reproduce this bug and fix it.
