### ISSUE TITLE
iOS bug - unwanted scrolling when focusing an input inside the modal

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#136]
I have no clue how to fix this issue with unwanted scrolling:

![ezgif com-resize 1](https://cloud.githubusercontent.com/assets/6059356/15341026/85c5138e-1c8c-11e6-91fc-5340f62ca3b2.gif)

This happens only if there's an input inside the modal and I tap that input. In the same moment that input got focus and native iOS keyboard become visible.

Any help will be much appreciated.

**Comment by limonte** [comment]
http://stackoverflow.com/q/37287148/1331425

**Comment by limonte** [comment]
https://github.com/scottjehl/Device-Bugs/issues/70

**Comment by KHam0425** [comment]
It looks like your screen touch is passing through the alert.  What if you autofocus the input element in the alert when it opens, which should bring the keyboard alive as the alert is opening, and eliminate the need to touch the screen to activate the input box.  Potentially this would stop the scroll.  Or, when an alert is active, scroll actions on the background screen would -= the amount +'d (sort of the way video games "trap" the mouse pointer in the game window by subtracting the position.x > screen.width)  Maybe get an element from the document, and any change of position of that element +/- would then cause the document to -/+ the same amount.  I just woke up, so that probably doesn't make sense.

**Comment by limonte** [comment]
>  I just woke up, so that probably doesn't make sense.

:laughing: 

> What if you autofocus the input element in the alert when it opens

Nice suggestion, I'll do that.

**Comment by limonte** [comment]
> What if you autofocus the input element in the alert when it opens

autofocus for iOS isn't available (google "ios modal input autofocus").

**Comment by KHam0425** [comment]
Can you focus on the input element with jquery? 
$("#textBox").focus();

**Comment by KHam0425** [comment]
https://github.com/driftyco/ionic-plugin-keyboard#keyboarddisablescroll may help.

**Comment by dllsystem** [comment]
```javascript
$(window).resize(function () {
    var modal = document.querySelector('.swal2-modal');
    if (modal) {
        var height = modal.clientHeight;
        modal.style.marginTop = '-' + parseInt(height / 2, 10) + 'px';
    }
});

// -----------------------------------------

var body = document.body; // ! important
body.style.overflow = 'hidden'; // ! important

swal({
    text: 'Update your comment:',
    input: 'textarea',
    inputValue: currentComment,
    confirmButtonText: 'Update',
    showCancelButton: true,
    inputValidator: function(value) {
        return new Promise(function(resolve, reject) {
            if (value) {
                resolve();
            } else {
                reject('You need to write something!');
            }
        });
    }
}).then(function(result) {
    body.style.overflow = 'visible'; // ! important
}, function(dismiss) {
    if (dismiss === 'cancel') {
        body.style.overflow = 'visible'; // ! important
        swal(
                'Deleted',
                'Your comment is deleted',
                'error'
        );
    }
});
```

**Comment by frankenstein-uk** [comment]
There is no clean solution yet?

**Comment by limonte** [comment]
@frankenstein-uk still no clean solution without hacks with changing `overflow` and calculation `margin-top`

**Comment by frankenstein-uk** [comment]
@limonte thanks for letting me know, I think it's up to iOS developers to fix this... I will keep loking for the solution, in case I find it, I will let you know.

**Comment by limonte** [comment]
@frankenstein-uk 

> I think it's up to iOS developers to fix this

I agree with you and that's why I'm not hurrying to fix this issue by hacky solutions

 > I will keep looking for the solution, in case I find it, I will let you know.

Thank you.

**Comment by limonte** [comment]
This issue is moving to #302

**Comment by jmcgrory** [comment]
> > What if you autofocus the input element in the alert when it opens  
>  
> autofocus for iOS isn't available (google "ios modal input autofocus").

@limonte you can trigger js focus on click events and the like on iOS safari, it just has to be part of another element being clicked. I only mention as this would have been a good use case with the initial button click (you'd essentially be able to transfer the focus).
