### ISSUE TITLE
Have callback been completely replaced by promises?

### ISSUE THREAD

**Issue by KHam0425** [limonte/sweetalert2#137]
I used swal2 prior to the newest release, and this particular section of my code was running properly using the same callback structure as the original swal:

```
swal(warning.alert,
    function(isConfirm) {
        console.log(isConfirm);
            if (isConfirm === true) {
                console.log('auth warning acknowledged.');
            } 
    }
)
```
Now, the if block never executes (followed by an else, which I never see either), which leads me to believe the entire callback is dead, in favor of promises.  Is that correct, or am I missing something in the implementation?

**Comment by limonte** [comment]
You are correct, callback was completely replaced by promise in [v1.0.0](https://github.com/limonte/sweetalert2/releases/tag/v1.0.0)

**Comment by KHam0425** [comment]
Well, that pretty much ruins Swal2 for me.  I was using Swal2 without queueing for the situations that needed promises, and standard construction from swal to work with the alert queueing I asked you about before.  Since the queue won't accept promises, I don't really have an option to stay with swal2, which is unfortunate, as I prefer the other improvements you've made to the other repo.
