### ISSUE TITLE
The method resetValidationError is not supported for this object (IE11)

### ISSUE THREAD

**Issue by Silvester20** [limonte/sweetalert2#138]
Also when promise.js is included I got this error when doing an AJAX call with a input (Ajax request example at the homepage of sweetalert2).

Also, when I click the OK or cancel button, nothing happends.
Could you, please in the next release, get rid of promise.js and fix this issue?

I am using IE 11.0.96 with the latest swal2.

**Comment by limonte** [comment]
Can't reproduce. Please make jsfille and reopen.
