### ISSUE TITLE
Small documentation issue

### ISSUE THREAD

**Issue by NitinMaaraj** [limonte/sweetalert2#14]
On this page - https://limonte.github.io/sweetalert2/ for A warning message, with a function attached to the "Confirm"-button...

**type:'warning"**
should be 
**type:'warning'**

swal({
            title: 'Are you sure?',
            text: 'You will not be able to recover this imaginary file!',
            type: **'**warning**"**,
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!',
            closeOnConfirm: false
        },
        function() {
            swal(
              'Deleted!',
              'Your file has been deleted.',
              'success'
            );
        });

**Comment by limonte** [comment]
Fixed, thank you @NitinMaaraj !

https://github.com/limonte/sweetalert2/commit/97513fbf2846858cd138262ed633feb24d26dd0c
