### ISSUE TITLE
Provide native browser fallbacks for standard alert types

### ISSUE THREAD

**Issue by samturrell** [limonte/sweetalert2#140]
Currently it doesn't function at all, ideally we should return the native alternatives, e.g. prompt, alert

**Comment by limonte** [comment]
Why do we need native fallbacks?

**Comment by XSupermanX** [comment]
Because SweetAlert2 doesn't work on IE9 or Earlier.
As long as you include promise.min.js it works on IE10 and IE11, but sweetalert2 does nothing when called on IE9.

**Comment by limonte** [comment]
@XSupermanX I don't want IE9 support. 

IE9 users should suffer.

![laughing-evil-hank-hill-11oRLY4FRk2s36](https://media0.giphy.com/media/11oRLY4FRk2s36/giphy.gif)

**Comment by XSupermanX** [comment]
Couldn't agree more.
But my superiors, couldn't disagree more.

It's fine, I'll just tell whoever complains to update their computers.
Lazy bastards.

**Comment by joshuabremer** [comment]
If anyone is looking at this issue: I made a PR to fix this:
https://github.com/limonte/sweetalert2/pull/204

**Comment by joshuabremer** [comment]
I made another PR that adds 9 lines and makes the CSS fully support IE9.

**Comment by limonte** [comment]
There won't be full, partial, unofficial or any other kind of IE9 support in swal2. I mean it.

IE9 should die and with trying to partially support it, we're slowing down the evolution of the Internet.

**Comment by joshuabremer** [comment]
I don't disagree that people should upgrade, but working in corporate environments change this substantially. Also supporting older customers, like people over the age of 60 usually involves having your software work ok on IE9.  jQuery supports IE9, Ember supports IE9, therefore we used those tools. 

Seems short-sided to make a principled stand against IE9 even though the proposed PR made the resulting library smaller and more consistent.
