### ISSUE TITLE
Closing modal by pressing Esc or clicking outside produces an error

### ISSUE THREAD

**Issue by samturrell** [limonte/sweetalert2#147]
Can be reproduced in the last example on the official examples page.

Error thrown: `sweetalert2.min.js:6 sweetAlert2 expects at least 1 attribute!`

**Comment by limonte** [comment]
Fixed in https://github.com/limonte/sweetalert2/commit/e95bd5dd578f2db10d2a7693a3510e40efba1379#diff-eacf331f0ffc35d4b482f1d15a887d3bR1127
