### ISSUE TITLE
Commiting dist/* only withing new-versions commits?

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#148]
@Tonkpils @samturrell I need your opinions on this topic.

Personally, I'd like to see in pull requests only changes of actual source code, not changes in build files. If we do so, code review is much easier as there are no files which distract the attention and should be skipped.

My proposal is to commit build files only within version commits e.g. https://github.com/limonte/sweetalert2/commit/63cdeb45eab950767b18b4b3a08448d05c05e8c3

What do you think?

**Comment by samturrell** [comment]
Sounds like a good idea. May not be so easy to enforce on a public contributions standpoint though, but as a collaborator i'm happy to abide by it.

Might be worth marking them as binary files in a `.gitattributes` file so that their diff doesn't show up rather than not committing them at all?

**Comment by Tonkpils** [comment]
I agree, I don't think contributors should be committing changes on distributions unless we're cutting a new release. On that note, it would be great if we formalized a release process so that we're not cutting out new versions on every PR merge.

**Comment by limonte** [comment]
@samturrell 

> Sounds like a good idea. May not be so easy to enforce on a public contributions standpoint though, but as a collaborator i'm happy to abide by it.

Lovely!

> Might be worth marking them as binary files in a .gitattributes file so that their diff doesn't show up rather than not committing them at all?

Great suggestion, as always :) I haven't succeed with `.gitattributes`, but there's another way, see https://github.com/limonte/sweetalert2/pull/149/files

@Tonkpils 

> I agree, I don't think contributors should be committing changes on distributions unless we're cutting a new release. 

All of us agreed :+1: 

> On that note, it would be great if we formalized a release process so that we're not cutting out new versions on every PR merge.

Good point, this is my first popular open-source project and I'll do some reading about releasing process. All suggestions are very welcome here.
