### ISSUE TITLE
How to close modal with html inside swal declaration?

### ISSUE THREAD

**Issue by PrestaShark** [limonte/sweetalert2#15]
Hi,
I want to use html link to close sweet alert 2 modal alert. it is possible?

I have something like this

swal({
 title: 'Product added to cart!',
 html: '<a href="#"  class="btn btn-default">I want more</a> <a href="#"  class="btn btn-success">Checkout</a> ',
 timer: 10000,
 showConfirmButton: false
});

So when someone click into I want more button the modal should close. Thanks in advance!

**Comment by limonte** [comment]
Sure it is :)

```js
swal({
  title: 'Product added to cart!',
  html: '<a href="#" onclick="swal.closeModal(); return false;">I want more Checkout</a>',
  timer: 10000,
  showConfirmButton: false
});
```

**Comment by PrestaShark** [comment]
Super fast answer! Super thanks!

BTW. SWAL2 is fare more better than SWAL... I can use smarty strings inside declaration too!
{l s='Some text'} or variables like {$product->name|escape:'htmlall':'UTF-8'}

Superb!

**Comment by limonte** [comment]
Glad it works for your projects! :+1:
