### ISSUE TITLE
[SUGGESTION] - Custom animation class?

### ISSUE THREAD

**Issue by Silvester20** [limonte/sweetalert2#150]
Is it possible to customize the type of CSS animation?

Right now the SweetAlert modal is faded in/out, but I like to choose some other animations from [animate.css](https://daneden.github.io/animate.css/)

**Comment by limonte** [comment]
Nice request @Silvester20! 

Something like this: https://jsfiddle.net/cqxywxaL/2/ ? :)

**Comment by Silvester20** [comment]
Thanks!

Yes that is indeed what I mean, looks good!

**Comment by yeomann** [comment]
+1 @limonte looking great

**Comment by limonte** [comment]
I thinks we're done here :) Reopen if needed @Silvester20

**Comment by Silvester20** [comment]
Awesome, thanks!
