### ISSUE TITLE
iphone bug

### ISSUE THREAD

**Issue by gouhary** [limonte/sweetalert2#153]
In your website https://limonte.github.io/sweetalert2/  , you have to fix the alerts widths because thay  are bigger than the screen width in portrait direction of iphone mobiles.
![img_0643](https://cloud.githubusercontent.com/assets/4875915/15683991/24415bd2-2776-11e6-9511-bd77919a3fd6.PNG)

**Comment by limonte** [comment]
Thank you @gouhary for reporting this issue! Should be fixed now, can you please check again.

**Comment by yeomann** [comment]
@gouhary  its seems to be working now. Tested on iPhone 5 ![img](https://i.imgsafe.org/defd628196.png)]

**Comment by limonte** [comment]
I think we're done here, @gouhary  reopen if needed
