### ISSUE TITLE
swal.finally not a function

### ISSUE THREAD

**Issue by hellsan631** [limonte/sweetalert2#156]
The polyfill your using for your promises doesn't include support for "promise.finally": https://jsfiddle.net/kdf82tc6/1/

This can be solved by using a promise.finally polyfill like this one: https://github.com/matthew-andrews/Promise.prototype.finally

I'm using this lib to wrap some internal logger functions, and having support for promise.finally would be the bees knees

**Comment by limonte** [comment]
native Promise object doesn't have `finally()` method:

![](https://i.imgur.com/wNer6Of.png)

Why `then()` doesn't work for you and you need `finally()`?

**Comment by hellsan631** [comment]
All of the previous promise libraries i've used supported finally, its a bit weird to see that native doesn't support it. The idea is to do some cleanup when the promise and any subsequent ```.then()``` have resolved.

https://github.com/domenic/promises-unwrapping/issues/18

I'm currently using this for a dialog library in an angular 2 application. Here is a use-case example:

I want to track when a modal is open, and perform some logic on modal open and modal close events. In this case, its applying a blur class to the root application component, so the background comes out blurred and slightly grayscale.
```ts
class LoggerService {
  events = new EventEmitter();

   dialogConfirm(title: String, text?: String, confirmText?: String, cancelText?: String): Promise<any> {
    
    // notify subscribers that the event window has opened.
    this.events.emit({value: 'open'});
    
    return swal({
      title: title,
      type: 'warning',
      text: text,
      reverseButtons: true,
      confirmButtonText: confirmText || 'Yes',
      showCancelButton: true,
      cancelButtonText: cancelText || 'No'
    })
    .finally(() => {

      // notify any event subscribers that the modal has closed
      this.events.emit({value: 'close'});
    });
  }
}

class TheLeagueAppComponent implements OnInit {
  modalOpen: boolean;

  constructor(
    private _logger: LoggerService
  ) {

  }

  ngOnInit() {    
    this._logger.events.subscribe(event => {
      this.modalOpen = event.value === 'open';
    });
  }
}
```

And lets say I want to do run a dialog, perform some logic in subsequent functions, and then close.
```ts
onDeleteMember(id: string) {
  this._logger
    .dialogConfirm('Delete Member', 'Are you sure?')
    .then(result => {
      if (result) {
        return this._http.delete(`api/member/${id}`);
      }
    });
}
```

Here is an example the effect in action

Blur:
https://gyazo.com/904c86268241534037b01d4da0a741da

Currently, as a workaround, I'm using a ```then()``` callback which ```Promise.resolve(return)``` resolves the returned value (in the case of a confirm dialog), but ideally I want to emit the event on full promise resolution, not as the first event after the modal has closed.

**Comment by limonte** [comment]
Hi @hellsan631 !

I read your comment several times and I'm still not sure why exactly you need `finally()` :)

 What you want is

```js
return swal({
  ...
})
.finally(() => {
  // notify any event subscribers that the modal has closed
});
```

This can be done with

```js
return swal({
  ...
})
.then(() => {
  // notify any event subscribers that the modal has closed
});
```

Swal2 for historical reasons doesn't use `reject`. Instead of it, there's the parameter in `then()` handler which is named `isConfirm` in most examples. 

In other words `then()` handler will be called in both 'confirm' and 'cancel' cases, so it's practically the same as `finally()` in AngularJS.

**Comment by hellsan631** [comment]
The reason why is the execution sequence. I want to perform the cleanup actions after the entire promise chain has resolved.

Consider this:
```js
success()
  .then(() => console.log('results 1'))
  .then(() => console.log('results 2'));

function success () {
  return swal({
     ...
  })
  .then(() => {
    console.log('cleanup');
  });
}
```

What would you get in the console when you closed the window?
```
cleanup
results 1
results 2
```

This is not ideal, because perhaps you want to execute something after your done with your promise chain, like for instance, disabling/setting a loading bar to 100%. (this is just some rough code, but outlines the problem with not having access to 'finally')

```ts
class LoggerService {
  constructor(
    private _loadingBar: LoadingBarService
  ) {}

  confirmProgress () {
    return swal({
       ...
    })
    .then(result => {

      // If we hit 'yes', then enable our loading bar as the first thing in the promise list
      if (result) this._loadingBar.enable();

      return Promise.resolve(result);
    });
    .finally(() => {

      // When the promise chain has finished, set our loading bar to 100%
      this._loadingBar.setPercent(100);

      setTimeout(() => this._loadingBar.disable(), 6000);
    });
  }
}

class UploadComponent {
  constructor(
    private _logger: LoggerService,
    private _uploadService: UploadService
  ) {}

  submit (images) {
    this._logger
      .confirmProgress('Do you want to upload both images?')
      .then(result => {
        return new Promise(resolve => {
          if (!result) return resolve(false);

          this._uploadService
            .upload(images[0])
            .then(() =>  {
              return this._uploadService.upload(images[1])
            })
            .then(resolve);
        });
      });
  }
}
```

Now you can summize that this can be done in a different way, by setting the progress bars in the UploadComponent. In this case, however the upload component's scope is tightly bound to only deal with the actual submission and upload of the two images. The UI and other services should be able to handle themselves without any necessary interaction between them.

Without a 'finally' method accessible in the initial return promise for swal, interaction like the one described above is impossible.

**Comment by limonte** [comment]
I just added an example of chaining modals: https://limonte.github.io/sweetalert2/#chaining-modals and you can see that `finally()` was used there.

All I need to make it works is adding `<script src="https://cdn.jsdelivr.net/promise.prototype.finally/1.0.1/finally.js"></script>`.

**Comment by hellsan631** [comment]
Oh nice. Didn't know that was all I needed to do to enable promise finally support for swal. Thanks!
