### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by midcore-nam** [limonte/sweetalert2#157]
For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue. Thank you!

JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

Uncaught SyntaxError: Unexpected token import                           sweetalert2.js:3 

import { defaultParams, sweetHTML } from './utils/default.js';

**Comment by limonte** [comment]
I believe you're using `src/sweetalert2.js`. Instead of it, you should use `dist/sweetalert2.js` or `dist/sweetalert2.min.js`
