### ISSUE TITLE
How to change enableLoading style 

### ISSUE THREAD

**Issue by essivision** [limonte/sweetalert2#158]
Hi 

I want to change style of enableLoading() to sweetalert 1.0 style `showLoaderOnConfirm`. What should I do?

Thanks

**Comment by limonte** [comment]
Nice suggestion @essivision! I'll implement `showLoaderOnConfirm` parameter.

**Comment by limonte** [comment]
Done in [v3.3.4](https://github.com/limonte/sweetalert2/releases/tag/v3.3.4), take a look at this example: https://limonte.github.io/sweetalert2/#ajax-request
