### ISSUE TITLE
How to use javascript AFTER the popup (rather than after button click)?

### ISSUE THREAD

**Issue by dylanh724** [limonte/sweetalert2#16]
For example,

I'm making a registration form http://i.imgur.com/zVWLyrB.png

I had to use jq's on() to change the date to jquery ui date. It would be much easier if I could add javascript at the same time this pops up (I can't use it early because sweetalert creates new DOM).

This is also useful for validation events before the button is clicked, such as if username is taken, if password isnt long enough, etc.

Any easy way to use JS/JQ while the message pops up, but BEFORE clicking the button or do I need to keep using jq on() events? I tried adding 
'<script>alert('hi');</script>' + //HTML Here
but it didn't seem to work.

**Comment by limonte** [comment]
Sorry, can't help you. SA2 wasn't designed for complicate cases like yours.

**Comment by dylanh724** [comment]
This was closed, but I found a way and wanted to ask, would you be interested in having a "form" type for SWAL2? I don't have too much time on my hands, but I can show you the code I used and maybe someone else can throw it in SWAL2? It's very friendly, and has live-validation (blur events):

You can even use my icon (it's SVG object). Check it out (animated GIF):

http://imgur.com/KYH6DaQ

**Comment by limonte** [comment]
I personally don't like much logic in popup forms. Popup modal just not designed for big forms. With simple forms SA2 already works fine.

**Comment by olitomas** [comment]
@limonte I agree with you. But providing a "onOpen" function would give the developer the option to decide for him or her self if custom login in the popup is a good idea.

**Comment by limonte** [comment]
Hi @olitomas, I think that swal2 can do what you want. Please provide the case where you need `onOpen` parameter.

**Comment by olitomas** [comment]
Maybe I was missing something, but I made a PR with the feature I felt was missing, where I explain this: https://github.com/limonte/sweetalert2/pull/129

**Comment by limonte** [comment]
@olitomas no need in new parameter :)

https://jsfiddle.net/limon/70aoLLnj/
