### ISSUE TITLE
closeOnConfirm configuration

### ISSUE THREAD

**Issue by emilkje** [limonte/sweetalert2#160]
Hi! First of all thanks for this awesome library. I was just wondering if you could elaborate on the decision to remove the closeOnConfirm configuration. I can't find anything on this in the issues, just the notice in the 2.0 changelog.

I have a problem without this config because I am using chained dialogues to create a wizard. How can I achieve similar functionality with swal > 2.0?

**Comment by limonte** [comment]
Hi @emilkje! Could you please show your code with `closeOnConfirm` parameter so I can suggest you how to change it to work with swal2?

**Comment by samturrell** [comment]
+1 I think this is a good feature to have. I'm sure it could be achieved with the ``preConfirm`` hook, but that seems better suited to validation type events.

**Comment by limonte** [comment]
> I'm sure it could be achieved with the preConfirm hook

Exactly. `preConfirm` was the nicer replacement for `closeOnConfirm` parameter.

> but that seems better suited to validation type events.

Not exactly true. For the validation there's `inputValidator` which is called before `preConfirm`.

I'm not sure if we need that old `closeOnConfirm` parameter from the original swal plugin.

@Tonkpils @jdcrensh  what do you think?

**Comment by emilkje** [comment]
Sorry for the late replay, and thanks for getting back to me @limonte :) Here is a demonstration of the behavior I'm aiming for: https://jsfiddle.net/97rmk6ap/. This is part of a bigger in-house prompt system, but I've tried to reduce the code to its bare essentials.

**Comment by limonte** [comment]
@emilkje I just released swal2 with modals chaining support (`swal.queue([Array])`), take a look on [this example](https://limonte.github.io/sweetalert2/#chaining-modals), it should be exactly what you need :)

**Comment by emilkje** [comment]
Thanks mate I will look into it. You can close this issue and I will open another if necessary.

**Comment by limonte** [comment]
Hope I helped you :)
