### ISSUE TITLE
npm install error on windows, git bash

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#161]
![swal-npm-windows](https://cloud.githubusercontent.com/assets/6059356/15830485/71a9d0f6-2bcd-11e6-80bd-c17948677d57.png)

**Comment by limonte** [comment]
Related to https://github.com/limonte/sweetalert2/pull/149

**Comment by samturrell** [comment]
http://stackoverflow.com/questions/12920652/git-update-index-assume-unchanged-returns-fatal-unable-to-mark-file - Anything here that can help you? Sorry I can't help more, don't have a windows machine to test on.

**Comment by limonte** [comment]
@samturrell thanks for helping me out with this :) Actually two answers helped me - one which you mentioned and http://stackoverflow.com/a/12288918/1331425
