### ISSUE TITLE
Complete rebuild on Vue.js

### ISSUE THREAD

**Issue by samturrell** [limonte/sweetalert2#163]
I'd like for this plugin to be rebuilt using the popular vuejs framework.

Pros:
- Properly modularise the code, splitting out template and logic into manageable components
- Better handling of dom events
- Adds data binding, so no need to query the dom for data or dom manipulation

Cons:
- Heavier overhead with pulling in the vuejs package, however other versions can be generated that exclude this and users can use their own vuejs package.
- Ease of development for new contributors - a slight learning curve, but all for the greater good in my opinion.

I'd like contributors opinions on this, as it would make most features a lot easier/nicer to implement. A basic example can be seen at http://samturrell.github.io/sweetalert2/public/

It's not a lot to go on right now, but the main example you see on pageload is an array of input types being dynamically added to the dom rather that the current process of showing/hiding a single type of input.

If it's something you guys are interested in pursuing, i'm happy to continue work on it and eventually merge it into this package as a major release.

**Comment by limonte** [comment]
I just watched screencasts on Laracasts about Vue.js and it's awesome!

Here's my opinion:

- swal2 should be dependency-free. Currently there's 1 dep - es6-polyfill which is used only if IE support is needed and theoretically can be removed after IE death :)
- swal2 should not be based on any JS framework. There's a ton of frameworks now. Today's trend is Vue.js, tomorrow there will be another "cool" framework :)
- rebuilding small modal window plugin to work on any framework smells like over-engineering to me.

So, my vote goes against rebuilding on any JS framework.
