### ISSUE TITLE
Promise is undefined

### ISSUE THREAD

**Issue by mehmetalidumlu** [limonte/sweetalert2#166]
Hi, 
I get "Promise is undefined" error from sweetalert2.min.js.

```
 $.ajax({
        type: 'GET',
        url: url,
        data: {
            test: test
        },
        error: function (xhr, status, error) {
            swal('Sorry...!', 'Server Message: <br><br>' + error, 'error');
            // Throw expection "Promise is undefined"
        }
    }).done(function (data) {
       
    });
```

Thanks...

**Comment by limonte** [comment]
Most probably you're getting this exception in IE.

For IE support Promise polyfill should be included beside sweetalert2.js:

```html
<!-- for IE support -->
<script src="bower_components/es6-promise/promise.min.js"></script>
```

**Comment by mehmetalidumlu** [comment]
Hi @limonte, thanks for help.
I added this script and problem resolved. But "OK" button and background click event not working in IE 11.

**Comment by limonte** [comment]
> But "OK" button and background click event not working in IE 11.

As I can see all works fine in IE11. Probably it's up to your environment.

**Comment by jennyanthony** [comment]
How do you add Promise polyfill without bower?

**Comment by samturrell** [comment]
`<script src="https://cdn.jsdelivr.net/es6-promise/latest/es6-promise.min.js"></script>`

**Comment by daerogami** [comment]
Came here from google; so just for reference this is what I added to my main page to prevent it from loading on non-IE browsers (borrowing from @samturrell's example):
```<!--[if IE]>
<script src="https://cdn.jsdelivr.net/es6-promise/latest/es6-promise.min.js"></script>
<![endif]-->```

If you need to target a specific version, see here: https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx

**Comment by nmiddendorff** [comment]
Adding **core-js** is the fix for IE. I tried adding the es6-promise but the button clicks still did nothing. After adding core-js it worked as expected.

**Comment by toverux** [comment]
core-js is the preferred polyfill, yes. It's pretty good and contains lots of polyfills.

**Comment by mcantillana** [comment]
How to add core-js to my project?
