### ISSUE TITLE
Post-Install script incompatible with docker

### ISSUE THREAD

**Issue by macpham** [limonte/sweetalert2#167]
We're using your library in our app that is running in a docker container. The post-install script relies on a .git file shouldn't be in our container.

```
> sweetalert2@3.3.4 postinstall /usr/src/app/node_modules/sweetalert2
> git ls-files dist | tr '\n' ' ' | xargs git update-index --assume-unchanged
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```

Can you make this `postinstall` conditional so we can skip it for our usage please?

**Comment by limonte** [comment]
Hi @macpham and thank you for reporting this! Should be fixed in latest version.

**Comment by macpham** [comment]
Thanks for the quick fix @limonte 👍
