### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Silvester20** [limonte/sweetalert2#168]
At "https://limonte.github.io/sweetalert2/", check the **email** example at the "INPUT TYPES" section and you will see what's wrong.

Btw; Thanks for the chaining method! Maybe adding a back button too would be nice.

**Comment by limonte** [comment]
> At "https://limonte.github.io/sweetalert2/", check the email example at the "INPUT TYPES" section and you will see what's wrong.

I don't see anything wrong.

**Comment by Silvester20** [comment]
Sure, I think **if (email)** should be **if (result)**, right?

`}).then(function(result) {
  if (email) {`

**Comment by limonte** [comment]
Oh, thanks! Sure, it should be `if (email)`. Fixed now.
