### ISSUE TITLE
Add support for a promise in inputOptions 

### ISSUE THREAD

**Issue by AmitMY** [limonte/sweetalert2#171]
If the data must load asyncronically, the alert should support the `inputOptions` to be a Promise, that only when resolves adds the values to the select, and until then shows the loading alert (dancing 3 dots)

Thanks

**Comment by limonte** [comment]
Done: https://limonte.github.io/sweetalert2/#radio-inputs

**Comment by AmitMY** [comment]
Amazing! thanks
