### ISSUE TITLE
Sweetalert2 migration

### ISSUE THREAD

**Issue by AmitMY** [limonte/sweetalert2#172]
For a couple of months I used sweetalert, and now that I found this library, I really want to use it - it is simpler for weird cases :)

The thing is - apparently migrating to sweetalert2 is not as trivial as I thought (It's easy, yes, but with so many alerts, I have to miss at least one)

Is there a way by any change you make a migration tool? meaning, the library will have 2 dist files:
sweetalert2.js, and sweetalert2-migrate.js (Like the new jQuery 3 migrate), and when both loaded, it will have backwards compatability with sweetalert, but will throw deprecation errors

**Comment by limonte** [comment]
@AmitMY first of all, thank you for all suggestion you submitted for swal2! 

Automated tool most probably won't be implemented, but I just created Wiki page: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2

You can contribute to it :)

**Comment by AmitMY** [comment]
Thanks!
The only other thing I noticed is that type: "input" fails..

If Ill find time I'll make a migration tool.

**Comment by limonte** [comment]
I just added info about input: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2#3-modal-with-input-field

Thank you!
