### ISSUE TITLE
Overlay - WebKit Browser

### ISSUE THREAD

**Issue by JAKgit** [limonte/sweetalert2#173]
WebKit does not show the overlay on the latest release.

On line 690 I have changed this:
`elem.style.opacity = 0;`
to this:
`elem.style.opacity = 1;`

Will that have any negative effect? Thank you for the great product.

**Comment by limonte** [comment]
Can't reproduce in Linux/Chrome and OSX/Safari. Most probably this issue is up to your environment.

**Comment by JAKgit** [comment]
It is a complete blank page with nothing in it, so I don't think so.

**Comment by limonte** [comment]
Can you please create JSFiddle?

JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

**Comment by JAKgit** [comment]
It only happens when the HTML file is blank. So don't worry that won't happen in most cases.
