### ISSUE TITLE
SWAL migration helper

### ISSUE THREAD

**Issue by AmitMY** [limonte/sweetalert2#174]
Here is a quick migration tool:
http://pastebin.com/8ZXM49xa

It has some backwards support, but not all.
Change the error messages however you like, and please include this file in the 'dist' folder. (It currently is helping me to migrate, probably missed a bunch of stuff)

**Comment by limonte** [comment]
I don't think this tool should be included in swal2 dist.
Most probably it doesn't cover all differences in plugins and it's undocumented.

**Comment by AmitMY** [comment]
Of course it does not cover everything. It is not even backwards compatible. but it does throw warnings on all of the Wiki differences, tries to fix stuff, and is very easy to improve.

It was a QUICK tool. Don't usually have time for stuff like this, but decided to make an exception because you were quick to respond and help in other issues.

Thanks!
