### ISSUE TITLE
Mandatory reject param?

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [limonte/sweetalert2#177]
Hi there!

I'm upgrading my code to v4, and I saw that the new `reject(dismiss)` Promise is mandatory to avoid browser errors. If I do not set a dismiss function, I get the following error in Chrome:

```
Uncaught (in promise) cancel
```

Would be possible to make this reject optional? Sometimes we just want to close the popup if the user hits cancel, and not show a new swal to confirm that the user clicked cancel successfully.

If I code an empty dismiss function just to avoid this error, ES6 linters will fire up to not create empty functions, and the code would not be accepted for deployment.

Best regards,
Rafael.

**Comment by limonte** [comment]
Hi @rafael-renan-pacheco ! I don't know at this moment how to suppress `Uncaught (in promise)` error messages in browser console.

**Comment by acupajoe** [comment]
@limonte is there currently a reason it does do a rejection of the promise? I don't see anywhere where they would be caught other than by the user at the end (unless that was the idea)

But you can do something like this:
```
return modalDependant.apply(this, args).catch(function(rejected) {
    console.log(rejected);
  });
```

**Comment by acupajoe** [comment]
@limonte ah yeah, I see what you mean. Thanks!

**Comment by acupajoe** [comment]
@limonte I'm not sure if this is something we actually want to pursue in swal but for the sake of providing a solution: we could make a wrapper class for the default Promise implementation and override the `then()` function call to catch silently if the two function parameters for `then()` are not supplied.

So something like:
```
//Note this is entirely untested
SwalPromise.prototype.then(func1, func2) {
    if (typeof func1 !== "function" && typeof func2 !== "function") {
        return false; //manual catch
    } else {
        return Promise.prototype.then(func1, func2); //go back to the normal implementation
    }
}
```

**Comment by limonte** [comment]
I'm not sure how to implement this idea, can you please create PR? Thank you @acupajoe !

**Comment by samturrell** [comment]
The above wouldn't work in cases where they're not using a .then() handler.

**Comment by samturrell** [comment]
The only way i can really see this being resolved is with an opt-in solution such as

```
Promise.prototype.done = function() {
    return this.catch(function() {
        // Silence is golden.
        // Catch promise rejections silently.
    });
};
```

And then `swal().done()` to suppress the error. 

There is no way to fix this without using a non-native promise implementation where we can suppress the error internally.

**Comment by limonte** [comment]
@samturrell I implemented your suggestion in v4.0.6 
https://jsfiddle.net/limon/2ya7akjq/

Thank you Sam, with your help we finally found the solution for this issue.

**Comment by limonte** [comment]
@rafael-renan-pacheco as to me, this issue can be closed as there's most probably no better solution.

**Comment by rafael-renan-pacheco** [comment]
Hi @limonte!

Of course! Thank you very much for your support :+1: 

Best regards,
Rafael.

**Comment by sembrex** [comment]
Hi, @limonte 
It works, thanks.
Instead of adding "done" after each swal, i put it in sweetalert2.js line1129 right after closing Promise
works great for me

**Comment by ltvan** [comment]
As issue with .done() as explained in #324, you can create a noop variable instead, like angular.noop.

For linter, just write as below:

```
function noop(){
  // do nothing
}
```
