### ISSUE TITLE
Support for audio playing

### ISSUE THREAD

**Issue by AmitMY** [limonte/sweetalert2#181]
Support for HTML5 Audio, such that when opening the alert an audio will start playing, and when closing it, it will pause, and removed from the DOM.

Here is swal 1 code I use:

```
swal({
    title: '<span style="font-size:14px;">At ' + $rootScope.formatDate(call.start_time) + ", By " + call.first_name + " " + call.last_name + '</span>',
    text: "<audio id='call_recordings' controls autoplay='autoplay'>" + '<source src="' + call.record + '" type="audio/mpeg">' + "</audio>",
    showCancelButton: true,
    cancelButtonText: "Close",
    closeOnCancel: false,
    showConfirmButton: false,
    html: true
}, function () {
    document.getElementById('call_recordings').pause();
    swal.close();
});
```

**Comment by limonte** [comment]
For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue. Thank you!

JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

Also, please specify the expected and the actual behaviour of swal2.

**Comment by AmitMY** [comment]
JSFiddle:
https://jsfiddle.net/ad3quksn/3/

The expected behavior is having an HTML audio
Actual behavior: showing text 'true'

**Comment by limonte** [comment]
Oh, I forgot to add that in migration guide, here it is: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2#4-custom-html-in-the-title-and-description

Pay attention to different ways of using `html` parameter in swal and swal2. Custom HTML functionality was implemented in swal2 before original swal.

**Comment by AmitMY** [comment]
Thanks!
