### ISSUE TITLE
Uncaught (in promise) overlay

### ISSUE THREAD

**Issue by federicolucca** [limonte/sweetalert2#185]
Hi,

i found this error, "Uncaught (in promise) overlay" this happen when i click out of the modal

https://jsfiddle.net/28tu8f7p/

Thanks
Federico

**Comment by limonte** [comment]
duplicate of https://github.com/limonte/sweetalert2/issues/177

**Comment by limonte** [comment]
starting from v4.0.6 you can fix this issue this way: https://jsfiddle.net/limon/2ya7akjq/

**Comment by limonte** [comment]
### https://github.com/limonte/sweetalert2#handling-dismissals

**Comment by carlHandy** [comment]
@limonte the solution you provided does not work. 

`.done()` is not a function. Is there another way to resolve this?
