### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by kalpitpandit** [limonte/sweetalert2#187]
Its throwing error **'Argument 'module' is not a function, got undefined'** while 

> require('sweetalert2') or require('sweetalert2').default

Any help?

**Comment by samturrell** [comment]
From a quick google search this seems to be more user related. Would it be possible to provide a testing environment so I can recreate and track down the problem?

**Comment by limonte** [comment]
agree with @samturrell :+1: 

@kalpitpandit please provide more details about your case.

**Comment by limonte** [comment]
@kalpitpandit reopen if needed

**Comment by kalpitpandit** [comment]
Sorry for late reply @samturrell @limonte .

I have created git repository with webpack environment. [https://github.com/kalpitpandit/sweetalert2-with-webpack](url)
