### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by quma** [limonte/sweetalert2#188]
Hallo,

first, thank you for the great script!
I have a question, how I can do that:

I open a Sweetalert PopUp with via Button.
This PopUp shows a Message with a continue Button like in your example "Chaining modals example".
I wont to load the content of a another page via ajax in the Sweetalert PopUp after clicking the continue button.

`$('div.swal2-content').load('index.php?route=common/cart/info ul li');`

But I cant attach this to the text section like this:
`
{ title: 'continiue', text: $('div.swal2-content').load('index.php?route=common/cart/info ul li'); },
`
Can you help me please ?
Best regards

**Comment by limonte** [comment]
This can't be done with swal2 at its current state. You have to found a workaround for your case, e.g. preloading templates.

**Comment by quma** [comment]
ok, thank you !

**Comment by acupajoe** [comment]
@quma you actually can do this with the new `onOpen` method added. You just have to get a little creative: https://jsfiddle.net/gr197j8n/1/

**Comment by quma** [comment]
Hallo acupajoe,
many thanks 👍

**Comment by acupajoe** [comment]
@quma Absolutely - hopefully that example makes sense!

**Comment by limonte** [comment]
nice trick @acupajoe!
