### ISSUE TITLE
SWAL2 cancel event is backwards

### ISSUE THREAD

**Issue by dylanh724** [limonte/sweetalert2#19]
<a href="http://i.imgur.com/gGfXnTA.png"><img src="http://i.imgur.com/gGfXnTA.png"></a>

**Comment by dylanh724** [comment]
I found my own thread a long time later -- I read isCancel in some other documentation, but it should  be isAccept, I suppose, if anyone else comes across this. You can handle the cancel button this way and just "return false" at the end of your cancel function code

**Comment by yigitozkavci** [comment]
This parameter is just an arbitrary name, and generally being used as "isConfirm". Therefore, logic better be implemented like this:
```
, function(isConfirm) {
	if(isConfirm) {
		// Confirm logic here
	} else {
		// Cancel logic here
	}
}
```

**Comment by dylanh724** [comment]
ah, thank you -- semi related, how would I handle cancelling via clicking outside? This event does not seem to be a "cancel" event
