### ISSUE TITLE
Uncaught (in promise) timer

### ISSUE THREAD

**Issue by orangecoding** [limonte/sweetalert2#190]
Hi.

Since the change of the promises, I'll get an error
`sweetalert2.min.js:1 Uncaught (in promise) timer`
when having an alert with a timer to close it.

See this example. A simple if() should do the trick..
https://jsfiddle.net/o0b675zm/

**Comment by limonte** [comment]
Thank you @orangecoding for reporting this issue.

Unfortunately, it's already open https://github.com/limonte/sweetalert2/issues/177 and I don't know how to fix it :/

**Comment by limonte** [comment]
starting from v4.0.6 you can fix this issue this way: https://jsfiddle.net/limon/2ya7akjq/

**Comment by limonte** [comment]
### https://github.com/limonte/sweetalert2#handling-dismissals

**Comment by simplenotezy** [comment]
That does not work. Error still persists: `Uncaught (in promise) timer` when using `.then(`

**Comment by limonte** [comment]
@simplenotezy upgrade to the latest version
