### ISSUE TITLE
Can I get a better example of how to use the option "showLoaderOnConfirm" with an ajax request?

### ISSUE THREAD

**Issue by ryanmortier** [limonte/sweetalert2#193]
For example, below is the command I'm executing:

### Defaults
```js
swal.setDefaults({
    allowOutsideClick: false,
    allowEscapeKey: false,
    showCloseButton: false,
    buttonsStyling: false,
    confirmButtonClass: 'btn btn-primary',
    cancelButtonClass: 'btn btn-default btn-swal-cancel'
});
```

### Script to delete a contact using ajax
```js
swal({
    title: "Delete contact?",
    text: "This contact will be permanently deleted and cannot be recovered. Are you sure?",
    type: "warning",
    confirmButtonText: "Delete",
    confirmButtonClass: 'btn btn-danger',
    showCancelButton: true,
    showLoaderOnConfirm: true
}, function () {
    this.$http.delete('/contacts/' + contact.id).then(function (response) {
        swal.close();
    }, function (response) {
        swal.showValidationError('Server Error!');
    });
}.bind(this));
```

This works on the original SweetAlert2 repository by `t4t5` but it doesn't work on yours. I've tried using the `}.then(function () {` but anything in there is run before the ajax finishes.

Thank you.

**Comment by limonte** [comment]
https://limonte.github.io/sweetalert2/#ajax-request

**Comment by ryanmortier** [comment]
@limonte Do I have to use the `preConfirm` option when using ajax?

**Comment by limonte** [comment]
No, `preConfirm` is an optional parameter. Please take a look on https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2

**Comment by ryanmortier** [comment]
Great, thank you. I've solved my ajax issue. However, I believe I've noticed another problem.

When `buttonsStyling` is set to `false`, the loader isn't shown. Is there a way to have my own styled buttons but still use the default loader?
