### ISSUE TITLE
When using custom button styling with "buttonStyling" set to "false", the loader isn't shown when using "showLoaderOnConfirm".

### ISSUE THREAD

**Issue by ryanmortier** [limonte/sweetalert2#194]
I realize this might be intentional and if it is, is there a way to get custom styled buttons and a loader?

JSFiddle: https://jsfiddle.net/ad3quksn/5/

**Comment by limonte** [comment]
@ryanmortier thanks for separating this issue, I'm working on it right now :)

**Comment by limonte** [comment]
Done in [v4.0.6](https://github.com/limonte/sweetalert2/releases/tag/v4.0.6)

**Comment by ryanmortier** [comment]
Thanks!
