### ISSUE TITLE
Problem with alertifyjs?

### ISSUE THREAD

**Issue by thearabbit** [limonte/sweetalert2#196]
I use popup form with `alertity js` in `Meteor JS`.
1- When my form submit success (form don't close), I show the `sweetalert2`, but it don't overlay.
It mean that I can click or use the form normally.
```js
// custom.css
.swal2-overlay {
    z-index: 2000;
}

.swal2-modal {
    z-index: 3000;
}
// Still don't work
```
2- When I press `escape key`, It close the `alertifyjs` too.
Please help me.

**Comment by thearabbit** [comment]
I tred
```js
{
allowOutsideClick: false
}
```
But still can be use the form.

**Comment by limonte** [comment]
Why are you using two plugins for modal dialogs at the same time?

**Comment by thearabbit** [comment]
I use popup form with `alertify js`, and then use `sweetaler2` for alert msg.

**Comment by limonte** [comment]
You're doing it wrong. Use `alertify js` for both popup form and alert messages.
