### ISSUE TITLE
When using Chrome, clicking on custom icon in confirm/cancel button does not close modal

### ISSUE THREAD

**Issue by chipmunkgeek** [limonte/sweetalert2#197]
I have encountered a possible bug with SweetAlert2 when using **Chrome**.  This buggy behavior does not appear when using *Firefox*. My configuration is:
```
Google Chrome 47.0.2526.106 (Official Build) (32-bit)
Revision 	  19b9e1a5713f4b9ae324bd59bbe16ca6eb91d0e0-refs/branch-heads/2526@{#532}
OS	          Linux 
Blink	      537.36 (@19b9e1a5713f4b9ae324bd59bbe16ca6eb91d0e0)
JavaScript	  V8 4.7.80.25
Flash	      21.0.0.213
User Agent	  Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko)
              Chrome/47.0.2526.106 Safari/537.36
```

It seems that, when using a custom HTML for the cancel or confirm button which includes an embedded icon (for example: `<i class="fa fa-thumbs-down"></i>`), the hover/click behavior for the button does not work when the mouse is over the icon.

This possible bug is reproducible at the [Github IO page for SweetAlert2](https://limonte.github.io/sweetalert2/), in the example regarding "Custom HTML description and buttons".

As I visit this page using **Chrome**, I do the following:
1. Click on the "Try me!" button next to the example.
2. Mouse over the blue part of the "Great!" button.  When I do this, there is proper hover behavior (button background gets darker).
3. As soon as I mouse over the thumbs up icon, the button background is no longer dark (meaning some sort of mouse out has occurred?)
4. When I click on the thumbs up icon, nothing happens.
5. It is only when I click on the actual blue button or the text (but *not* the thumbs up icon) that the sweet alert modal closes.

**Comment by limonte** [comment]
Thank you @chipmunkgeek for such detailed bug-report! :+1: :+1: 

Fixed in [v4.0.7](https://github.com/limonte/sweetalert2/releases/tag/v4.0.7)
