### ISSUE TITLE
Animation Sporadically Hanging in Chrome

### ISSUE THREAD

**Issue by sykth** [limonte/sweetalert2#198]
Hi,

First off great plugin - really enjoying it.  I was wondering if you have experienced a sporadic issue where the sweet alert does not finish the close animation when you click the confirm box?

I've attached an image to illustrate how the box "hangs" in Chrome version 51.0.2704.103 m (can't repeat this in IE).

It seems moving the page with the scroller/mouse wheel seems to finish the animation but I was just concerned in case users thought the box had froze.

(attachment):
![sweetalert2bug](https://cloud.githubusercontent.com/assets/2370935/16557211/5db4bd44-41d6-11e6-8625-1814c2cec96f.jpg)

Thanks

**Comment by limonte** [comment]
Can't reproduce in latest Chrome both in Win10 and Ubuntu
