### ISSUE TITLE
window.open() triggers popup blocker

### ISSUE THREAD

**Issue by Coriou** [limonte/sweetalert2#199]
I used to use the original SWAL and I have a simple modal with two different actions on the two buttons (confirm & cancel) : confirm will open a new modal, cancel will open a page in a new tab.
My code looked like this :

```
var dialog = swal({
    title: 'My Title',
    html: html,
}, function( isConfirm ){
    if ( isConfirm ) {
        swal({
            title: 'Other title',
            html: html2,
        });
    }else{
        window.open( myUrl, '_blank' );
        swal.closeModal();
    }
});
```

No problems with my old code, did the just just fine. I'm in the process of upgrading to SWAL 2 which I much prefer. However, I'm experiencing an issue with the similar code ported to SWAL 2 : the `window.open()` method will trigger the popup blocker because the browser thinks it's not triggered by the user (in reality though, it totally is since the user has to click on my "cancel" button). 
Here's what my code looks like now :

```
var dialog = swal({
    title: 'My Title',
    html: html,
}).then(function(){
    swal({
        title: 'Other title',
        html: html2,
        showCancelButton: true,
    });
},function(dismiss){
    if ( dismiss === 'cancel' ) {
        window.open( myUrl, '_blank' );
        swal.closeModal();
    }
});
```

You can test it on JsFiddle : https://jsfiddle.net/z8491etu/

Any way to go around this ? I'm not sure how to let the browser know that the "dismiss" method is indeed called after a user action. Thanks !

**Comment by limonte** [comment]
https://jsfiddle.net/limon/w1yvhnjk/

**Comment by Coriou** [comment]
> https://jsfiddle.net/limon/w1yvhnjk/

Thanks. Well, I guess you're using Chrome - or another WebKit based browser.

Two things here :

1. In Firefox, the browser I was using for my tests, it doesn't change anything
2. In Chrome, my Fiddle doesn't work : it will never load the second SWAL modal... Not sure why though. I took my own code and simplified it to the minimum required for this issue, guess I screwed up somewhere.

Anyway, the Fiddle was misleading. My problem is not with chaining SWALs actually. My problem is I want to the browser to know that a `window.open()` action on the confirm or cancel button is actually user generated so it's not caught but the browser's anti pop-up. I'm sorry if I'm not clear.

**Comment by limonte** [comment]
You're clear and I understand what you want to perform. I can see now what you mean, I'm facing the same 'Firefox prevented this site from opening a pop-up window'. Unfortunately, I don't know how to fix this and my personal opinion - you're doing it wrong, `window.open()` shouldn't be in cancel button handler.

**Comment by Coriou** [comment]
Yeah, I don't know how to fix it either. SWAL 1 didn't have this problem for some reason, I can only guess it's because SWAL 2 is using promises and the problem is most likely happens at a lower level than SWAL 2.

I agree with you on the general idea that it shouldn't be there. But in my case, it really is the best place for it to be. I'm using SWAL to give my users a few options, and one of them is to open an URL in another tab. I could have a button in the content, but then the buttons in my modal would be kinda stupid : "Click on this button in the content to perform action 1 but click on the button in the "footer of the modal" to perform action 2". I don't see anyway around it.

Thanks for your help anyway :)

**Comment by limonte** [comment]
Only one solution that I can suppose is to use custom buttons by passing them to the `html` parameter.

**Comment by acupajoe** [comment]
@Coriou: Based on this question: https://stackoverflow.com/questions/9514698/bypass-popup-blocker-on-window-open-when-jquery-event-preventdefault-is-set

It's because of the asynchronous nature of promises. You can do a semi-hackish manual bind though if you really want to get this working: 
https://jsfiddle.net/t7hfffch/2/

**Comment by limonte** [comment]
@acupajoe nice trick :)

**Comment by Coriou** [comment]
Hey @acupajoe nice trick indeed ! That's awesome, thank you for taking the time !
