### ISSUE TITLE
SHIFT+TAB broken during swal()

### ISSUE THREAD

**Issue by dylanh724** [limonte/sweetalert2#20]
Only tab forward works, tab back does nothing. For some reason it completely takes over the khook for tab backwards..

Others experiencing this, reported 9 months ago: http://i.imgur.com/uoeq73h.png

Related: ENTER khook doesn't work either .. have to set some really ugly bindings.

**Comment by limonte** [comment]
@dylanh724 done in v0.2.2

https://github.com/limonte/sweetalert2/commit/3101489965b96857324478710b60302301c4391d

Thanks :+1:
