### ISSUE TITLE
Not working in Safari Mobile iOS 7

### ISSUE THREAD

**Issue by isaiasmac** [limonte/sweetalert2#201]
`}(), Promise.prototype.done = function() {`

that line is given me the error in Mobile Safari on iOS 7.1.2 :

In the console it shows me this: 
**ReferenceError: Can't find variable: Promise**

**Comment by limonte** [comment]
For iOS 7 you need to include Promise polyfill:

```
<script src="bower_components/es6-promise/promise.min.js"></script>
```

**Comment by isaiasmac** [comment]
Thanks @limonte 
It works 👍 👍

**Comment by outluch** [comment]
You need es6-promise.auto, actually. Maybe es6-promise lib changed.
