### ISSUE TITLE
Conflict with Select2 plugin

### ISSUE THREAD

**Issue by fcpauldiaz** [limonte/sweetalert2#206]
I'm using the select2 plugin but it seems that the select input is always rendered with visibility options, this makes that the select2 renders an empty select.

This conflict is shown when I'm not using the select option.

JSFIDDLE: https://jsfiddle.net/qxb2ryo9/5/

**Comment by samturrell** [comment]
Hi Pablo,

I would recommend you make your select2 opt-in rather than globally bound to selector, e.g. $('select.select2').select2()

Sam Turrell

**Comment by fcpauldiaz** [comment]
Thanks Sam, it worked.
