### ISSUE TITLE
Default value on sweet alert select 

### ISSUE THREAD

**Issue by Xosmond** [limonte/sweetalert2#207]
I have a select sweet alert (select with options) and i would like to make a default value, is there anyway? i wanted to make "selected='selected' " but i can't find any option to make this achievable.
Help please.

Thanks

**Comment by limonte** [comment]
There's `inputValue` parameter which you can use for setting the initial value of a select: https://jsfiddle.net/L87xem1y/1/

**Comment by Herz3h** [comment]
I don't think this is documented on the website. `inputValue` doesn't mention select inputs

**Comment by limonte** [comment]
> I don't think this is documented on the website. `inputValue` doesn't mention select inputs

Good point @Herz3h! I just improved the docs: https://sweetalert2.github.io/#input-value
