### ISSUE TITLE
textarea validation

### ISSUE THREAD

**Issue by vieraleonel** [limonte/sweetalert2#209]
When using textarea input, the validator does not detect change like other types. 

For example, if a validate that the input is not empty, when I "reject()" the error appears correctly but when I start typing the error does not disappear. Then, when confirm is clicked, the error disappears but ".then" is not executed. You have to click it again to finally "submit".

Here there is a jsfiddle with the example: https://jsfiddle.net/vieraleonel1/cmqn7s8c/2/

**Comment by limonte** [comment]
Thank you @vieraleonel for reporting this issue!

Fixed in [v4.0.9](https://github.com/limonte/sweetalert2/releases/tag/v4.0.9)
