### ISSUE TITLE
Get current sweetalert instance

### ISSUE THREAD

**Issue by maeishoj** [limonte/sweetalert2#21]
I want to access the current sweetalert instance i have open and depending on what button the user clicks, change some value in the modal.

I cannot see to figure out however how to access the instance, is it possible?

**Comment by limonte** [comment]
@maeishoj I don't think you can change some value in the modal after standard button click. Only way to do this is to use custom buttons by using `html` parameter.

**Comment by limonte** [comment]
this example can be helpful for you:

![](https://i.imgur.com/1PhuGbD.png)

**Comment by maeishoj** [comment]
im using angular and the ngSweetAlert directive, so I was hoping there was a way I could bind a scope variable to "html" parameter.. i will try. thanks.

Would have been awesome to get the current instance even if we could do something like $('.sweet-alert').swal().title = "newTitle".
