### ISSUE TITLE
InvalidCharacterError when using multiple classes

### ISSUE THREAD

**Issue by oli-laban** [limonte/sweetalert2#211]
Using multiple classes, for example `'button success'`, within the swal options results in an `InvalidCharacterError` and prevents the alert from opening.

This can also be seen within the [demos](https://limonte.github.io/sweetalert2/) on the alert labelled '_... and by passing a parameter, you can execute something else for "Cancel"_' where the example uses `successButtonClass: 'btn btn-success'`.

The full error message (which occurs at line 439 of the prettified `sweetalert2.min.js`):

`sweetalert2.min.js:1 Uncaught InvalidCharacterError: Failed to execute 'contains' on 'DOMTokenList': The token provided ('btn btn-success') contains HTML space characters, which are not valid in tokens.`

**Comment by limonte** [comment]
Thank you @oli-laban for reporting this issue! Fixed in [v4.0.10](https://github.com/limonte/sweetalert2/releases/tag/v4.0.10)
