### ISSUE TITLE
On 'dismiss' reject promise with Error instance to supress bluebird warning

### ISSUE THREAD

**Issue by alex-shamshurin** [limonte/sweetalert2#213]
**Warning: a promise was rejected with a non-error**

Due to a historic mistake in JavaScript, the throw statement is allowed to be used with any value, not just errors, and Promises/A+ choosing to inherit this mistake, it is possible to reject a promise with a value that is not an error.

An error is an object that is a instanceof Error. It will at minimum have the properties .stack and .message, which are an absolute must to have for any value that is being used in an automatic propagation mechanism such as exceptions and rejections. This is because errors are usually handled many levels above from where they actually originated from - the error object must have sufficient metadata about it so that its ultimate handler many levels above will have all the information needed for creating a useful high level error report.

Since all objects support having properties you might still wonder why exactly does it have to be an error object and not just any object. In addition to supporting properties, an equally important feature necessary for values that are automatically propagated is the stack trace property (.stack). A stack trace allows you easily find where an error originated from.

You should heed this warning because rejecting a promise with a non-error makes debugging extremely hard and costly. Additionally, if you reject with simple primitives such as undefined (commonly caused by simple calling reject()) you cannot handle errors at all because it's impossible to tell from undefined what exactly went wrong. All you can tell the user is that "something went wrong" and lose them forever

**Comment by limonte** [comment]
Just add `.done()` to `swal()` call, see the example: https://jsfiddle.net/limon/ad3quksn/

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/issues/177

**Comment by limonte** [comment]
@alex-shamshurin in future please try not to copy-paste paragraphs of text but to explain the issue (actual and expected results, how to reproduce the issue, jsfiddle).

**Comment by alex-shamshurin** [comment]
@limonte Ok.

this one 

    swal(…).done();

does not suppress warnings

**Comment by limonte** [comment]
Can you please make the jsfiddle?

**Comment by alex-shamshurin** [comment]
Hmm, jsfiddle has no console output. To where bluebird will log? I think just `reject(new Error('user cancel'))` might be enough.

**Comment by ltvan** [comment]
@alex-shamshurin: it's not because of Error object. That's the "unhandled rejection". @limonte adds `.done()` method which is alias of `.catch(function(){})` but it does not replace the `.done()` method of Bluebird. Check #324 for more information.

**Comment by alex-shamshurin** [comment]
"unhandled rejection" ? But I get warning about reject with not error. 
done() is done, but throwing a Error object is necessary in catch.

**Comment by limonte** [comment]
Starting from [v5.3.3](https://github.com/limonte/sweetalert2/releases/tag/v5.3.3) `.done()` is DEPRECATED and will be removed in next major release. Use `.catch(swal.noop)` instead.
