### ISSUE TITLE
classList + polyfill error

### ISSUE THREAD

**Issue by fmieres** [limonte/sweetalert2#215]
After  44e875c79059322821916ebaefaa43cd2d2c9c9a
i got errors in `elem.classList.add(classes[i]);` if i have already polifylled array.

See example (see console)

https://jsfiddle.net/Illiax/ad3quksn/9/

I don't know if i this is intended or not.

**Comment by limonte** [comment]
can anybody reproduce this issue?

**Comment by acupajoe** [comment]
IE Edge:

https://jsfiddle.net/ad3quksn/10/

SCRIPT5022: InvalidCharacterError
File: sweetalert2.min.js, Line: 1, Column: 9860

**Comment by samturrell** [comment]
Fully reproducible on latest chrome (mac)

**Comment by limonte** [comment]
Something strange here, I just tested in all Windows browsers and still can't reproduce this :cry: 

:beer: for anyone who can fix this invisible for me issue

**Comment by samturrell** [comment]
Ok, so this issue appears to be user error, as seen here, you shouldn't be doing what you're doing: http://stackoverflow.com/a/948379/1375989

Fix:
```
if (!Array.prototype.contains) {
    Object.defineProperty(Array.prototype, 'contains', {
        enumerable: false,
        writable: true,
        value: function(element) {
            return !!~this.indexOf(element);
        }
    });
}
if (!Array.prototype.last){
    Object.defineProperty(Array.prototype, 'last', {
        enumerable: false,
        writable: true,
        value: function() {
            return this[this.length - 1];
        }
    })
};
```

**Comment by limonte** [comment]
Nice research @samturrell ! You're awesome, as always.

**Comment by fmieres** [comment]
And thanks for also giving me advice :)
