### ISSUE TITLE
How to add count down in display text

### ISSUE THREAD

**Issue by essivision** [limonte/sweetalert2#216]
Hi,

Thanks for your plugin. I wan to use count down in ajax request but doesn't any options for this work. I think you can add this feature to your library. I create manually count down but it doesn't work correctly after 2 times. 

My code: http://codepen.io/essvision/pen/QEQmGY?editors=1011

**Comment by limonte** [comment]
Countdown functionality most probably won't be implemented to swal2, you should do it by yourself for your project.
