### ISSUE TITLE
Safari: <swal2 input: 'file'> doesn't work if <swal2 input: 'text'> was shown before

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#217]
Bug can be reproduced on https://limonte.github.io/sweetalert2/ in Safari.

Steps to reproduce:

1. Launch modal with `input: 'text'`
2. Close it
3. Launch modal with `input: 'file'`

Input inside the modal won't have `type="file"`

**Comment by limonte** [comment]
Related SO question: http://stackoverflow.com/q/38466760/1331425

**Comment by samturrell** [comment]
@limonte - I'd probably remove from dom, update, and then reinsert.

**Comment by limonte** [comment]
@samturrell yeah, inserting a new input will fix this issue for sure.
