### ISSUE TITLE
Exception during application startup in IE 9 (elem.classList)

### ISSUE THREAD

**Issue by fracz** [limonte/sweetalert2#218]
I know you support IE10+. But this is the only library that prevents my app from running on IE9 in an *acceptable* way, because an exception is being thrown on this code **during application startup**:

```
return elem.classList.contains(className);
```

With message

```
Cannot read property „contains” for undefined on empty call.
```

It is [unsupported](http://caniuse.com/#search=classList), indeed. But IMO, it should not fail during application startup (module load). I would accept it failing when showing the first dialog (well, dear user, no modals in IE9! go and update your browser).

As a workaround, one may include the https://github.com/eligrey/classList.js. Still, it's sad that the whole app does not start because we use a few dialogs in rare cases.

**Comment by limonte** [comment]
IE10+ means IE10+, not IE10+ with partial IE9 support.

Related issue: https://github.com/limonte/sweetalert2/issues/140

**Comment by fracz** [comment]
IE10+ means that this lib can display dialog on IE10+.

It should not mean that you cannot use your application ON IE10- even if you do not display any.
