### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by Tklaversma** [limonte/sweetalert2#220]
Hi,

When a sweetalert opens up, the button (for example 'Ok') has the background-color of the hover. But when you hover over the button and then unhover, the button has the actual background-color it suppose to have (or at least the background-color is now lighter than before hovered).

So the background-color is different before first hover and when a button has been hovered.

**Comment by limonte** [comment]
Thank you @Tklaversma for reporting this, fixed in [v4.0.12](https://github.com/limonte/sweetalert2/releases/tag/v4.0.12)
