### ISSUE TITLE
Uncaught (in promise) esc (or cancel)

### ISSUE THREAD

**Issue by Tklaversma** [limonte/sweetalert2#221]
When pressing cancel or esc when using ajax with swal2, we get a `Uncaught (in promise) esc (or cancel)` error.

See [jsfiddle](https://jsfiddle.net/ad3quksn/18/).

Anyone got an idea?

**EDIT:**
It's not only when using ajax, but also when just using just an info box. See [jsfiddle](https://jsfiddle.net/ad3quksn/20/). I think it has to do with the fact that I'm using jQuery 3.1.0.

**Comment by samturrell** [comment]
Add .done(); to the end of your swal call if not providing callbacks.

https://jsfiddle.net/ad3quksn/19/

**Comment by Tklaversma** [comment]
@samturrell The problem is fixed when using ajax. But still on my simple modal I see the error (see [jsfiddle](https://jsfiddle.net/ad3quksn/20/)).

**Comment by samturrell** [comment]
You HAVE to use `.done()` on any swal call that doesn't provide callbacks in order to suppress the exception thrown by the Promise. This isn't ideal, but it's just the nature of how Promises work.

**Comment by Tklaversma** [comment]
@samturrell Maybe a good idea to add this to the documentataion?

**Comment by samturrell** [comment]
Yep, wasn't aware it wasn't added. @limonte - could you add please :)

**Comment by birjolaxew** [comment]
This is because the promise will reject if the background or <kbd>Esc</kbd> is used to close the modal. If you do not catch the rejection, it'll be thrown as an error. This is what `Uncaught (in promise)` means.

To solve this, simply `.catch()` the promise. Note that the solution suggested by @samturrell, which is to use `.done()`, is jQuery-only. No such method exists in the JS promise specification. The native JS equivalent would be to do

    swal("...")
        .catch(e => {}) // catch the rejection, but do nothing with it. Then continue to next `.then`
        .then( ... ); // this will be called whether the promise rejects or resolves

I agree though, this definitely should be included in the documentation.

**Comment by limonte** [comment]
@birjolaxew 

>  Note that the solution suggested by @samturrell, which is to use .done(), is jQuery-only. No such method exists in the JS promise specification. The native JS equivalent would be to do

Not true. `done()` helper isn't related to jQuery, it's implemented to swal2: https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.js#L955-L962

> I agree though, this definitely should be made more clear in the documentation.

Will be done soon. Thank you @birjolaxew for your feedback!

**Comment by birjolaxew** [comment]
@limonte Huh, didn't expect that. Thanks for the correction.

**Comment by Tklaversma** [comment]
Ok, so the problem is solved by adding `done()` to the `swal()`'s, but this is not correctly working in IE11 with the `promise.min.js`included in the header.

When you look at my [fiddle](https://jsfiddle.net/ad3quksn/27/) in IE11, you'll will notice when you clickon Escape or just cancel....IE11 will show another modal and prompt the error `The method done() is not supported by this object` in the console.

Am I doing something wrong in my Fiddle or is `done()` just not supported by the included `promise.min.js`?

Any help to get this working in IE11 as well would be much appreciated!

**Comment by limonte** [comment]
@Tklaversma This issue is related to the order of including swal2 and Promise polyfill. To solve it make sure that Promise polyfill is included **BEFORE** swal2.

**Comment by limonte** [comment]
Resolved in #240. Thanks to @birjolaxew :beers:

**Comment by ElegantSudo** [comment]
How exactly does this work? I'm trying:

```
How exactly does this work? I'm trying:

```js
swal({
	title: "Are you sure?",
	text: "You won't be able to revert this.",
	type: "warning",
	showCancelButton: true,
	confirmButtonText: "Yes, delete it!",
	confirmButtonColor: "#d33",
	cancelButtonColor: "#C2BCBC",
}).then(ajaxFunc).catch(swal.noop)
```

And it's not working as described.

**Comment by limonte** [comment]
Your example works like described in docs. Be sure you're using the latest version.

**Comment by ElegantSudo** [comment]
@limonte the new version gives my application a `swal is not defined` error.

**Comment by birjolaxew** [comment]
@ElegantSudo You're really going to have to include more details when you report an issue; explain what you're doing, include code examples, so on and so forth. We can't help you if "it's not working" is all you give us

**Comment by ElegantSudo** [comment]
@birjolaxew on the newest Meteor version, it's in my lib folder, I think you're using the var keyword to define swal whereas before you didn't.

**Comment by birjolaxew** [comment]
@ElegantStudio I don't think anything has changed in our definition process lately. We use Rollup to package our library as a UMD module, so it should be exposed regardless of how it's loaded.

I'm not particularly familiar with Meteor, but if you find the problem (or can replicate it in a JSFiddle or similar), that'd be helpful
