### ISSUE TITLE
Selected for radio or select

### ISSUE THREAD

**Issue by thelastinuit** [limonte/sweetalert2#222]
Is there anyway to set a selected radio or select input?

If not, could it be a new feat?

**Comment by samturrell** [comment]
The `inputValue` option can be used to set the initial value, or are you talking in terms of setting it afterwards via an API?

**Comment by limonte** [comment]
Duplicate of https://github.com/limonte/sweetalert2/issues/207

**Comment by thelastinuit** [comment]
@samturrell inputValue works for input select/radio type?
