### ISSUE TITLE
How do I disable/enable only and only the confirm button, based on some boolean condition(angularjs)

### ISSUE THREAD

**Issue by sbnighut** [limonte/sweetalert2#226]
For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue. Thank you!

JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

**Comment by limonte** [comment]
I just added `swal.disableConfirmButton()`/`swal.enableConfirmButton()` and released [v4.0.14](https://github.com/limonte/sweetalert2/releases/tag/v4.0.14).

I can't help you with AngularJS implementation as this project isn't related to any framework.

**Comment by sbnighut** [comment]
Thanks limonte, this would help

**Comment by MrPardeep** [comment]
@limonte How can we use these method's any working example would be great !!

**Comment by ZeeshanAdilButt** [comment]
These methods can be used in any options provided by sweet alert like:

  ```
swal({
            title: 'Please Enter Page Name',
            input: 'text',
            inputValue: someValuehere,
            confirmButtonText: 'Save',
            showLoaderOnConfirm: true,
            onOpen: function (){
                swal.disableConfirmButton();
            }
})
```

**Comment by ZeeshanAdilButt** [comment]
@limonte 

How can I trigger something on any **input** into the sweet alert's text box, is there something like `onInput` or something similar. I need to use `swal.enableConfirmButton()` on input.

**Comment by slevy85** [comment]
If you want to allow the user to confirm the popup depending on his input youcan use the property `inputValidator`.
```
swal({
{...}
 inputValidator: (value) => {
         if(value) return;
         return 'Please give a value'
        },
})
```

**Comment by ZeeshanAdilButt** [comment]
@slevy85 Thanks for the update.

however, I found a better solution to achieve this at StackOverflow:

```
swal({
  input: 'text',
  onOpen: function () {
    swal.disableConfirmButton();
    swal.getInput().addEventListener('keyup', function(e) {
      if(e.target.value === '') {
        swal.disableConfirmButton();
      } else {
        swal.enableConfirmButton();
      }
    })
  }
});
```

Thanks to @limonte

**Comment by kheengz** [comment]
this works for me `$(".confirm").attr('disabled', 'disabled'); `
```
  swal({   
            title: "Want to delete this item?",   
            text: "You will not be able to undo this action!",   
            type: "warning",   
            showCancelButton: true,   
            confirmButtonColor: "#DD6B55",   
            confirmButtonText: "Yes, delete it!",   
            closeOnConfirm: false 
        }, function(){ 
          $(".confirm").attr('disabled', 'disabled'); 

        });
```

**Comment by FredyWenger** [comment]
For **Swal2**, the button seems to be: swal2-confirm:
 $(".swal2-confirm").attr('disabled', 'disabled'); 
seems to work, to disable the button.

**Comment by Anupam199620** [comment]
Found a better solution:-
let html = 'Hi! this is a demo.';
Swal.fire({
    title: 'Want to delete this item?',
    showCancelButton: true,
    confirmButtonColor: 'rgb(20, 155, 177)',
    cancelButtonColor: '#757575',
    confirmButtonText: 'Confirm',
    showCloseButton: true,
    html: html,
    didOpen: function (){
        $(".swal2-confirm").attr('disabled', true);
    }
})
