### ISSUE TITLE
Ajax goes away when processing

### ISSUE THREAD

**Issue by Kiroteryn** [limonte/sweetalert2#228]
https://jsfiddle.net/pyw0on3h/
http://recordit.co/EWfMeIlanJ

You can see the loading circle for a brief 0.2 seconds, then it goes away, only to return when finished processing.

Shouldn't this code keep the window open during processing? 

<details> 
  <summary>My question: **How can I keep the swal up, with the spinning ajax, until I want to .close() it or pop up a new success swal?** (Too many thoughts, trial and error below, dropped down via the arrow, if you want to see it)</summary>
I was looking at this:

https://limonte.github.io/sweetalert2/#ajax-request
from https://github.com/limonte/sweetalert2/issues/193

and it doesn't seem to answer the question:

**preConfirm** seems to be BEFORE the ajax is actually sent, so it would be just a fake 2 seconds vs the old version that would last until the real Ajax returned and opened a success **swal** or to simply **swal.close()**, so hmm.. I'm either not understanding the newer syntax or this question/above ticket is still unanswered.

By referencing here: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2 , this does not seem like a replacement at all 

**How can I indefinitely show the loading window like _CloseOnConfirm_ did like I'm trying to do in my simple fiddle example above?**

**EDIT:** I'll be googling more about Promises to make sure I'm not misunderstanding promises - is THIS where you'd actually make the ajax call then? Hmm, brb Google

**EDIT 2:** Ah I misunderstood promises, in general. At first, I thought a promise was something that was only included in Swal2 until I realized it's external. So I put the full ajax in preConfirm and can just simply close/show a success swal under then()? Will close if I get it working myself, WIP, if I'm getting this

**EDIT 3:** **...but how can I tell if they clicked accept and not cancel? Or preConfirm only fires when submit (and not cancel)?

**THE FINAL QUESTION:**
Ok after some trial and error, I got things MOSTLY working - seems that you handle the entire ajax in the preConfirm , and this only happens after a proper submit (not a cancel or null):

(with the old versions I'd just swal.enableLoading(), do what I need to do, then either swal.close() or show a success swal)

However, the question still remains -- In the example above in the migration page, only a timeout is offered; if I get rid of the timeout, the same issue occurs (the box goes away, and a new one comes up later): **How can I keep the swal up, with the spinning ajax, until I want to .close() it or pop up a new success swal?**
</details>

**EDIT:** Ah, the ajax itself goes in the preConfirm, so I misunderstood promises -- **However,** the question still remains ..

**EDIT 2:** I have a workaround, but not an answer: Simply never resolve() the promise. However, I'm sure the creators would shoot me if they saw my code doing this. Any proper way to handle this? Perhaps pass the resolve to my other functions, then resolve() it just before I popup a success swal?

(+Edited for TL;DR)

**Comment by limonte** [comment]
The largest issue for now, but I don't understand what you asking about.

**Comment by Kiroteryn** [comment]
@limonte are you sure.. that you know what _you_ are talking about..? I was searching for an answer to my issue, and so many others have had similar issues which you just ninja close without actually resolving. You realize this is an issue tracker?

Every closed topic I can find has you commenting something like "I don't understand", links to a generic FAQ, or just closing the issue if you simply feel like not answering it.

Awesome product, but man, you are the most toxic person I've seen here just looking at the closed ticket history finding an answer.

**Comment by acupajoe** [comment]
@Kiroteryn yes this is an issue tracker - which means that the tickets here are for tracking areas in the library that do not work or fail to work consistently. Most of the tickets you mentioned @limonte closing 'early' are tickets that a user opened because they didn't read through the documentation or were asking questions that were already answered. Since those issues are focused more on 'how do I do this?' rather than 'this is a broken functionality' they don't technically qualify as issues with the library.

However this does raise the question @limonte, should we create a Stackoverflow tag for Sweetalert for tracking actual coding requests?

In the meantime, to answer your question on promises, you just have to pass a reference to your promise resolve function within your outside functions. See the example here with your console open: https://jsfiddle.net/pyw0on3h/1/

**Comment by limonte** [comment]
> should we create a Stackoverflow tag for Sweetalert for tracking actual coding requests?

`sweetalert` tag already exists on SO: http://stackoverflow.com/questions/tagged/sweetalert , I subscribed to all these questions and help sometimes if I can:

- http://stackoverflow.com/a/38086157/1331425
- http://stackoverflow.com/a/37795106/1331425
- http://stackoverflow.com/a/37682082/1331425

**Comment by acupajoe** [comment]
@limonte wonderful, in the future I will ask users to create a stackoverflow question in these cases

**Comment by limonte** [comment]
> in the future I will ask users to create a stackoverflow question in these cases

Thanks! I think it would be nice to inform contributors about StackOverflow before submitting issues: https://github.com/limonte/sweetalert2/pull/230
