### ISSUE TITLE
Call function after timeout

### ISSUE THREAD

**Issue by Djip** [limonte/sweetalert2#23]
Hi

I really miss the function to attach a function when a timer timesout, rather than when a user clicks the ok button.

**Comment by limonte** [comment]
This isn't related to swal2. You can implement timeout manually.

**Comment by Djip** [comment]
So how do i attach a function to when swals timer times out ?

**Comment by limonte** [comment]
by reading manual about `setTimeout()` JS method ;)

**Comment by Djip** [comment]
Well well, not really helped me anything, was already implemented, just didn't knew since i came from Sweetalert to Sweetalert2.

swal({
        title: "Logging in!",
        type : "success",
        confirmButtonColor: "#A5DC86",
        timer: 1000
}, function(){
        location.reload();
});

**Comment by Tanujasingh** [comment]
Only Close the popup without reloading the page..

swal({
        title: "Logging in!",
        type : "success",
        confirmButtonColor: "#A5DC86",
        timer: 1000
}, function(){
        swal.close();
});
