### ISSUE TITLE
Unknown parameter "customClass"

### ISSUE THREAD

**Issue by Tklaversma** [limonte/sweetalert2#237]
Since 4.1.0 I'm getting the error `SweetAlert2: Unknown parameter "customClass"`, although the `customClass` parameter is still working (and I hope it will keep working!!!).

```
swal({
    title             : __('Weet u het zeker?'),
    html              : __('Het is niet mogelijk om dit te herstellen!') + "",
    type              : 'warning',
    showCancelButton  : true,
    confirmButtonText : __('Ja, verwijder'),
    customClass       : 'delete'
});
```

The code shown above will add the class `delete` to the direct child `swal2-modal` of the container. Doing so, I can adjust the modal for specific circumstances, which is quite handy!

Is this option going to be deleted or is it replaced?

**EDIT:**
This problem is solved btw by just adding `customClass : null` to the default parameters. Can you do this and repost 4.1.1 :D?

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/releases/tag/v4.1.1
