### ISSUE TITLE
New input "type" number or masks

### ISSUE THREAD

**Issue by alissonbarison** [limonte/sweetalert2#238]
You could have a new type of input number or can add masks

**Comment by limonte** [comment]
Nice suggestion, we'll try to add the input type number after (or in scope of) merging https://github.com/limonte/sweetalert2/tree/feature/multiple-inputs

**Comment by waveminded** [comment]
That would be great!  I was just looking to see if it supported the type="tel" for loading the number keyboard on mobile devices.

**Comment by limonte** [comment]
Done in [v4.2.5](https://github.com/limonte/sweetalert2/releases/tag/v4.2.5)

**Comment by phiterf** [comment]
I needed a solution in order to make my input have a mask, so I used mask.js and with this code:

```
onOpen: function () {
        $('.swal2-input').mask('0,99999');
}
```

Perhaps this could help on the masked input issue ;)

**Comment by matheusbozetti** [comment]
@phiter > I needed a solution in order to make my input have a mask, so I used mask.js with this code:
> 
> ```
> onOpen: function () {
>         $('.swal2-input').mask('0,99999');
> }
> ```
> 
> Perhaps this could help on the masked input issue ;)

Thanks, man. It was exactly what I needed.
