### ISSUE TITLE
Fadeout animation width issue (small screens)

### ISSUE THREAD

**Issue by birjolaxew** [limonte/sweetalert2#242]
On smaller screens (~525px wide) the width of alerts gets increased slightly when fading out. This results in a slight jump when fading out.
[Related JSFiddle](http://jsfiddle.net/ad3quksn/30/). Reproduced on Chrome, IE11 and Edge.

![GIF example](https://cloud.githubusercontent.com/assets/4542461/17484808/f6e8c688-5d8b-11e6-88d9-5d290b577240.gif)

The below image shows two frames, one immediately before the hide animation starts, one immediately after. The window width was ~515px. The effect is more visible on smaller screens.

![Annotated screenshots](https://cloud.githubusercontent.com/assets/4542461/17484832/0dcad9d6-5d8c-11e6-8da5-db1bdf5abf4e.png)

**Comment by birjolaxew** [comment]
Seems to come from [dom.js#L236-L241](https://github.com/limonte/sweetalert2/blob/master/src/utils/dom.js#L236-L241) removing the media query generated by [sweetalert2.js](https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.js#L28-L44). This should be moved to *after* the animation ends.

**Comment by limonte** [comment]
@birjolaxew perfectly done! [v4.1.3](https://github.com/limonte/sweetalert2/releases/tag/v4.1.3)
