### ISSUE TITLE
Add option to have cancel be default action

### ISSUE THREAD

**Issue by angineering** [limonte/sweetalert2#244]
Currently setting `reverseButtons: true` does not reverse the behaviour of the space/enter key to click "cancel" instead of "confirm". This means that pressing enter still uses the "confirm" button.

It would be nice to reverse this behaviour when reversing the button positions, so defensive behaviour can be the default in that case.

It looks like this behaviour primarily lives here: https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.js#L522-L523

**Comment by birjolaxew** [comment]
In addition to sweetalert2.js#L522-L523 (which handles enter/space when it's not from an element), we should also focus the cancel button ([#L764](https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.js#L764), which always targets `$confirmButton` because of [dom.j#L40](https://github.com/limonte/sweetalert2/blob/master/src/utils/dom.js#L40))

**Comment by limonte** [comment]
In my opinion `reverseButtons` parameter is related to the order of buttons in the modal, it should not change default focused button.

If anyone of collaborators thinks I'm wrong, feel free to reopen this issue.

**Comment by angineering** [comment]
@limonte would it be an acceptable option to add a new parameter for reversing/changing default focused button?

**Comment by birjolaxew** [comment]
I too feel that we lack a way to change default behavior. It can be useful to have cancel be the default.

We should consider whether this should be bound to button order, though - people might want the default to be on the left/right depending on the rest of their system, so we might want to add it as another option.

**Comment by limonte** [comment]
> would it be an acceptable option to add a new parameter for reversing/changing default focused button?

I just looked for similar issues on t4t5/sweetalert and there are some, so I should agree with you and add that parameter, even if I personally don't see how it can be useful :)

I'm planning to make it this way `focusCancel: boolean` - what do you think @birjolaxew ?

**Comment by birjolaxew** [comment]
@limonte Seems fine to me. If we're planning to add more complex options (eg. multiple buttons) later, then I'd be careful about how specific the property is. I'd say it's all good though (and adding more buttons/focus states would make the options more complex than we likely want anyway).

**Comment by limonte** [comment]
Done in [v4.1.6](https://github.com/limonte/sweetalert2/releases/tag/v4.1.6)

**Comment by angineering** [comment]
Thank you very much! I really appreciate the quick turnaround on this.
