### ISSUE TITLE
ignore customClass

### ISSUE THREAD

**Issue by hannesLP** [limonte/sweetalert2#253]
after opening and closing an alert with a customClass (eg. 'swal-wide') and open it afterwords with another customClass (eg. 'swal-small') the prevoius class remains and the new alert has the still the class 'swal-wide'

**Comment by birjolaxew** [comment]
Could you provide a JSFiddle? [I cannot reproduce it.](https://jsfiddle.net/usoa6ou5/)

**Comment by limonte** [comment]
This issue was fixes couple of months ago. It's fixed in latest, update your dependency.

**Comment by birjolaxew** [comment]
(specific version this was fixed in: [v0.4.5](https://github.com/limonte/sweetalert2/releases/tag/v0.4.5))

**Comment by limonte** [comment]
@birjolaxew wow. How have you found that release so fast? Are you magician? :)

**Comment by birjolaxew** [comment]
@limonte I am omniscient! (well, [the search is](https://github.com/limonte/sweetalert2/issues?utf8=%E2%9C%93&q=is%3Aissue%20customClass))

**Comment by hannesLP** [comment]
i've got it: THANKS
