### ISSUE TITLE
Can't get symlink working in gh-pages

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#256]
Today [Simpler GitHub Pages publishing](https://github.com/blog/2228-simpler-github-pages-publishing) was introduced.

I'm trying to move the page with examples from `gh-pages` branch to `/docs` folder of `master` branch.

Currently, without success as I can't get the [symlink to `dist` folder](https://github.com/limonte/sweetalert2/blob/master/docs/dist) working. After pushing to master, I'm instantly receiving this email: 

> The page build failed with the following error:
> 
> The symbolic link `/dist` targets a file which does not exist within your site's repository. For more information, see https://help.github.com/articles/page-build-failed-symlink-does-not-exist-within-your-site-s-repository.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds

Does anyone know how to workaround this and make symlink working?

**Comment by birjolaxew** [comment]
Just throwing out ideas here, since I won't be able to test until tomorrow evening:

- Does the symlink work on your OS? (content seems fine to me, so I suppose it should)
- Does Jekyll compile [locally](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/)? (if so, something about git or GitHub is messing it up)
- Tried with a trailing slash in the symlink? (definitely shouldn't change a thing, but might as well try)
- Tried if a symlink to a file works?

**Comment by limonte** [comment]
@birjolaxew 

> Does the symlink work on your OS? (content seems fine to me, so I suppose it should)

Yes.

> Does Jekyll compile locally? (if so, something about git or GitHub is messing it up)

I succeeded to compile local version, and the same thing locally - 404 for symlinks. It seems that Jekyll doesn't support symlinks at all: https://github.com/jekyll/jekyll/pull/315

---

Currently, there are symlinks in `gh-pages` branch which are working by adding empty [`.nojekyll`](https://github.com/limonte/sweetalert2/blob/gh-pages/.nojekyll) file.

Unfortunately, it seems that `.nojekyll` does nothing inside the `docs` folder.

**Comment by limonte** [comment]
Related Y Combinator topic: https://news.ycombinator.com/item?id=12306658

**Comment by limonte** [comment]
Done in https://github.com/limonte/sweetalert2/commit/24e33e559723d92103c17e32ba592380a6dab19f

GitHub pages are now at master, not at master/docs:
![ifzoebx](https://cloud.githubusercontent.com/assets/6059356/17941963/b69d2b80-6a35-11e6-9c6a-dc0661c74bf7.png)
