### ISSUE TITLE
queue function bug when animation is true

### ISSUE THREAD

**Issue by erbelair** [limonte/sweetalert2#262]
If animation is on (by default), and the `swal.queue()` function is called, you cannot use the escape key to close the dialog after you advance one step (unless you do so quicker than the animation takes to complete).
This is caused by the `dom.resetPrevState();` call in the `sweetAlert.closeModal()` function. The `dom.resetPrevState()` function sets the `window.onkeydown` event listener (among other things). Since our modal for the second step has opened before the modal for the first step has completed its closing animation, the `window.onkeydown` listener is set to null (or whatever it was previously) sometime after the second modal shows.

Test in the following fiddle:
https://jsfiddle.net/erb423/wxgfet52/

1. Click 'show' button
2. Click 'next' button and wait a second
3. Press escape. The modal should close, but it does not.

I would propose calling `dom.resetPrevState()` immediately towards the end of the `sweetAlert.closeModal()` function, rather than waiting until the animation completes.

**Comment by limonte** [comment]
Thank you @erbelair for such a detailed bug-report.

> I would propose calling dom.resetPrevState() immediately towards the end of the sweetAlert.closeModal() function, rather than waiting until the animation completes.

Not so simple, as this will undone https://github.com/limonte/sweetalert2/pull/243/commits/553a69832a34beb26f2575113feb31ccd96b26bd

We'll take care of it in a couple of days as currently there's WIP on the project structure, hope this issue isn't critical for you and you can wait.

**Comment by erbelair** [comment]
Ah, I figured it was put there for a reason. Well that is good to know. Thanks.
