### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by simo9000** [limonte/sweetalert2#264]
I was writing a test case for the [State Machine PR](https://github.com/limonte/sweetalert2/pull/241) and I discovered something. The technique (shown below) that was used in the 'queue' test, which I copied for 'dynamic queue', to test the title of alerts that follow the initial one does not work. 

~~~~ 
setTimeout(function() {
  assert.equal('Step 2', $('.swal2-modal h2').text());
  swal.clickConfirm();
});
~~~~ 

If you mutate the asserted value the test still passes. I tried adding a second parameter (milliseconds) to the setTimeout call and it did not help. Right now only the first assert line in these test cases is actually testing anything. I was going to rely on a series of title assertions to ensure the state machine proceeds as intended.

**Comment by birjolaxew** [comment]
Looks to me like the queue test simply isn't using QUnit properly. It should be doing [an async test](https://api.qunitjs.com/async/).

**Comment by limonte** [comment]
Fixed now, thanks guys!
