### ISSUE TITLE
Add parameters to define width and height for modal

### ISSUE THREAD

**Issue by Rikk** [limonte/sweetalert2#265]
How to define variable width/height for modal? Looks like it can't calculate things properly it these are used. Eg.: `width: '50%'` , `width: '5vw'` etc.

Furthermore, I think `max-width` and `max-height` are also important to have, especially for images.

**Comment by limonte** [comment]
Nice request @Rikk Give me some time to test if we can bring these improvements to swal2.

**Comment by limonte** [comment]
Not so simple to add these things. Could you please add the use-case examples for all parameters you've requested, e.g. instead "important to have" I'd like to see "important to have because ... , here's the example: ..."

I'm requesting this because I personally don't see how it could be so "important to have".

**Comment by acupajoe** [comment]
@limonte I can think of a few use cases. With the additional parameters and event bindings that swal2 supports now, it's becoming more than just a dialog modal. You could use swal2 to display videos or dynamic content, videos, iframes, images, etc. that it could be useful to have sized to a specific standard. 

I do realize these uses cases go beyond what the  original use cases for what swal and swal2 were, but  I don't necessarily think that's a bad thing.

Thoughts?

**Comment by Rikk** [comment]
Important for mobile, fixed-widths usually will be cut on small screens. A good ability for a popup is to automatically adapt itself to the environment it is present.
I see swal2 (maybe also original swal) uses margin-left and a px value for width to calculate its position...
```js
modal.style.width = params.width + 'px';
modal.style.marginLeft = -params.width / 2 + 'px';
```
Instead why doesn't it calculate window.width, get its own width, then find the center? And because it is position:fixed, maybe top and left values are only things it needs to calculate to position itself.

**Comment by limonte** [comment]
Agree with you guys. I added the ability to set `width` in percents to [v4.2.2](https://github.com/limonte/sweetalert2/releases/tag/v4.2.2). Let's not complicate the plugin any further for now with `height`, `max-width`, `max-height`, etc.
