### ISSUE TITLE
Uncaught ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by peratik** [limonte/sweetalert2#267]
Hello

I want to use sweetalert2 on android webview, it says:
Uncaught ReferenceError: Promise is not defined

Please advice.

Thank you

**Comment by limonte** [comment]
Promises are not supported on 4.4: http://caniuse.com/#search=promise
you have to implement a polifill for this.
Take a look at https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2#1-ie-support
