### ISSUE TITLE
Highlight on Android Webview

### ISSUE THREAD

**Issue by peratik** [limonte/sweetalert2#268]
Hello

There is a highlight on sweetalert (Android Webview)

This solution is not fixed:

http://danbarnett.net/how-to-hide-android-webview-highlight-border-or-change-its-color-142.html

Please advice

Thank you

**Comment by limonte** [comment]
Will be fixed in next release, I'll notify you about it here.

**Comment by birjolaxew** [comment]
Is there a screenshot of this? I can't replicate on my Android (admittedly not Wear) - only outline I see is the focus outline.

**Comment by peratik** [comment]
Screenshot:

![photo_2016-08-29_16-36-53](https://cloud.githubusercontent.com/assets/6568353/18050976/12747524-6e07-11e6-885c-1cf98a4e2707.jpg)

**Comment by birjolaxew** [comment]
@peratik Thank you! That definitely seems like something we should have fixed. I still can't reproduce on my Android (using a webview browser) though.

Could you please verify that [it happens on this JSFiddle](https://jsfiddle.net/c97h2pv2/embedded/result/), or possibly [modify it so it does happen](https://jsfiddle.net/c97h2pv2/)?

**Comment by peratik** [comment]
![photo_2016-08-29_16-59-27](https://cloud.githubusercontent.com/assets/6568353/18051468/02f2159a-6e0a-11e6-97c3-a14670866d2b.jpg)

**Comment by birjolaxew** [comment]
Well, I'm stumped. Seems like it might be an issue with an older webview (are you using Android 4.0?) misapplying the tap highlight (seems to be where the button was halfway through the animation).

We could either remove the tap highlight, thus removing an expected UI pattern, or we could file it as wont-fix due to old/buggy browser. There are obviously pros and cons of both.

**Comment by peratik** [comment]
Yes it is old webview.

**Comment by limonte** [comment]
@peratik should be fixed in [v4.2.5](https://github.com/limonte/sweetalert2/releases/tag/v4.2.5)
