### ISSUE TITLE
Improve documentation about dynamic queues

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#270]
I'm not happy with the part of the documentation for the State Machine feature. 

As to me, this are things that should be improved: 

- the usage example, it should be more clear and simple
- separate the `swal.queue()` description from the `Methods` table to the standalone section.

**Comment by simo9000** [comment]
I can help with this if you want. The [fiddle](https://jsfiddle.net/r5ssrjhu/4/) from [#261](https://github.com/limonte/sweetalert2/issues/261) might be a better usage example.

**Comment by limonte** [comment]
Thank you @simo9000! I think we will need your help here. To make really nice example with the State Machine functionality, I think we should probably implement Progress bar with numbered steps: #273

Please leave your opinion about it. Thanks!

**Comment by simo9000** [comment]
Alright, I can work on a standalone section for the state machine function in the readme file while the numbered steps feature is completed. Some things we should agree on for the usage example are:

1. Number of steps to be included
2. Which queue altering methods to demonstrate (the breadth of which will depend on no. 1.
3. What we should have the handlers do besides alter the queue (i.e. handle input, ajax...)

Once we have settled on these then i can make the new usage example in a fiddle for us to review. This will streamline the PR.

**Comment by birjolaxew** [comment]
I think the most important thing to is to include an example that shows why you'd use the state machine over the normal method (and I must admit, I'm struggling to find an example).

**Comment by simo9000** [comment]
@birjolaxew i'll admit the use cases for the state machine are not abundant but they do exist. Here is a [fiddle](https://jsfiddle.net/simo9000/o3fjk5sa/4/) of a simple example where an add could be inserted via a state machine given the right circumstances.

**Comment by limonte** [comment]
I refactored dynamic queues functionality to be much simpler:
https://limonte.github.io/sweetalert2/#dynamic-queue

@simo9000 You can either refactor your projects to use a new way of dynamic queues of stay on 4.2.* version.

**Comment by simo9000** [comment]
@limonte looks good. That is simpler as it keeps the interface more imperative.
