### ISSUE TITLE
Should we have range value beside input[type=range] ?

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#271]
I just added `input[type=range]` support, here's the example: https://limonte.github.io/sweetalert2/#input-range

My question is to collaborators and other UI specialists: should we have by default `<output>` tag with current range value? As you probably know, the native behaviour for `input[type=range]` is to show slider only, without value:

![](https://i.imgur.com/2qz1FpT.png)

As to me it would be nice for plugin users to have something like this by default:

![](https://i.imgur.com/pQ5zL2Z.png)

I think, in most cases, it's useful to see the current value.

Thoughts?

**Comment by Silvester20** [comment]
In my opinion you should show the current range value of the slider by default, but a option to hide the chosen value is useful too in some cases.

**Comment by acupajoe** [comment]
I would also agree that a range slider would be useful to have in sweetalert. However, I don't think the html5 range slider itself will be particularly helpful without a lot of additional parameters and stylings. Might we add just another dependency instead of the standard HTML5 range slider? 

My favorite is currently: 
http://refreshless.com/nouislider/ 

Otherwise, I agree, the item value should either be shown while dragging (over the slider) or permanently in its own div.

**Comment by limonte** [comment]
Done in [v4.3.2](https://github.com/limonte/sweetalert2/releases/tag/v4.3.2)

**Comment by ledzgio** [comment]
It would be a nice idea to have the **output** value number editable as an input field, doing this it's easier to use the range slider also with smartphones. I noticed sometimes doesn't work properly, especially when min and step are very small (in my case is 0.001 and this makes hard sometimes to select the proper value).

**Comment by gverni** [comment]
I personally don't use the slider a lot, but I agree that is not really _mobile-friendly_. @limonte if you agree this is a useful feature (I personally do) I can look into implementing it?

**Comment by limonte** [comment]
It feels wrong to convert _output_ into _input_

I can't find any example of a similar solution, so I don't think the use-case is widely used and should be implemented in the scope of the plugin for popups.

If there's a slide range from 1 to 1000 with step 0.001, IMO the issue isn't in the UX of a slider, the issue is in the decision of UX developer.

**Comment by limonte** [comment]
Here's the solution of `input[type=range]` + `input[type=number]`: 

- source: https://glitch.com/edit/#!/caterwauling-plywood?path=swal2.js:28:64
- live demo: https://caterwauling-plywood.glitch.me/

The solution is quite straightforward, but I believe we shouldn't add the additional complexity to the codebase becase the use-case is quite rare.

**Comment by gverni** [comment]
> It feels wrong to convert output into input

I completely agree with you. Another way of looking at it though, is to consider range + output as single _composite_ input element: in this case both elements _should_ be able to change the value of the control. I feel this is extremely useful to give a fine grained control on small screen devices. But at the end of the day this has nothing to do (strictly) with Sweetalert2, and more to do with the `range` input (see my next comment as well)

> I believe we shouldn't add the additional complexity to the codebase becase the use-case is quite rare

This is a very good point. So even though I consider that useful, I agree we should not complicate the code base. 

> Here's the solution of input[type=range] + input[type=number]:

I like that @limonte. I'll add it to the [sweetalert2-examples](https://github.com/sweetalert2/sweetalert2-examples) repo. As I said above, it may be useful for those that choose to have a range that should work (with fine grained values) on small screen as well.

**Comment by ledzgio** [comment]
> Here's the solution of `input[type=range]` + `input[type=number]`:
> 
> * source: https://glitch.com/edit/#!/caterwauling-plywood?path=swal2.js:28:64
> * live demo: https://caterwauling-plywood.glitch.me/
> 
> The solution is quite straightforward, but I believe we shouldn't add the additional complexity to the codebase becase the use-case is quite rare.

This works perfect for what I need to do. Thank you.
