### ISSUE TITLE
Progress bar with numbered steps - show steps for queues

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#273]
Progress bar with numbered steps functionality will be useful beside modal queues:

![](http://i.stack.imgur.com/mgdfI.png)

I'm working on naming this functionality and currently I'm here:

### 1. Introduce 2 new parameters: `progressSteps (array of strings)` and `currentProgressStep (int)`, example:

```js
progressSteps: [
  '<i class="fa fa-check" aria-hidden="true"></i>', // nice ✅ symbol
  '2',
  '3'
],
currentProgressStep: 1
```

### 2. Introduce 4 new methods:

- `swal.getProgressSteps()`
- `swal.setProgressSteps([])`
- `swal.showProgressSteps()`
- `swal.hideProgressSteps()`

--- 

What do you think about this?

**Comment by birjolaxew** [comment]
I'm definitely a fan. Would make the queue functionality actually have an impact, instead of simply being another interface too.

I'd like to see a minimal implementation of just the DOM element first though - I'd think it'd be challenging to support longer strings.

**Comment by simo9000** [comment]
interesting... My first thought is this informs the user about the existence and status of the queue. Is it your intention that the methods get/setProgressSteps have any connection to the steps array that actually runs the queue function or is it your intention to maintain a separate list of labels for display purposes only? My concern is that the state machine ads a potential for non-determinism in the progress steps and even allows for cycles as the current usage examples shows. I'd say we want to make sure the numbered steps is optional such that the lib user can choose whether or not this adds or detracts given the complexity of their queue.

**Comment by acupajoe** [comment]
Instead of separating this out into the global methods - why not bundle this with queue / state machine functionality? I can only really see the use cases within those two areas, as they would be the only places where programmatically maintaining the numbers would be possible. 

So something like:

```
swal.setDefaults({
...
showProgressSteps: true
...
});

swal.queue([{swalObject}, {swalObject}, {swalObject}], {
    progressSteps: {
         values: ["swal1", "swal2", "swal3"],
         ....
    }
});
```

**Comment by limonte** [comment]
>  I can only really see the use cases within those two areas

Not true, here's the simple example with progress steps and without queue:

```js
swal.setDefaults({progressSteps: ['1', '2']});

swal({
  title: 'Step 1',
  type: 'question 1',
  currentProgressStep: 0
})
.then(function() {
  swal({
    title: 'Step 2',
    type: 'question 1',
    currentProgressStep: 1
  });
});
```

**Comment by simo9000** [comment]
I was actually thinking something along the same lines as @acupajoe. But instead of a separate array, add an `progressStepValue` attribute which can be added to each swalObject and then we would add a routine to walk the queue array itself to build the progress bar with numbered steps. This way if the queue is altered in the state machine, the progressSteps won't have to be altered separately.

**Comment by limonte** [comment]
> build the progress bar with numbered steps

We shouldn't limit the imagination of swal2 users with numbers only :) Progress steps [could](https://d13yacurqjgara.cloudfront.net/users/1693/screenshots/773791/installation-flow-dribbble-retina.gif) [be](https://d13yacurqjgara.cloudfront.net/users/1693/screenshots/1664914/onboarding-steps-animated.gif) [different](http://static1.squarespace.com/static/554a803ae4b0a8f7cf3b52a6/t/56d9e5652fe131106fdecd64/1457120620998/) :)

**Comment by simo9000** [comment]
@limonte agreed i was just trying to refer to this new UI concept by the title you gave the issue. Sorry for the confusion.

**Comment by limonte** [comment]
I just made the simple PR just to check the DOM element and discuss further details about this functionality: #275

**Comment by limonte** [comment]
Done in (v4.2.8)[https://github.com/limonte/sweetalert2/releases/tag/v4.2.8]
