### ISSUE TITLE
npm shrinkwrap fails due to packages using "latest" for dependency requirement

### ISSUE THREAD

**Issue by MatthewHerbst** [limonte/sweetalert2#274]
I recently attempted to `npm shrinkwrap` a React project where I use this library. Another dependency I use depends on the `es6-promise` package which this library also depends on. Because of that other dependency, I had manually done an `npm install --save es6-promise` within my package.

However, because this package uses the `latest` tag instead of specifying a more specific semver version, `shrinkwrap` was unable to resolve the two different versions of the same `es6-promise` dependency, and so failed.

```
λ npm shrinkwrap
...
...
...
npm WARN shrinkwrap   sweetalert2: '^4.2.4' }
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have es6-promise@3.2.1 (expected: latest) /Users/matt/repos/experiments-ui/node_modules/sweetalert2/node_modules/es6-promise
```

I had to manually change the semver version in the `sweetalert2` `package.json` for `shrinkwrap` to work correctly.

![image](https://cloud.githubusercontent.com/assets/1287375/18291188/6c8bd324-743b-11e6-91e1-150ec5aa0048.png)

**Comment by limonte** [comment]
`npm -v` ?

**Comment by MatthewHerbst** [comment]
You can see the full details in the error message above.

Node `v6.3.0`
npm `v3.10.3`

**Comment by limonte** [comment]
from https://github.com/uber/npm-shrinkwrap:

> Note: npm >= 3 is currently not supported.

More info: https://github.com/npm/npm/issues/9703

**Comment by MatthewHerbst** [comment]
Thanks for the npm bug link! Though do they use Uber's version still? All I could find was [`shrinkwrap.js`](https://github.com/npm/npm/blob/2a5977e0c65b244e92d848fcd56f2f80ba8cdf3b/lib/shrinkwrap.js), but no mention of the dependency coming from Uber's package.

**Comment by limonte** [comment]
> Do they use Uber's version still? All I could find was shrinkwrap.js

Your link is correct, mine is not. They are not using Uber's version anymore as I can see.
