### ISSUE TITLE
Disable document scroll when sweetalert is active

### ISSUE THREAD

**Issue by frodik** [limonte/sweetalert2#277]
I would appreciate if document under sweetalert would have disabled scrolling. It is easily achievable by adding class, e.g. "sw_active" to body and .sw_active { overflow:hidden } 

That way, when scrolling in sweet alert, document under it wouldn't move too.  Which I think should be expectable behaviour.

**Comment by birjolaxew** [comment]
Will be a side effect of fixing [#272](https://github.com/limonte/sweetalert2/issues/272#issuecomment-244626738). Also see #225

**Comment by limonte** [comment]
Done in [v5.0.0](https://github.com/limonte/sweetalert2/releases/tag/v5.0.0).

**Comment by adarqui** [comment]
Hey, quick question, couldn't find it in the existing issues. Ok so, how do I enable document scroll? I'd actually like the user to be able to document scroll while the modal is open. Is there a simple way to achieve this?

Thanks!
