### ISSUE TITLE
Error on preConfirm

### ISSUE THREAD

**Issue by stephenvicino** [limonte/sweetalert2#279]
I am getting a `TypeError: e.preConfirm(...) is undefined` error when trying to user preConfirm.

Here is my code: 

```js
swal({
    title: 'Authentication',
    imageUrl: "<<IMG URL>>",
    html: '<label>Username</label><input type="test" class="swal2-input" autofocus autocomplete="off" id='username>' +
      '<label>Password</label><input type="password" class="swal2-input" autocomplete="off" d='password>',
    showLoaderOnConfirm: true,
    showCloseButton: true,
    showCancelButton: true,
    customClass: "auth_swal",
    preConfirm: function(result) {
      process_credentials($('#username').val(), $('#password').val());
    }
  });
```

**Comment by limonte** [comment]
From docs:

> preConfirm: Function to execute before confirm, should return Promise, see usage example.

To get more help read [contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md), add JSFiddle (template: https://jsfiddle.net/limon/ad3quksn/) and reopen.
