### ISSUE TITLE
SweetAlert block bootstrap Switch

### ISSUE THREAD

**Issue by samuel9554** [limonte/sweetalert2#281]
Hi,

I'm trying to use BootStrap switch inside the sweet alert box in HTML.

`swal({
				  title: 'Setting schedule for ' + date.format("DD/MM/YYYY"),
				  html:
					'<div class="col-sm-12 nopadding">' +
					'<b>Type : </b><select onchange="changeEventHandler(event);"><option></option><option value="workorder">Work Order</option><option value="note">Note</option></select></br>' +
					'<div id="content"><input class="form-control" type="checkbox" name="schedule_private" value="1" checked></div>' +
					'</div>',
				  showCloseButton: true,
				  showCancelButton: true,
				  confirmButtonText:
					'Submit',
				  cancelButtonText:
					'Cancel'
				})`

Outside the sweetAlert the checkbox are replace without issue but inside isn't working.

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/blob/master/contributing.md
