### ISSUE TITLE
Some times the alert dialog not show in the center,but I click again, It is correct.

### ISSUE THREAD

**Issue by xygahs0801** [limonte/sweetalert2#282]
![image](https://cloud.githubusercontent.com/assets/3293775/18468032/c6ddcf00-79d4-11e6-82c2-db7be227e40d.png)

**Comment by xygahs0801** [comment]
I found the reason.Because my image not loaded.so the sweetalert can not calculate the height appropriatly.

**Comment by limonte** [comment]
could you please make the [jsfiddle](https://jsfiddle.net/limon/ad3quksn/) with your case so we can reproduce and fix it, thanks!

**Comment by limonte** [comment]
reopen with the jsfiddle please

**Comment by kevinvanmierlo** [comment]
@limonte This was with an older version of sweetalert2. I had the same problem, but after updating to the latest version it works great!

**Comment by birjolaxew** [comment]
@kevinvanmierlo Relevant issue: #248 (closed by #252, released in v4.1.7)

**Comment by kevinvanmierlo** [comment]
@birjolaxew Thanks for the info!
