### ISSUE TITLE
Overlay doesn't close after 4.2.8

### ISSUE THREAD

**Issue by rasmuswoelk** [limonte/sweetalert2#284]
Hi

I just updated SweetAlert2 from NPM and noticed that the overlay doesn't close when the modal closes. 

Also it adds styling to the swal-overlay div: `opacity: 0,14` - this should be: `opacity: 0.14`

For me this bug can be re-created on the example page: https://limonte.github.io/sweetalert2/ in Chrome 52 for Mac. It's **working** in Firefox though!

**Comment by limonte** [comment]
Can anybody reproduce this issue? I can't.

**Comment by birjolaxew** [comment]
Nope. Tested in Chrome 53 (+ Chromium 53 + Firefox 48) on Arch.

**Comment by rasmuswoelk** [comment]
Weird. I tried in Safari 9.1.3 and Firefox 48 and it **works**.

Tried in Chrome 52 for Mac - both in inkognito and regular - and it fails on the demo site.

I open any alert and when it closes the overlay is still there.

**Comment by rasmuswoelk** [comment]
In Chrome 53 it works fine on Windows.

**Comment by rasmuswoelk** [comment]
I restarted my Chrome-app and now it works. That is very very weird but it works now!
