### ISSUE TITLE
Cannon install latest version of sweetalert2

### ISSUE THREAD

**Issue by orangecoding** [limonte/sweetalert2#286]
If I try to install the latest version 4.3.0, I'll get this message.

`[ERROR] npm ERR! No compatible version found: sweetalert2@4.3.0
[ERROR] npm ERR! Valid install targets:
[ERROR] npm ERR! 4.2.8,(...)`

**Comment by limonte** [comment]
I can't reproduce this issue: 

![](https://i.imgur.com/ekLNoy9.png)

**Comment by niftylettuce** [comment]
I just installed it fine myself

**Comment by orangecoding** [comment]
Sorry can be closed. Was an issue at my nexus repo 👍
