### ISSUE TITLE
`.queue` method not working by default

### ISSUE THREAD

**Issue by niftylettuce** [limonte/sweetalert2#287]
```js
swal.queue([
  { title: 'Foo', text: 'bar', type: 'success' },
  { title: 'Foo', text: 'bar', type: 'success' },
  { title: 'Foo', text: 'bar', type: 'success' },
  { title: 'Foo', text: 'bar', type: 'success' },
  { title: 'Foo', text: 'bar', type: 'success' }
]).then();
```

Outputs the following error:

`Uncaught (in promise) TypeError: Cannot read property 'setAttribute' of null(…)`

Which is at this code <https://github.com/limonte/sweetalert2/blob/master/dist/sweetalert2.js#L1310>:

```js
    return new Promise(function(resolve, reject) {
      (function step(i, callback) {
        if (i < queue.length) {
          modal.setAttribute('data-queue-step', i); // <---------
```

**Comment by niftylettuce** [comment]
I got it to work @limonte by adding a `swal()` before `swal.queue` as `swal().queue(steps).then();`

Perhaps this needs updated in the docs or there needs to be a patch in place that if `getModal` returns null, then it needs to create a new instance.

**Comment by niftylettuce** [comment]
Edit: I actually needed to make it `swal();` and then `swal.queue(steps)`

Though this throws this error now `SweetAlert2 expects at least 1 attribute!`

**Comment by niftylettuce** [comment]
OK so @limonte we should add documentation that if you `require` or `import` the package (e.g. with `browserify` or `webpack`) then we need to manually run `swal.init();`.

```js
import swal from 'sweetalert2';

(() => {
  swal.init();
  swal.queue(steps).then();
})();
```

**Comment by limonte** [comment]
Thank you @niftylettuce for such a detailed issue and searching the bug. Fixed in [v4.3.1](https://github.com/limonte/sweetalert2/releases/tag/v4.3.1)

:beers:

**Comment by niftylettuce** [comment]
@limonte You are badass.  Thank you!!! 🍻  Do you have a PayPal donation page like I have at https://paypal.me/niftylettuce?  If so let me know!  I am using SweetAlert2 in CrocodileJS at

**Comment by niftylettuce** [comment]
@limonte https://github.com/crocodilejs/crocodile-node-mvc-framework#flash-messaging

**Comment by limonte** [comment]
Thank you @niftylettuce for nice word about my open-source project. I'm really happy to make the world a little bit better with SweetAlert2 :)  

I'm currently living in Serbia and paypal.me doesn't work here:

![](https://i.imgur.com/N9Q1l2o.png)

But I think I succeed with the simpler solution: https://github.com/limonte/sweetalert2/commit/3549565feb2e3f743f18a5b6f6880595a9c36d7e

It will be great if you could make the first donation and test that button because I can't test it as PayPal doesn't allow sending money to yourself :)

**Comment by niftylettuce** [comment]
<img width="780" alt="screen shot 2016-09-15 at 8 48 01 am" src="https://cloud.githubusercontent.com/assets/523141/18550300/1f51f312-7b21-11e6-8333-3e2fe5ec861e.png">

**Comment by limonte** [comment]
:disappointed: 

Thank you anyway for testing it out. 

I've removed this button temporary, I'm moving to EU next month and it will be returned :)

**Comment by limonte** [comment]
Howdy @niftylettuce
Hope you are well and CrocodileJS will be released soon!

I moved to Finland and created https://www.paypal.me/limonte so if you are still willing to make a donation, I will be more than happy to receive the first one :)

Thanks in advance! :beers:

**Comment by SaadFarhanIdress** [comment]
I did not understand how to fix this issue. My code is:
```javascript
const result = await Swal.mixin({
    input: 'text',
    confirmButtonText: 'Next >',
    showCancelButton: true,
    progressSteps: ['1', '2'],
}).queue([

])
```

The error says: 
```Property 'queue' does not exist on type 'typeof Swal'```

Is it due to the version change? I found its use on a blog post which is 2 years old. I found most of the packages outdated.
