### ISSUE TITLE
Height is too large

### ISSUE THREAD

**Issue by quma** [limonte/sweetalert2#291]
Hallo,

I use the owl-carousel script to display some images in the sweet alert PopUp.
The images are displayed in a row (float).
But what happens is ( I think so ) sweetarlert2 calculates for each image the hight and I get a to large popup .... the min-hight of my pop up is to large. 

Is there a way to solve this problem like... set min-hight manually  or something else?

I use sweetalert2 v5 

best regards

**Comment by limonte** [comment]
I'm not sure I understand your request, please create jsfiddle so I can see and reproduce the issue.

**Comment by quma** [comment]
Thank you for the fast response.
I just send you a email with screenshots.

**Comment by limonte** [comment]
Thank you @quma for the email with the detailed explanation. This issue should be fixed in [https://github.com/limonte/sweetalert2/releases/tag/v5.0.3](https://github.com/limonte/sweetalert2/releases/tag/v5.0.3) without any changes in your code.

Please try the latest swal2.

**Comment by quma** [comment]
WOW thank you !

after I use the sweetalert2-common.js it works !!!

**Comment by limonte** [comment]
Nice :)
