### ISSUE TITLE
Display on the back

### ISSUE THREAD

**Issue by LuisEGR** [limonte/sweetalert2#292]
I have a problem with this sweetalert2, I've used Sweatalert (the original), and never had a problem with that, but now I want to put some HTML in the description, but when I change to sweatalert2 the modal/alert shows on the back of my modal(Custombox). I've tried to use diferent z-index on the ".swal2-modal" but it doesn't work, allways is behind the Custombox, Sweatalert original works fine but don't suppots HTML.

I hope you can help me

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/blob/master/contributing.md

> 
> For bug reports, please include:
> 
> a [jsfiddle](https://jsfiddle.net/limon/ad3quksn/) in order for us to be able to reproduce the issue.
