### ISSUE TITLE
Breaking changes from 4 to 5?

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [limonte/sweetalert2#293]
Hi @limonte!

I just saw you updated sweetalert2 main version from 4 to 5.

Did this happen due some breaking changes?

Best regards,
Rafael Pacheco.

**Comment by limonte** [comment]
I don't think it's actually a "breaking" change, but it is big enough to bump the major version, read more here: https://github.com/limonte/sweetalert2/issues/272#issuecomment-244626738
