### ISSUE TITLE
Unable to prevent Sweet Alert from closing when hitting Confirm

### ISSUE THREAD

**Issue by RossTsachev** [limonte/sweetalert2#294]
Trying to prevent the sweet alert from closing, but so far to no avail.
Here is my jsfiddle:
https://jsfiddle.net/RossTsachev/26fut4aL/8/
I'm sure I'm doing something terribly wrong, but can't figure out what

**Comment by limonte** [comment]
Here's your example, fixed: https://jsfiddle.net/26fut4aL/9/
You probably want to read about promises in JS: http://www.html5rocks.com/en/tutorials/es6/promises/
See another example: https://limonte.github.io/sweetalert2/#ajax-request

Thanks for using swal2, have a great day!

**Comment by RossTsachev** [comment]
Thank you!
