### ISSUE TITLE
Z-index conflict with Magnific-Popup

### ISSUE THREAD

**Issue by rafael-renan-pacheco** [limonte/sweetalert2#296]
Hi there!

After updating from 4 to 5, when sweetalert2 is fired inside a Magnific-Popup, it loses the z-index battle to it. Magnific-Popup has a wrapper under the body tag, called mfp-wrap, with a z-index of 1043 (magic number).

Sweetalert2 also has a wrapper under the body tag, called swal2-container, with a z-index of 1000. So it is fired bellow the magnific-popup, which is a problem.

This is easily solved by overwriting sweetalert2 z-index to a number above 1043, but would be possible, in order to enhance this plugin, to programmatically detected the needed z-index to ensure that sweetalert2 will fire up above everything? For example, detected which tag bellow body has the biggest z-index, then set the sweetalert2 z-index to that number + 1.

Best regards,
Rafael Pacheco.

**Comment by limonte** [comment]
Maybe we should just assign the max `z-index` value for `.swal2-container`? It's [2147483647](http://stackoverflow.com/a/856569/1331425).

**Comment by rafael-renan-pacheco** [comment]
As sweetalert2 represents a popup that must be the top most frame, I think it's okay to max it up. But this number must be compatible with all browsers. Maybe a little less aggressive number, like 10000? I don't recall seeing any modal plugin which uses big z-indexes.

**Comment by samturrell** [comment]
I'd probably say something around 1060. That would also put it above bootstrap modals. I wouldn't set it to the max because some plugins such as jquery datepicker attach to the body by default and would need to be above sweetalert for use in the modal.

**Comment by limonte** [comment]
nice point with a datepicker, I'll make it `1060`.

**Comment by limonte** [comment]
Fixed in [v5.0.5](https://github.com/limonte/sweetalert2/releases/tag/v5.0.5).

Thank you both @rafael-renan-pacheco for reporting and @samturrell for pointing out possible datepicker inside the swal2 modal.

**Comment by JamoCA** [comment]
I'm using MagnificPopUp 1.1.0 (latest) and sweetalert 7.0.5 (latest). The sweetalert modal is properly displayed and the buttons are clickable, but if I add a "password" field, I won't gain focus. I've increased the z-index, but it didn't seem to make any difference.  Is this the same issue as bootstrap?

CASE USE: I'm using MagnificPopUp to display product details (via Ajax) on a web-based POS. Any buttons with a specific class trigger sweetalert to display prompt to require an administrative passcode to override before continuing. It works, until the buttons are clicked within a MagnificPopUp modal.

**Comment by irman** [comment]
@JamoCA I'm having the exact same issue right now. Any solution yet?

**Comment by irman** [comment]
I think I've found my solution, just in case anyone wondering. Simplifying this: https://github.com/dimsemenov/Magnific-Popup/issues/897

I just add that line on magnific open callback. E.g:

```
$('.listing').magnificPopup({
    ....
    callbacks: {
        open: function() {
            // Disabling focus enforcement by magnific
            $.magnificPopup.instance._onFocusIn = function(e) {};
         }
    }
});
```
