### ISSUE TITLE
Cannot scroll content anymore

### ISSUE THREAD

**Issue by samturrell** [limonte/sweetalert2#297]
Content now just tries to scroll to the top of the screen producing a juddering motion.

![scrolling bug](https://www.dropbox.com/s/jo4znx9vya5e9nl/swal%20scroll2.gif?dl=1)

That specific gif example is on macOS Sierra Chrome 53.0.2785.116
macOS Firefox 49.0 has the same effects as chrome.

Also does it on macOS Sierra Safari 10 but the content gets gradually dragged up into the top overflow. 
![scrolling bug on safari](https://www.dropbox.com/s/yajwjto5cru2vvs/swal%20scroll%20-%20safari.gif?dl=1)

https://jsfiddle.net/ad3quksn/43/

Also when this is fixed, i'd recommend adding 10px of padding to the .swal2-container as per my fiddle to make it look nicer at mobile breakpoint. I'd like to fix this myself but have zero free time recently.

**Comment by limonte** [comment]
Thank you @samturrell for reporting this issue. Currently, I have no idea how to fix it :/ Any help will be much appreciated here?

**Comment by limonte** [comment]
Got it, will be fixed asap.

**Comment by limonte** [comment]
Fixed in [v5.0.5](https://github.com/limonte/sweetalert2/releases/tag/v5.0.5).

Thank you @samturrell :beers:
