### ISSUE TITLE
Unable to scroll in v5.x

### ISSUE THREAD

**Issue by birjolaxew** [limonte/sweetalert2#298]
Had the chance to test v5.x today. Found I couldn't scroll on overflowing alerts (tested in Chromium & Firefox)

[JSFiddle.](https://jsfiddle.net/v65vtL2q/)

Fixed if `max-height: 90%` is removed from `.swal2-modal`. I'd also suggest adding a bit of padding to `.swal2-container` so the overflowing modal doesn't touch the window edges.

**Comment by samturrell** [comment]
#297 :)

(Cheers, @limonte!)

**Comment by birjolaxew** [comment]
Ah cheers, should've checked the closed issues now that I'm not watching the repo

**Comment by limonte** [comment]
Cheers :beers: :)
