### ISSUE TITLE
Modal has max-height on first open in v5.0.5

### ISSUE THREAD

**Issue by birjolaxew** [limonte/sweetalert2#299]
[JSFiddle.](https://jsfiddle.net/aktvgq7m/)

The first time the modal is opened, it is limited by its max-height making it so you scroll the modal, not the container. I have no idea why that doesn't happen on following opens.

Fixed by removing the `max-height: 90%` from `.swal2-modal` ([fixed JSFiddle](https://jsfiddle.net/aktvgq7m/1/))

**Comment by limonte** [comment]
Done in [v5.0.6](https://github.com/limonte/sweetalert2/releases/tag/v5.0.6).

Thank you @birjolaxew :beers:
