### ISSUE TITLE
New issue Tab key not working after opening two Sweet Alert Modals in a row

### ISSUE THREAD

**Issue by bkintanar** [limonte/sweetalert2#30]
As mentioned in t4t5/sweetalert#127. Tab key is screwed up if opening two swal modals in a row.

This https://github.com/t4t5/sweetalert/issues/127#issuecomment-136958062 workaround works.

**Comment by limonte** [comment]
Can't reproduce this bug. Please specify steps to reprodyce so I can fix it or send pull request :)
