### ISSUE TITLE
problem with table tag and td tag

### ISSUE THREAD

**Issue by truelineinfotech** [limonte/sweetalert2#300]
when i print html table on swettalert2. there are lots of `<br>` tags at the beginning of output.
here is code that i am using.
```
function view_data(id) {
     $.ajax({
        url: "<?php echo base_url('common/ajax/view_user') ?>",
        type: 'POST',
        dataType: 'html',
        data: {id:id},
      })
      .done(function(data) {
        swal({
              title: 'User Details',
              text: data,
              width:"600px",
            });
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        console.log("complete");
      });
     // alert(data_table);

  }
```
![sweetalert_error](https://cloud.githubusercontent.com/assets/3807730/18715355/99a1405e-8036-11e6-91cc-eebafb8a9a37.png)

![sweetalert_error2](https://cloud.githubusercontent.com/assets/3807730/18715474/097118dc-8037-11e6-8d6a-b4f4e2acb588.png)

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/blob/master/contributing.md

> 
> For bug reports, please include:
> 
> a [jsfiddle](https://jsfiddle.net/limon/ad3quksn/) in order for us to be able to reproduce the issue.
