### ISSUE TITLE
animation: false not working?

### ISSUE THREAD

**Issue by charleslcso** [limonte/sweetalert2#31]
It seems that setting animation: to false has no effect.

The animation need to be disabled because the "success" graphics has artifics. See attachment.

![screen shot 2015-10-06 at 11 35 30 am](https://cloud.githubusercontent.com/assets/520537/10299621/bb18e976-6c1e-11e5-928a-637f5d84233e.jpg)

**Comment by crabbly** [comment]
@charleslcso the animation set to false affects the popup modal only. When set to false you can see it won't have it's default "bounce" animation effect when opening the alert. 
It however doesn't affect the icon animation though, as you pointed. Maybe it could have an option to disable that as well.

**Comment by limonte** [comment]
@crabbly :+1:

**Comment by inattee** [comment]
put an !important on it.
