### ISSUE TITLE
focused button

### ISSUE THREAD

**Issue by lucasfernog** [limonte/sweetalert2#310]
Pressing tab should inform the user which button is focused.

**Comment by limonte** [comment]
Which kind of user informing do you mean? There's the outline for buttons.

**Comment by lucasfernog** [comment]
hmm my bad, same color for outline and button tricked me

**Comment by limonte** [comment]
Yeah, default color for the outline in Chrome/Safari is blue, which is almost similar to the Confirm button color. 

In Firefox/IE/Edge there's default dotted outline for buttons
