### ISSUE TITLE
ES6 imports not working on v5.2.0

### ISSUE THREAD

**Issue by joextodd** [limonte/sweetalert2#311]
Since upgrading to v5.2.0, using ES6 imports is no longer working. Just get a ReferenceError saying swal is not defined. 

This [JSFiddle](https://jsfiddle.net/joerobot/u4qufgsq/) doesn't really illustrate the point.

**Comment by limonte** [comment]
> This JSFiddle doesn't really illustrate the point.

Could you please make the jsfiddle that illustrate the point? :)

**Comment by joextodd** [comment]
Sorry that was the wrong link. I have tried to recreate it, but not sure it's possible in JSFiddle.

[JSFiddle](https://jsfiddle.net/joerobot/nL2q3opn/1/)

**Comment by joshterrill** [comment]
I have an angular 2 project that I'm trying to use this on. I installed it, then tried to import it, and typescript is saying it can't find the module.

**Comment by joextodd** [comment]
Tried to recreate the issue with a bare bones project, and it no longer causes an error so must be something I have done wrong. Closing issue.

**Comment by ctf0** [comment]
@limonte had the same issue today and the fix was binding to the window
```js
import { default as swal } from 'sweetalert2'
window.swal = swal;
```
