### ISSUE TITLE
Show Sweetalert2 on mandatory form field errors

### ISSUE THREAD

**Issue by 2braincells2go** [limonte/sweetalert2#313]
Firstly, great script, love it.

Have a submit message form using in school project. Trying to replace the default javascript alert and use Sweetalert2. Failing miserably...

Can Sweetalert2 be used to replace default javascript alerts on form errors? Can't seem to get working if so. Any example be greatly appreciated.

Thanks,

Woody

**Comment by limonte** [comment]
https://limonte.github.io/sweetalert2/

**Comment by 2braincells2go** [comment]
Sorry to have bothered you.

**Comment by acupajoe** [comment]
@2braincells2go you will be better suited asking this question (and providing your implementation) on stackoverflow under the `sweetalert` tag. Issues on this repository are **not** for coding implementation questions but rather issues on the library. There are several contributors who actively watch the stackoverflow tag who would be willing to help.

**Comment by 2braincells2go** [comment]
Thanks @acupajoe , appreciate the input. Got a class to teach later this evening and was trying to get my  lesson plan back on track. My bad.

**Comment by acupajoe** [comment]
@2braincells2go No worries! Hope you get your solution!
