### ISSUE TITLE
Using Bootswatch themes with Sweetalert

### ISSUE THREAD

**Issue by KillerSquid** [limonte/sweetalert2#314]
First off- great job on SA2!  I have been using SAs for quite a while now and you have added so many awesome features!  thank you!
With Tristan's version you had the option to apply Bootstrap themes to the SA modal.  I'm working on a project right now where the user has the option to choose from the themes available through Bootswatch (http://bootswatch.com/) and I wanted to implement the same theme for the SAs.  
Any thoughts on how to do this or do you plan to add theming at some point in a future release?
I tried customClass: 'modal' thinking maybe that would force it but it just made the SA full screen.
Thanks again!

**Comment by limonte** [comment]
Thank you @KillerSquid for nice words about the plugin! :)

Unfortunately, I don't have plans to implement Bootswatch themes into SweetAlert2. You can always add custom styles for buttons by including the corresponding CSS and setting `confirmButtonClass` and `cancelButtonClass` parameters:

```js
swal({
  ...
  confirmButtonClass: 'btn btn-primary',
  cancelButtonClass: 'btn btn-danger',
  buttonsStyling: false,
  ...
})
