### ISSUE TITLE
Remove Old Alert

### ISSUE THREAD

**Issue by cnsconsultores** [limonte/sweetalert2#315]
Hello.

Excuse me for my english.

I have a button submit with validate form. When any field is empty. I have a standard alert with message "You have to complete fields from form...".

I can't access to the code of this button but I can to assign code by jQuery. At the moment I have on my jQuery code that when click on button submit display message with sweetalert. The problem is that if the fields of form is not complete I have also the old alert with message "You have to...." and at the same time I have the message from sweetalert2 "You form is sending....".  Actually, the form is not sent because it fails validation.

How I can to do for when the form is not validate not display message from sweetalert??

Thank you 
Regards.

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
