### ISSUE TITLE
loading window is displaying on the left with full height instead of center.

### ISSUE THREAD

**Issue by midcore-nam** [limonte/sweetalert2#317]
![image](https://cloud.githubusercontent.com/assets/16084009/19274822/7e69d256-8f9f-11e6-99f0-6949db971775.png)

**Comment by limonte** [comment]
I can't reproduce this issue.

>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by midcore-nam** [comment]
nvm. I have the same class name "loading" in my css. I've changed mine. Thanks for quick respond.

**Comment by limonte** [comment]
FYI: In [v5.2.1](https://github.com/limonte/sweetalert2/releases/tag/v5.2.1) I changes `.loading` class to `.swal2-loading` to prevent conflicts.

Thanks for reporting this issue!
