### ISSUE TITLE
Change text

### ISSUE THREAD

**Issue by MusicMonkey5555** [limonte/sweetalert2#319]
It would be nice to add a setTitle and setText function to swal so you could call
swal.setText("Something different"); and it would change the text in the open prompt. This allows for stuff like countdowns using an interval.

Currently I am doing this by just calling: 
$('.swal2-content').text("Something different");

But it would nice for it to be a black box and not have to look at what the id's are or worry about them changing.

Simple enough and I don't think it would add any overhead or anything.

**Comment by limonte** [comment]
> $('.swal2-content').text("Something different");

You shouldn't rely on `.swal2-` classes. This is the right way:

```js
swal({
 html: '<div class="your-container">...</div>',
})

$('.your-container').text("Something different");
```

As to `setText()` method, I don't think it's really needed. If we add `setText()` other users will ask for  `setHtml()`, `setImage()`, `setEveryOtherParameter()` to be added and the plugin will become a hell of setters.
