### ISSUE TITLE
Uncaught (in promise) overlay in version 5.3.1

### ISSUE THREAD

**Issue by diegomfloripa** [limonte/sweetalert2#321]
Error returned to happen in version 5.2.3

**Comment by diegomfloripa** [comment]
Uncaught (in promise) overlay #185

**Comment by birjolaxew** [comment]
As described in [the readme](https://github.com/limonte/sweetalert2#handling-dismissals):

> When an alert is dismissed by the user, the Promise returned by swal() will reject with a string documenting the reason it was dismissed:
> [...]
> If rejections are not handled, it will be logged as an error. To avoid this, add a rejection handler to the Promise. Alternatively, SweetAlert2 provides the .done() method as a quick way to simply suppress the errors:
