### ISSUE TITLE
Bootstrap 3 conflict

### ISSUE THREAD

**Issue by jasonjianfr** [limonte/sweetalert2#322]
Hi, I try the sample code below:

https://jsfiddle.net/mnqm11w0/

I found the swal doesn't work, till the External Resources of Bootstrap removed, so I check the HTML and found the container div of swal would always been added the "fade" class first, just like - class="swal2-container fade swal2-in" -.

Is there any way to solve it or get some workaround?
Thank.

**Comment by dev-seahouse** [comment]
Add this : 
.swal2-container.fade{
  opacity: 1;
}

**Comment by orangecoding** [comment]
This is a bug that must have been introduced in some of the later versions as I'Ve updated today from 5.2.1. In 5.2.1, sweetalert worked ok.

**Comment by limonte** [comment]
Fixed in [v5.3.2](https://github.com/limonte/sweetalert2/releases/tag/v5.3.2) 
Thanks a lot @jasonjianfr for reporting this!
