### ISSUE TITLE
Alert jumps to top of page (Firefox)

### ISSUE THREAD

**Issue by damanic** [limonte/sweetalert2#323]
Observed on Firefox 49.0.1 - Windows 10

The browser scrolls to top of page before showing the alert. 

In Chrome the alert is shown without moving page position, which I assume is the correct behaviour.

Bug?

**Comment by limonte** [comment]
Fixed in [v5.3.2](https://github.com/limonte/sweetalert2/releases/tag/v5.3.2) 
Thanks a lot @damanic for reporting this!
