### ISSUE TITLE
Replace  .done() with .catch(function(){})

### ISSUE THREAD

**Issue by ltvan** [limonte/sweetalert2#324]
I suggest to update your document to use this to suppress the unhandled rejection instead of solution in issue #177 :
```
 swal(...).catch(function(){});
```

Reasons: You leave default .done if exists, that causes issue with other polyfill library such as bluebird. .done() still throws unhandled rejection error.

**Comment by limonte** [comment]
Thanks, but no. This will be a huge breaking change for most swal2 users.

**Comment by ltvan** [comment]
You can still keep your code as it is, but it's should be depreciated and update the document to let user know about the best way to do. At least, they won't get headache like issue #213. Your solution won't work.

**Comment by birjolaxew** [comment]
I definitely support updating the readme to use `.catch` instead of `.done`. Could optionally expose a noop method on swal:

    swal(...)
        .catch(swal.noop)

As @Itvan suggests, the current `.done` should stay in the code for at least one major release, but be deprecated due to clashes with other libraries

**Comment by limonte** [comment]
Thanks @ltvan for reporting this issue.
Thanks @birjolaxew for suggesting the nice trick with `swal.noop()`

Done: https://github.com/limonte/sweetalert2/releases/tag/v5.3.3
