### ISSUE TITLE
Remove es6-promise dependency from bower package

### ISSUE THREAD

**Issue by ltvan** [limonte/sweetalert2#325]
es6-promise should be optional dependency, not a required dependency. We can use other promise polyfill or just decide to drop IE support.

**Comment by limonte** [comment]
Thanks, but no. You don't have to include `es6-promise` in your project :)

**Comment by ltvan** [comment]
But you are referencing es6-promise as required dependency and it downloads every time I install your bower package.

**Comment by MarkHerhold** [comment]
I respectfully disagree with the stance on including `es6-promise` as a direct dependency. Users should be able to provide their own promise polyfill (such as `Bluebird`) or none at all (native promises). This just adds unnecessary bloat.

**Comment by MarkHerhold** [comment]
Going through the rest of the issues related to this, it looks like @limonte suffered from a relentless number of issues where many people complained about promise-related errors. Is this why the `es6-promise` was added?

**Comment by limonte** [comment]
@MarkHerhold Yes, many developers want the solution that just works, without any customization. Including `es6-promise` by default makes it easier to many swal2 users to get started.
