### ISSUE TITLE
Extra Input Field That I Do Not Specify 

### ISSUE THREAD

**Issue by antho1jp** [limonte/sweetalert2#326]
I love this pop up solution and have been using since Sweet Alert 1. I've used this in many of my web applications but something is happening that I'm not sure how to troubleshoot. Just using a simple call the pop-up is including a text input field on every single pop-up. There are some pop-ups I do want them to have the input, but others I do not. Is there any way I can trouble shoot this, are there any caching settings or something that you would know that could cause this? This just happened out of nowhere it is really strange.

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
