### ISSUE TITLE
Suggestion - Hide selected text when loading animation is active

### ISSUE THREAD

**Issue by Silvester20** [limonte/sweetalert2#327]
Sorry to increase the issue count from 0 to 1 :p

Altough this is not a issue but also not a how to I decided to post it here.
So as the title says I've got a (very little) improvement suggestion.

When the loading animation is active and you hit ctrl+A (select all) you will see the text from the confirm button. I don't like this and added the CSS property `user-select: none;` to the class
`.swal2-modal .styled.loading` for my self, but maybe this could be the default in the core of swal2?
It makes sence in my opinion right?

So in [this](http://imgur.com/z8Stm32) example the text "yes" from the confirm button is in normal case not visible until you hit select all. This could be prevented by adding user-select: none; to the swal2-modal .styled.loading class.

**Comment by limonte** [comment]
Nice request @Silvester20, as always :)

> Sorry to increase the issue count from 0 to 1 :p
:laughing: 

Done in [v5.3.4](https://github.com/limonte/sweetalert2/releases/tag/v5.3.4)

**Comment by Silvester20** [comment]
Each time Swal2 is getting better and better, thanks for everything!
