### ISSUE TITLE
Alert card retains size of previous card shown very briefly.

### ISSUE THREAD

**Issue by AlexSwensen** [limonte/sweetalert2#328]
Currently:
Perfect example is actually on the demo page. Under "more examples" select the second example down, close it, and then select the first. You should notice that for a split second, the card retains it's old content and dimensions.

It should: have its content changed, and then the card should be shown, so the user doesn't see the box resize.

**Comment by limonte** [comment]
Thank you @AlexSwensen for reporting this issue!

Fixed in [v5.3.5](https://github.com/limonte/sweetalert2/releases/tag/v5.3.5)
