### ISSUE TITLE
allowOutsideClick not working

### ISSUE THREAD

**Issue by avatarr** [limonte/sweetalert2#329]
I can't use this option "allowOutsideClick: false" So I still click outside on overlay , How do I fix this ?

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
