### ISSUE TITLE
Use-case of closeOnConfirm

### ISSUE THREAD

**Issue by riyuk** [limonte/sweetalert2#330]
I've searched through past issues and I think your solution with preConfirm is the better choice in most cases instead of `closeOnConfirm`.

But I still think the use of this parameter is not completly replaced by preConfirm.
In swal1 I could just do `closeOnConfirm` `true` as well as `showLoaderOnConfirm` when I redirect the User to another Page.

Example in swal1:

```
// within click evt.
swal({
    // title, text, type, confirmButtonText etc.
    showCancelButton: true,
    showLoaderOnConfirm: true,
    closeOnConfirm: false,
    html: true
}, function() {
    NProgress.start();
    window.location.href = url;
});
```

In `swal2` I need to do the following to archieve the same:

```
// eg.: within click event
$('a.foo').on('click touchstart', function() {
var url = $(this).attr('href');
swal({
    // other options
    // eg: text: 'Are you sure to delete this User?',
    //closeOnConfirm: false,
    showCancelButton: true,
    preConfirm: function() {
        return new Promise(function(resolve, reject) {
            NProgress.start();
            window.location.href = url;
        });
    },
    showLoaderOnConfirm: true
}).catch(swal.noop);

return false;//prevent click event/redirect on <a>
});
```

Am I missing something?
Wouldn't it be easier to add back the `closeOnConfirm` option like this:

```
swal({
    // other options
    // eg: text: 'Are you sure to delete this User?',
    closeOnConfirm: false,
    showCancelButton: true,
    showLoaderOnConfirm: true
}).then(function() {
    NProgress.start();
    window.location.href = url;
}).catch(swal.noop);
```

**Comment by limonte** [comment]
Thank you @riyuk for submitting this suggestion, but swal2 doesn't work this way.

For swal2 **confirm** is the event which is fired **after** closing a modal. Since you don't want to close a modal and show the loader, you should use **preConfirm** parameter.
