### ISSUE TITLE
Override element styles set by Javascript

### ISSUE THREAD

**Issue by ahallora** [limonte/sweetalert2#332]
Hi. Thanks for a great plugin! 👍 

I would like to change the apperance of the modals, but it seems that the divs have some hardcoded/JS-code styles assigned to the elements, making it unable to be overriden by css-rules.

![screen shot 2016-10-21 at 10 32 58](https://cloud.githubusercontent.com/assets/5302751/19591960/f12b40f4-9779-11e6-91b4-4dc73074db1f.png)

How can I remove the fixed background, width and padding for the `.swal2-modal` elements and instead define them in my css? 

Thanks in advance. 😄

**Comment by limonte** [comment]
For changing background, width and padding properties you can use:

- related swal2 parameters: `background`, `width` and `padding`
- add `customClass: 'your-class'` + `.your-class { background: ... !important; }`

**Comment by ahallora** [comment]
Okay, thanks. I was hoping there was a cleaner way of doing this, but never mind - it gets the job done. It's good. 👍  😄
