### ISSUE TITLE
Timer error

### ISSUE THREAD

**Issue by dvLden** [limonte/sweetalert2#333]
I'm unsure how to report this to you as I did not dig into your code, but I have this bit of code:

```
return swal({
    text: baseApp.quizComplete,
    type: 'success',
    showConfirmButton: false,
    timer: 3000
})
```

Once timer ticks out, swal closes successfully, but the error appears in the console:
Uncaught (in promise) timer - error line points to the following bit of code

`reject('timer')`

Using `"sweetalert2": "^5.3.8"`

**Comment by birjolaxew** [comment]
Please see [the readme](https://github.com/limonte/sweetalert2/blob/master/README.md#handling-dismissals), where this is explained.

**Comment by limonte** [comment]
Related issue: https://github.com/limonte/sweetalert2/issues/321

**Comment by dvLden** [comment]
Whoops... Sorry about that. Did not catch that part in README...
Got it!
