### ISSUE TITLE
callback is not working in wechat(android)

### ISSUE THREAD

**Issue by QiiSyhx** [limonte/sweetalert2#334]
wechat is a Social software app in china.
swal callback function not working on the app web browser.
the demo in sweetalert2
`swal({
  title: "Are you sure?",
  text: "You will not be able to recover this imaginary file!",
  type: "warning",
  showCancelButton: true,
  confirmButtonColor: "#DD6B55",
  confirmButtonText: "Yes, delete it!",
  closeOnConfirm: false
},
function(){
  //not working
  swal("Deleted!", "Your imaginary file has been deleted.", "success");
});`

**Comment by birjolaxew** [comment]
WeChat probably use the devices built-in browser. What version of Android/iOS/other OS are you on?

**Comment by mehtonen-boox** [comment]
I have the same issue. Android version is 4.4.2. Built-in browser. Callbacks are not called. Might be because it's using polyfill library for Promises on that device?

**Comment by limonte** [comment]
I'm not familiar with WeChat and how that messenger can use JS. Could you please give an example or describe how this issue can be reproduced.

Thanks.

**Comment by AlexSwensen** [comment]
I would say this is an issue with wechat, and not sweetalert2.

**Comment by limonte** [comment]
> I would say this is an issue with wechat, and not sweetalert2.

I agree.

I'm closing this issue for now. @QiiSyhx reopen with details if needed.
