### ISSUE TITLE
Support npm installation of type definitions (Typescript 2.0)  for sweetalert2

### ISSUE THREAD

**Issue by ClaudioNunes** [limonte/sweetalert2#335]

**Comment by birjolaxew** [comment]
You're definitely going to have to explain this more.

**Comment by acupajoe** [comment]
My assumption is a `sweetalert2.d.ts` declaration file so that it can be included into typescript projects see: [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). Although a description would have been nice on the issue lol

**Comment by birjolaxew** [comment]
[Better resource on declaration files](http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) (which is what I assume @ClaudioNunes meant).

**Comment by ClaudioNunes** [comment]
Sorry,

What I meant was "support  npm installation of type definitions for sweetalert2"  as described in [What I meant was "support  npm installation of type definitions for sweetalert2"  as described in [](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/)  and already possible with sweetalert

**Comment by ClaudioNunes** [comment]
Sorry,
What I meant was "support  npm installation of type definitions for sweetalert2"  as described in https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/ and already possible with sweetalert

**Comment by limonte** [comment]
I am not familiar with Typescript at the moment, probably I will be in near future :)

Any help with making SweetAlert2 and Typescript will be much appreciated.

**Comment by tlewis17** [comment]
I've been needing to dive more into TypeScript myself. I started to give it a shot. Here is my initial attempts. I still need to work on the function callbacks and promises. It probably is far from perfect since I'm a TypeScript noobie.

https://gist.github.com/tlewis17/8312a354b92bff6ccc0f1fdc4c9fb91e#file-index-d-ts

**Comment by birjolaxew** [comment]
[Here's the old SweetAlert .d.ts for reference.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sweetalert/sweetalert.d.ts)

**Comment by limonte** [comment]
Done in [v6.2.5](https://github.com/limonte/sweetalert2/releases/tag/v6.2.5) via #381.
