### ISSUE TITLE
Chaining results return undefined

### ISSUE THREAD

**Issue by KillerSquid** [limonte/sweetalert2#336]
Okay, I'm at a loss here.  All the inputs are behaving correctly but my `results` keep returning `undefined`.  Any thoughts?  Using latest SWAL version and jQuery 3.1.0
my code:
  
     $(".createacctbtn").click(function(){
            swal.setDefaults({
                  confirmButtonText: 'Next &rarr;',
                  reverseButtons: true,
                  showCancelButton: true,
                  animation: false,
                  progressSteps: ['1', '2', '3']
               })

            var steps = [
              {
                  text: 'Enter your name',
                  input:'text'
              },
                {
                    text:'Enter your desired password',
                    input: 'password'
                },
                {
                    text: 'Enter your email address',
                    input: 'email'
                }
            ]

            swal.queue(steps).then(function(result) {
              swal.resetDefaults()
              swal({
                title: 'All done!',
                html:
                  'Your answers: <pre>' +
                    JSON.stringify(result) +
                  '</pre>',
                confirmButtonText: 'Lovely!',
                showCancelButton: false
              })
            }, function() {
              swal.resetDefaults()
            })
    });
```

**Comment by limonte** [comment]
update swal2 to the latest.

**Comment by limonte** [comment]
Probably, your issue is related to https://github.com/jsdelivr/jsdelivr/issues/14468

**Comment by KillerSquid** [comment]
Weird- I updated the latest version an hour ago and was getting `undefined`.  Just did it again and now it's working.  Thanks!

**Comment by limonte** [comment]
@KillerSquid great! Just for notice, which package manager did you use?

**Comment by KillerSquid** [comment]
Just downloaded directly from GitHub and added it to my page via `<script src="./js/sweetalert2.min.js" type="text/javascript"></script>` then dumped cache and hard reloaded in Chrome. (online app in development)
