### ISSUE TITLE
Promisse then and reject

### ISSUE THREAD

**Issue by nikko1337** [limonte/sweetalert2#337]
I am trying to use swal so I have the code:

` swal({
        title: 'Success!',
        text: 'test',
        type: 'success',
    })
   .then(function() {console.log('test'); }
});`

My problem is if the user clicks outside swal the then part will not be executed, so I have to do:

` swal({
        title: 'Success!',
        text: 'test',
        type: 'success',
    })
   .then(function() {console.log('test'); }, function() {console.log('test');})
});`

So now I have duplicated code. I would have to create a function to be called in the success and dismiss event. Is there anyway to avoid that?

**Comment by limonte** [comment]
clicks outside !== confirm button click, so it can't be handled in one place.

Outside click is the dismissal, [handling dismissals](https://github.com/limonte/sweetalert2#handling-dismissals).

**Comment by nikko1337** [comment]
@limonte  This is not a confirmation tho, it's just a success message.

**Comment by limonte** [comment]
You can use finally polyfill for Promise, [jsfiddle](https://jsfiddle.net/poht7ga8/1/)

**Comment by nikko1337** [comment]
Thanks!

**Comment by limonte** [comment]
You're welcome :)

Don't forget to include the finally polyfill to be able to use it: https://cdn.jsdelivr.net/promise.prototype.finally/1.0.1/finally.js
