### ISSUE TITLE
Extjs conflicting z-index

### ISSUE THREAD

**Issue by FenixGit** [limonte/sweetalert2#341]
Hi,

Please, change o .swal2-container z-index: 1060 to 19060. If it stay with 1060, stay under  popup windows.

Thanks

**Comment by limonte** [comment]
You should override .swal2-container z-index in your project.

Related comment: https://github.com/limonte/sweetalert2/issues/296#issuecomment-248434501

For example, if we set .swal2-container z-index to 19060, then we'll make a new conflict between swal2 and http://dbushell.github.io/Pikaday/ which has z-index 9999
