### ISSUE TITLE
Custom class strings are not properly sanitized

### ISSUE THREAD

**Issue by daerogami** [limonte/sweetalert2#342]
If the class list has trailing whitespace, add function fails with the error `Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.`
the exact offending param `confirmButtonClass: "btn btn-lg btn-danger ",`

**Comment by birjolaxew** [comment]
[Cannot reproduce.](https://jsfiddle.net/ad3quksn/47/) Could you provide a JSFiddle example so we can debug it?

**Comment by limonte** [comment]
@birjolaxew :) In future let's assign the issue before coding :)

**Comment by birjolaxew** [comment]
@limonte Heh, good idea.

**Comment by limonte** [comment]
@birjolaxew btw, I [switched](https://github.com/limonte/sweetalert2/commit/c14dece481494db037edeb7b02519fa2f2fadb52) the swal2 JS linting from eslint to [standard](https://github.com/feross/standard).

One of standard rules is: 

> No semicolons – [It's](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) [fine.](http://inimino.org/~inimino/blog/javascript_semicolons) [Really!](https://www.youtube.com/watch?v=gsfbh17Ax9I)

**Comment by limonte** [comment]
Fixed in [v6.0.0](https://github.com/limonte/sweetalert2/releases/tag/v6.0.0)
