### ISSUE TITLE
swal() does not appear to be returning a promise

### ISSUE THREAD

**Issue by daerogami** [limonte/sweetalert2#343]
[Offending Code](https://gist.github.com/daerogami/6316b11d75ba109814a6a5ed6316c12f)

The above code results in the following error.
`Cannot read property 'then' of undefined`

**Comment by birjolaxew** [comment]
[Cannot reproduce.](https://jsfiddle.net/ad3quksn/47/) Could you provide a JSFiddle example so we can debug it?

**Comment by limonte** [comment]
I also can't reproduce. @daerogami reopen with jsfiddle if needed :)

**Comment by daerogami** [comment]
Confirmed that this was caused by an angular wrapper. [This one](https://github.com/JumBay/ngSweetAlert2/blob/master/SweetAlert.js) properly forwards swal's promise type.
