### ISSUE TITLE
Disable focus of input field on showInputError

### ISSUE THREAD

**Issue by virik** [limonte/sweetalert2#344]
Would be really great to get an option for this on iOS devices.

I've removed the code from js file myself, but this break future updates of course.

**Comment by limonte** [comment]
And which element should get focus instead of input field?

**Comment by virik** [comment]
No one :)

The point is to prevent the keyboard from popping up. Example:

In our app we ask the user for his email address. If he doesn't want to share this, he will leave the input empty and click next. We then display an error message telling him to confirm, and at the same time the keyboard pops up.

**Comment by limonte** [comment]
This case is too custom, for introducing the new option.
