### ISSUE TITLE
Support animationIn and animationOut

### ISSUE THREAD

**Issue by pabloleban** [limonte/sweetalert2#346]
I want to set `animation:false` only on the **open** of the modal, **but not on the close** of it, so I thought that maybe a cool way to fix this is to have something like `animationOpen` or `animationIn` and `animationClose` or `animationOut`. So by making `animationOpen: false,` I would be able to achieve that.

**Comment by limonte** [comment]
Your case is too custom to be implemented in the library. You should disable closing animation per your project: https://jsfiddle.net/ad3quksn/49/
