### ISSUE TITLE
Multiple inputs demo on homepage

### ISSUE THREAD

**Issue by rol4400** [limonte/sweetalert2#348]
The code sample does not work. It should say:
swal({
      title: 'Multiple inputs',
      html: '<input id="swal-input1" class="swal2-input" autofocus><input id="swal-input2" class="swal2-input">',
      preConfirm: function () {
        return new Promise(function (resolve) {
          resolve([
            $('#swal-input1').val(),
            $('#swal-input2').val()
          ])
        })
      }
    }).then(function (result) {
      swal(JSON.stringify(result))
    }).catch(swal.noop)
instead.

**Comment by limonte** [comment]
Fixed, thanks @rol4400

**Comment by rol4400** [comment]
np
