### ISSUE TITLE
Doesn't work on native Android browser (Samsung Galaxy Note 3)

### ISSUE THREAD

**Issue by sandropoluan** [limonte/sweetalert2#353]
Sweetalert2 doesn't work on android native browser (Samsung Galaxy Note 3).
Already tried to visit the https://limonte.github.io/sweetalert2/ and try to open all the example  dialogs and no one is working.

**Comment by limonte** [comment]
Thanks for reporting, but I don't believe this issue will be fixed because SweetAlert2 doesn't support it: https://github.com/limonte/sweetalert2#browser-compatibility

**Comment by birjolaxew** [comment]
Could also be an issue with an old Android version. If you're still running <4.4.4 it'll definitely break, what with promises not being supported.
