### ISSUE TITLE
Bug on iOS devices when body is positioned relatively

### ISSUE THREAD

**Issue by ekscentrysytet** [limonte/sweetalert2#355]
When `body` element has style `position: relative` sweet alert assigns it's top property for iOS devices so when alert dissapears I can't scroll back to top of the page because content is cutted off. You can check it on the [demo page](https://limonte.github.io/sweetalert2/) by setting `position: relative` and enabling device mode.

**Comment by birjolaxew** [comment]
Should be fixed if we reset `document.body.style.top` in [`undoIOSfix`](https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.js#L290-L296).

**Comment by ekscentrysytet** [comment]
Thank you! Will be waiting for fix!
