### ISSUE TITLE
Preconfirm on queue

### ISSUE THREAD

**Issue by Taytus** [limonte/sweetalert2#359]
I'd like to show a loader as in the Ajax request example but at the end of the chain.

I want to show ["question A", "question B"] and trigger an ajax call with the preconfirm animation in that example after "question b" is displayed without loading an extra modal.

Currently, if I set preconfirm, it triggers for every question and showLoaderOnConfirm:true does nothing.

Thanks!

**Comment by limonte** [comment]
Could you please provide simple jsfiddle so I can reproduce this bug?

JSFiddle template: https://jsfiddle.net/ad3quksn/51/

**Comment by Taytus** [comment]
I kinda fixed it with a hacky solution: https://jsfiddle.net/ad3quksn/66/
Thank you!!
