### ISSUE TITLE
$ is not a function when using smoothscroll

### ISSUE THREAD

**Issue by angeltcho** [limonte/sweetalert2#36]
Hello, 
I have an issue in sweetalert2 that I don't have in sweetalert.

While using both this code : 
```
    $(document).on('click', '.sscroll', function (e) { // Au clic sur un élément
        href = $(this).attr('href');
        nhref = href.charAt(0);
        if (nhref === '#') {
            e.preventDefault();
            $('html,body').animate({
                scrollTop: $(this.hash).offset().top
            }, 1200);
        } else {
            window.location.href = href;
        }
        return false;
    });
```

Console will return "$ is not a function"
jQuery version is : 1.11.2

Thank you

**Comment by limonte** [comment]
@angeltcho did you hear about [code indentation](https://en.wikipedia.org/wiki/Indent_style)? Please edit your code example so it can be readable, thanks.

**Comment by limonte** [comment]
@angeltcho thank you, on which line do you have `Console will return "$ is not a function"` exception?
