### ISSUE TITLE
Only text is behaving as link after swal is shown in IE 10

### ISSUE THREAD

**Issue by leonardoteck** [limonte/sweetalert2#361]
Given the following code:
```html
<a href="#">
    <div style="width: 100px; height: 100px; background: cyan; margin-left: 50px;">
        test link
    </div>
</a>
```
The expected result is:
![image](https://cloud.githubusercontent.com/assets/12712633/20811875/950a92e6-b7f6-11e6-8509-2da9adec0ad1.png)

But in IE 10, after swal is shown, I got this:
![image](https://cloud.githubusercontent.com/assets/12712633/20811917/bb3e9aca-b7f6-11e6-9ec8-cf9b9e06f249.png)
![image](https://cloud.githubusercontent.com/assets/12712633/20811931/c6a4d000-b7f6-11e6-99b3-30012adbda4c.png)

The solution I found for now is to remove the swal DOM element every time I use it.

**Comment by limonte** [comment]
First of all, thanks for reporting this @leonardoteck !

But, unfortunately, after looking at the browsers statistics today I decided to drop IE10 support.

Sorry, I hope you understand me :)

**Comment by leonardoteck** [comment]
That's OK. Thanks for this amazing tool!
