### ISSUE TITLE
Modal closes instantly if open button is on the same spot as close button

### ISSUE THREAD

**Issue by hxhjx** [limonte/sweetalert2#363]
It seems like there is a small input block delay missing.

I also couldnt find any options for that.

Is there any solution to this problem?

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
