### ISSUE TITLE
iOS browser bar pops up

### ISSUE THREAD

**Issue by Jordy-A** [limonte/sweetalert2#364]
Each time I click a button to open an alert, the browser bar on my iPhone 5 (Safari) pops up. It's only an issue with Sweetalert2. Not with v1, or with bootstrap modals or something like that. [See this gif](http://i.giphy.com/3oriO4PDdI5jUz26ze.gif).

When I scroll down, the browser bar, slides out, but when I open an alert again, the browser bar popups. Has it something to do with positioning the alert?

**Comment by limonte** [comment]
Thanks for reporting this @Jordy-A 

Any help with fixing this issue will be much appreciated.

**Comment by limonte** [comment]
I tried several times with different approaches and unfortunately, I need to say that this couldn't be fixed. It's the iOS Safari issue and I can't come up with any hack for fixing it.
