### ISSUE TITLE
Password input support for queue

### ISSUE THREAD

**Issue by Taytus** [limonte/sweetalert2#365]
I'm using queue to ask for username/password. 
It is possible to configure the second (or any) step to have a password field?
Thank you.

**Comment by limonte** [comment]
https://limonte.github.io/sweetalert2/#input-password

**Comment by Taytus** [comment]
@limonte Thank you for the link, that didn't solved my problem thou.

For anyone looking for a solution to similar problem, this is how I fixed it:

`swal.setDefaults({
        input: 'text',
        confirmButtonText: 'Next &rarr;',
        showCancelButton: true,
        animation: false,
        progressSteps:aux_progress_steps($steps),
        showLoaderOnConfirm:true,

        inputValidator: function (result) {
            return new Promise(function (resolve, reject) {
                if (result) {
                    resolve()
                } else {
                    reject('You need to write something!')
                }
            })
        },
        preConfirm: function() {

            if(swal.getQueueStep() == $steps.length-1) {
                return new Promise(function (resolve, reject) {
                    setTimeout(function() {

                        resolve();
                    }, 100);

                }).then(function(){
                    swal('Ajax request finished');
                })
            }else{
               //THIS IS THE FIX
                swal.setDefaults({input: 'password'});

                return new Promise(function (resolve) {
                    setTimeout(function() {
                        resolve();
                    }, 1);
                });
            }
        }

    });`
