### ISSUE TITLE
timer needs to be reset when 'closeOnConfirm' is set to false

### ISSUE THREAD

**Issue by electronicsguy** [limonte/sweetalert2#37]
If the alert has a timer set (say n seconds), and 'closeOnConfirm' is set to false, then the second window that appears (after confirm) will get closed if 'n' seconds elapse. This time includes the time spent in deciding confirm or no. 

The timer needs to be reset in between for correct/desirable operation.

**Comment by crabbly** [comment]
I could not replicate this issue. 
Below is a fiddle, exactly as you described (I believe), and the second window won't get closed.
https://jsfiddle.net/crabbly/wmydys9L/
Make sure you are using the latest version of the library.

**Comment by limonte** [comment]
thank you @crabbly for jsfiddle!
