### ISSUE TITLE
Newlines in `text` after 6.2.2

### ISSUE THREAD

**Issue by rorc** [limonte/sweetalert2#371]
Now if pass array to text, ites will be `text.join()`
But how i can each error set in new string?
`errors.join('<br>')` outputs `<br>` as text and `errors.join("\n")` not working :(

**Comment by birjolaxew** [comment]
If you want linebreaks between each element in the array, you should use `html` instead of `text` (and `.join('<br>')` as in your example).

This was the one breaking change in #369, and is mostly just a simplification (now `text` sets text, `html` sets HTML - before `text` formatted the string and then set text, `html` set HTML), but it could be reimplemented if @limonte would rather avoid the breaking change. Leaving this open for @limonte to see.

**Comment by rorc** [comment]
@birjolaxew its very inconvenience using swal all time with object as params, that get line-breaks
`swal({ html: err.join('<br>'), title: 'title', etc })` => inconvenience
`swal('Error :(', err.join("\n"))` => clearly, simplicity and great =)

**Comment by birjolaxew** [comment]
Seems more like we should consider the second parameter to be `html` instead of `text` if it's a string (which is also how `title` works now). Doing so shouldn't be a breaking change, considering #362.

**Comment by akarelas** [comment]
Wouldn't it be even better for the second parameter to be text, but convert it manually into HTML, while substituting "\n" with "<br />" ?

**Comment by birjolaxew** [comment]
@akarelas That would be the other option. The problems I personally have with that solution is that

1. There's no super pretty solution. We'd have to manually convert specific characters (eg. `<` and `>` to `&lt;` and `&gt;`), which isn't quite as pretty as letting the browser handle it.
2. Separation of concerns. SweetAlert2 isn't intended to be an escape library. While it isn't particularly difficult, I'd rather leave HTML escaping to something that's intended for the purpose (eg. the browser), and not have to worry about it.
3. Relatively arbitrary formatting rules. If we're going to be guessing at what the user wants (eg. by replacing `\n` with `<br>`), then we might as well also add logic for wrapping text paragraphs in paragraph tags, putting links in anchor tags, or whatever other formatting you'd expect people to want to use. It's easier to just take the stance of "you give us what you want us to display, we display it".

Again, it's not particularly hard to implement, and as mentioned in my first comment the decision is ultimately up to @limonte, but I'd personally prefer not modifying `text` before it's inserted.

**Comment by limonte** [comment]
I totally agree with the @birjolaxew's proposal:

> Seems more like we should consider the second parameter to be html instead of text if it's a string (which is also how title works now). Doing so shouldn't be a breaking change, considering #362, and would turn your code into swal('Error :(', err.join('<br>')).

**Comment by akarelas** [comment]
I guess it's not very difficult for the user to define a function that will convert text into HTML and replace "\n" into br's, so I'm ok with that.

**Comment by limonte** [comment]
Done in [v6.2.3](https://github.com/limonte/sweetalert2/releases/tag/v6.2.3), you can now use swal2 like this:

```js
swal('Error :(', err.join('<br>'))
```

**Comment by rorc** [comment]
Thanks, i am happy now =)

**Comment by 3du4** [comment]
I have a string with new lines inside of the text variable, how do I display the new lines inside of the alert?

**Comment by limonte** [comment]
@3du4 https://jsfiddle.net/opwznh9x/2/

**Comment by 3du4** [comment]
@limonte, thank you. I had to create function to replace all concurrences but it worked :)

**Comment by stayingcool** [comment]
In my case I had to use this to replace all occurenences:
`str.replace(/\n/ig, '');`

Look at the answer by Dmitriy: 
[https://stackoverflow.com/questions/35808205/javascript-replace-from-string]
