### ISSUE TITLE
Disable onCancel exception

### ISSUE THREAD

**Issue by rorc** [limonte/sweetalert2#372]
Hi)

Hi i can disable exception (`uncaught exception: cancel`) on cancel button?

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/issues?q=is%3Aissue+uncaught+exception+is%3Aclosed

**Comment by rorc** [comment]
Can i do this globally? `.catch(swal.noop)` ?

**Comment by birjolaxew** [comment]
You could always proxy the `swal` function:

    swal = (function(){
      var _swal = swal;
      return function(){
        return _swal.apply(_swal, arguments).catch(_swal.noop);
      };
    })();

**Comment by rorc** [comment]
@birjolaxew  Oh, so crutch :) But works, thanks =)

**Comment by rorc** [comment]
@birjolaxew But no, on press OK, anyway triggers resolve function (

**Comment by birjolaxew** [comment]
@rorc Yes. That's how promises work. If an error is caught and handled, then all following `.then` callbacks will be called like normal. You can't both have a generic `.catch` callback and also only call `.then` when the alert is succesful.
