### ISSUE TITLE
Prevent ENTER?

### ISSUE THREAD

**Issue by alepodj** [limonte/sweetalert2#373]
Simple Error Message:

swal({
             title: "Error!",
             html: "Error",
             type: "error",
             allowEscapeKey: false,
             allowOutsideClick: false,
             showConfirmButton: false,
             timer: 5000
});

In a case like this, i want to force the user to wait the timer, confirmation buttons are disabled, no mouse click, no escape, but ENTER seem to dismiss the swal window, is there a 'allowEnterKey: false' type of functionality?

https://jsfiddle.net/fwwzhtun/10/

Thanks in advance.

**Comment by birjolaxew** [comment]
Seems like a bug with [our key handler](https://github.com/limonte/sweetalert2/blob/0aa8736134528dec35c1c2942b50fa9470f5aca2/src/sweetalert2.js#L592-L600) not respecting `showConfirmButton`/`showCancelButton`.

**Comment by limonte** [comment]
Fixed in https://github.com/limonte/sweetalert2/releases/tag/v6.2.4

Thanks for reporting @alepodj !
