### ISSUE TITLE
Text input not clickable when bootstrap modal is open

### ISSUE THREAD

**Issue by tobiv** [limonte/sweetalert2#374]
Fiddle: https://jsfiddle.net/0Lng89tq/2/

When a bootstrap modal is open and a sweetalert opens on top of it, text input is not clickable. Buttons however work fine. I also noticed that the alert text can't be selected.
If you remove the bootstrap modal div (not backdrop), text input becomes selectable again.

I fiddled around with z-index/positioning on the sweetalert, but can't figure out what's happening.

**Comment by birjolaxew** [comment]
It's not an issue with z-index ([swal2 specifically has its z-index set to be above bootstrap modals](https://github.com/limonte/sweetalert2/issues/296#issuecomment-248434501)), but an issue with some kind of event listener setting the focused element to be the bootstrap modal whenever it loses focus.

Buttons and the backdrop still work since they rely on click, not focus.

---

Debugging:
Dev tools, select `.modal.fade.in`, "Event listeners" tab, remove first `focusin` listener (the one with jQuery as a source), problem is fixed. Now to figure out where in Bootstrap's code that event is attached.

**Comment by tobiv** [comment]
Excellent, thanks for your answer. Looking for the event listener, I found a solution in bootstrap:

```
    $('#myModal').on('shown.bs.modal', function() {
        $(document).off('focusin.modal');
    });
```
https://jsfiddle.net/0Lng89tq/5/

**Comment by birjolaxew** [comment]
Note that if you want to (kind of sort of) fix this on your page, you can remove the responsible event listener by doing:

    $(document).off('focusin.bs.modal')

Note that this will allow focus to be <kbd>Tab</kbd>'ed to inputs/buttons outside of the modal.

**Comment by limonte** [comment]
nice trick @tobiv :+1:

**Comment by birjolaxew** [comment]
@tobiv Yes, that was the solution I was going to suggest. Good find.

Note that doing so will allow the user to <kbd>Tab</kbd> to inputs/buttons outside of the modal.

**Comment by moazam1** [comment]
Thanks @tobiv

**Comment by lc850** [comment]
Thanks @tobiv real and good solution.

**Comment by cookienfy** [comment]
Excellent, Thanks for @tobiv . This problem has confused a long time. Today it was solved finally.

**Comment by JamoCA** [comment]
Hey @tobiv I noticed the bootstrap solution you posted in 2016 doesn't appear to work now.
https://jsfiddle.net/0Lng89tq/5/

MagnificPopUp hasn't changed since Feb 2016, so I'm wondering if something in sweetalert regressed or if new browser features are preventing this from functioning properly.

**Comment by aramiscubillo** [comment]
For me the problem was that I was using jquery 3.2.1, so I change it to 2.1.3 which was use on previous app we had develop and everything worked fine. Might be something with jquery and bootstrap compatibility versions.

**Comment by madmark81** [comment]
I'm looking to solve this problem in R. Would anyone here know how to code it for R? I have an app with the problem here on github that you can use to try. Would really appreciate any help!

**Comment by samturrell** [comment]
@madmark81 and anyone else that come across this issue, you can usually solve bootstrap modal focus issues by disabling the focus enforcement using `$.fn.modal.Constructor.prototype.enforceFocus = function () {};`

**Comment by madmark81** [comment]
Thanks for your fast response, but Yeah I found that line of code, only I
don't know how to convert it so that it works in R.
I assume you can't use it like this

Mark

**Comment by limonte** [comment]
> and anyone else that come across this issue, you can usually solve bootstrap modal focus issues by disabling the focus enforcement using `$.fn.modal.Constructor.prototype.enforceFocus = function () {};`

Confirming this, @JamoCA here's your case fixed: https://jsfiddle.net/0Lng89tq/34/

**Comment by madmark81** [comment]
@limonite I was asking for a solution using R and Shiny. Any clue how to make that line of code work in R?

**Comment by adykn** [comment]
Thanks all around...

**Comment by MichaelTheHuman** [comment]
To anyone who's got this issue using Bootstrap 4 instead of 3 as in answers above, use this instead: 
`$.fn.modal.Constructor.prototype._enforceFocus = function() {};`

**Comment by stephanvierkant** [comment]
Overriding `enforeFocus` works, but can anyone explain the downsides of this? That method exist in `modal.js` for a reason, I presume.

Shouldn't we try to make a PR so `enforeFocus` is an option in Bootstrap?

**Comment by MujeebAyokunle** [comment]
I am facing the same problem with my angular 7 project. If anyone has a solution to that, kindly respond.
![Screenshot (5)](https://user-images.githubusercontent.com/25282432/65717491-62941200-e099-11e9-92ac-df2a1b65b172.png)

**Comment by pathik-appachhi** [comment]
Try to **remove the tabIndex property of the modal**, when your input/textbox is open. **Set it back to what ever it was, when you close input/textbox**. This would resolve the issue **irrespective bootstrap version**, and **without compromising the user experience flow**.

**Comment by RPJack** [comment]
@tobiv  Thank you!!! good solution

**Comment by limonte** [comment]
Live demo: https://sweetalert2.github.io/recipe-gallery/bootstrap.html

**Comment by Blimie** [comment]
@tobiv Thank you!!! was wracking my brains on this!

**Comment by peterchibunna** [comment]
Add **data-bs-focus="false"** to the modal html. 
```
<div class="modal fade" id="dialog_box" data-bs-focus="false" aria-hidden="true" tabindex="-1">
...
```

Source https://stackoverflow.com/questions/69269449/ckeditors-popup-input-fields-dont-work-when-used-with-bootstrap-5-modal-ckedit

**Comment by kawtog** [comment]
Thank You Very much it so fix the problem @kiasta 
I'm using bootstrap 5.1.3
`$.fn.modal.Constructor.prototype._initializeFocusTrap = function () { return { activate: function () { }, deactivate: function () { } } };`

**Comment by omd166** [comment]
Removing tabindex="-1" from myModal seems to do the job: [Fiddle](https://jsfiddle.net/L40cL6zk/1/)

The problem is tabindex, because if you set it to -1, you won't be able to access that element.

**Comment by taufiqridha** [comment]
For someone running on bootstrap@5.1.3  I solved this by set focus option to false on Modal object.
Something like
`const containerClaimReqModal = document.getElementById("claim-request-detail-modal");
const claimReqModal = new bootstrap.Modal(containerClaimReqModal,{focus:false});`

**Comment by theoaks** [comment]
> 

This doesn't work on bootstrap 5 modal. Is there another way to fix it for bootstrap 5?

**Comment by amolkapadi** [comment]
> Removing tabindex="-1" from myModal seems to do the job: [Fiddle](https://jsfiddle.net/L40cL6zk/1/)
> 
> The problem is tabindex, because if you set it to -1, you won't be able to access that element.

Thank you so much ..its working

**Comment by amolkapadi** [comment]
Removing tabindex="-1" from Modal.......

**Comment by HamzaIlyas** [comment]
> Try to **remove the tabIndex property of the modal**, when your input/textbox is open. **Set it back to what ever it was, when you close input/textbox**. This would resolve the issue **irrespective bootstrap version**, and **without compromising the user experience flow**.

Thank you!

**Comment by tariqulislam16** [comment]
> I found a potential solution for bootstrap 5.1.0+.
> 
> `$.fn.modal.Constructor.prototype._initializeFocusTrap = () => ({ activate: () => { }, deactivate: () => { } });`
> 
> The activate and deactivate property needs to be added because otherwise it will throw errors when opening/closing the bootstrap modal. Setting data-bs-focus to false did not work. Setting $(document).off('bs.focustrap') also did not work. This was the only thing that worked for me.



> I found a potential solution for bootstrap 5.1.0+.
> 
> `$.fn.modal.Constructor.prototype._initializeFocusTrap = () => ({ activate: () => { }, deactivate: () => { } });`
> 
> The activate and deactivate property needs to be added because otherwise it will throw errors when opening/closing the bootstrap modal. Setting data-bs-focus to false did not work. Setting $(document).off('bs.focustrap') also did not work. This was the only thing that worked for me.

It worked for me. Using Bootstrap 5.3.0. Thanks.

**Comment by marcogarganigo** [comment]
faster solution: remove the tabindex attr in the modal

**Comment by haotrg035** [comment]
> Excellent, thanks for your answer. Looking for the event listener, I found a solution in bootstrap:
> 
> ```
>     $('#myModal').on('shown.bs.modal', function() {
>         $(document).off('focusin.modal');
>     });
> ```
> 
> https://jsfiddle.net/0Lng89tq/5/

saved my ass, Thanks bro.

**Comment by Kartikeya-chatterbug** [comment]
> > Excellent, thanks for your answer. Looking for the event listener, I found a solution in bootstrap:
> > ```
> >     $('#myModal').on('shown.bs.modal', function() {
> >         $(document).off('focusin.modal');
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://jsfiddle.net/0Lng89tq/5/
> 
> saved my ass, Thanks bro.

Doesn't work anymore :(

**Comment by yrizzz** [comment]
> Add **data-bs-focus="false"** to the modal html.
> 
> ```
> <div class="modal fade" id="dialog_box" data-bs-focus="false" aria-hidden="true" tabindex="-1">
> ...
> ```
> 
> Source https://stackoverflow.com/questions/69269449/ckeditors-popup-input-fields-dont-work-when-used-with-bootstrap-5-modal-ckedit

PERFECT !

**Comment by ogumemura** [comment]
Bootstrap 5.1.x environment.
```
    $('#myModal').on('shown.bs.modal', function() {
        $(document).off('focusin.modal');
    });
```
I had the same problem when the "offcanvas" modal was displayed and thought this technique would solve the problem, but after trying various methods, I could not solve it.

```
    $(document).off('focusin');  //NG
    $(document).off('focusin.bs.focustrap'); //NG
    ....
```
I had no choice but to read the BootStrap source and call ". _focustrap.deactivate()" to remove the 'focusin' event set in "document".

```
var elm = document.getElementById( 'offcanvasObject' );
var o = new bootstrap.Offcanvas(elm);
$( '#offcanvasObject' )'on( 'shown.bs.offcanvas', function () {
  o._focustrap.deactivate();
}
```

**Comment by id2002** [comment]
> Add **data-bs-focus="false"** to the modal html.
> 
> ```
> <div class="modal fade" id="dialog_box" data-bs-focus="false" aria-hidden="true" tabindex="-1">
> ...
> ```
> 
> Source https://stackoverflow.com/questions/69269449/ckeditors-popup-input-fields-dont-work-when-used-with-bootstrap-5-modal-ckedit

This option worked for me

**Comment by JohnnyDRussell** [comment]
On the didOpen() function of the swal, we append its container inside the bootstrap modal body, which allows it to be part of the focus elements without breaking the functionality of preventing focus to go behind the modal:

```
Swal.fire({
    didOpen: () => {
        const swalContainer = document.querySelector('.swal2-container');
        const modalBody = document.querySelector('.modal-body');
        if (swalContainer && modalBody) {
            modalBody.appendChild(swalContainer);
        }
    }
});
```

**Comment by RohanMahajan707** [comment]
Thank you @tobiv Your solution worked for me. Though I was using custom popup instead of sweet alert.
