### ISSUE TITLE
Input type select not working on some browsers

### ISSUE THREAD

**Issue by Kostronor** [limonte/sweetalert2#377]
This should be a select with 3 options (firefox mobile):

![image](https://cloud.githubusercontent.com/assets/644950/21438567/05684710-c88a-11e6-97d7-40334ce4f19c.png)

On Microsoft Edge this looks like three buttons sideways.

Currently checking all browsers I can think of.

**Comment by birjolaxew** [comment]
[JSFiddle example.](https://jsfiddle.net/hxzhpg3w/)

Could not reproduce in my (admittedly old) W10/Edge VM. Could you provide a JSFiddle with an example?

**Comment by Kostronor** [comment]
I found what is the problem, I am using materializecss for my site and their css changes the input. I made a JSFiddle with it: https://jsfiddle.net/2jmf6L6w/1/
My Edge is currently working but I'll test it on mobile, there is was the prominent problem...

**Comment by Kostronor** [comment]
Okay I tried this, with all mobile browsers and the jsfiddle works perfectly fine... I'll close this till I can reproduce the issue in a fiddle!
