### ISSUE TITLE
inputClass not working

### ISSUE THREAD

**Issue by marcuslma** [limonte/sweetalert2#378]
Hello,

I am trying to use the option `inputClass`, but it's not working.
It's being added to the input element, but my class style is being ignored.

My code:
```
swal({
  type: 'info',
  text: 'Entrer your email.',
  input: 'email',
  inputClass: 'my-swal2-input',
  confirmButtonText: 'Send',
  confirmButtonColor: '#97CB5F',
  showCancelButton: true,
  cancelButtonText: 'Cancel',
  allowOutsideClick: false,
  showLoaderOnConfirm: true,
  preConfirm: function (email) {
    return new Promise(function (resolve, reject) {
      setTimeout(function () {
        if (email === 'taken@example.com') {
          reject('This email is already taken.')
        } else {
          resolve()
        }
      }, 2000)
    })
  }
}).then(function (email) {
  swal({
    type: 'success',
    title: 'Ajax request finished!',
    html: 'Submitted email: ' + email
  })
});
```

My class:
```
.my-swal2-input {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  outline: 0;
  color: #FFFFFF;
  text-align: center;
  border-top: 0;
  border-right: 0;
  border-left: 0;
  border-bottom: 1px solid #FFFFFF;
  background-color: transparent;
  border-radius: 0;
}
```

HTML output:
`<input class="swal2-input my-swal2-input" placeholder="" type="email" style="display: block;">`

Class output (default from SweetAlert2):
```
.swal2-modal .swal2-input {
  width: 100%;
  box-sizing: border-box;
  border-radius: 3px;
  border: 1px solid #d9d9d9;
  font-size: 18px;
  box-shadow: inset 0 1px 1px rgba(0,0,0,.06);
  -webkit-transition: border-color box-shadow .3s;
  transition: border-color box-shadow .3s;
}
```

Waiting for help, thank you!

**Comment by limonte** [comment]
HTML output is correct, you should check your CSS styles. For more help please reopen with jsfiddle https://github.com/limonte/sweetalert2/blob/master/contributing.md

**Comment by marcuslma** [comment]
I tested into feedle: https://jsfiddle.net/o1hkat2h/2/
It's working properly there.

I am using through npm package: `import { default as swal } from 'sweetalert2'`
And it's not working.

**Comment by birjolaxew** [comment]
If we can't reproduce it, we'll have trouble helping you fix it.

If the alert is being opened (with the correct class), but your custom CSS isn't applied, then it probably isn't a problem with swal. I'd suggest checking if your CSS is actually included on the page using the browser's dev tools.

**Comment by marcuslma** [comment]
Guys, I am so sorry, for wasting your time.
A fucking `;` after my class was breaking everything.
Sorry again, so amateur...
