### ISSUE TITLE
Callback for each queue item?

### ISSUE THREAD

**Issue by Script47** [limonte/sweetalert2#383]
I was wondering if there are callbacks for each queue item?

```javascript
var steps = [
        {
            title: 'Big Blah',
            text: 'Welcome, blah blah.',
            onNext: function () {}
        },

        {
            title: 'More Blah',
            text: 'Some more blah?'
        }
    ];
```

As you can see the ```onNext()``` clause I've added, that is obviously pseudo-code, is there anything currently like that implemented?

Thanks!

**Comment by toverux** [comment]
Hi,

Yes, you have something like that, but it's way better. It's the `preConfirm` option.
It gets executed when the user clicks the confirm button (no joking!)
Assign a function to it, that *must* return a Promise. When the promise is resolved, the next step is shown. If the promise is rejected, the rejection will be displayed as a validation error.

So, you can control the transition to the next step, display an error, and even do the validation asynchronously, thanks to the promise.

ES2015 example:

```js
swal.setDefaults({
    input: 'text',
    confirmButtonText: 'Next',
    animation: false,
    progressSteps: ['1', '2', '3']
});

swal.queue([
    {
        title: 'Question 1',
        preConfirm: answer => new Promise((resolve, reject) => {
            resolve(answer); // validation ok, go to next step.
            
            // or:
            reject(`Answer "${answer}" is invalid.`);
        })
    },
    'Question 2',
    'Question 3'
]).then(
    (result) => {
        console.info(result);
        swal.resetDefaults();
    },
    () => swal.resetDefaults()
);
```

See the implementation itself: https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.js#L405

**Comment by birjolaxew** [comment]
Yep, as @toverux mentioned, `preConfirm` can function like what you're looking for. You just have to `return Promise.resolve()` at the end of it ([JSFiddle](https://jsfiddle.net/mv5v3kg4/)).
