### ISSUE TITLE
Custom root element

### ISSUE THREAD

**Issue by SasSam** [limonte/sweetalert2#392]
Referring to the original issue in Sweet Alert project: https://github.com/t4t5/sweetalert/issues/469

> It would be nice if you could specify which element sweet alert appends to, instead of defaulting to the body.

So for example if we could define the element in the options, that would be great. Like this:
```
swal({
  title: "Sweet!",
  text: "This should append to my div with my-class classname",
  appendTo: ".my-class"
});
```
The selector could be a class name or ID with # sign.

Thanks!

**Comment by readme42** [comment]
If going configurably, I personaly would prefer the insert-logic used by ng-bootstrap for modals. They enforce the template 

```html
<template ngbModalContainer></template>
```

somewhere in your markup. The Modal is inserted at exactly this place.

**Comment by limonte** [comment]
Which behavior of the gray overlay you're expecting in this case - to fill only parent element or whole body?

**Comment by SasSam** [comment]
@readme42 I'm not using Angular.

**Comment by SasSam** [comment]
@limonte I'd detach the whole ".swal2-container" element and append it to the newly defined "root" element.

**Comment by SasSam** [comment]
Currently it's hardcoded in the dom.js to append it to the body.
https://github.com/limonte/sweetalert2/blob/master/src/utils/dom.js#L25

**Comment by limonte** [comment]
Could you please answer my question? :)

**Comment by SasSam** [comment]
@limonte Ahh.... sorry! I'd see the same behaviour as it has now, so it should fill the whole body. However it could be an another feature in the future to define its scope. :)

**Comment by toverux** [comment]
@limonte did you read the original issue in t4t5's repository? There may effectively be some use cases. And of course, the overlay would still fill the viewport.

**Comment by limonte** [comment]
This will be easily added after https://github.com/limonte/sweetalert2/pull/414 merged

**Comment by limonte** [comment]
It would be great if any of you can take a look on https://github.com/limonte/sweetalert2/pull/443
