### ISSUE TITLE
alert dialog behind modal dialog

### ISSUE THREAD

**Issue by vowtree** [limonte/sweetalert2#393]
`<div class="modal fade" id="ajax" role="basic" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <img src="{% static "plugin/metronic/global/img/loading-spinner-grey.gif" %}" alt="" class="loading">                        
                    </div>
                </div>
            </div>
        </div>`
I open a modal dialog and put a button on it ,  when click the button and show sweetalert dialog，but the sweetalert dialog is behind the modal dialog ，how to let the sweetalert on the top ??

**Comment by birjolaxew** [comment]
Please see [our contribution guidelines](https://github.com/limonte/sweetalert2/blob/master/contributing.md):

> For bug reports, please include:
> 
> - a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
> ...
> 
> JSFiddle template: https://jsfiddle.net/ad3quksn/51/

**Comment by limonte** [comment]
Welcome to Github @vowtree:) Please read https://github.com/limonte/sweetalert2/blob/master/contributing.md and reopen this issue with jsfiddle if needed.
