### ISSUE TITLE
Can I add an input field AND textview below that input field?

### ISSUE THREAD

**Issue by asafl1976** [limonte/sweetalert2#394]
I would like to add an input field AND textview below that input field, so i can enter an email address in the input filed and email body in the textview, is that possible somehow?
THANKS

**Comment by toverux** [comment]
Multiple inputs aren't supported directly, but you can workaround using our preConfirm hook that lets you modify the value returned by the promise.

> Multiple inputs aren't supported, you can achieve them by using html and preConfirm parameters.
Inside the preConfirm() function you can pass the custom result to the resolve() function as a parameter:

```js
swal({
  title: 'Multiple inputs',
  html:
    '<input id="swal-input1" class="swal2-input" autofocus>' +
    '<input id="swal-input2" class="swal2-input">',
  preConfirm: function () {
    return new Promise(function (resolve) {
      resolve([
        $('#swal-input1').val(),
        $('#swal-input2').val()
      ])
    })
  }
}).then(function (result) {
  swal(JSON.stringify(result))
}).catch(swal.noop)
```

(The example comes from the documentation, juste before the "Methods" title)
