### ISSUE TITLE
[Suggestion] Change the default font-family

### ISSUE THREAD

**Issue by dethierx** [limonte/sweetalert2#398]
Hello.
First thanks for your job ;)

The font "Helvetica Neue" doesn't include a lot of (special) characters (ex: çéèêëµ€).
I see the problem in title and text/html part. No problem with texts of buttons.
The problem occurs in Google Chrome 55 and Internet Explorer 11. No problem with FireFox 33 and Microsoft Edge 38. Not tested in Safari/Opera.

This is a Plunker to reproduce the problem. Uncomment my custom style to see my solution.
https://plnkr.co/edit/HlxZTS9xz2xZIubhIGRH?p=preview

**Comment by toverux** [comment]
Hm, are you sure that you're not having an encoding issue or something?
I see that Helvetica Neue is the primary font of Bootstrap, for example. They would not take an ascii-only font :)

On Linotype, I read that Helvetica Neue *["supports up to 100 languages, such as English, German, French, Arabic, and Russa."](https://www.linotype.com/fr/1266/neue-helvetica-famille.html)*.

**Comment by dethierx** [comment]
I try the plunker with 2 other computers, no problem.
The one with problem: windows 7 64bits.
![sweetalert2_fontfamily](https://cloud.githubusercontent.com/assets/9282673/21734071/da7dac8c-d461-11e6-95de-494a3bd7acb2.png)

**Comment by limonte** [comment]
Tested in Linux/Chrome and Win7/Chrome and can't reproduce. This issue is up to your environment, @dethierx

**Comment by dethierx** [comment]
I delete my local buggy font "helvetica regular.ttf" and and everything works perfectly.
