### ISSUE TITLE
Enter(return) key reopens a closed alert and disables Enter key for other alerts

### ISSUE THREAD

**Issue by nickfederighi** [limonte/sweetalert2#40]
I thought this may have been an issue with my configuration, but it's reproducible on the demo page https://limonte.github.io/sweetalert2/

After opening an alert, exiting the alert by any means other than using the confirm button (such as clicking on the cancel button, pressing escape, or exiting the alert by clicking outside) will cause pressing the Enter key to reopen the alert.

**Comment by limonte** [comment]
When you click the button on the demo page that button gets a focus and click event. Click event cause modal opening. When you close the modal window focus will be returned to the button. And when you hit enter it cause click event on button by default.

So it's not a bug :)

**Comment by nickfederighi** [comment]
Unfortunately, I'm not sure that is problem. Maybe I'm wrong... In my implementation, I have textareas and other input fields in a form. If the user is focused on a textarea and presses the enter key to create a newline, the old alert will still pop up. The button that was clicked to create the alert is no longer in focus when this occurs.

**Comment by limonte** [comment]
reproduse that issue with https://jsfiddle.net/  so I can look into it, thanks

**Comment by nickfederighi** [comment]
Here's a link to the fiddle. 
https://jsfiddle.net/nickfederighi/t8w2eLma/11/
Let me know if you have any questions. Thanks for your help.

**Comment by limonte** [comment]
Thank you for the really great fiddle which is helped me to resolve this issue!

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/releases/tag/v0.2.8
