### ISSUE TITLE
Ability to enable document scroll when sweetalert is active

### ISSUE THREAD

**Issue by adarqui** [limonte/sweetalert2#400]
I see it was explicitly disabled in #277 . Is there any way I can somehow enable it (configurable)? I'd actually like the user to be able to document scroll while the modal is open.

Thanks!

**Comment by acupajoe** [comment]
It's just a css change, you can globally allow scroll by editing the `body.swal2-in` selector to be `overflow-y:auto` instead of hidden in your CSS file.

**Comment by adarqui** [comment]
Cool thanks alot! That worked.

**Comment by dr-andy** [comment]
Should be `body.swal2-shown{overflow-y:auto}`

**Comment by avimar** [comment]
For anyone else that ends up here wanting to scroll a wide table:

If you make a table wider than the screen size (pretty small on mobile), then you can't scroll it.

Simple solution: wrap the table in a `div`, like so: `<div style="overflow-x:auto;"><table...>`

(Thanks to https://www.w3schools.com/howto/howto_css_table_responsive.asp but I mistakenly thought I could apply that style to the `table` directly...)
