### ISSUE TITLE
+ character inside e-mail addresses

### ISSUE THREAD

**Issue by karl-ravn** [limonte/sweetalert2#404]
The e-mail standard is not really followed when using input:"email". I try to add a "+" character inside my address (standard google behavior to multiply your e-mail addresses under one account), but the regex is not supporting this. It should allow a + inside the username part.

**Comment by limonte** [comment]
Fixed in https://github.com/limonte/sweetalert2/pull/405

I'll make a patch release soon.

**Comment by limonte** [comment]
Done in [v6.3.1](https://github.com/limonte/sweetalert2/releases/tag/v6.3.1)
