### ISSUE TITLE
Cannot run another function (this.rundelete) on swal success

### ISSUE THREAD

**Issue by veerajongit** [limonte/sweetalert2#407]
Error: Uncaught (in promise): TypeError: Cannot read property 'rundelete' of null
TypeError: Cannot read property 'rundelete' of null

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
