### ISSUE TITLE
Date Input

### ISSUE THREAD

**Issue by IronCoderXYZ** [limonte/sweetalert2#408]
Hi,

I am really loving the Sweet Alert 2 project.

I have used the chaining modals option to collect user input, but I really need to collect a date as well. I cannot figure out how to do this, I can't embed any datepicker either.

Please advise!

Thank you

**Comment by acupajoe** [comment]
There's not currently a datepicker included for swal2, you can get this done using the `html` to create your html input and running your javascript datepicker binding within the `onOpen` option.

**Comment by toverux** [comment]
@acupajoe's solution is the way you want to go. We won't include a datepicker library to avoid bloating the library with tons of vendor javascript and css, that very few people will use. Moreover, it's not SweetAlert's responsibility to choose a date picker that integrates correclty in your application (in terms of design, date format, etc).

However, I think that we could support HTML5 date-related input types: `date`, `time` and `datetime`.
The support for those inputs are pretty bad atm on desktop, and `date` gives nothing but a text input on Chrome and maybe others. However, on mobile, the support seems to be much, much better, since the browser can use the widgets from the OSes. And, well, that's standard!

**Comment by IronCoderXYZ** [comment]
@acupajoe @toverux 
Thank you, I am absolutely fine with using my JQuery datepicker within sweetalert, but I could not find any examples on the internet on how to call my datepicker function, could someone clarify?

My datepicker code is as follows, and I am using the sweetalert chaining modals option.

```
$(function () {
    $('#datepicker').datepicker({

        onSelect: function () { // When cal is opened execute
            var currentDate = new Date($("#datepicker").datepicker("getDate"));
            var strDateTime = currentDate.getDate() + "/" + (currentDate.getMonth() + 1) + "/" + currentDate.getFullYear();
            startDatabaseQueries(strDateTime);
        }
    })
});
```

**Comment by toverux** [comment]
Here are two examples with jQuery UI's datepicker:

Select a date then confirm : https://jsfiddle.net/u3gjb11x/
Confirm-on-select : https://jsfiddle.net/r8fqcsor/

**Comment by IronCoderXYZ** [comment]
@toverux Thank you so much for providing an example!
I feel as though I am doing something wrong though, I tried implementing your code in my chaining modal but the datepicker is not showing: (I know I am missing the promis function but I am just trying to get the datepicker to show)

```
function bodyStatsEntry() {
    swal.setDefaults({
        input: 'text',
        width: 400,
        padding: 20,
        background: '#fff url(//pptback.com/uploads/blue-squares-backgrounds-powerpoint.jpg)',
        confirmButtonText: 'Next &rarr;',
        showCancelButton: true,
        animation: false,
        progressSteps: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']
    });

    var steps = [
        {
            html: '<div id="datepicker"></div>',
            onOpen: function() {$('#datepicker').datepicker();},
            title: '<span style="color:#98D4E4">Arm Size<span>'
            //text: 'Chaining swal2 modals is easy'
        },
        '<span style="color:#98D4E4">Body Fat Percentage<span>',
        '<span style="color:#98D4E4">Calf Size<span>',
        '<span style="color:#98D4E4">Chest Size<span>',
        '<span style="color:#98D4E4">Forearms Size<span>',
        '<span style="color:#98D4E4">Hips Size<span>',
        '<span style="color:#98D4E4">Neck Size<span>',
        '<span style="color:#98D4E4">Shoulder Size<span>',
        '<span style="color:#98D4E4">Thighs Size<span>',
        '<span style="color:#98D4E4">Waist Size<span>',
        '<span style="color:#98D4E4">Weight<span>'
    ];
    swal.queue(steps).then(function (result) {
        swal.resetDefaults()
        swal(
                'Body Stats Submitted',
                '',
                'success'
                ),
                arms = result[0];
        bodyfat = result[1];
        calves = result[2];
        chest = result[3];
        forearms = result[4];
        hips = result[5];
        neck = result[6];
        shoulders = result[7];
        thighs = result[8];
        waist = result[9];
        weight = result[10];
        console.log(arms, bodyfat, calves, chest, forearms, hips, neck, shoulders, thighs, waist, weight);
        writeNewPost();
    }, function () {
        swal.resetDefaults();
    });
}
```

**Comment by IronCoderXYZ** [comment]
Edit, not sure why the dev would downvote someone trying to use his project; I am trying to learn here.

**Comment by toverux** [comment]
@IronCoderXYZ Don't be angry, it's simply not the right place to ask for help. Your suggestion (adding support for dates) was ok, but now the discussion is leaving the scope of the library, and we're definitely not here to teach JavaScript.
So, try to debug this yourself, and if you're really lost, post a question on StackOverflow, with a link to a jsfiddle to reproduce. Tenths of developers on StackOverflow are there to help, and could answer your question. That may even be me!

**Comment by IronCoderXYZ** [comment]
@toverux Thank you for taking the high road, I understand.
