### ISSUE TITLE
Adding option contentStyling?

### ISSUE THREAD

**Issue by rorc** [limonte/sweetalert2#409]
Same as buttonsStyling? 😄 
Its convenient when i dont want apply swal2 styles like `line-height`, `font-size` etc.
Now, swal2 class `.swal2-content` breaks my original styles.

**Comment by limonte** [comment]
Overhead, what you want could be easily performed with `onOpen()` handler and `getContent()`: https://jsfiddle.net/ad3quksn/70/

**Comment by rorc** [comment]
Its inconvenient, because i have to **overwrite** all styles, when i could just write my own styles.
Its clean and good 😃

**Comment by limonte** [comment]
I should agree with you here, see my suggestion in the related issue: https://github.com/limonte/sweetalert2/issues/410#issuecomment-277520432

**Comment by rorc** [comment]
@limonte Yea, thanks 👍
