### ISSUE TITLE
Can i back to previous swal?

### ISSUE THREAD

**Issue by rorc** [limonte/sweetalert2#411]
I have opened swal, and onCancel i again show another swal with question "Are u shure to close swal?", and after dismiss i want to return first swal 😄
This is possible?

**Comment by toverux** [comment]
Basically, no.
`swal()` does not creates, for example, reusable "SwalModal" objects that you can show or dismiss. Each call to swal is purely procedural, and patches the DOM to show a modal.

What you're asking, however, is partially implementable with some dirty spaghetti code (multiple calls to swal, reusing arguments declared before in the scope).

**Comment by rorc** [comment]
@toverux Maybe this can do with queue? How i can roam by steps in queues?

**Comment by limonte** [comment]
Going back and forth is possible now with async/await: https://jsfiddle.net/ad3quksn/252/
