### ISSUE TITLE
How i can get access to swal2 modal content?

### ISSUE THREAD

**Issue by rorc** [limonte/sweetalert2#412]
Inside callbacks, without direct `$('.swal2-content')`? 😄

**Comment by toverux** [comment]
Hm, maybe you can use the first parameter of the onClose callback.
See https://github.com/limonte/sweetalert2/blob/master/sweetalert2.d.ts#L457

It's a raw HTMLElement however, not a jQuery wrapper, since SweetAlert is not a jQuery plugin and does not depends on jQuery. But `onClose: function(modalElement) { $(modalElement); }` is still better than a selector for sure.

We can't modify the Promise signature returned by `swal()` without causing a breaking change.

**Comment by rorc** [comment]
@toverux Sigh. I have form in swal content. And i want to get access to this form for some operation and submit on swal accept, not onClose 😃

**Comment by toverux** [comment]
Oh, then you may want to do that : https://jsfiddle.net/c63u5o85/3/
So your modal resolves directly with the data. Still uses a selector, that said. But a little better.

**Comment by rorc** [comment]
@toverux Oh dude, thanks for idea of using preConfirm 😃

**Comment by limonte** [comment]
Done in [v6.3.2](https://github.com/limonte/sweetalert2/releases/tag/v6.3.2)

```js
swal.getContent()
```

@rorc Thanks for the nice request!

**Comment by rorc** [comment]
@limonte Hmm, maybe will be better, if `swal.getContent() ` will return fresh content without wrapper `.swal2-content`? 😄

**Comment by limonte** [comment]
Your request was `$('.swal2-content')`, it's exactly how `swal.getContent()` works and that's the right way.

**Comment by rorc** [comment]
@limonte Yea, but i need content without uneccesary wrapper only.
I written `$('.swal2-content')` only for find for inside swal.
My final code was `$('.swal2-content form')` =)

**Comment by limonte** [comment]
http://www.w3schools.com/jsref/prop_element_children.asp

**Comment by rorc** [comment]
@limonte Dude, i meant `swal.getContent()` for getting **clean user content** without excess wrappers...

**Comment by limonte** [comment]
What should `swal.getContent()` return in your opinion for those cases: 

1. `swal({text: 'simle text'})`
2. `swal({html: '<p>paragraph 1</p><p>paragraph 2</p>'})`

**Comment by rorc** [comment]
".swal2-content".innerHTML

**Comment by limonte** [comment]
> ".swal2-content".innerHTML

How string with HTML of the `swal2-content` could be useful?

**Comment by rorc** [comment]
Here my case:
```
$.get(e.target, function(response) {
                    swal({
                        html: response,
                        /* some params */
                    }).then(() => {
                        let form = $(swal.getContent().children);

                        $.post(form[0].action, form.serialize());
                    });
                });
```
