### ISSUE TITLE
Checking SweetAlert Support

### ISSUE THREAD

**Issue by AVONnadozie** [limonte/sweetalert2#417]
I noticed SweetAlert does not work on some mobile devices. How do i check if SweetAlert is supported for the current browser?

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2#browser-compatibility

**Comment by RandonJordan** [comment]
I don't know if this is the support page and can help me but I have been having an issue with sweetalert. Just started using it this morning and all day I have been trying to figure this out. My issue is that my alerts always come with a input box and the default error message on top of my custom error message. All i want is my custom error message with no input box or default writing.
