### ISSUE TITLE
how to add sound notification ?

### ISSUE THREAD

**Issue by Nemra1** [limonte/sweetalert2#418]
how ican add some media file ext like .ogg or .wav to playing in popup box  when order !

**Comment by limonte** [comment]
https://jsfiddle.net/ad3quksn/69/

**Comment by xalexbo** [comment]
Hi limonte, it runs on FF for Windows.
I wasn't able to make it work on iPad: both on FF and Safari it doesn't work - no sound was played, is this due to some iOS limit?
Thanks

**Comment by limonte** [comment]
@xalexbo yes, for iOS tap is required to produce some sound. Here you go with the example which works in iOS: https://jsfiddle.net/ad3quksn/126/

**Comment by xalexbo** [comment]
in my case swal is fired by body onload so the question is: to make play a sound on iPad when swal is shown is it required a button click?
I mean more generally that also a page which loads on browser cannot play any sound without user interaction?
Thanks

**Comment by patrickhlauke** [comment]
@xalexbo yes, that's an iOS limitation aimed at not having sites annoy users with unwanted/autoplaying sounds
