### ISSUE TITLE
Firefox won't work

### ISSUE THREAD

**Issue by charleslcso** [limonte/sweetalert2#419]
I'm migrating from an older version of swal2 to swal2 6.3.2. But I'm having difficulties.

I'm testing a very basic block of code:

```
<script type="text/javascript">
swal({
  title: 'Auto close alert!',
  text: 'I will close in 2 seconds.',
  showLoaderOnConfirm: true,
  preConfirm: function() {
    return new Promise(function(resolve) {
      setTimeout(function() {
        resolve();
      }, 0);
    });
  }
}).then( 

	function () {
	}, 
	function (dismiss) {
    	$.get('index.php?route=module/alert/clearAlert'),
    	console.log('I was closed by the timer')
	}

).catch(swal.noop)
</script>
```

It works on Chrome 54, Safari 10, but not Firefox 51.

Please ignore the $.get() for the moment.

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by charleslcso** [comment]
Got it

**Comment by limonte** [comment]
Can't reproduce. Reopen with jsfiddle if needed.
