### ISSUE TITLE
Image upload feature?

### ISSUE THREAD

**Issue by yigitozkavci** [limonte/sweetalert2#42]
I know that this meant to be an alert plugin, but it also has a "input field" feature that I often use. 
I needed an image upload in my project and doing it with sweetalert would be nice since it is being used all over my project. If that would be accepted, I am ready to work on it and send a pull request.

**Comment by limonte** [comment]
Thanks for using swal2, but image uploading functionality is pretty project-specific. I'd like to keep swal2 simple and easy to use.
