### ISSUE TITLE
How to call ajax with swal2 6.3.2?

### ISSUE THREAD

**Issue by charleslcso** [limonte/sweetalert2#420]
In the earlier version swal2 2.x.x, I can call ajax after clicking on Cancel or Confirm button by doing this:

```
swal({
...
}).then(function(isConfirm) {
     $.ajax({
           url: '<external url>',
           method: 'get',
           async: false,
           success: function() {},
           error: function() {}
     });
})
```

This method to call ajax no longer works... and there is no mention of this in the migration doc.

Please help!

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
