### ISSUE TITLE
Hitting enter key (return) twice in a row really fast calls confirm event handler twice

### ISSUE THREAD

**Issue by akonyer** [limonte/sweetalert2#421]
As the title says, if you hit the enter key two times in a row really quickly, the confirmation event handler is called twice. I think the buttons need to be debounced or deactivated after the first click.

**Comment by birjolaxew** [comment]
Cannot reproduce on [this JSFiddle](https://jsfiddle.net/0jmuv529/). In fact, hitting enter twice now throws an error after #414 - could you please verify that this still happens on the newest version?

Leaving the issue open as we should still disable the buttons once they're clicked once.

**Comment by akonyer** [comment]
This does not seem to be happening after updating, you are correct.

Thank you. I was using an older version when I was getting this issue before.

**Comment by limonte** [comment]
Fixed in [v6.4.1](https://github.com/limonte/sweetalert2/releases/tag/v6.4.1) :tada:
