### ISSUE TITLE
does sweetalert have notification like toastr notification 

### ISSUE THREAD

**Issue by azarzaza** [limonte/sweetalert2#424]
does sweet alert have a notification like a toaster notification 
and have a sound notification

**Comment by limonte** [comment]
> does sweet alert have a notification like a toaster notification

Nope.

> and have a sound notification

https://jsfiddle.net/ad3quksn/69/

**Comment by Jackson45252** [comment]
Now you have it!!
`swal.mixin()`

**Comment by johnthagen** [comment]
For the current version of `sweetalert2` I had to modify the code slightly:

```ts
import Swal from "sweetalert2";

const toast = Swal.mixin({
  toast: true,
  position: 'top-end',
  showConfirmButton: false,
  timer: 3000
});

toast.fire({
  icon: "success",
  title: "Signed in successfully",
});
```

**Comment by bbehera277** [comment]
Can someone please help me with below concerns :
1. How to close the toast of sweetalert 2 by clicking outside ?
2. Also how to customize the size of the alert popups & toast popups(As the size is too big and doesn't look good for all screen sizes) ? 
@sweetalert2, please help.
