### ISSUE TITLE
showValidationError() without inputs produces TypeError

### ISSUE THREAD

**Issue by jdussouillez** [limonte/sweetalert2#425]
I am using the release 6.3.2 and I get a TypeError when I use "showValidationError" without inputs.
The validation error message is displayed but then I get :

```
Uncaught TypeError: Cannot read property 'focus' of null
    at focusInput (sweetalert2.js:249)
    at Function.sweetAlert.showValidationError (sweetalert2.js:1168)
    at ...
```

The input is null so the line https://github.com/limonte/sweetalert2/blob/master/dist/sweetalert2.js#L249 throws an error (called by https://github.com/limonte/sweetalert2/blob/master/dist/sweetalert2.js#L1168).

JSFiddle : https://jsfiddle.net/wx3L3vmj/

**Comment by limonte** [comment]
Thanks a lot for such a nicely detailed bug-report @jdussouillez, done in [v6.3.3](https://github.com/limonte/sweetalert2/releases/tag/v6.3.3)

**Comment by jdussouillez** [comment]
Wow, that was fast ! Thanks!
