### ISSUE TITLE
typescript error when using preConfirm() with input parameter

### ISSUE THREAD

**Issue by giwiro** [limonte/sweetalert2#426]
When i use the preConfirm with the input tag like this:

![screen shot 2017-01-30 at 7 18 49 pm](https://cloud.githubusercontent.com/assets/5349520/22447525/f91731f0-e720-11e6-8273-72ebf1c083ed.png)

It shows an error. I tried to change the ts file to this:
```javascript
preConfirm?: (flag:any) => Promise<any>;
```
And it works, would it be the right solution ??

**Comment by giwiro** [comment]
Thanks :D

**Comment by limonte** [comment]
Thanks for reporting @giwiro, done in [v6.3.3](https://github.com/limonte/sweetalert2/releases/tag/v6.3.3)
