### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by diondkb** [limonte/sweetalert2#429]
Hi,

Setting imageWidth and height dont seem to have an effect on the result? 

Regards,
Dion

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by limonte** [comment]
Can't reproduce, reopen with jsfiddle if needed.
