### ISSUE TITLE
Deal with dismiss for each step

### ISSUE THREAD

**Issue by flavienaudin** [limonte/sweetalert2#430]
Hi,
I'm using chained modals and I wonder if it is possible to execute certain code according to the step where the user dismissed ?
Actually, if I call swall.getQueueStep() in the second function which handling the dismiss in then(), the return is "null"
Here my code : 
`wal.queue(steps).then(function (result) {`
     ` // here I treat "confirm"`
`}, function (dismiss) {`
     `var swalCuurrentStep = swal.getQueueStep();`
     `console.log("swalCuurrentStep  : " + swalCuurrentStep);`
`});`

Thank for the help.

**Comment by limonte** [comment]
Please include a [jsfiddle](https://jsfiddle.net/)

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

**Comment by flavienaudin** [comment]
Here the jsFindle : https://jsfiddle.net/limon/ad3quksn/ (I used your template)

**Comment by flavienaudin** [comment]
I would like to precise why I need to know the current step, maybe I misused SweetAlert :
I use the cancelButton as a confirmButton, but without input validation (here the email), to let the choice to the user to fill or no the email and continue. 
So, If the dismiss == cancel, so I call the business function, as I do when the user fills the input and clicks on the confirmButton.

If there is a better way to do, I would be glade to know it.

Thx again

**Comment by limonte** [comment]
https://jsfiddle.net/89Lkw8g5/7/

**Comment by flavienaudin** [comment]
I would like to keep two buttons "Later" / "Send me the email" so that I'm sure the user is conscious of its action : I give important information inside the second modal. But as I have two solutions (yours and mine using external variables). it's ok for me.

Maybe if there is other demands like mine later, perhaps it could be an interesting feature to have the possibility to set multiple confirmButton, like "Yes No Cancel" alert windows. Or just a "Yes/No" that both are confirm action.

Thank a lot for your answer and reactivity.
