### ISSUE TITLE
pass argument in resolve

### ISSUE THREAD

**Issue by ChazyTheBest** [limonte/sweetalert2#431]
I need to pass a boolean to `then(function)` so in case there's a server error I can use `type: 'error'`. Is there any way to do it?

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by ChazyTheBest** [comment]
Sorry.

I've opened a question in SO: http://stackoverflow.com/q/42024794/4067132
