### ISSUE TITLE
Broken css since v6.3.4

### ISSUE THREAD

**Issue by MannikJ** [limonte/sweetalert2#434]
Since v6.3.4 the layout is broken when the alert is opened. I found out that the class `swal2-in` and  `style="padding-right: 19px"` on the body element are responsible for this problem. 
My app makes heavy use of flex containers. 
**When swal is open, the body grows infinitely in height and a scroll bar appears.**
When I remove swal2-in and the padding, everything is centered fine and the background looks like supposed to. In v6.3.3 everything is working properly out of the box.
At the moment I have no time to find out what exactly you have to do to recreate the issue.

**Comment by limonte** [comment]
Oops, sorry for this issue. It seems I was out of my mind yesterday :)

Should be fixed in [v6.3.7](https://github.com/limonte/sweetalert2/releases/tag/v6.3.7)

Thanks for reporting! :beers:

**Comment by MannikJ** [comment]
Perfect! Thank you!

**Comment by limonte** [comment]
Thanks for using swal2!
