### ISSUE TITLE
Add visual regression tests

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#435]
The visual appearance should be added in order to keep the high level of plugin quality, [gemini](https://github.com/gemini-testing/gemini) + [SauceLabs](https://saucelabs.com/) seems to be the right tooling for it.

**Comment by elnegrito007** [comment]
existe un error al tener dos swal de tipo password, en el limite máximo de caracteres porque toma el anterior

**Comment by toverux** [comment]
@elnegrito007 Ce n'est pas le bon endroit pour poster une demande d'aide (=> StackOverflow), et merci d'écrire en anglais, sinon moi j'écris en français :)

**Comment by limonte** [comment]
Can't make it work with gemini. Anybody have any suggestion for visual regression testing?

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2-visual-tests
