### ISSUE TITLE
Multiple instances break subsequent sweetalerts

### ISSUE THREAD

**Issue by caseyWebb** [limonte/sweetalert2#438]
In our app, we have a commons bundle as well as an app bundle, either of which can call sweetalert. Although there is only one copy of sweetalert, it creates multiple instances for some reason I haven't yet been able to track down. This causes all sorts of issues b/c the `sweetContainer` is not the correct reference half the time.

**Comment by limonte** [comment]
I just bumped the swal2 version to [v6.4.0](https://github.com/limonte/sweetalert2/releases/tag/v6.4.0)

Thanks for your contributions @caseyWebb!
