### ISSUE TITLE
Inconsistent Behavior Across platform

### ISSUE THREAD

**Issue by joshberg** [limonte/sweetalert2#441]
EDIT:
There seems to have been an issue with how I implemented the API. It is functioning perfectly now on both Android and PC. You may close this issue. Thank you!

Original:
I am developing an application that is for multi-platform. I am chaining these modal dialogues as a way to log into the application; however, I am getting some strange behavior. My current design looks something like this:

```javascript
swal({optionsForEmpLogin})
   .then(function(empNo){
      swal({optionsForEmpSuccess})
         .then(function(userClosed){
               ShowNextSWAL()
            },function(timerClosed){
               ShowNextSWAL()
            });
      }, function(){swal(error)});
```

This works perfectly on desktop, but on tablet it does not. Desktop is using chrome browser as is the android device. Now something strange, if I do this:

```javascript
swal({optionsForEmpLogin})
   .then(function(empNo){
      swal({optionsForEmpSuccess})
         .then(function(userClosed){
            },function(timerClosed){
            });
      ShowNextSWAL()
      }, function(){swal(error)}
```

That shows the next swal() on both pc and tablet; however, the success dialogues do not display. I'm guessing I am probably implementing this wrong. Let me know if my assumption is correct or if there is something else I'm missing. The ShowNextSWAL() is a function that just contains a 
```javascript
swal({options}).then(function(){swal(success)})
```

Fiddle: https://jsfiddle.net/hk38dbhh/

**Comment by limonte** [comment]
For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

**Comment by joshberg** [comment]
Sorry about that. First time using jsfiddle. I've updated my report.

**Comment by birjolaxew** [comment]
Closing based on

> EDIT:
There seems to have been an issue with how I implemented the API. It is functioning perfectly now on both Android and PC. You may close this issue. Thank you!

If you feel like sharing what you did wrong, it might help other people who stumble upon the issue later :smile:

**Comment by joshberg** [comment]
I did change how I was dealing with the catch. Instead of doing the Promise().then().catch() design I instead opted for the Promise().then(function(resolve){},function(reject){}) way of doing things. I think there were some other Javascript errors in the called functions that were actually causing the problems.
