### ISSUE TITLE
Promise without any required validation

### ISSUE THREAD

**Issue by aloysius-tim** [limonte/sweetalert2#444]
Hey !

I would like to use sweetAlert2 only to chain a loading modal type then a success or error modal.

Click on a button would directly shows SweetAlert2 loading modal then when promise resolved show the success/error modal.

Is that something currently possible ? Display the loading modal without using any previous modal with input fields etc ...

Thanks for your time,
Tim

**Comment by birjolaxew** [comment]
It is possible in the sense that you can use `swal.showLoading()` and `swal.hideLoading()` to toggle the loading states. See [this JSFiddle](https://jsfiddle.net/tmbhxw2a/).

**Comment by aloysius-tim** [comment]
Thanks a lot ;)
