### ISSUE TITLE
Alert jumps to top of page (Chrome)

### ISSUE THREAD

**Issue by ivanvermeyen** [limonte/sweetalert2#448]
Hey, 

When an alert pops up, the page jumps to the top.
I'm using Chrome 56.0.2924.87 (64-bit) and I'm using ES6.
Firefox and Safari have the same behavior.

**Comment by ivanvermeyen** [comment]
Sorry, here is the fiddle:
https://jsfiddle.net/gtgLgrhe/1/

When I remove the `html, body` height and use a `.box` height of `100vh` instead of `100%`, then it doesn't jump up: https://jsfiddle.net/gtgLgrhe/2/

**Comment by limonte** [comment]
Thanks for reporting @ivanvermeyen! Fixed in [v6.4.2](https://github.com/limonte/sweetalert2/releases/tag/v6.4.2)

**Comment by limonte** [comment]
https://jsfiddle.net/gtgLgrhe/3/
