### ISSUE TITLE
404 error while importing the sweetalert2 module in angular2

### ISSUE THREAD

**Issue by daybaryour** [limonte/sweetalert2#449]
hello, thank you for a fantastic plugin and continued support

i'm trying to use sweetalert for my angular2 applicaiton and after installing with npm and including in my application with 

import {default as swal} from 'sweetalert2';

I get a 404 error 

![image](https://cloud.githubusercontent.com/assets/5998280/22975651/c702fd5c-f387-11e6-87cb-f5ac239a4c81.png)

**Comment by limonte** [comment]
StackOverflow is the right place for questions like this. As I can see you already asked there: http://stackoverflow.com/q/42250180/1331425 so I'm closing this issue in favor of StackOverflow.
