### ISSUE TITLE
Sweet alert & bootstrap modal togheter

### ISSUE THREAD

**Issue by andreiculda** [limonte/sweetalert2#45]
Hi,

I have a bootstrap modal with lots of inputs in a form. Tabbing through inputs works OK. I have another button on the same page that opens a sweet alert for a confirmation of a delete operation from a table.
Once I open a swal, close it and open again the bootstrap modal tabbing is not working anymore inside the modal. On page refresh i am able again to tab through the modal inputs. I think it has something to do with both sweet alert and bootstrap modal having the same tabindex -1. Using javascript alert confirm for the deletion operation does not interfere with the modal also.

Do any of you have the same issue?

**Comment by limonte** [comment]
reproduce the issue with https://jsfiddle.net/ so I can look into it, thanks

**Comment by andreiculda** [comment]
yeah ... was going to do that. On it right now.

**Comment by limonte** [comment]
thank you in advance @andreiculda for your efforts

**Comment by andreiculda** [comment]
Here you go: https://jsfiddle.net/0j7drxtd/19/. The process:
1. click add new user
2. tab through modal inputs. Works OK.
3. Close modal and click open Swal.
3. Click Ok or Cancel no matter.
4. Open again the modal and tab through inputs. Does not work anymore.

Note: I did not find a CDN for sweetalert2 so i just pasted the js and css in the fiddle.

**Comment by andreiculda** [comment]
Not sure if really tab index issue so I changed the issue title. If you could fix it soon you'll be the real MVP :).

**Comment by limonte** [comment]
That bug was fixed here: https://github.com/limonte/sweetalert2/issues/40

You need to update swal2 to latest.

I updated your example, you can see it working now: https://jsfiddle.net/0j7drxtd/20/

**Comment by andreiculda** [comment]
This is perfect. Thank you very much.
