### ISSUE TITLE
inline body didn't remove in delete alert when i remove success alert after deleted.

### ISSUE THREAD

**Issue by pixieaka** [limonte/sweetalert2#450]
inline body "style="padding-right: 17px;" didn't remove in delete alert when i remove success alert after deleted. 

swal({
                    title: 'Delete Confirmation ?',
                    text: 'Are you sure ?',
                    confirmButtonText: 'Confirm',
                    cancelButtonText: 'Cancel',
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33'
                }).then(function () {
                    ==/// if i add here swal('success !', '', 'success'); it remove padding. ///==
                }, error => {
                    swal('error', 'error', 'error');
                }).catch(swal.noop)

![a1](https://cloud.githubusercontent.com/assets/17777237/23007351/dae927a4-f410-11e6-8002-eedbb87f60b6.JPG)

**Comment by limonte** [comment]
Use `swal.close()` instead of manual removing the modal.

**Comment by pixieaka** [comment]
it not working the padding still

**Comment by limonte** [comment]
For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
