### ISSUE TITLE
Question: Is there support for multiple input fields?

### ISSUE THREAD

**Issue by S-Hodgson-MMOARgames** [limonte/sweetalert2#451]
I was just curious if sweet alert 2 supported multiple input fields, or do I need to queue up a bunch of alerts to handle each one by one?

**Comment by toverux** [comment]
That's not directly supported by SweetAlert (because we keep things simple), but you can do it by writing the HTML yourself.

From the [documentation](https://limonte.github.io/sweetalert2/):

> Multiple inputs aren't supported, you can achieve them by using html and preConfirm parameters.
> Inside the preConfirm() function you can pass the custom result to the resolve() function as a parameter:
> 
> ```
> swal({
>   title: 'Multiple inputs',
>   html:
>     '<input id="swal-input1" class="swal2-input">' +
>     '<input id="swal-input2" class="swal2-input">',
>   preConfirm: function () {
>     return new Promise(function (resolve) {
>       resolve([
>         $('#swal-input1').val(),
>         $('#swal-input2').val()
>       ])
>     })
>   },
>   onOpen: function () {
>     $('#swal-input1').focus()
>   }
> }).then(function (result) {
>   swal(JSON.stringify(result))
> }).catch(swal.noop)
> ```
>

**Comment by S-Hodgson-MMOARgames** [comment]
Thanks for the quick reply.

**Comment by typicalcoda** [comment]
Thanks for this.

**Comment by MoussaOudihat** [comment]
How can i set the html input required in sweetalert2

**Comment by gverni** [comment]
@MoussaOudihat have a look to [this](https://stackoverflow.com/questions/54577739/sweetalert2-validation-required-for-one-of-the-fields/54582551#54582551). If it doesn't answer your question, please raise a new question on stackoverflow.

**Comment by rosaiph** [comment]
olá

**Comment by rosaiph** [comment]
> Isso não é diretamente suportado pelo SweetAlert (porque mantemos as coisas simples), mas você pode fazê-lo escrevendo o HTML sozinho.
> 
> Da [documentação](https://sweetalert2.github.io/) :
> 
> > Múltiplas entradas não são suportadas, você pode alcançá-las usando `html`e `preConfirm`parâmetros. 
> > Dentro da função preConfirm () você pode passar o resultado personalizado para ser retornado
> 
> ```js
> const {valor :  formValues } =  espera  swal ({
>   título :  ' Múltiplos insumos ' ,
>   html : 
>     ' <input id = "entrada-swal1" classe = "entrada-swal2"> '  + 
>     ' <entrada id = "entrada-swal2" classe = "entrada-swal2"> ' ,
>   focusConfirm :  false ,
>    preConfirm : () => {
>      return [
>        documento . getElementById ( ' swal-input1 ' ). valor ,
>        documento . getElementById ( ' swal-input2 ' ). valor
>     ]
>   }
> })
> ```

usei desta forma mas os meus inputs não aparecem, pode me ajudar ?

**Comment by gverni** [comment]
Hi @rosaiph, can you translate your comment in english please?

**Comment by taxpayer** [comment]
@rosaiph O idioma padrão para dúvidas e outras perguntas neste repositório é o inglês. Mande suas dúvidas em inglês ou então procure ajuda no Stackoverflow em português por tag: https://pt.stackoverflow.com/questions/tagged/sweetalert

@gverni "The standard language for doubts and other questions in the repo is English. Send your doubts in English ou look for help in Stackoverflow in Portuguese using a tag: https://pt.stackoverflow.com/questions/tagged/sweetalert" ;-)

**Comment by rosaiph** [comment]
good afternoon,

I have this sweetalert and I need to apply a validation to not let pass my inputs empty, but I do not know but what to do already tried jquery validate everything but it does not work can help me follow my Swal

 swal.fire (
                {title: "End Event!",
                animation: true,
                customClass: 'bounceInDown',
                showCancelButton: true,
                confirmButtonText: "Confirm",
                html: "<form id = 'formValidate' class = 'formValidate'> Write a resolution to end Event" +
                        "<input id = 'resolution' name = 'resolution' type = 'text' class = 'form_input' required minlenght = '2' placeholder = 'Describe why you are finalizing this event' required style = 'width: 80%; padding: 12px 20px; margin: 8px 0; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; '/> "+" </ br> "+
                        "<input id = 'date' name = 'date' type = 'text' class = 'form_input' required placeholder = 'Data' required style = 'width: 38%; height = 40%; padding: 12px 20px; margin: 8px 0; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; '/> "+" & nbsp & nbsp & nbsp & nbsp & nbsp "
                        "<input id = 'end_time' name = 'end_time' type = 'text' class = 'form_input' required placeholder = 'Time' required style = 'width: 38%; height = 40%; padding: 12px 20px; margin: 8px 0; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; '/> "+
                        "</ form>",
                    
 
                    preconfirm: () => {
                         
                      resolution = document.getElementById ('resolution'). value;
                      date = document.getElementById ('date'). value;
                      end_time = document.getElementById ('end_time'). value;
                        
                        return [resolution, date, end_time]
                           
                    }

                })

**Comment by rosaiph** [comment]
I have a simulator. https://codepen.io/anon/pen/OqVqaN

**Comment by gverni** [comment]
Hi @rosaiph colu you raise you question as an issue on https://github.com/sweetalert2/sweetalert2-examples? I'm going to help you there

**Comment by gverni** [comment]
@rosaiph I created an example of custom form validation [here](https://github.com/sweetalert2/sweetalert2-examples/tree/master/forms/login)

**Comment by rosaiph** [comment]
> Oi @rosaiph você poderia levantar sua questão como um problema em https://github.com/sweetalert2/sweetalert2-examples ? Eu vou te ajudar lá


Hello,

How do I use this to ask for help in this tool that you told me?

**Comment by rosaiph** [comment]
> @rosaiph Eu criei um exemplo de validação de formulário personalizado [aqui](https://github.com/sweetalert2/sweetalert2-examples/tree/master/forms/login)

Hello,

Thank you, I'll see your example!

**Comment by gverni** [comment]
Thanks @rosaiph. If you have any doubts with the example, then please just raise an issue on [that repository](https://github.com/sweetalert2/sweetalert2-examples) (not this one)

**Comment by rosaiph** [comment]
Thank you so much, it saved my day.

**Comment by edsonlima2506** [comment]
I'm using "content" instead "html", because when I use "html:" it doesn't works, anyone have one solution to use "content" with two inputs?
