### ISSUE TITLE
Background disappears Ipad

### ISSUE THREAD

**Issue by LoneyGG** [limonte/sweetalert2#452]
If I run a swal in chrome full screen it works prefectly fine, but if I test it in an ipad or in the chrome with device ipad selected (1024x768) it makes the background disappear.

Pictures:
- Full screen (working fine): https://gyazo.com/1cb471fb152eca38f7b6ef3bb39df441
- Ipad resolution (background disappears): https://gyazo.com/1ac5770723f5aa4c04a490d3883abfc4

The blue background just disappears when the alert pop up and when I close the alert it shows up again.
¿Any fix for this?

EDIT: jsfiddle:
https://jsfiddle.net/ad3quksn/75/

This is the background used btw:

    background: rgb(0, 187, 255);
    background: -moz-linear-gradient(left, rgba(0, 187, 255, 1) 45%, rgba(43, 0, 255, 1) 100%);
    background: -webkit-linear-gradient(left, rgba(0, 187, 255, 1) 45%, rgba(43, 0, 255, 1) 100%);
    background: linear-gradient(to right, rgba(0, 187, 255, 1) 45%, rgba(43, 0, 255, 1) 100%);
    filter: progid: DXImageTransform.Microsoft.gradient( startColorstr='#00bbff', endColorstr='#2b00ff', GradientType=1);
    overflow: hidden;

I would appreciate any type of help.
Regards

**Comment by limonte** [comment]
For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by LoneyGG** [comment]
Here is the fiddle:
https://jsfiddle.net/ad3quksn/75/

See that it works fine full screen, but if u press f12 (In chrome nad select devices ipad 1024x768) the background disappears.

**Comment by limonte** [comment]
> ¿Maybe a position:fixed issue?

Exactly. You need to add `background-attachment: fixed;` to `body`: https://jsfiddle.net/ad3quksn/76/

**Comment by LoneyGG** [comment]
Oh man, ty very much!! Pro programmer ;)
