### ISSUE TITLE
Loading animation at wrong position

### ISSUE THREAD

**Issue by Vuurvlieg** [limonte/sweetalert2#453]
When using the confirm button the loading-animation is not at the same position of the cancel button. 
See http://i.imgur.com/UNGHHFQ.png

Before https://github.com/limonte/sweetalert2/commit/b47916754f6a111c0e8df1b854f883ea10a4e58f it was good.

**Comment by limonte** [comment]
Dear everyone! I'm on my vacation 10 days from now, won't be able to code anything. But still I could merge stuff and bump patch release :) If anyone could fix this issue, please go ahead :rocket:
