### ISSUE TITLE
swal.queue return to first step & go to another step

### ISSUE THREAD

**Issue by mfd** [limonte/sweetalert2#457]
1) how to get back to the previous step?
2) if I check input value ->  go to another step?

**Comment by limonte** [comment]
> how to get back to the previous step?

Currently this is not supported.

> if I check input value -> go to another step?

https://limonte.github.io/sweetalert2/#dynamic-queue

**Comment by NinoZX** [comment]
Hi guys!

Any news maybe on going back to previous step?
If no news, do you maybe have some suggestions about how to implement something similar?

Thank you very much for your great work!

**Comment by limonte** [comment]
Thanks for the question @NinoZX!

Now going back and forth is possible with async/await: https://jsfiddle.net/ad3quksn/251/

**Comment by NinoZX** [comment]
Thank you very much @limonte !

This is great help, you are really awesome... keep up the good work.
Best regards!

**Comment by fas3r** [comment]
Hello @limonte ,

Do the method still apply or there is a new way to do since 2017 :) ?

Thanks

**Comment by gverni** [comment]
@fas3r `await`/`async` is still the default method for that. You can see an example / reference [here](https://sweetalert2.github.io/sweetalert2-examples/queue/back-button/) (source code for the example [here](https://github.com/sweetalert2/sweetalert2-examples/tree/master/src/queue/back-button))

**Comment by fas3r** [comment]
Hello @gverni ,

Ok, sorry I did not check the queue folder. 

Thanks again.
