### ISSUE TITLE
SweetAlert Steps, is posible to get a value from the previous step?

### ISSUE THREAD

**Issue by ArthurReinhart** [limonte/sweetalert2#459]
Hi, thanks for mantaining this awesome project, i have an issue trying to hadle a steps queue, i have a select on my first modal step, then in the second modal y want a form with options, but depending on the value of select value of the first step (modal), i want to show a form between 3 different forms i have.

What i want to do is:
1st step modal --> selection field (3 options)
2nd step modal --> 3 different forms( or 1 with various fields which i want to show/hide depending on step1 value)

**Comment by limonte** [comment]
Hi @ArthurReinhart 

Here's the simple example of functionality you're looking for: https://jsfiddle.net/ad3quksn/79/

More details you can find at the documentation page: https://limonte.github.io/sweetalert2/#dynamic-queue
