### ISSUE TITLE
is there a possibility to show buttons after a reject ?

### ISSUE THREAD

**Issue by cromartie1984** [limonte/sweetalert2#461]
Is there a possibility to show buttons after a reject ?

Can't find any methods to do that.

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
