### ISSUE TITLE
Bug:Permanent 'display:none' on hr ( $btnSpacer)

### ISSUE THREAD

**Issue by Rogacz667** [limonte/sweetalert2#47]
Hi!
If we hide all buttons, we hide the 'hr' markup. After this every alert doesn't have any space between buttons and message. Reason of this is missing 'else' at line 654 : ' if (!params.showConfirmButton && !params.showCancelButton) {
      hide($btnSpacer);
    }'

Code to test:
sweetAlert({
                title: '1',
                text: 'Are you sure you want to test?',                
                closeOnConfirm: false,
                animation: "slide-from-top",
            },
            function (inputValue) {
                if (inputValue) {
                    swal({
                        title: '2.Processing...',
                        showConfirmButton: false,
                        allowOutsideClick: false,
                        allowEscapeKey: false,
                        timer:1000
                    },function(){
                        setTimeout(function() {
                            swal('3', 'error', 'error');
                        }, 1000);
                        
                    });
                }});
The second alert hide 'hr'.
The third does't have hr too, but it is necessary.

If we add 'else show($btnSpacer);' the bug is fixed

**Comment by limonte** [comment]
Thank you @Rogacz667! this bug is fixed now (https://github.com/limonte/sweetalert2/commit/4142e803ab50e69e449962001baa787ffae2686c)

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/releases/tag/v0.2.10
