### ISSUE TITLE
自动关闭时回调有问题

### ISSUE THREAD

**Issue by LoveHikari** [limonte/sweetalert2#471]
浏览器报“Uncaught (in promise) timer”
原因是第812行代码有问题，应该改为
return new Promise(function (resolve, reject) {
    // Close on timer
    if (params.timer) {
      modal.timeout = setTimeout(function () {
        sweetAlert.closeModal(params.onClose);
        resolve();
      }, params.timer);
    } else {
        reject('timer');
    }

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/issues/221
