### ISSUE TITLE
Select field and custom input display only the input value as result

### ISSUE THREAD

**Issue by dukenst2006** [limonte/sweetalert2#475]
I have this:

```js
swal({
    title: 'Please Select a contact to send money',
    input: 'select',
    inputOptions: {
     '1': 'Jhon',
    '2': 'Gemie',
    '3': 'Paul'
     },
   inputPlaceholder: 'Select a contact',
   html: 'Amount: <input id="amount" class="form-control swal2-input">',
   preConfirm: function () {
      return new Promise(function (resolve) {
      resolve(
      document.getElementById('amount').value,
       )
     })
   }
  onOpen: function () {
    $('#swal-input1').focus()
  }
}).then(function (result) {
  swal(JSON.stringify(result))
}).catch(swal.noop)
```

This code above show only the text input value as result, How can i get also the select value in the result array. Any idea, Thanks !!

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
