### ISSUE TITLE
"swal is not defined" after migrating from Sweet Alert 1

### ISSUE THREAD

**Issue by egeersoz** [limonte/sweetalert2#477]
I was previously using the original Sweet Alert, and things were working fine. Upgraded to SA2 and followed the migration guide. My code:

```javascript
import swal from "sweetalert2"

swal({
    title: "Are you sure?",
    text: "This cannot be undone.",
    type: "warning",
    showCancelButton: true,
    confirmButtonColor: "#DD6B55",
    confirmButtonText: "Yes.",
    closeOnConfirm: false,
    showLoaderOnConfirm: true
}).then(function() {
    /* do stuff */
})
```

This results in `swal is not defined`.

Webpack doesn't report an error, so it's not a compilation issue. Do I have to do something else to make this work? Other than switching from callbacks to promises as per the migration guide, nothing else has changed in my code. Using Chrome.

**Comment by toverux** [comment]
Could you tell us what version of Webpack you use, and the transpiler (TypeScript, Babel...)?
Also, please post the relevant part of the JavaScript that Webpack produces.

**Comment by limonte** [comment]
![](https://i.imgflip.com/1mamcs.jpg)

**Comment by limonte** [comment]
@egeersoz I just updated https://github.com/limonte/sweetalert2-webpack-demo to latest versions, works fine, take a look.

**Comment by egeersoz** [comment]
For anyone struggling with this, I finally resolved it by re-importing swal in each component in which it is invoked. Importing it just in main.js didn't work.

I use Vue.js. Did not have this problem with the original SweetAlert.

**Comment by webhacking** [comment]
@egeersoz me too

**Comment by toverux** [comment]
Just in case you're wondering, this is normal and indicates that your module bundler does your job correctly, and that `swal` is no longer a global bject manually attached to the `window`.

**Comment by webhacking** [comment]
```javascript
import swal from 'sweetalert2';

window.swal = swal
```

**Comment by omererbil** [comment]
i had resolved this issue by replacing sweetalert2 cdn
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.29.2/sweetalert2.all.js"></script>

**Comment by hagolo** [comment]
> i had resolved this issue by replacing sweetalert2 cdn
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.29.2/sweetalert2.all.js"></script>

Thank you ) its worked for me

**Comment by kshitish45** [comment]
i had resolved this issue by replacing sweetalert2 cdn
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.29.2/sweetalert2.all.js"></script> 

Thank you :) its also worked for me

**Comment by gverni** [comment]
@hagolo @kshitish45 would you mind providing the full description of your problem with the code on a new issue? Keep in mind that you are using an outdated source for the sweetalert code (see [here](https://github.com/sweetalert2/sweetalert2/releases) for the latest version) and you are not benefitting from the latest bug fixes / improvement.

**Comment by limonte** [comment]
Also, I recommend using jsdelivr as CDN service: 

```html
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>
```

**Comment by zhxscript** [comment]
> import swal from 'sweetalert2';
> 
> window.swal = swal

This did it for me

**Comment by GarbledTTT** [comment]
> i had resolved this issue by replacing sweetalert2 cdn
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.29.2/sweetalert2.all.js"></script>
> Thank you :) its also worked for me

Wow , That's great

**Comment by gverni** [comment]
@GarbledTTT the cloudflare CDN is not the _official_ one. Please use the one pointed by limonte  above:

```html
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
```

**Comment by wandaazhar007** [comment]
> i had resolved this issue by replacing sweetalert2 cdn
> 
> <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.29.2/sweetalert2.all.js"></script>

Thanks dude. It's works

**Comment by linces** [comment]
How and where to do it?

**Comment by linces** [comment]
How and where to do it?

> @GarbledTTT the cloudflare CDN is not the _official_ one. Please use the one pointed by limonte above:
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
> ```
