### ISSUE TITLE
The dialog box is not displayed

### ISSUE THREAD

**Issue by sxhjlzl** [limonte/sweetalert2#478]
The dialog box is not displayed
Before use： 
![image](https://cloud.githubusercontent.com/assets/12149913/24449431/d24ad142-14a9-11e7-95b1-91b5667a7888.png)

After use  
![image](https://cloud.githubusercontent.com/assets/12149913/24449486/f2d17c04-14a9-11e7-8089-0497342ab89f.png)

The page is also messy，Help me find this question

**Comment by sxhjlzl** [comment]
Using the vue+element-ui

**Comment by sxhjlzl** [comment]
Use this way to import
import swal from 'sweetalert2' 
only import  js file，no import  css file
![image](https://cloud.githubusercontent.com/assets/12149913/24450863/1cb9959c-14af-11e7-9cd3-e8e52adf6483.png)

**Comment by limonte** [comment]
You answered your own question here:

> only import js file，no import css file

It's our fault that we missing the information about CSS import, sorry for this inconvenience. 

You need to import it explicitly: 

```js
import './node_modules/sweetalert2/dist/sweetalert2.css'
```

We are working on the documentation improvement: https://github.com/limonte/sweetalert2/issues/422

Thanks for using the swal2 and have a nice day!
