### ISSUE TITLE
Need another button

### ISSUE THREAD

**Issue by dtruel** [limonte/sweetalert2#48]
Hi,

I'd like to be able to add another button for the simple use case on exit:

Return to editing
Discard Changes and exit
Save and exit

any plans on doing this?  I need this functionality so I might be able to do a pr if there is no other way.  I'm not too familiar with this library though, so if anybody has any tips on how to do it they would be appreciated.

It might be nice to give the ability to make unlimited buttons too, like this:

``` javascript
customButtons:[{
  name:"My Button",
  onClick:function(){
    //do stuff
  }
}]
```

Maybe in v3 we could do it like this:

```javascript
{
  title:"swal",
  buttons:[
    {
       text:"save",
       type:"success",
       onClick:function(){
        //do stuff
       }
    }
  ]
}

**Comment by limonte** [comment]
I want to keep swal2 as simple as possible. 

You can always implement custom buttons by using `html` parameter:

```
swal({   
  title: 'Custom buttons',   
  html: 'Lorem ipsum <hr><button>Return to editing</button> <button>Discard</button> <button>Save</button>', 
  showConfirmButton: false 
});
```

**Comment by seiyria** [comment]
The problem here is, how do we bind closing the swal and passing in a result while doing so? Without that it's not particularly useful to just add custom buttons.

**Comment by simo9000** [comment]
What if we enabled the html parameter to accept an element in addition to html text. This way you could create your custom content (i.e. buttons) but before handing it to swal you could attach event callbacks to it. with this you could make a complete backbone view or react component and have it live inside a swal. To keep things simple, the custom component callbacks would only have access to the global swal methods but that should be sufficient to close an alert from a custom element callback.

**Comment by acupajoe** [comment]
@seiyria take a look at the event binding params, just pass the bindings for your results in using the  `onOpen` params.

**Comment by seiyria** [comment]
@acupajoe Do you happen to have an example? I don't see anything in the docs: https://limonte.github.io/sweetalert2/

**Comment by acupajoe** [comment]
From #199 https://jsfiddle.net/t7hfffch/2/

**Comment by seiyria** [comment]
@acupajoe Thanks, I'll give that a try.

**Comment by seiyria** [comment]
@acupajoe A few things - that looks like lots of jQuery which I am not using (so I'm not sure how easily translateable it is to vanilla js), but that aside, it doesn't seem to return values via the promise created by swal, which is kinda what I'm going for. I guess I could have separate callbacks for each button but I don't really want to do that if possible.

**Comment by acupajoe** [comment]
@seiyria - please be sure to provide the entire problem specification in the future. Currently there's not a way to do what you're asking involving the promise as well without some hacky code. (i.e. binding actions to a variable and passing the event along to a preconfirm switch statement)

I don't particularly see this use case as one that is applicable to the vast majority of our users, but I'm happy to be proven wrong. Adding additional buttons would, in my opinion, clutter the interface more than necessary as well as require a good bit of conditional formatting be added to the library for a small use case, which isn't ideal.

The solution I provided should not be hard to port into vanilla.js, it's just a find and event binding statement. So, provided you can deal not having the promises part, that would be the option I would pursue. Otherwise you're welcome to fork the repo and provide a PR for review. I know most of the other contributors are either busy or working on other PRs at the moment.

**Comment by seiyria** [comment]
I will probably end up doing that, but I do find the case for more than 2 buttons to be a useful one. My use case is as such: I have a dialog that pops up where people can view more information about a certain piece of equipment (and then close it). The request I'd gotten was to be able to choose to equip the item, discard the item, or close the dialog. Even if I had to assign it numbers - 0, 1, and undefined/false for cancel, that would be sufficient.

Given that even windows has yes/no/cancel dialogs, I think it's strange to not at least support 3 buttons, but even stranger is not supporting N buttons (and leaving it up to the implementer to deal with issues like how many go in a row, etc).

**Comment by seiyria** [comment]
@acupajoe Just curious, does my use case persuade you any bit to at least add a third button? I still think, bare minimum, yes/no/cancel is what dialog boxes such as this should support.

**Comment by limonte** [comment]
Unfortunately, the sweetalert2 plugin wasn't designed from beginning for N buttons and It's the complex task to refactor it to support N buttons.

> I don't particularly see this use case as one that is applicable to the vast majority of our users

I think so too. For small percentage of use-cases we will increase the plugin complexity twice or even more. 

@seiyria if you need 3 or more buttons you should either use the hacky solution mentioned by @acupajoe or choose another plugin.
