### ISSUE TITLE
Html selector and sweetalert2 button to show custom message....

### ISSUE THREAD

**Issue by lithos-g** [limonte/sweetalert2#481]
Hello,

I have a selector with 10 options and I want when someone selects 1 to show message "Success", from 2-5 show message "Fail", from 6-8 message "Try again!" and from 9-10 show message "Not accepted".
I tried it with if but I get the same message for all options...

Here is my HTML code:

[HTML.txt](https://github.com/limonte/sweetalert2/files/886702/HTML.txt)

Thanks in advance for your help!

**Comment by limonte** [comment]
https://jsfiddle.net/ad3quksn/81/
