### ISSUE TITLE
Wrong close button border

### ISSUE THREAD

**Issue by rorc** [limonte/sweetalert2#482]
Forgot add `border: none` to `swal2-close`
http://joxi.ru/Y2LqPzBu05q6A6

**Comment by limonte** [comment]
Thanks for reporting! OS/browser?

**Comment by rorc** [comment]
Windows 10, firefox and chrome

**Comment by limonte** [comment]
Can't reproduce, make sure you're using the latest CSS files

**Comment by rorc** [comment]
My swal version is 6.5.2
I import swal styles this way `@import 'node_modules/sweetalert2/src/sweetalert2';`

**Comment by limonte** [comment]
can you reproduce the same issue on https://limonte.github.io/sweetalert2/ ?

**Comment by rorc** [comment]
http://joxi.ru/Y2LqPzBu0586A6

**Comment by rorc** [comment]
Hmm, here is ok http://joxi.ru/Dr8nJRjHe8yD26

**Comment by rorc** [comment]
Btw, this rules for border from example.css http://joxi.ru/KAx58BNI75RLr8

**Comment by limonte** [comment]
Fixed in [v6.5.3](https://github.com/limonte/sweetalert2/releases/tag/v6.5.3)

Thanks a lot :beers:

**Comment by rorc** [comment]
Thx u too 👍
