### ISSUE TITLE
This package is too awesome

### ISSUE THREAD

**Issue by mattbrunetti** [limonte/sweetalert2#484]
It's making all the other packages on NPM look bad

**Comment by limonte** [comment]
Thanks :beers:

**Comment by limonte** [comment]
Hola @mattbrunetti! 

Do you want to become a collaborator of this project? :) https://github.com/limonte/sweetalert2/issues/130

**Comment by mattbrunetti** [comment]
@limonte I'd be honored. Just complicated that my collaboration so far has been at work, and management probably wouldn't approve of me getting too involved on their dime. 

But I may have some free personal time this weekend for #485 part B, and I can't help but always check what's going on here :)

So yeah, I'd love to be a collaborator, but going forward I should use my personal Github account @zenflow (yeah, kinda lame I have to have two Github accounts)

:beers:

**Comment by limonte** [comment]
Welcome, @zenflow :)

---

> Just complicated that my collaboration so far has been at work, and management probably wouldn't approve of me getting too involved on their dime.

Companies don't own us. Work doesn't own us. Management doesn't own us. It is important as free-thinking beings that we don't feel constantly trapped and indebted to work all the time.
