### ISSUE TITLE
Testing with QUnit

### ISSUE THREAD

**Issue by herghost** [limonte/sweetalert2#486]
Hi All, any hints on how to assert if a dialog is visible?

I am trying to test the following code block

` var BranchPromise = getBranches();
    BranchPromise.then(function (BranchData) {
        var BranchOptions = [];
        $.each(BranchData, function (i, d) {
            BranchOptions.push(d.BranchDescription)
        });

        swal({
            title: 'Delivery Branch',
            text: 'Please choose the branch below where the customer would like the order delivered',
            showCancelButton: false,
            input: 'select',
            inputOptions: BranchOptions
        }).then(function (result) {
            DeliveryType = "Other";
            DeliverToBranch = BranchData[result].BranchCode;
            ItemOrder();
        });
    });`

`QUnit.test("Other clicked", function (assert) {

    SetupClickEvents();
    $('#qunit-fixture').append('<div id="other"></div>');
    var clickEvent = $.Event("click");
    $('#other').trigger(clickEvent);
    
    ??????????

});
`

Nothing appears in my dom for the alert, once the test has failed I get the swal2-container visible, but by then it is too late to assert against it.

**Comment by limonte** [comment]
[stackoverflow.com/questions/ask](https://stackoverflow.com/questions/ask)
