### ISSUE TITLE
Horizontal rule display is not getting reset.

### ISSUE THREAD

**Issue by CSWilson** [limonte/sweetalert2#49]
When you click the confirm button, the horizontal rule above the button gets a style applied to it **display: none;** if you activate another instance of **swal** the horizontal rule is still set to display none.

**Comment by limonte** [comment]
Can you please reproduce this issue with https://jsfiddle.net/ so I can look into it, thanks

**Comment by limonte** [comment]
This bug is resolved in latest release. Thanks @CSWilson for the report!
