### ISSUE TITLE
.then not running on android device standard internet app

### ISSUE THREAD

**Issue by pknad505** [limonte/sweetalert2#492]
I am trying to use sweetalert to open a alert message to allow for the user to reset there password via email.
It is able to open the first message asking for the menu however the .then function doesnt run.
This is the current code below for the javascript:
```
function forgotPassword() {
    swal({
        title: 'Forgot Password?',
        input: 'email',
        text: 'Please input your password',
        width: '60%'
    }).then(function (email) {
        swal({
            type: 'info',
            html: 'A reset email will be sent to if the account exists: ' + email
        })
    })

}
```

I am currently using a Galaxy S6 using android 6.0.1 with the internet browser that comes installed and not chrome. Once you use the chrome app it works fine. Ive tested it on my other devices (Windows 10 phone and iPhone) and it works fine.

It is expected to run just like you have in your documentation because I copied and pasted the code pretty much but some text changes and put it in a function.

**Comment by limonte** [comment]
I believe that you need to include the Promise polyfill to get swal2 work in that android browser:

```html
<script src="https://cdn.jsdelivr.net/es6-promise/latest/es6-promise.auto.min.js"></script> 
```

**Comment by limonte** [comment]
Also, you can try other polyfills suggested here https://github.com/limonte/sweetalert2/issues/416#issuecomment-273932817

**Comment by pknad505** [comment]
So I have added the script you told me to do earlier however this still hasn't fixed the problem on android browser. I am not sure how to include core-js like the other suggests because I am not using commonJS

**Comment by limonte** [comment]
```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
```

**Comment by pknad505** [comment]
Perfect that works now thank you very much

**Comment by pknad505** [comment]
I would suggest to add this into the documentation

**Comment by Ge0f3** [comment]
<script src="https://cdn.jsdelivr.net/es6-promise/latest/es6-promise.auto.min.js"></script>  will this make it work in Iphone safari browser also ?
