### ISSUE TITLE
IE11 Array.from issue

### ISSUE THREAD

**Issue by blairjo** [limonte/sweetalert2#493]
Hi,

I see in the migration guide from the original library that we should include the es6-promise library.
I have added that, but we still get an error on this line of code:

```
return Array.from(uniqueFocusableElements);
```

The error is because Array.from is not defined, and that is not defined in the es6-promise library.
I found  [this](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill) polyfill, but I'm curious why no-one else has had an issue. 

Am I missing something?

Thanks

**Comment by blairjo** [comment]
Hi,

Thanks for fixing this so promptly!
Will you be releasing the new version to bower soon?

Thanks

**Comment by limonte** [comment]
Done: https://github.com/limonte/sweetalert2/releases/tag/v6.5.6

**Comment by blairjo** [comment]
awesome, thanks!

**Comment by limonte** [comment]
Thanks for using swal2! :beers:

**Comment by thr0wn** [comment]
Array.from was added again [here](https://github.com/limonte/sweetalert2/blob/429208d8e9c0ea0efbe1733420d2ae1676a8c997/src/utils/dom.js#L158). Although core.js avoids issues with it, seems weird it reappearing shortly after 59c8148fe2d5673af9438f57dda27189ea9cb9fd, commit that solved the previous Array.from issue. Is this a bug?

thanks.

**Comment by zenflow** [comment]
The line @thr0wn references uses `Array.from` to convert a [NodeList](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) to an array. Not sure what the recommended IE11-compatible way to do this is, but I'll look into it.

**Comment by FinesseRus** [comment]
_for the collaborators:_ Try to import the [core-js](https://github.com/zloirock/core-js) polyfill. After that you will be able to use `Array.from` without a butthurt.

**Comment by limonte** [comment]
@FinesseRus Would you like to join this project as a collaborator? I just sent you the invite, feel free to accept or reject it :)

Once you accept the invitation, I'll be able to request review from you in cases like #796 - take a look :)

**Comment by limonte** [comment]
fixed in v7.3.2, thanks for reporting!

**Comment by FinesseRus** [comment]
@limonte Thank you for invitation. I will help as much as I can, I don't have much free time.

**Comment by limonte** [comment]
> Thank you for invitation. I will help as much as I can, I don't have much free time.

Just participating in discussions will be enough. I found your bug-reports and comments valuable. Keep up the good work! :muscle:
