### ISSUE TITLE
Button elements don't need role="button" nor tabindex="0"

### ISSUE THREAD

**Issue by weboverhauls** [limonte/sweetalert2#494]
Button elements don't need role="button" nor tabindex="0". The button role and keyboard access is inherent to the button element.

Suggest removing role="button" and tabindex="0" attributes from all rendering of button elements.

`<button type="button" role="button" tabindex="0" class="swal2-cancel swal2-styled" style="display: none; background-color: rgb(170, 170, 170);">Cancel</button>`

**Comment by limonte** [comment]
Hi @weboverhauls and thanks for reporting this. It seems that you're right and buttons don't need `role="button"` nor `tabindex="0"`. Could you please make changes [here](https://github.com/limonte/sweetalert2/blob/master/src/utils/dom.js#L118-L121) and submit the PR?

Thanks in advance and have a great day!

**Comment by limonte** [comment]
Released in [v6.6.0](https://github.com/limonte/sweetalert2/releases/tag/v6.6.0), thanks for contributing!
