### ISSUE TITLE
Congratulations to everyone! We are in trending repositories list! :tada:

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#498]
SweetAlert 2 is in [trending JS repositories](https://github.com/trending/js) today :tada: :tada: :tada: 

> <img src="https://i.imgur.com/lemOY13.png" width="600">

VueJS, Bootstrap and React are our current neighbors in the most popular JS projects list :nerd_face: 

I would like to say THANK YOU to all of the project contributors and particularly:

 - @birjolaxew 
 - @toverux 
 - @samturrell 
 - @acupajoe 
 - @Tonkpils 

You are real rock-n-rollas, guys.

--- 

Let me tell you one short story. When I was looking for a job couple of months ago and participating interviews I got one question about this project: 

> Why did you chose the `rollup` for building npm module files?

And my answer was: 

> I don't know exact reasoning, @samturrell did that :D I just checked that it works as expected and pressed the "Merge" button :D 

As an author of this repo, I don't need to know every single part of the project, that's why we're doing open-source projects together. We have our strong and weak parts of knowledge and by combining our strong parts we are able to produce **great stuff**.

Once again, thank you guys! Keep on rock-n-rolling!

**Comment by toverux** [comment]
Congratulations to you too! You're doing a very good job on this library, including communication and project management, and that's also why I've decided to bring some help from times to times.
I'm very proud of Swal2 for being in the JavaScript trending repositories (111 stars a day :o ).

**Comment by taxpayer** [comment]
There was a question few weeks ago asking "how would people know this project is the replacer of the original one?". I answered that it would be a natural path to go to swal2 because, well, it *IS* the current well-mantained project. But I think that Swal2 in the trending repositories is a better answer to that question than mine... ;-)

**Comment by Vuurvlieg** [comment]
Swal2 is getting better and better. Many improvements and new features where added compared to the original swal. Also the customization of swal and responsiveness is awesome and thats one of the reasons why swal2 is totally awesome.

Thanks to @limonte and everyone who reported bugs or posted PR's!

**Comment by samturrell** [comment]
Awesome stuff guys, been good to see all the constant releases and improvements being made. Hoping to contribute more at some point when I have some more free time, but it looks like you guys are killing it 👌 

P.S. @limonte I wouldn't have held it against you if you took all the credit in your interview 😉

**Comment by StephanBijzitter** [comment]
Great!

I just found this on Google after typing "sweetalert". We'll look into switching over to this fork soon :-)

**Comment by limonte** [comment]
It was great to be in trending for 3 days :)

![img_0892](https://cloud.githubusercontent.com/assets/6059356/24846822/bbc69fe4-1dc5-11e7-8fe6-34da0edaf09c.PNG)
