### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by prateekvarma** [limonte/sweetalert2#5]
Hello @limonte , i appreciate your work and i have been trying to implement sweetalert2, but unfortunately the alerts do not popup at all in your current versions. I request you to please have a  look at the code.
Many thanks!

**Comment by limonte** [comment]
@prateekvarma can you please show me some code. How you're using sweetalert2 and is there any errors in console?

**Comment by prateekvarma** [comment]
Hello @limonte , thank you for the reply. Whats happening is - when i download the ZIP file from github, and after opening the index.html file from the "example" folder, none of the buttons show a sweetAlert. You can check it yourself, and for some strange reason it does not work...

**Comment by andyharney** [comment]
I can confirm this, it is not an issue with sweetalert2 though. Its just sweetalert2.min.js isn't loaded.
Just alter the html to reflect the correct file paths, e.g.
```html   
<!-- This is what you need -->
<script src="../dist/sweetalert2.min.js"></script> 
<link rel="stylesheet" href="../dist/sweetalert2.css">`

**Comment by prateekvarma** [comment]
Ah dear lord LOL ... yes @andyharney , you're right.
To be exactly specific, the sweetalert2.min.js file, and the sweetalert2.css files both miss one 'dot'.
It'll be great if you guys could add it in the repository, so it won't confuse anyone.
Many thanks, you guys rock!

**Comment by limonte** [comment]
@andyharney thanks for helping!

**Comment by andyharney** [comment]
@limonte No problem. Thanks for your fork of SweetAlert2.
