### ISSUE TITLE
List of "gotcha"s

### ISSUE THREAD

**Issue by StephanBijzitter** [limonte/sweetalert2#500]
When calling swal as a response to a click (or similar) event, the popup can automatically close itself, and that can be terribly annoying if you don't know the reason. As it stands, the reason is that mobile devices (most of all), submit more than one event when the user touches the screen. The first event would trigger the button and show the popup, but the second event would then trigger the popup to close.

The solution in this case is to call `preventDefault` before showing the popup:
```js
function onClick(event) {
    event.preventDefault(); // without this, there's a chance the swal popup closes itself

    swal("It works!");
}
```
Perhaps it would be useful for have a list of these kinds of behaviours present in this repository. Especially in this case the sweetalert2 module appears broken, while it is really the browser that is being a bit weird to preserve backward compatibility with older websites.

**Comment by limonte** [comment]
platform/browser?

**Comment by limonte** [comment]
I can't reproduce this issue (https://jsfiddle.net/ad3quksn/84/show/)

In future for bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by StephanBijzitter** [comment]
This wasn't intended as a bug report, as it's not a bug in this module. It's simply quirky browser behaviour for many mobile devices. I'm quite sure there must be more of these strange quirks, so it would be nice to start a little list somewhere.

In my case I was using Chrome on an Android 6 device, but that really doesn't matter.

@limonte
