### ISSUE TITLE
Allow to format the error response 

### ISSUE THREAD

**Issue by vexilo** [limonte/sweetalert2#504]
Hi i have this function for deleting users via ajax

```
swal({
    title: 'Are you sure do you want to delete?',
    showLoaderOnConfirm: true,
    preConfirm: function () {
        //  make an ajax request like a promise (works fine)
        return App.delete('/users/' + user.id, this.form)
    }.bind(this)
}).then(function () {
    swal({
        title: 'User Deleted!',
        type: 'success',
    });
});
```

Actually works fine but i trying to simulate an unexpected error response and when the response is for example a 500 response code and a simple string the message shows in the modal.

Thats nice, but in my app i want that the default response for ajax errors was a json. In this case now the error message says: "[object Object]".

I think a good feature will be a configuration option to manage the error response, something like a function, for example:

```
{
 //... Another options,
   errorParser: function (error) {
       if(/*error_is_json*/) {
           // Returns some attribute from my object
           return error.message; 
       },
       return error;
   }
}
```

**Comment by mattbrunetti** [comment]
@vexilo This package may soon be separating validation errors (user errors) from real errors (system errors). See issue #485.

The intended purpose of the message display you're referring to is validation errors, so I imagine it won't be automatically wired to display system errors; I think that responsibility would be out of scope of this package, though I can't say for sure.

**Comment by limonte** [comment]
>  I think that responsibility would be out of scope of this package

Agree, to project-related to be in scope of this plugin.
