### ISSUE TITLE
Disable autocomplete and such... on input

### ISSUE THREAD

**Issue by Kyslik** [limonte/sweetalert2#505]
Is there any way to disable `autocomplete`, `autocorrect`, `autocapitalize`, `spellcheck` on generated input field?

`<input ... autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">`

**Comment by mattbrunetti** [comment]
You could use the `onOpen` option and the `swal.getInput()` method

**Comment by Kyslik** [comment]
Thanks @limonte :)
