### ISSUE TITLE
Used in vue2,type="success"  No animation effect

### ISSUE THREAD

**Issue by sxhjlzl** [limonte/sweetalert2#506]
![image](https://cloud.githubusercontent.com/assets/12149913/25122859/077bc290-2459-11e7-87f4-eac16e984a84.png)

Used in vue2,type="success" and type="error" No animation effect

import swal from "sweetalert2";
import "../../../static/css/sweetalert2.css";

**Comment by limonte** [comment]
Update CSS styles to the latest.
