### ISSUE TITLE
SweetAlert2 display error on Safari for iOS

### ISSUE THREAD

**Issue by AFTERWAKE** [limonte/sweetalert2#510]
Hey limonte! Really love what you've done with sweetalert, I've worked with the original before, and I decided to put your version on a website me and a few guys are designing for a class I'm in.

I am using sweetalerts for the login/register/about page of our site. I injected an html form into the login/register ones so that I can easily do a POST request and have multiple input forms, and the about link just brings up a standard sweetalert with a couple sentences about the site. As it is, everything works flawlessly on every single broswer except Safari for iOS. It works on macOS, it works on Chrome, Firefox, and Edge.

First off, have you seen any errors with mobile safari and sweetalerts? I thought maybe it was the custom html I used that messed it up, but the About link also doesn't display. Sweetalerts on your website work on mobile Safari, but when I put the same code (with diferent text for title and message) on our project website, it stops working. My site is using session variables and cookies, but other than that, it's just plain html and css with javascript logic for the login/register.

The About sweetalert code is:

```js
$('#about').on('click', function () {
  swal({
    title: 'Hello!',
    text: 'Lone Forest is a text-based adventure game where you must find your way through the forest. Log in or Register an account to begin playing.',
    type: 'info',
    showCancelButton: false,
    confirmButtonColor: '#3085d6',
    confirmButtonText: 'Cool'
  })
})
});
```

Here is the website where it doesn't work:
https://loneforest.chaisefarrar.xyz/

And here is the github source code:
https://github.com/afterthought325/LoneForest

See LoneForest/index.php for main page, `LoneForest/js/loginpage.js` for the javascript logic and sweetalert usage, and see `LoneForest/login/testLogin/index.php` and `LoneForest/login/testRegister/index.php` for where the post request goes to for checking login.

Here is what it looks like using Safari on iOS:

Before clicking "Login":
https://i.groupme.com/640x1136.png.94d90270cbc44446afc36e68597c4fc0

After clicking "Login":
https://i.groupme.com/640x1136.png.8610335e971b4b1c842e9a0a19bd4436

What it looks like on Chrome on my Samsung S7 after clicking "Login"(aka what it should look like):
http://i.imgur.com/aNojwRq.png

I've run out of ideas on how to fix this, and I'm tempted to just not care since it's just for a school project. If you can help though, I would really appreciate it.

**Comment by AFTERWAKE** [comment]
By the way, if you want a working username/password without having to register, you can use username/password bob/bob. Though I don't think you really need to log in unless you just wanna play the game haha

**Comment by AFTERWAKE** [comment]
Here is a jsfiddle if you'd like that.

https://jsfiddle.net/7j24bnbk/2/

**Comment by limonte** [comment]
`w3.css` cause the issue, not swal2. Without `w3.css` all works fine: https://jsfiddle.net/7j24bnbk/9/show/
