### ISSUE TITLE
When clicking quickly : Uncaught TypeError: Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by vipdorian** [limonte/sweetalert2#512]
To reproduce the bug:
Browse to this page : https://limonte.github.io/sweetalert2/
Focus the button "Try me!" under "A success message!"
Then press "Enter" about 4 times quickly.
Look at the console:

Uncaught TypeError: Cannot read property 'removeChild' of null
    at removeModalAndResetState (sweetalert2.js:1518)
    at HTMLDivElement.swalCloseEventFinished (sweetalert2.js:1530)

**Comment by vipdorian** [comment]
I am not able to reproduce this bug when animation='false'.

**Comment by limonte** [comment]
Fixed in [v6.6.1](https://github.com/limonte/sweetalert2/releases/tag/v6.6.1), thanks for reporting! :beers:

**Comment by vipdorian** [comment]
This was fast!!!
