### ISSUE TITLE
UC Browser - modal width is incorrect

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#514]
Separation from #513 

- Device: ASUS Zenfone 2, Android 5
- Browser: UC Browser

![image](https://cloud.githubusercontent.com/assets/27913553/25316896/5ca5da90-2877-11e7-8f90-c79979002bfc.png)

**Comment by limonte** [comment]
I can confirm the same issue in the UC Browser on the Google Next device.

**Comment by limonte** [comment]
Fixed in [v6.6.2](https://github.com/limonte/sweetalert2/releases/tag/v6.6.2), thanks!

**Comment by sakettiwari** [comment]
Hi, issue is fixed, and every modal is working well in UC except one, the 'error' message modal. It blinks a little extra and it's not normal. I have checked it several times.
