### ISSUE TITLE
How to add custom button in sweet alert

### ISSUE THREAD

**Issue by vibingopal** [limonte/sweetalert2#515]
Hi Team, 

Could you please let me know how to add custom button in sweet alert. I need to call a custom method on user perform operation on button  and unable to print $ value .
Any suggestions on this please?

Iam using Angular2 framework.

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
