### ISSUE TITLE
Unable to call normal methods inside sweet alert

### ISSUE THREAD

**Issue by vibingopal** [limonte/sweetalert2#516]
Hi Team,

I am unable to call normal methods on events inside sweet alert. Any idea please?

Thanks

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
