### ISSUE TITLE
Load aspx page inside it

### ISSUE THREAD

**Issue by cristo1985** [limonte/sweetalert2#520]
Hi, how can i load an aspx page inside it? Thanks.
Cris

**Comment by mattbrunetti** [comment]
Use an `<iframe>` element within the `html` option, or fetch the aspx page with AJAX and pass it in for the `html` option

**Comment by cristo1985** [comment]
Ok i think simply use html: <iframe>....</iframe> but my page is an external file... than i must put source in iframe true?

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
