### ISSUE TITLE
Old IE and Upload Function inside

### ISSUE THREAD

**Issue by cristo1985** [limonte/sweetalert2#522]
Hi i've 2 question:

- About old IE why not work? How can i make it working?
- And is there a simples function to integrato for uploading file and send trough email? Using only html and jquery?
Thanks
Cris

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
