### ISSUE TITLE
callback function not work in this code

### ISSUE THREAD

**Issue by zwl1619** [limonte/sweetalert2#527]
I want to give users an alert before submitting a form, the code is like this:
```
<form id="deleteForm" action="/articles/{{ $article->id }}" method="POST">
    {{ method_field('DELETE') }}
    {{ csrf_field() }}
    <input class="btn btn-danger btn-sm need-alert" type="submit" value="delete">
</form>

<script>
$( "#deleteForm" ).submit(function( event ) {
        event.preventDefault();

        //sweetalert2 code
        swal({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then(function () {
            $(this).submit();
        }).catch(swal.noop);
});
</script>
```
The alert box could be shown correctly,
but the code in `then()` doesn't work,
how do I write it?

**Comment by psafx** [comment]
Just replace your $(this).submit(); with $('#deleteForm').off('submit').submit();

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
