### ISSUE TITLE
Possibility to define global defaults?

### ISSUE THREAD

**Issue by nhaberl** [limonte/sweetalert2#530]
Would like to know if it's possible to define global defaults for the config values like button color and so on

**Comment by toverux** [comment]
Yes, via `swal.setDefaults({ Object })`.

> **`swal.setDefaults({ Object })`**
> If you end up using a lot of the same settings when calling SweetAlert2, you can use setDefaults at the start of your program to set them once and for all!

`swal.resetDefaults()` also exists - it's useful when configuring a queue of modals and avoid repeating the same configuration, and without erasing global defaults forever.

See the complete reference in the README for more.

**Comment by AlbertMN** [comment]
@limonte this functionality doesn't seem to exist anymore. Is that correct? If so, is there an alternative function that I'm missing?

**Comment by limonte** [comment]
@AlbertMN correct. `setDefaults` was deprecated in v8 and removed in v9. Use `.mixin()` instead: https://sweetalert2.github.io/#mixin
