### ISSUE TITLE
2 or more alerts showing last alert only

### ISSUE THREAD

**Issue by arabgenius** [limonte/sweetalert2#531]
Hello
if I have 2 or more alerts .. it shows me the last one ,, not one by one like the original alert
see this
https://jsfiddle.net/opwznh9x/
 thanks

**Comment by limonte** [comment]
Probably you're looking for `swal.queue`: https://jsfiddle.net/opwznh9x/1/

See more examples of chaining (queueing) modals: https://limonte.github.io/sweetalert2/#chaining-modals

**Comment by arabgenius** [comment]
Hello again
see this code which I used in old sweetalert ,, how to convert it into QUEUE
`swal( { title: "title hele",text: "msg here", confirmButtonText: "open file",showCancelButton: true,cancelButtonText: "dismess" },function(isConfirm){ if (isConfirm) { $.get('{$baseurl}user/notifi/{$notification.id}'); window.location = '{$notification.url}' } } );`
