### ISSUE TITLE
Error in sweetalert2 prevents use with zone.js

### ISSUE THREAD

**Issue by MichaelJCole** [limonte/sweetalert2#54]
Hi, zone.js is used in zones, which is used by Meteor's Kadira for in browser error reporting to a server.

sweetAlert2 has an error, which doesn't seem to bother chrome, but when combined with zone.js prevents the callback from being called.

I tried to explain it here: https://github.com/meteorhacks/zones/issues/85
and here: https://github.com/angular/zone.js/issues/260

Those issues are about zone.js, but this is the root cause:
```
Error: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at s (https://dashboard-dev.hello.io/packages/patrickml_swal.js?06d775f51a9debdd71fd5de7eb0594d0e94eed1b:32:7559)
    at HTMLButtonElement.p (https://dashboard-dev.hello.io/packages/patrickml_swal.js?06d775f51a9debdd71fd5de7eb0594d0e94eed1b:32:3375)
```

**Comment by limonte** [comment]
the best place to submit this issue https://github.com/patrickml/swal/
