### ISSUE TITLE
Input type url not accepting parameters

### ISSUE THREAD

**Issue by nishou** [limonte/sweetalert2#542]
Hi,

1. Go to the fiddle https://jsfiddle.net/nishzone/jnLjLpt7/2/
2. Enter the url https://www.youtube.com/watch?v=PWgvGjAhvIw in the input box.
3. Expected behavior is success
4. Actual behavior is failure with the error message Invalid URL.

Regards,
Nisha

**Comment by limonte** [comment]
Fixed in [v6.6.5](https://github.com/limonte/sweetalert2/releases/tag/v6.6.5), thanks for reporting :beers:

**Comment by nishou** [comment]
Awesome! Thank you 👍
