### ISSUE TITLE
Page unresponsive after confirm

### ISSUE THREAD

**Issue by anutting** [limonte/sweetalert2#545]
Hi limonte,

I've got a couple swal alerts one after the other. After the second one closes the page is still faded grey and I can't scroll, click, or interact with it whatsoever. It may be something with how I'm handling the promises, but it all was working fine before I changed the input from text to select.

Here's an example of my setup:
```
     swal({
              title: "Select an item",
              input: "select",
              inputOptions: inputOptionsPromise,
              showCancelButton: true,
              animation: "slide-from-top"
              }).then(function(item){
                  $.get('/handle-item, {item:item}, function (res) {
                         if (res.statusCode == '201') {
                          swal("Request successful!", "Please come again", "success");
                          updateStatus("success");
                      }
                      else {
                          swal({ title:"Oops...", text:"route could not be reached", type:"error"});
                      }

                  }).then(function(){
                      //attempting to remedy the issue, page is still unresponsive
                      document.querySelector('.modal-backdrop').remove();
                      document.querySelector('div.swal2-container').remove();
                  });
              },
              function (dismiss) {
                  if (dismiss === 'overlay') { 
                      // ignore
                  } else {
                      throw dismiss;
                  }
              });
```
The issue occurs after clicking "OK" or dismissing by overlay on the error modal.

Any help would be appreciated. Thanks!

**Comment by limonte** [comment]
Replace 

```js
document.querySelector('.modal-backdrop').remove();  document.querySelector('div.swal2-container').remove();
```

with `swal.close()`

**Comment by anutting** [comment]
thanks for such a quick reply! but that only closes the modal and the page remains faded out and unresponsive

i tried changing the code to be:
``
     swal({
              title: "Select an item",
              input: "select",
              inputOptions: inputOptionsPromise,
              showCancelButton: true,
              animation: "slide-from-top"
              }).then(function(item){
                  $.get('/handle-item, {item:item}, function (res) {
                         if (res.statusCode == '201') {
                          swal("Request successful!", "Please come again", "success");
                          updateStatus("success");
                      }
                      else {
                          swal({ title:"Oops...", text:"route could not be reached", type:"error"});
                      }

                  })
                  }).done(function(){
                         swal.close();
                     });
              },
              function (dismiss) {
                  if (dismiss === 'overlay') { 
                      // ignore
                  } else {
                      throw dismiss;
                  }
              });
``

**Comment by VinyP** [comment]
I am currently having this issue, on IE11. The page remains faded out and unresponsive. Any fix for this??

**Comment by anutting** [comment]
I haven't tested anything on IE11 so I can't speak specifically to that browser, but my issue was with the $.get request not being resolved. I ended up promisifying the whole thing, for example:
```javascript
swal.queue([{
              title: "Select an item",
              input: "select",
              inputOptions: getOptionsPromise, //promise that resolves with a key:value object
              showCancelButton: true,
              showCloseButton: true,
              inputPlaceholder: 'Select Option',
              animation: "slide-from-top",
              showLoaderOnConfirm: true,
              preConfirm:
                  function(option){
                      return new Promise(function(resolve){
                          $.get('/option-list', {
                              parameter: 'param'
                          }).always(function(res){
                                  if (res.statusCode === 201) {
                                      swal.insertQueueStep({title:"Input sent!", type: "success", showCloseButton: true});
                                  } else {
                                      swal.insertQueueStep({ title: "Oops...", text: "There was a problem sending!", type: "error", showCloseButton: true});
                                  }
                              resolve();
                          });
                      });
                    }
          }]);
```
