### ISSUE TITLE
Is it possible to close a specific modal?

### ISSUE THREAD

**Issue by Script47** [limonte/sweetalert2#546]
As the example can be seen below:

```javascript
var swal_one = [...];
var swal_two = [...];

swal.close(swal_one);
```

So a reference to the alert you want closing is provided so it doesn't clash with other alerts.

**Comment by limonte** [comment]
SweetAlert2 doesn't support multiple alerts, so your question doesn't make sense.

**Comment by jvcunha** [comment]
It makes sense because I have a situation that would need this functionality. For example, I have a loading in ajax and at the end when I give a close, ajax opens another showing an error. At the close of loading, close the 2 at the same time! The user can not see the error message ...

**Comment by zenflow** [comment]
Despite you need for this functionality, sweetalert2 supports only one modals at a time, so the question doesn't make sense (you can only close the currently open modal)

**Comment by seanvree** [comment]
Sweetalert2 is bad ass.  I do wish, however, that there was a way to asynchronously load two modals. 

Cheers.

**Comment by gverni** [comment]
Hey @seanvree would you mind explaining the use case for that? A modal (by definition) is a child window that the user must interact with. If you have multiple modals the user still have to interact with them one by one. So you might as well have a sequence of modals instead, for example using queues and mixins.

**Comment by seanvree** [comment]
@gverni  I wasn't aware that a modal MUST be interacted with by the user. In that case, you're right. 

I was just trying to have two "alerts" (non-interactive) in the browser at the same time.

**Comment by taxpayer** [comment]
@seanvree If you want multiple non-interactive alerts (or messages) at the same time, why don't you go with toasts?

Look for the *toast* option in the configuration.
