### ISSUE TITLE
'animation' bug

### ISSUE THREAD

**Issue by ApolloCr** [limonte/sweetalert2#552]
Following #551 
Actually I know about 'animation' and I found bug maybe?
For me is modal not animated but success and error icons are animated, then I found this is happening when
```
swal({
  title: 'Auto close alert!',
  type: 'success',
  animation: 'false',
})
```
and everything is static with
```
swal({
  title: 'Auto close alert!',
  type: 'success',
  animation: false,
})
```

Actually this will be very useful, with this 3 levels of animation (off, icons, icons+modal), just maybe better values 'none', 'icons', 'all' and true = 'all' and false = 'none' for backwards compatibility.

thanks

**Comment by limonte** [comment]
Make sure you are using the latest version of plugin.
