### ISSUE TITLE
Radio checkbox - showing previous labels on revisit

### ISSUE THREAD

**Issue by stack-its** [limonte/sweetalert2#554]
I'm seeing a bug when running input radio.  If I click on the cell, get the alert, click cancel, then click on it again, I get the previous labels showing in the alert, see screenshot.
<img width="306" alt="062" src="https://user-images.githubusercontent.com/1207542/27520143-6dce987e-59c9-11e7-8d48-8e401e3f9216.png">

 jsfiddle: https://jsfiddle.net/billparti/ad3quksn/106/
Note: the fiddle doesn't seem to get the bug, so how do I insure the labels are removed before the new ones are rendered?  I've tried removing the labels in two different locations in the fiddle, but to no avail.

Thanks, Bill

**Comment by limonte** [comment]
> Note: the fiddle doesn't seem to get the bug

Hi Bill, if you are not able to reproduce the issue in jsfiddle, then it's probably in your app code, not in SweetAlert2.

Feel free to comment here in case you will succeed with reproducing the issue in jsfiddle.
