### ISSUE TITLE
'animation' bug

### ISSUE THREAD

**Issue by ApolloCr** [limonte/sweetalert2#555]
Following #552 
why you not giving me chance to answer? you just close issue and I need always open new...

I'm using version 6.6.5 and these is bug that
`animation: 'false'`
make modal not animated but ok and error icon is animated.

this is error as "animation" should accept only boolean true or false and if not, it should use default value

**Comment by limonte** [comment]
`'false' !== false`

**Comment by limonte** [comment]
PS you can leave comment for closed issues ;)
