### ISSUE TITLE
Generated HTML is not XML-serializable

### ISSUE THREAD

**Issue by Spetnik** [limonte/sweetalert2#559]
Currently the HTML generated by sweetalert2 is not valid XML, which causes issues when used in XML-serialized HTML (such as XHTML). I will try to create a PR to fix this.

**Comment by limonte** [comment]
Many thanks @Spetnik  for reporting and trying to fix this issue!

**Comment by Spetnik** [comment]
Ouch just saw that I'm not supposed to commit the dist files. I'll redo it!
