### ISSUE TITLE
Outside click of modal window is NOT returning callback

### ISSUE THREAD

**Issue by dylanh724** [limonte/sweetalert2#56]
We can do swal(function(isConfirm) {}); to handle cancel btn click if !isConfirm,

**..but what about clicking outside the window?** it is neither confirmed nor cancelled

**Comment by limonte** [comment]
Done in https://github.com/limonte/sweetalert2/releases/tag/v0.3.3

Callback is called now on click outside the modal. `isConfirm` will be `undefined`.

**Comment by dylanh724** [comment]
(Confirmed working - thanks!!)
