### ISSUE TITLE
Overlay change background color

### ISSUE THREAD

**Issue by cristo1985** [limonte/sweetalert2#565]
Hi,
i tried change it:

.swal2-container.swal2-shown {
    background-color: rgba(0, 0, 0, 0.4);
}

to
.swal2-container.swal2-shown {
background: #a6a6a6 url(images/ui-bg_dots-small_65_a6a6a6_2x2.png) 50% 50% repeat;
    opacity: .4;
    filter: Alpha(Opacity=40);
}

But it render container of swal dialog transparent but visible. How can i change color of only overlay?
Thanks!
Cris

**Comment by limonte** [comment]
https://jsfiddle.net/ad3quksn/118/
