### ISSUE TITLE
sweet alert dont work for some mozilla firefox browser

### ISSUE THREAD

**Issue by m-alinasab** [limonte/sweetalert2#568]
hi .

i install this package on Vue Project .
on the Google Chrome no problem to work but in the mozilla ( version 54.0.1 (64-bit) ) don't work but Added sweet Alert to DOM ( html code to inspect Element ) .

please see image : 

http://up.vbiran.ir/uploads/847914996771705139_1.png
http://up.vbiran.ir/uploads/12475149967716836603_2.png
http://up.vbiran.ir/uploads/3197514996771695078_3.png

Even the example you put up is also a problem.
https://limonte.github.io/sweetalert2/

please help me .

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by acupajoe** [comment]
@HennesseyJ It was closed because there was not a minimum reproducible example provided. Issues are closed if they don't follow the bug reporting guidelines and then reopened once a user provides a debuggable example.

I'm happy to reopen this issue if you can provide a more detailed bug report!

**Comment by mfarajewicz** [comment]
I would like to ask for reopening the issue by providing some simple way of reproducing it. However there is no way to show it in JsFiddle as Firefox Extension is completely separate environment. Is there a chance that if I create minimal working example of extension with SweetAlert for Chrome & Firefox to compare, you'll have a look on that?

**Comment by mfarajewicz** [comment]
Ok guys I figured out what is happening. Code of SweetAlert.js is fine. Problem is that Firefox has different `this` object than Chrome in extension env. Checkout solution here: 
https://devtraintravel.wordpress.com/2018/03/27/browser-extension-differences-episode-1/

**Comment by limonte** [comment]
Thanks a lot for sharing your research @mfarajewicz!
