### ISSUE TITLE
Target as string or element

### ISSUE THREAD

**Issue by erickmonteiro** [limonte/sweetalert2#571]
Target parameter could be able to inform an element directly rather than just string.

Similar to the example below:
$('ul li .btn').on('click', function(e){
    swal({
        target: $(this).closest('li')[0]
        ...
    });
});

Swal2 code:
...
var targetElement = document.querySelector(params.target);
if( !targetElement )
{ ...

It could be:
...
var targetElement = typeof params.target === 'string' ? document.querySelector(params.target) : params.target;
if( !targetElement )
{ ...

**Comment by limonte** [comment]
Nice suggestion @erickmonteiro! Are you able to create a PR with this improvement?

**Comment by erickmonteiro** [comment]
PR created, thank you.

**Comment by limonte** [comment]
Implemented in https://github.com/limonte/sweetalert2/pull/592
