### ISSUE TITLE
SweetAlertOptions.progressSteps inconsistent type definition

### ISSUE THREAD

**Issue by michaelbull** [limonte/sweetalert2#574]
The type definition of the [`progressSteps`](https://github.com/limonte/sweetalert2/blob/master/sweetalert2.d.ts#L534) field inside of the `SweetAlertOptions` class specifies an array of `SweetAlertOptions`, however the [example](https://limonte.github.io/sweetalert2/#chaining-modals) shows it being used as an array of strings.

The [`setProgressSteps`](https://github.com/limonte/sweetalert2/blob/master/sweetalert2.d.ts#L179) method also takes an array of strings, therefore I think the `progressSteps` field inside of the `SweetAlertOptions` class should be updated to expect an array of strings.

**Comment by limonte** [comment]
The [example](https://limonte.github.io/sweetalert2/#chaining-modals) you linked uses the array of `SweetAlertOptions`:

```js
var steps = [
  {
    title: 'Question 1',
    text: 'Chaining swal2 modals is easy'
  },
  'Question 2',
  'Question 3'
]
```

Array of strings is the edge case.

**Comment by michaelbull** [comment]
No it doesn't?


The [example](https://limonte.github.io/sweetalert2/#chaining-modals) sets: 
```
swal.setDefaults({
  input: 'text',
  confirmButtonText: 'Next &rarr;',
  showCancelButton: true,
  animation: false,
  progressSteps: ['1', '2', '3']
})
```

Note: `progressSteps: ['1', '2', '3']`

**Comment by limonte** [comment]
Oops, my bad sorry.

**Comment by michaelbull** [comment]
If I pass the array of `SweetAlertOptions` to the `progressSteps` field when calling `swal.setDefaults` (example below), then [this happens](http://i.imgur.com/ii86TbG.png) (note the step numbers are replaced with `[object Object]`).

```typescript
        let steps: SweetAlertOptions[] = [
            {
                title: 'Question 1',
                text: 'Chaining swal2 modals is easy'
            },
            {
                title: 'Question 2',
                text: 'q2'
            },
            {
                title: 'Question 3',
                text: 'q3'
            }
        ];

        swal.setDefaults({
            input: 'text',
            confirmButtonText: 'Next &rarr;',
            showCancelButton: true,
            animation: false,
            progressSteps: steps
        });
```

**Comment by limonte** [comment]
Yeah, it should definitely be array of strings, could you please submit a PR with the fix?

**Comment by limonte** [comment]
Thanks a lot @michaelbull for reporting and fixing this! :beers:

**Comment by michaelbull** [comment]
Thanks again!
