### ISSUE TITLE
HTML Field, invoking JS within the embedded html.

### ISSUE THREAD

**Issue by integrateddigital** [limonte/sweetalert2#576]
Hi, 

This is a great library ! Thank you so much. 
This is not an issue, but rather a question; I apologize if this is the wrong place, .. 
My question is on regards to the HTML field on sweetalert2; 
I have a rather large block of html, and instead of '<html...> + '<more html ...> , 
I call a JS function, like this: 

swal{(...........                         
.
.
.
html: document.getElementById('htmlappender').innerHTML
.
})
and the htmlappender element is this: 

<script id="htmlappender" type="text/html">    
    <h1 style ="color:red">Hello</h1>    
</script>

and that works great, I can insert large blocks of HTML without having to concatenate 
lots of strings; 

However, how would I go about if the embedded HTML needs to invoke JS ... ? 
for example, 
if I change the above element to: 

< script id="htmlappender" type="text/html">    
    < h1 style ="color:red">Hello</h1>    
 
         CallJS(); // is interpreted as content

<    /script    >

I also tried a button,invoking js using the onclick event, but also to no avail; 

Ideally there shouldnt be a need to click a button, ... 

essentially: How to I embed JS within the embedded HTML via the swal .. html: field ? 

Thanks in advance for your kind attention, and thanks for this great library ! 
best regards,
s

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by integrateddigital** [comment]
thanks for replying.   my issue is not about how to do it, but rather to verify if swal html field can or cannot handle embedded js object within the passed html, 
however if the swal htm field is supposed to handle an object as described above, then I'd say it would be a broken functionality, given that I have no problem doing that outside swal, unless you have an example ? if you say no, then that's it, but if you say yes then obviously the problem is me, at which point Id open a question externally....thanks again for replying, txs
tx

**Comment by limonte** [comment]
In that case please come up with jsfiddle for your question

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by integrateddigital** [comment]
With all due respect, you could have said 'yes it's possible' or 'no it's not possible'... 
it is pointless to have such a great library when the fundamental point of sharing knowledge is 
pushed away with, and I apologize to say: arrogance.
thanks for your reply anyway.,
