### ISSUE TITLE
Front test swal promise return with Jasmine

### ISSUE THREAD

**Issue by FGAUTREAULT** [limonte/sweetalert2#577]
Hi, first of all thxs for your work it's great to maintain sweet alert !

I am getting an issue that I hope some of you overcame, testing the return promise of the swal() function ?

I am using swal in my component like this :
```javascript
handleUpdate(newDate) {
    const swal = require('sweetalert2');
    swal({
        title: ...,
        text: ...,
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: ...,
        cancelButtonText: ...
    }).then(() => {
        this.doSomething();
    }, (dismiss) => {
        if (dismiss === 'cancel' || dismiss === 'overlay' || dismiss === 'esc') {
            this.doSomethingElse();
        }
    });
}
```

And testing as follow :

```javascript
it('With modification and click OK', fakeAsync(() => {
    // GIVEN
    comp.isDataModify = true;
    const swal = require('sweetalert2');
    spyOn(swal, 'swal').and.returnValue(Promise.resolve());
    // WHEN
    comp.handleUpdate(new Date('06/12/2017'));
    // THEN
    expect(comp.isDataModify).toBe(false);
}));
```

I don't really know if I am getting the right object to spy on ? Or it's not the right way to spy on Promises ? I got the syntax from angular documentation :
[https://angular.io/guide/testing#test-a-component-with-an-async-service](url)

Txs in advance for any help on this.

**Comment by limonte** [comment]
try to format your question, it looks messy now. 

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by FGAUTREAULT** [comment]
Yeah sorry for that I saw it when I published.

**Comment by limonte** [comment]
Sorry, but I can't help here as this question is actually unrelated to SweetAlert2, but to Jasmine and AngularJS.

**Comment by FGAUTREAULT** [comment]
I understand. I post it here in case people had already tried to test sweetalert2 with Jasmine and it could be interesting for people to know either how to test it. Anyway I'll post here if I find a solution !

**Comment by FGAUTREAULT** [comment]
Here it is !

You need to declare SweetAlert as a service
```javascript
import * as SweetAlert from 'sweetalert2';
```
Then use the default method to build it
```javascript
SweetAlert.default({
        title: ...,
        text: ...
    })
    .then(() => { ... });
```
And finally with Jasmine spy on the default method to get the promise
```javascript
spyOn(SweetAlert, 'default').and.callFake(function () {
    return Promise.resolve(function() {
        // Data will only be modified inside the Promise
        expect(...).toBe(...);
    });
});
```

**Comment by sreekanthyuv** [comment]
Can you please post the spec file for this sweet alert 2 @FGAUTREAULT

**Comment by prmkishor** [comment]
```
deleteItem(itemId) {
    Swal({
      titleText: 'Are you sure to delete item?',
      confirmButtonText: 'Yes',
      cancelButtonText: 'No',
      showCancelButton: true
    }).then((result) => {
      if (result.value !== undefined && result.value) {
        this.itemService.deleteItem(itemId);
      }
    });
  }
```
can be tested as below
```
it('should call api to delete item on confirmation', (done) => {
    component.deleteItem('1004');
    expect(Swal.isVisible()).toBeTruthy();
    expect(Swal.getTitle().textContent).toEqual('Are you sure to delete item?');
    Swal.clickConfirm();
    spyOn(itemService, 'deleteItem').and.returnValue(Observable.of({}));
    setTimeout(() => {
      expect(itemService.deleteItem).toHaveBeenCalledWith('1004');
      done();
    });
  });
```
For more detail https://github.com/prmkishor/sweetAletUnitTesting/wiki/sweetAlert2-Angular-Unit-Testing
