### ISSUE TITLE
Swal with Custom HTML

### ISSUE THREAD

**Issue by Junior1337** [limonte/sweetalert2#578]
In sample code we can found:
`swal({
  title: '<i>HTML</i> <u>example</u>',
  type: 'info',
  html:
    'You can use <b>bold text</b>, ' +
    '<a href="//github.com">links</a> ' +
    'and other HTML tags',
  showCloseButton: true,
  showCancelButton: true,
  confirmButtonText:
    '<i class="fa fa-thumbs-up"></i> Great!',
  cancelButtonText:
    '<i class="fa fa-thumbs-down"></i>'
})`

But the correct use is:
`swal({
  title: '<i>HTML</i> <u>example</u>',
  type: 'info',
  html: true,
  text:
    'You can use <b>bold text</b>, ' +
    '<a href="//github.com">links</a> ' +
    'and other HTML tags',
  showCloseButton: true,
  showCancelButton: true,
  confirmButtonText:
    '<i class="fa fa-thumbs-up"></i> Great!',
  cancelButtonText:
    '<i class="fa fa-thumbs-down"></i>'
})`

**html** need to be **true** and the content is in **text**

**Comment by limonte** [comment]
> html need to be true and the content is in text

This is true for the original SweetAlert plugin: https://github.com/t4t5/sweetalert 

SweetAlert and SweetAlert2 are 2 different projects with slightlhy different API, see the migration guide: https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2

**Comment by KSahithyan** [comment]
But it says html is not in the SwalOptions..?
What should I do now?

I am using sweetalert@2.1.2

**Comment by gverni** [comment]
Hi @KSahithyan I think you are using Sweetalert and not Sweetalert2. The repo for sweetalert is [here](https://github.com/t4t5/sweetalert). You are more than wellcome to move to Sweetalert2 using [this guide](https://github.com/sweetalert2/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2)

**Comment by KSahithyan** [comment]
@gverni Sorry I am using Sweetalert2. But HTML is not in that, that was changed as content..
link :- https://sweetalert.js.org/guides/#upgrading-from-1x

**Comment by gverni** [comment]
@KSahithyan what you are using is Sweetalert version 2.x not Sweetalert2. I know, the names can be confusing, but Sweetalert2 (this repo) is a fork of Sweetalert. If you have problem with Sweetalert you need to use the [other repo](https://github.com/t4t5/sweetalert). Hope this clarify
