### ISSUE TITLE
Maxlenght and other attributes on input?

### ISSUE THREAD

**Issue by Silvester20** [limonte/sweetalert2#58]
First of all thanks for keeping this nice plugin alive!

So I was wondering if you could add a option to give an array of attributes to an input type, so I can add maxlenght to the input field for example.

I am using this:

`	title: 'Test',
              text: 'Enter some text',
	type: "input",
	showCancelButton: true,
	closeOnConfirm: false,
	showLoaderOnConfirm: true
`

**Comment by limonte** [comment]
You can do whatever you want within the `html` parameter:

```
swal({
  title: 'Maxlength', 
  html: '<p><input id="input-field" maxlength="32">'
});
```

**Comment by Silvester20** [comment]
Okay thanks!

**Comment by Cenlan71** [comment]
Thanks to inputAttributes: { }, you could pass any attribute accepted by that input in html

Example: 
`swal({
    title: "{{__('Nueva observación')}}",
    input: 'textarea',
    inputAttributes: {
        maxlength: 200,
    }
})`
