### ISSUE TITLE
Double Click bug?

### ISSUE THREAD

**Issue by gabrielalack** [limonte/sweetalert2#581]
I noticed that if you accidentally double click a button that activates the alert, causing you to click outside the alert screen before it fully loads, the alert window closes but the overlay does not go away, causing your whole app to be effectively disabled.

**Comment by limonte** [comment]
Browser/OS?

**Comment by gabrielalack** [comment]
Happens on both Chrome and Firefox

Mac OS Sierra 10.12.5

Chrome Version 59.0.3071.115 (Official Build) (64-bit)
Firefox 54.0.1 (64-bit)

Swal 6.6.6

**Comment by limonte** [comment]
Can't reproduce, could you please provide the jsfiddle?

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
