### ISSUE TITLE
Can i use it with `vue.js` and `axios`?

### ISSUE THREAD

**Issue by haeyon098** [limonte/sweetalert2#583]
I want to use `seetalert2` with `vue.js` and `axios`.
so, I tired like this.
```javascript
deleteProject(projectCode)
{
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then(function () {
                axios.delete(this.projectApi + '/' + projectCode)
                 .then(res => {
                 this.projectResults = res.data.content;
                 this.totalItems = res.data.totalElements;
                     swal(
                         'Deleted!',
                         'Your file has been deleted.',
                         'success'
                     );
                 })
                 .catch(err => {
                 console.log(err);
                 });
 });
```
#### error
![image](https://user-images.githubusercontent.com/29598014/28453031-4c082810-6e30-11e7-84d7-eb207e7a5a64.png)

But, I have a error code.
I think it doesn't work from `axios` to the end.
Can i use it with `vue.js` and `axios`? How can i use?

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
