### ISSUE TITLE
icon animation not work

### ISSUE THREAD

**Issue by navotera** [limonte/sweetalert2#584]
![image](https://user-images.githubusercontent.com/1424851/28489729-670b3784-6efc-11e7-939a-f583be5c9d83.png)

why animation either error or succes icon not show.... please check the attachment
thanks

**Comment by limonte** [comment]
Browser/OS?

**Comment by navotera** [comment]
Windows 10 and firefox developer edition latest

**Comment by navotera** [comment]
Google chrome too latest version

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by navotera** [comment]
ok i get it it somehow i insert the wrong sweetalert (ver 1) in my html page. sorry.. 

thanks for this awesome library
