### ISSUE TITLE
Sweetalert closes immediately when Enter key is used

### ISSUE THREAD

**Issue by manukaleel** [limonte/sweetalert2#585]
I have an event that triggers when the Enter key is pressed, that triggers the sweet alert to come up. But this closes immediately after opening. But when the same function runs on a mouse click event, then Sweetalert pop up remains open. I think what's happening is, on the Enter key event it immediately detects that the Enter key's been pressed and closes the popup. How can I stop this?

Thanks.

**Comment by limonte** [comment]
Probably you want to take a look on the `allowEnterKey` option.

Otherwise, for bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
