### ISSUE TITLE
Evaluating html in a list

### ISSUE THREAD

**Issue by lippomano** [limonte/sweetalert2#588]
Is it possible to put a list into html?
Something like this: 
```
  <ul>
    <li *ngFor="let hero of heroes">
      {{ hero }}
    </li>
  </ul>
```
I need to show list as the text of the swal, this is what I do:
```
swal({
        title: 'title',
        type: 'error',
        html: '<ul><li *ngFor="let err of messageErr">{{err}}</li></ul>'
      });
```
But It seems that don't evaluate {{ err }} 
![cattura](https://user-images.githubusercontent.com/27501745/28961937-594b8da8-7904-11e7-8a23-7305e627a9a6.PNG)

**Comment by patrickhlauke** [comment]
This is an issue relating to Angular, not SweetAlert. I'd suggest asking on relevant Angular forums/lists.

**Comment by limonte** [comment]
Take a look on the Angular 2+ wrapper for SweetAlert2: https://github.com/toverux/ngsweetalert2 - it's great!
