### ISSUE TITLE
It will not work in Angular v4.3.0 version , please let us know how to resolve this issue

### ISSUE THREAD

**Issue by vittal288** [limonte/sweetalert2#589]

**Comment by vittal288** [comment]
No error in the console

**Comment by patrickhlauke** [comment]
You'd need to be a lot more specific about what "will not work" means in this context. A reduced test case or similar (on jsfiddle, codepen, etc) would help. But more generally, this (how to integrate SweetAlert in whatever you're doing in Angular) is likely something that you should ask in Angular-related forums/lists.

**Comment by limonte** [comment]
Take a look on the great Angular 2+ wrapper for SweetAlert2: https://github.com/toverux/ngsweetalert2

**Comment by toverux** [comment]
@vittal288 Please also check that you've included SweetAlert's CSS somewhere, it's not installed automatically. If you have no JavaScript error, that is likely the problem.
