### ISSUE TITLE
Remove inline styling from buttons

### ISSUE THREAD

**Issue by canfiax** [limonte/sweetalert2#59]
I am using bootstrap, but setting `confirmButtonClass: 'btn btn-primary',` does not change any style.

This is because of some inline styling:

![image](https://cloud.githubusercontent.com/assets/3786627/13507047/2b1016aa-e181-11e5-8161-80c499fadd72.png)

     style="display: inline-block; border-left-color: rgb(48, 133, 214); border-right-color: rgb(48, 133, 214); background-color: rgb(48, 133, 214);"

How can I disable this?

**Comment by limonte** [comment]
Thank you again @canfiax for the another great suggestion!

Done https://github.com/limonte/sweetalert2/releases/tag/v0.4.1

```
  confirmButtonClass: 'btn btn-primary',
  buttonsStyling: false,
```

**Comment by canfiax** [comment]
Thank you again @limonte for another fast response! :+1:

**Comment by kennyhyun** [comment]
How can I disable `buttonsStyling` when I use like...

    swal('Any fool can use a computer')

Is there any global configurations?

**Comment by limonte** [comment]
@kennyhyun 

> How can I disable buttonsStyling

```js
swal({
  text: 'Any fool can use a computer',
  buttonsStyling: false
})
```

> Is there any global configurations?

```js
swal.setDefauls({buttonsStyling: false});
swal('Any fool can use a computer')
```

**Comment by kennyhyun** [comment]
@limonte Cool! Thanks, I should have read the document carefully.
