### ISSUE TITLE
SweetAlert dialog cannot be clicked (is it behind everything else in the DOM???)

### ISSUE THREAD

**Issue by Reechee88** [limonte/sweetalert2#590]
Hey!

I am experiencing a very strange error/behavior. I had used sweetalert with great success in several projects, but in my current project it has something wrong. I have the following, simple code:
`
swal('Hello')
`
The dialog appears and can be seen. But I cannot click on the 'OK' button, neither inside the dialog. I inspect it with debugger and it seems that the dialog is behind the other contents of the page. 

How is it possible? Where should I look for the error? 

Please give me some hints.

Thanks,
Richard

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by andytwoods** [comment]
Hi, I had EXACTLY this issue. It turned out I was not using the most uptodate CSS :)

**Comment by Reechee88** [comment]
You are right. It was a CSS problem. The template style that I am using has overriden the CSS of SweetAlert! Thanks 👍
