### ISSUE TITLE
Syntax errors in stylesheet

### ISSUE THREAD

**Issue by simshaun** [limonte/sweetalert2#591]
https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.scss#L119
`margin-left: 5px 0 15px;`
I assume that is supposed to be `margin`?

https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.scss#L213
`transition: border-color box-shadow .3s;`
Error is: mismatched property value.
I assume that is supposed to be `transition: border-color .3s, box-shadow .3s;`?

**Comment by limonte** [comment]
Thanks for reporting @simshaun !

https://github.com/limonte/sweetalert2/releases/tag/v6.6.7 :rocket:
