### ISSUE TITLE
I can't use it with bulma.io

### ISSUE THREAD

**Issue by ranaclyde** [limonte/sweetalert2#594]
When I run it, it doesn't show it well.

Code:
```
// HTML
<a class="button is-info" @click="prueba">Click me</a>

// JS
import swal from 'sweetalert2'
// basic vuejs structure
prueba () {
      swal('Hello')
}
```
I am use Vuejs 2.3.3 and Bulma 0.5.0

![image](https://user-images.githubusercontent.com/19784573/29173562-11bdcd10-7dba-11e7-9f4d-2ae1b7f66ce4.png)

The red part is sweetAlert 👎 

Some help?

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by toverux** [comment]
@ranaclyde: I presume you haven't included SweetAlert's CSS vendor file. Importing the JavaScript is not enough.
Either use the SASS distribution, or import `sweetalert2/dist/sweetalert2.min.css` like you do with other vendor CSS files.

**Comment by ranaclyde** [comment]
@toverux Thanks for your response. I solved it with [vue-sweetalert Component](https://github.com/limonte/sweetalert2)
