### ISSUE TITLE
swal is not defined

### ISSUE THREAD

**Issue by masterminding** [limonte/sweetalert2#596]
The Menu and Location links are supposed to be Sweet Alerts that aren't working. I keep getting this error: swal is not defined.

**Web Page**
[https://masterminding.github.io/smoothie-queen/](url)

**Github**
[https://github.com/masterminding/smoothie-queen/tree/gh-pages](url)

**Comment by patrickhlauke** [comment]
"Failed to load resource: the server responded with a status of 404 ()"

fix your code first to point to the correct location of the script...
