### ISSUE TITLE
Request: Add on jsDelivr

### ISSUE THREAD

**Issue by zhiru** [limonte/sweetalert2#60]
I use Sweetalert with jsDelivr, but i want to use Sweetalert2, can you add on jsDelivr?

Info of adding: https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

tks.

**Comment by limonte** [comment]
https://github.com/jsdelivr/jsdelivr/pull/10278

**Comment by zhiru** [comment]
Tks! I'm waiting for approval :+1:

**Comment by limonte** [comment]
http://www.jsdelivr.com/projects/sweetalert2
