### ISSUE TITLE
showLoaderOnConfirm issue

### ISSUE THREAD

**Issue by newoutlaw98** [limonte/sweetalert2#600]
Hello,

I'm trying to do the following but the loader icon doesn't show on my button. What am i doing wrong?
Thanks in advance.

	swal({    
	title: 'Send Email?',
        text: 'This will distribute emails ',   
        type: 'question',   
        showCancelButton: true,   
        confirmButtonColor: '#DD6B55',   
        confirmButtonText: 'Send',   
        showLoaderOnConfirm: true
      }).then(function() {
    	  $.post('Email', function(data) {
    		  if (data.pass)
    			  swal('Sent!', 'Emails distributed.', 'success')
    		  else
    			  swal('Error!', 'Emails could not be sent.', 'error') 
    	  	  })
      }).catch(swal.noop)

**Comment by limonte** [comment]
https://limonte.github.io/sweetalert2/#ajax-request

**Comment by newoutlaw98** [comment]
Hello,
Thanks for your response. I have already looked at the examples. However, my question is why doesnt my code work? Is it because i dont have the preconfirm code? In the docs it states its optional? Please provide some useful feedback rather than hyperlink to minimal documentation and just closing the question.

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/commit/f3035c1aa2760774b84072a848f3fc4dd883af9a + https://github.com/limonte/sweetalert2/commit/7e94e84c56803a4c3647dd54264fbec6d78fd024

**Comment by newoutlaw98** [comment]
ok, thanks. So you've pointed me to the documentation which states I must use the preConfirm function in order to use the showLoaderOnConfirm flag. Do you have any documentation on what resolve() is? Do you have docs on what Promise does? Do you docs on why setTimeout is used? Where does the AJAX call go, inside the Promise function? All of this is still unclear to me.
