### ISSUE TITLE
Contributing and conduct guidelines aren't visible when user creating an issue

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#601]
On this page https://github.com/limonte/sweetalert2/issues/new I expect to see the block with links to contributing guide and code of conduct:

![](https://i.imgur.com/mKQJjZi.png)

Example: https://github.com/vuejs/vue/issues/new

Corresponding files are in the repo: https://github.com/limonte/sweetalert2/tree/master/.github 

Anybody has any idea why that block isn't visible for the SweetAlert2 repo?

**Comment by huglester** [comment]
Hello
I see it: http://pic.webas.lt/webas.lt-bd85cd6ba9.png
both links also work

**Comment by toverux** [comment]
Yep - I see that block too, projects owners are probably exempt of such warnings :)

**Comment by limonte** [comment]
> Yep - I see that block too, projects owners are probably exempt of such warnings :)

That makes sense, thanks for the feedback @huglester and @toverux :beers:
