### ISSUE TITLE
Request you to  publish your sweetalert2 package to atmosphere for Meteor audience out there

### ISSUE THREAD

**Issue by abhishekps782** [limonte/sweetalert2#602]
Hi Limonte,
    I would request you to please publish your package to atmosphere for the benefit of the meteor audience out there waiting to use your awesome library.

Thanks

**Comment by limonte** [comment]
It's there, isn't it? https://atmospherejs.com/cleandersonlobo/sweetalert2

**Comment by abhishekps782** [comment]
Thanks for your prompt response.  I am facing this issue - fix Uncaught TypeError: Cannot read property 'removeChild' of null (#512 #487)  which has been fixed with your https://github.com/limonte/sweetalert2/releases/tag/v6.6.1 release. But there is no updated versions or releases for the atmosphere sweetalert2.

**Comment by limonte** [comment]
ping @cleandersonlobo :)

**Comment by abhishekps782** [comment]
pinged him already. waiting for his response !!

**Comment by limonte** [comment]
And also, you can use npm packages in Meteor, take a look on docs: https://guide.meteor.com/atmosphere-vs-npm.html#when-npm

**Comment by abhishekps782** [comment]
I am not on meteor 1.3 or higher version and the workaround is using some other package specifically to install npm packages.

**Comment by cleandersonlobo** [comment]
Upgraded to the latest release(v6.6.9) **;)**

**Comment by limonte** [comment]
Many thanks @cleandersonlobo for publishing the sweetalert2 and keeping it up-to-date! :beers:
