### ISSUE TITLE
get return value of confirmed button ?

### ISSUE THREAD

**Issue by navotera** [limonte/sweetalert2#603]
pardon me to open this as issue but i cannot find in the documentation about this. 
i want to know what  button that user clicked, is there any method to achive this ? 

here my code : 
```
function deleteConfirm(url, id)
{
    

        swal({
          title: 'Anda yakin ingin menghapus ?',
          text: "Data yang dihapus tidak bisa dikembalikan lagi",
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Ya, Hapus'
        }).then(function () {

        return true;
        });
}

//the code below to test the return value not work : 
//this would return undefined
 var confirm = deleteConfirm(url, id);
  console.log(confirm);
```

Thanks u for any suggestion

**Comment by limonte** [comment]
https://limonte.github.io/sweetalert2/#dismiss-handle

**Comment by navotera** [comment]
Is there any method
If(dismiss == "ok")

Because i want to catch if user prefer ok / confirm button not cancel or
like such as overlay and timer

**Comment by limonte** [comment]
> Is there any method
If(dismiss == "ok")

No, sorry.
