### ISSUE TITLE
Warning in console  SweetAlert2: Unknown parameter "closeOnConfirm"

### ISSUE THREAD

**Issue by restubaliantara** [limonte/sweetalert2#605]
i get this warn SweetAlert2: Unknown parameter "closeOnConfirm" in the console. Why ?

**Comment by zenflow** [comment]
@restubaliantara `closeOnConfirm` is not a parameter for sweetalert2. There are a few breaking changes from the original sweetalert package. This should help - https://github.com/limonte/sweetalert2/wiki/Migration-from-SweetAlert-to-SweetAlert2#5-closeonconfirm-and-closeoncancel-parameters-replaced-with-preconfirm
