### ISSUE TITLE
Show two swal at same time

### ISSUE THREAD

**Issue by Igao92** [limonte/sweetalert2#606]
Hello,

Is it possible to display another modal, without close previous Swal?

I have a scenario where my user needs an action, and yet it's the time it's finishing notifying him with another Swal, but this closes the first Swal.

Every help is welcome!

Cheers!

**Comment by limonte** [comment]
Every additional effort to your question is welcome ;)

**Comment by Igao92** [comment]
@limonte please, see:

https://prnt.sc/gegwml

**Comment by toverux** [comment]
Unfortunately, this is not possible for now. The library is designed to handle one alert at a time, and you can notice that evrey `swal.*` function is static (there is no alert instance with instance methods), meaning that there's no chance to display more than one modal.

However, I've always thought it was a good limitation. Alerts are cool, but stacking them is horrible for the UX. I know you probably won't like what I'll say, but maybe you should find a better way to interact with the user :)

(I don't understand the language in your screenshot so I can't recommend another solution, but I'm pretty sure you don't *need* to display two alerts at a time)

**Comment by Igao92** [comment]
I agree with you in parts...

Swal stops being just an "alert" when this supports other features inside it (HTML, AJAX, IMAGES, FORMS, ETC ...)

In my scenario I am using a Swal with confirmation, but at the same time I need to warn my user that their time is running out.

And as it is an "alert" I wanted to keep using Swal. :)

But make sure this will not make me stop using it ... I'll think of a different way of notifying my user.

Thanks for the time!

**Comment by enforb** [comment]
I FIXED IT!

Really easy fix!!!!

In function **init(params)**
`
var c = getContainer();
if (c) {
//            c.parentNode.removeChild(c); //this row must be disabled
}
`

In function **getContainer()** just **':last-child'** selector was added.
`var getContainer = function getContainer() {
        return document.body.querySelector('.' + swalClasses.container + ':last-child');
    };`

That's all... 

Enjoy :)

**Comment by bugfreetech** [comment]
> 
> 
> I FIXED IT!
> 
> Really easy fix!!!!
> 
> In function **init(params)**
> `var c = getContainer(); if (c) { // c.parentNode.removeChild(c); //this row must be disabled }`
> 
> In function **getContainer()** just **':last-child'** selector was added.
> `var getContainer = function getContainer() { return document.body.querySelector('.' + swalClasses.container + ':last-child'); };`
> 
> That's all...
> 
> Enjoy :)

Very promising to begin with, it allowed me an alert plus a toast - HOWEVER once the toast self-destructs everything becomes broken (if more than one toast shows it gets worse and worse)
It is very disappointing that the 'toast' feature couldn't be instanced & behave like actual toast (with stacking)

**Comment by jratiwanich** [comment]
Beside this jQuery fix above, Has anyone found a solution to fix the Alert and Toast running at the same time? I'm running into the same situation where we have a toasting popping up and destroy the alert dialog - especially the Confirmation Dialog that waits for user to interact. In my opinion, the toaster and the alert modal should not be on the same thread.

**Comment by rxliuli** [comment]
Are there any other packages recommended?
