### ISSUE TITLE
`showLoading` modal doesn't stay visible in `then`

### ISSUE THREAD

**Issue by LindaHaviv** [limonte/sweetalert2#609]
The loading state appears for a very short time (noticeable in HTML, but not visible on the screen), and then disappears:

```js
swal("hi").then(() => swal.showLoading())
```

By adding a long enough delay, the loading modal will remain open.

```js
// doesn't work
swal("hi").then(() => setTimeout(() => swal.showLoading(), 42))

// works
swal("hi").then(() => setTimeout(() => swal.showLoading(), 1000))
```

**Comment by limonte** [comment]
These code examples are weird. Why do you want to show loader after closing modal? I don't know your context, but you probably looking  for the `showLoaderOnConfirm` parameter.

**Comment by LindaHaviv** [comment]
@limonte `swal({ title: "hi", showLoaderOnConfirm: true })` doesn't show the loader either. 

I want to show the loading state to show the user that something is going on.

```js
swal("hi").then(() =>  {
  swal.showLoading()
  return doSomethingAsync()
}).then(() => {
  return doSomethingElseAsync()
}).catch(err => {
  swal({ title: "oops", text: err.message, type: "error" })
});
```

**Comment by limonte** [comment]
Take a look on the [AJAX example](https://limonte.github.io/sweetalert2/#ajax-request), also there's `onOpen` parameter you might want to use.

**Comment by FHDumont** [comment]
Hi @LindaHaviv, I have the same problem, did you fix it?
Best regards.
