### ISSUE TITLE
Swal not closing only in IE11.

### ISSUE THREAD

**Issue by VinyP** [limonte/sweetalert2#611]
After clicking ok on a simple SWAL, the box is removed however the background overlay still remains and page remains faded out and unresponsive.
```
swal(
                'ERROR!',
                'Please check email and/or captcha',
                'error'
            ).catch(swal.noop)

```
**See Image**: 
![screen shot 2017-09-07 at 3 25 39 pm](https://user-images.githubusercontent.com/24439307/30216224-21f44c9a-9467-11e7-8a0f-a0c2d75e0d94.png)

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
