### ISSUE TITLE
Inject CSS into JS?

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#612]
Should we get rid of standalone CSS file and inject styles dynamically in JS? If we do so, https://github.com/limonte/sweetalert2/issues/422 will be fixed for free and many users will get a better DX (developer experience).

There's probably some rollup plugin which will help up handle this, but I didn't perform any research on that.

I'd like to hear your opinions and technical suggestions how to implement this in a nice and efficient way. 

cc @toverux @samturrell

**Comment by patrickhlauke** [comment]
Personally, I prefer separation of intent, and the flexibility for custom styling of separating CSS and JS (i.e. authors being able to easily restyle stuff without having to dive into the JS itself)

**Comment by samturrell** [comment]
Agreed, I think it's better to keep these separate. This gives more flexibility for the developer implementing the plugin into their workflow. 

However, that said it may be possible to generate an entirely separate bundle to add this functionality e.g. `sweetalert2.all.js` which includes the css-in-js.

**Comment by limonte** [comment]
> However, that said it may be possible to generate an entirely separate bundle to add this functionality e.g. sweetalert2.all.js which includes the css-in-js.

Sounds like a perfect option :+1:

**Comment by toverux** [comment]
I agree with the arguments above. I've already mentioned the possibility of injecting Swal's style at runtime in a dynamically-created <style> element. But given the profusion and fragmentation in the styling technologies today, a bare CSS file is still the most interoperable technique that can make everyone happy.

If we start injecting the file in the JS, some will be happy, but we'll surely get issues like "can't you just provide a CSS file and let me do what I want with it?"

While the current solution isn't perfect, it will stay the de-facto standard to distribute vendor styles for a while and most developers are aware of that.

So : `sweetalert2.all.js` + docs seems to be a good solution as long as we don't set it as the default entry point (`main`).

To implement that, well, I don't know Rollup but that's what I would do with Webpack :
 - The current bundle stays unchanged and the entry point is `src/sweetalert2.js`
 - Create a new entry point (`src/sweetalert2.all.js`) that exports the API of `src/sweetalert2.js`, and injects the CSS by creating a <style> element, which is the closest thing to a CSS file.
 - That new entry point is compiled in a `sweetalert2.all.min.js` Webpack bundle.
 - Configure Webpack so when the new entry point `import`s the CSS, it imports the file as a string.

I presume this will be very similar with Rollup.

**Comment by limonte** [comment]
Fixed with #644 

KUDOS to drunk ninja master @samturrell :beers:

**Comment by limonte** [comment]
Just update the demo of using SweetAlert2 with Webpack, looks great! https://github.com/limonte/sweetalert2-webpack-demo/commit/d8b2631967654bc4a1af2dfb091e07f17138a645#diff-168726dbe96b3ce427e7fedce31bb0bc


@toverux sorry for probably stupid question, but could you please help me to understand 

> So : sweetalert2.all.js + docs seems to be a good solution as long as we don't set it as the default entry point (main).

why don't we want `all.js` as the default entry point?

**Comment by toverux** [comment]
> why don't we want all.js as the default entry point?

Well, I guess I'm just used to have the control on vendor stylesheets "by default". But as the new solution seems to be easier for most people, and since it's still possible to get the style aside of the JS if needed, I'm not hostile to change that, at all :)

However, I think we should wait for the next major to change it then. Otherwise people will get Swal's styles downloaded and applied two times. Not a _breaking_ change per se, but, erh.

**Comment by limonte** [comment]
> Well, I guess I'm just used to have the control on vendor stylesheets "by default". But as the new solution seems to be easier for most people, and since it's still possible to get the style aside of the JS if needed, I'm not hostile to change that, at all :)

Thanks! :+1: 

> However, I think we should wait for the next major to change it then. Otherwise people will get Swal's styles downloaded and applied two times. Not a breaking change per se, but, erh.

Yeah, that's kinda a breaking change as I understand correctly. So next major it is :+1:

**Comment by toverux** [comment]
> that's kinda a breaking change as I understand correctly

Not in the sense that it wil break or pop errors, but not much better, technically speaking.
(Tagging the issue with _"next major"_ even if it's solved, so we can remember to change that)

**Comment by limonte** [comment]
Perfect, thanks!

**Comment by limonte** [comment]
## The combined JS+CSS version is now default: https://github.com/limonte/sweetalert2/releases/tag/v7.0.0
