### ISSUE TITLE
Suggestion: inputParent option

### ISSUE THREAD

**Issue by mnavarrocarter** [limonte/sweetalert2#613]
Hey!

I was just thinking that would be really cool to have a feature that allows to create an input parent option, so we can wrap inputs into another element. This because some frameworks like Bulma do that with some form elements, like select. So, for example:

```
input: 'select',
inputParent: 'div',
inputParentClass: 'select',
```

That would return:

```
<div class="select">
    <select></select>
</div>
```

How about that?

**Comment by toverux** [comment]
Hi @mnavarrocarter, for this you can use the `html` option to set custom HTML with you styled input. Then, use `preConfirm` to get the inputs' values.

See an example here : https://github.com/limonte/sweetalert2/issues/394#issuecomment-270404166

We can't add options for every use case, or we'll end up creating a whole wrapper around the DOM ;)
The existing options intend to provide support for most use cases. You're already in an "advanced usage" scenario.
