### ISSUE TITLE
Stop reset form value

### ISSUE THREAD

**Issue by vishalsingh119** [limonte/sweetalert2#616]
I am using sweetalert for form reset btn, but when popup trigger it clear all form data. i want when user click on yes thenonly clear the form.

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
