### ISSUE TITLE
Ok and Cancel buttons inverted positions

### ISSUE THREAD

**Issue by DieguitoBueno** [limonte/sweetalert2#62]
Hello friends,

How do I invert the default position of the buttons ?
I want the OK button to be at the RIGHT side.

Thanks!

**Comment by limonte** [comment]
Nice request @DieguitoBueno !

Done https://github.com/limonte/sweetalert2/releases/tag/v0.4.2

Use `reverseButtons` parameter, set it to `true` to swap buttons.

**Comment by DieguitoBueno** [comment]
Thanks, @limonte  !! Great job :+1:

**Comment by KevinPan** [comment]
This doesn't work in the latest release

**Comment by limonte** [comment]
> This doesn't work in the latest release

That's not true.
