### ISSUE TITLE
The alert appears embedded on the page's foot

### ISSUE THREAD

**Issue by andrescrovetto** [limonte/sweetalert2#623]
<img width="626" alt="captura de pantalla 2017-09-17 a la s 10 42 52" src="https://user-images.githubusercontent.com/20328832/30521413-c6bff500-9b95-11e7-84c0-7c85daf4fd90.png">

**Comment by toverux** [comment]
Hi @andrescrovetto,

You also have to include SweetAlert's CSS file. Since you're using Angular, here's a little help: https://github.com/toverux/ngsweetalert2/issues/22#issuecomment-329462497

**Comment by limonte** [comment]
We recently released v6.10.0 which contains all-in-one version with JS and CSS in one place.

You can import it this way:

```
import swal from 'sweetalert2/dist/sweetalert2.all.min.js'
```

PS. In the next major version (v7.0.0) the combined JS + CSS version sweetalert2.all.min.js will be the default entry point and it will be possible to import it as usual: `import swal from 'sweetalert2'`
