### ISSUE TITLE
Trouble using 'input' parameter in Angular2

### ISSUE THREAD

**Issue by borkjt9** [limonte/sweetalert2#624]
Hi,

I am having trouble with implementing a simple swal in Angular2. My version of sweetalert2 is 6.6.8. When I write the following code: 
`  onEditDescription(): void {
    const modal_option = {
      title: 'Edit Description',
      input: 'textarea',
      showCloseButton: true,
      showCancelButton: true,
      confirmButtonText: 'Save',
      cancelButtonText: 'Cancel'
    };
    swal(modal_option).then(
      (text) => { this.basket.basketDescription = text; },
      (dismiss) => {}
    );
  }`, 

I get the following error: Argument of type '{ title: string; input: string; showCloseButton: boolean; showCancelButton: boolean; confirmButto...' is not assignable to parameter of type 'SweetAlertOptions'.
  Types of property 'input' are incompatible.
    Type 'string' is not assignable to type 'SweetAlertInputType'.

Any help would be appreciated. Thanks in advance!

**Comment by toverux** [comment]
Hm, however `SweetAlertInputType` is a union type of strings, that includes `"textarea"`. What version of TypeScript do you use?

To workaround the problem until this is solved, you can still do : `swal({ ...yourOptions } as any)` to disable the type checking on the options ;)

**Comment by limonte** [comment]
For Angular2+ projects I highly recommend to use https://github.com/toverux/ngsweetalert2

**Comment by toverux** [comment]
@limonte This could be a problem with [sweetalert2.d.ts](https://github.com/limonte/sweetalert2/blob/master/sweetalert2.d.ts), TypeScript doesn't like when @borkjt9 passes `{ input: 'textarea' }` in the options, but I can't understand why it wouldn't (very outdated TS version maybe ?).
