### ISSUE TITLE
angular component as swal.html

### ISSUE THREAD

**Issue by shayts** [limonte/sweetalert2#625]
I have an angular project which works fine with sweetalert/swal.

I need to add an angular component to the swal.
something like this:
swal({
            title: "some title",
            html: '<app-datetime-range-picker></app-datetime-range-picker>',
            type: "info",
            allowOutsideClick: false,
            allowEscapeKey: false,
        });

but of course it's not working because  <app-datetime-range-picker> is not an html attribute/tag.

any way to accomplish that?

**Comment by limonte** [comment]
For Angular2+ projects I highly recommend to use https://github.com/toverux/ngsweetalert2

**Comment by tavuntu** [comment]
@limonte that plugins seems awesome, thanks for the info.
