### ISSUE TITLE
Overlay not closing in IE11 when using Angular 2

### ISSUE THREAD

**Issue by Trevald** [limonte/sweetalert2#626]
**Plunkr that reproduces the problem:**
[http://plnkr.co/edit/annOPVlyddeqWoH3VdcQ?p=preview](http://plnkr.co/edit/annOPVlyddeqWoH3VdcQ?p=preview)

**Expected behavior:**
When closing the modal by clicking "Ok" the overlay should be removed.

**Actual behavior:**
In IE 11 the overlay is not removed. Works fine in Chrome and FF though.

**Comment by limonte** [comment]
@toverux do you maybe have time to take a look on this issue?

**Comment by Trevald** [comment]
I updated the plunker to read from a local SweetAlert and added som logging. I it seems like the callback for the animationEndEvent-listener never is called. If i skip to the else-part it closes the overlay.

`// If animation is supported, animate
  if (animationEndEvent && !hasClass(modal, swalClasses.noanimation)) {
    console.log('Animation supported', modal); // <-- Everything is fine here
    modal.addEventListener(animationEndEvent, function swalCloseEventFinished() {
      console.log('Animation done!', modal); // <-- Never get here
      modal.removeEventListener(animationEndEvent, swalCloseEventFinished);
      console.log('removeModalAndResetState');
      if (hasClass(modal, swalClasses.hide)) {
        removeModalAndResetState();
      }
});`

The animationEndEvent is "MSAnimationEnd" but if I change that to non-prefixed "animationend". It works! Maybe NG is hijacking the animation events. 

Lol, noticed now that I read _toverux_ as _trevald_. Did someone say egocentric?

**Comment by limonte** [comment]
Thanks a lot @Trevald for the valuable feedback!

We don't actually need `MSAnimationEnd`, proof: http://jsfiddle.net/xTxBe/143/

@Trevald con you confirm the jsfiddle above works as expected in IE?

**Comment by Trevald** [comment]
It works the same in IE11 as in Chrome:
- I click element.
- It spinns 360deg
- Standard JS alert showing the text "animationend"

3 days from report to solution, open-source at it's best. Thanks for the quick replies.

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/releases/tag/v6.9.1 :tada:

**Comment by limonte** [comment]
@Trevald could you please let me know if `v6.9.1` works fine in IE11, thanks in advance!

**Comment by Trevald** [comment]
Updated Plunkr to use 6.9.1 from CDN instead of local version. And it works as expected in IE11, animation and all.

**Comment by limonte** [comment]
Thanks!
