### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by hiphigi** [limonte/sweetalert2#627]
Can't get any SWAL2 objects to register in IE 8 - 11 .

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by limonte** [comment]
This issue was debugged in https://github.com/limonte/sweetalert2/issues/626 and fixed in [v6.9.1](https://github.com/limonte/sweetalert2/releases/tag/v6.9.1)

**Comment by limonte** [comment]
@hiphigi  could you please let me know if `v6.9.1` works fine in IE11, thanks in advance!
