### ISSUE TITLE
sweetalert css not used

### ISSUE THREAD

**Issue by k9yosh** [limonte/sweetalert2#628]
I'm using sweetalert in a vue js app. And i'm using this by importing via typescript  `import swal from 'sweetalert2'`. This works for sweetalert 1, but not sweetalert 2. It's being replaced by Semantic UI css. 

![capture](https://user-images.githubusercontent.com/10962954/30678216-4eec5bce-9eae-11e7-93f6-7daf6b605bad.PNG)

**Comment by Martinnord** [comment]
How did you fix this issue?

**Comment by limonte** [comment]
We recently released v6.10.0 which contains all-in-one version with JS and CSS in one place.

You can import it this way:

```
import swal from 'sweetalert2/dist/sweetalert2.all.min.js'
```

PS. In the next major version (v7.0.0) the combined JS + CSS version sweetalert2.all.min.js will be the default entry point and it will be possible to import it as usual: `import swal from 'sweetalert2'`

**Comment by k9yosh** [comment]
@Martinnord I could not find a fix. I moved to another alert library. But seems like they fixed it.

**Comment by k9yosh** [comment]
@limonte Thanks, i'll try it this way :)

**Comment by k9yosh** [comment]
@limonte I tried the new release v6.11.4 but still, no progress. I tried the new release in following ways:

1. Loading sweetalert2 via typescript using import swal from 'sweetalert2/dist/sweetalert2.all.js'.
2. Removing all other css files and keeping just this.
3. Loading sweetalert2 from html file using <script> tag. (CDN sweetalert2.all.js v6.11.4)

Styles do not get loaded at all. Only the external css files are loaded. But the Javascript works without any issues. Only the styles are ignored. You can replicate this issue following this small tutorial. But instead of using sweetalert, use sweetalert2. Tutorial works just fine with sweetalert, 

You might be able to replicate the issue within 20 mins : [Vue Tutorial](https://scotch.io/tutorials/build-a-to-do-app-with-vue-js-2)

**Comment by toverux** [comment]
That's strange. I mean, there's no reason for the styles for not applying as soon as they're loaded. We don't use any bizarre technique, just plain CSS. It may be a framework-specific problem (styles encapsulation maybe? But usually frameworks don't mind about global styles). Would you please send us a plunkr/jsfiddle link so we can actually see what's going on?

**Comment by limonte** [comment]
Let's reopen this and investigate the issue.

**Comment by davikawasaki** [comment]
@k9yosh I had the same problem in my VueJS project and it was solved importing sweetalert2.all.min.js:

![screenshot from 2017-11-05 13-21-51](https://user-images.githubusercontent.com/12398127/32416178-66682278-c22c-11e7-90f7-990280abfa1f.png)

How your styles are being generated? Maybe I'm wrong, but perhaps your project builder can't find sweetalert2 styles while building 'semantic.min.css' - webpack in my case works like a charm for style injection.

**Comment by k9yosh** [comment]
@limonte @davikawasaki @toverux I found the issue. It's my mistake actually. I had some pages that load sweetalert that I did not remove. I didn't remove 'em because I just wanted to test and see whether sweetalert2 will work just fine. So actually, the javascript that worked wasn't sweetalert2.all.js. It was the sweetalert.js. Although the sweetalert2 script got loaded, it's being overridden by the sweetalert script. I completely forgot that I had used sweetalert in other pages. Sorry guys for the trouble. 

But there's this one thing that keeps bugging me. It was there from the beginning... I still get this issue [params.html.cloneNode is not a function](https://github.com/limonte/sweetalert2/issues/631)

**Comment by limonte** [comment]
Thanks @k9yosh for the detailed report! I'll close this issue and reopen the one you mentioned.

Have a good working week!

**Comment by k9yosh** [comment]
@limonte Appreciate your great support. Keep up the good work. And you have a great week too :)

**Comment by juanvictorbascopecastro** [comment]
I deleted the node modules and ran npm i again, and everything worked normal
