### ISSUE TITLE
multiple fields and focus - on iPad

### ISSUE THREAD

**Issue by xalexbo** [limonte/sweetalert2#629]
Hi, I wrote down the code published some time ago about managing multiple fields to use it as interface to let user input username and password. 
I'm using iPad iOS v.10.3.3 and sweetalert2 is the latest version available.
swal2 is shown when the user clicks a button but no field is focused.
My purpose is when swal is shown to put focus automatically on the first empty field; when both fields are completed I wanted to submit passing both values to another function or redirect.
Is this possible or iOS doesn't allow it?
Thanks for any help.

**Comment by xalexbo** [comment]
I forgot to mention original source: 
https://github.com/limonte/sweetalert2/issues/451

**Comment by limonte** [comment]
Hi @xalexbo and thanks for the good question! Most probably you're looking for the `focusConfirm` parameter which was added in the latest version (https://github.com/limonte/sweetalert2/releases/tag/v6.9.0). It's `true` by default and if you set it to `false`, the first element in tab order inside the modal will be focused.

You can try it with your mobile device: https://limonte.github.io/sweetalert2/#multiple-inputs

The first input should be focused if `focusConfirm` is `false`

**Comment by xalexbo** [comment]
Well, a very good clue: it was just what I was looking for.
Thanks Limon!

**Comment by limonte** [comment]
You're welcome! Thanks for using SweetAlert2!
