### ISSUE TITLE
A way to set global defaults

### ISSUE THREAD

**Issue by canfiax** [limonte/sweetalert2#63]
It would be cool with a way that you could specific defaults for all alerts. For instance, I need to change the default text of the cancelButton to something else, because I'm currently localizing my project. Or maybe I'd like to put a default class to the alerts, without having to specify this class on all alerts.

In other plugins, such as Dropzone.js, they have a built in way to define some globals (illustrated here as well: http://www.dropzonejs.com/#events)

Here you can specify Dropzone like this:

    var myDropzone = new Dropzone("div#myId", { url: "/file/post", autoDiscover: false});

Now, if you'd like to turn `autoDiscover` off by default, on all `Dropzone` elements, you can simply set below variable:

    Dropzone.autoDiscover = false;

So now below code will work as well, having autodiscover off:

    var myDropzone = new Dropzone("div#myId", { url: "/file/post"});

If I wish to override the default setting, i.e. set autoDiscover to true again on a specific element, I can simply do:

    var myDropzone = new Dropzone("div#myId", { url: "/file/post", autoDiscover: true});

Makes sense?

**Comment by limonte** [comment]
@canfiax if I understand your request correctly, you're looking for [swal.setDefaults()](https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.js#L554)

**Comment by canfiax** [comment]
Exactly. Thanks!

**Comment by limonte** [comment]
@canfiax great! :) I added missing note about that function to docs: https://github.com/limonte/sweetalert2/commit/2454f6947598d6024a0a6da48959ca36e08f645f

**Comment by canfiax** [comment]
Yeah I saw that @limonte great!
