### ISSUE TITLE
Issues calling service after submission w/ Angular 2

### ISSUE THREAD

**Issue by m1xf1t** [limonte/sweetalert2#630]
Hi there,

I'm using Angular 2 w/ SweetAlert2.

> swal({
      title: 'Message All Models',
      input: 'textarea',
      inputPlaceholder: 'Type your message here',
      showCancelButton: true
    }).then(function() {
      this.modelService.messageModels()
    }, function(dismiss) {
      console.log('Dismissed')
 });

**PROBLEM:**
> I'm able to run this service outside of the swal() but for some reason when I run after the then() I get the following error:

**ERROR:**
>ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'modelService' of undefined
TypeError: Cannot read property 'modelService' of undefined
    at model-list.component.ts:174 - [ this is where service is called ]

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by m1xf1t** [comment]
Understood! Will do.

**Comment by toverux** [comment]
This is not a bug, this is a misuse of the language :smile: 

@m1xf1t: replace :

```typescript
.then(function() {
  this.modelService.messageModels()
})
```

with :

```typescript
.then(() => {
  this.modelService.messageModels()
})

// shortest :
.then(() => this.modelService.messageModels())
```

That should work.
The arrow function expression will bind the current context of `this` to the anonymous function being created. Using `function`, the scope of `this` is volatile and determined at the call site (inside SweetAlert).

I suggest you to read one of the articles here: https://www.google.fr/search?q=this+context+javascript&oq=this+context+&aqs=chrome.1.69i57j0l5.2632j0j7&sourceid=chrome&ie=UTF-8 (sorry for the Google link, no offense, I just don't know what article to choose).

**Comment by m1xf1t** [comment]
Thank you @toverux!

**Comment by Abhilash-k-p** [comment]
x

**Comment by FabianMontoya** [comment]
This saved me in a project haha, I didn't understand why I got the error `TypeError: Cannot read property '$swal' of undefined` thanks @toverux .
