### ISSUE TITLE
params.html.cloneNode is not a function

### ISSUE THREAD

**Issue by k9yosh** [limonte/sweetalert2#631]
When i use sweetalert using `import swal from 'sweetalert'` it's working fine. But when i try to use the same for sweetalert2 as `import swal from 'sweetalert2'` it gives me the following error.

```
Uncaught TypeError: params.html.cloneNode is not a function                              sweetalert2.js?85ed:624 
    at setParameters (sweetalert2.js?85ed:624)
    at sweetAlert (sweetalert2.js?85ed:946)
    at VueComponent.openForm (CreateTodo.vue?603e:45)
    at boundFn (vue.esm.js?65d7:179)
    at HTMLButtonElement.invoker (vue.esm.js?65d7:1821)
setParameters @ sweetalert2.js?85ed:624
sweetAlert @ sweetalert2.js?85ed:946
openForm @ CreateTodo.vue?603e:45
boundFn @ vue.esm.js?65d7:179
invoker @ vue.esm.js?65d7:1821
```

Then i tried removing the module import and explicitly setting up the css and js in my html file, then sweetalert2.css is ignored. It's overriden by another css. And when i add sweetalert.css, it is working fine. I tried changing the order of css files, but nothing happens.

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by k9yosh** [comment]
@limonte i'm sorry but i'm new to vue.js, so i don't have much of an idea on how to replicate the issue in a jsfiddle. I get this error only for sweetalert2. I use a webpack based project with npm. I tried importing sweetalert from CDN, importing it as ES6 module. Both gives the same error. But i can use sweetalert without a problem. Error directly points sweetalert2.js line 624. Am i missing some dependency? Cuz it says params.html.cloneNode is not a function.

**Comment by limonte** [comment]
show us at least usage case of calling `swal({...})`

**Comment by k9yosh** [comment]
This is my script where i use sweetalert2 ([Test Script](https://jsfiddle.net/k9yosh/xmdu94u0/)).

**Comment by k9yosh** [comment]
[UPDATE] : loading this from CDN using <script> tag resolves this. I loaded both js and css files from CDN and commented the `import swal from 'sweetalert2'`. But when i do that, the sweetalert2.css doesnt get applied. It's just ignored. 

![capture](https://user-images.githubusercontent.com/10962954/30798487-7f11e458-a1f7-11e7-82f6-de14f5d768fa.PNG)

**Comment by k9yosh** [comment]
This is the error I get... I have no idea about the cause of this issue. Am I missing any dependencies?
![capture1](https://user-images.githubusercontent.com/10962954/32425831-10de1f0a-c2dc-11e7-970a-047b97ae8e5a.PNG)

This is my script. I just use a sweetalert here in my opernForm() method. 
![capture2](https://user-images.githubusercontent.com/10962954/32425855-4dc2e068-c2dc-11e7-9a97-971b6a95dd8d.PNG)

**Comment by limonte** [comment]
You're using the code example from https://sweetalert.js.org/ which is a different project. The author of that project is careless about its users, that's why I made SweetAlert2.

SweetAlert:
- https://github.com/t4t5/sweetalert/
- https://sweetalert.js.org/

SweetAlert2:
- https://github.com/limonte/sweetalert2/
- https://limonte.github.io/sweetalert2/
