### ISSUE TITLE
Bug: document scroll is active in Safari

### ISSUE THREAD

**Issue by Zerebokep** [limonte/sweetalert2#632]
title

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
