### ISSUE TITLE
Feature Request: Add param to disable auto focus

### ISSUE THREAD

**Issue by Zerebokep** [limonte/sweetalert2#633]
title

**Comment by limonte** [comment]
```js
onOpen: () => document.activeElement.blur()
```

https://jsfiddle.net/ad3quksn/124/

**Comment by Zerebokep** [comment]
It seems this workaround doesn't work anymore after updating from 6.9.0 to the current version. I used it with setDefaults.

Also $(this) seems to be undefined inside onOpen.
