### ISSUE TITLE
Overlay stick into the dom on IE11

### ISSUE THREAD

**Issue by KhaledSMQ** [limonte/sweetalert2#635]
I am using sweetalert2 with angular 4 application there is problem on IE11 but didn't show on chrome or Edge or firefox,
the overlay div didn't removed from DOM  after the dialog closed. any idea ?
i have tried to add 
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
but didn't work also i tried to add into my polyfills.ts
 import 'core-js/es6/promise';
but didn't solve the problem.

is it a bug or something missing in my code.

**Comment by toverux** [comment]
Hi @KhaledSMQ,

Please upgrade to the latest version, i.e [v.6.9.1](https://github.com/limonte/sweetalert2/releases/tag/v6.9.1). It contains a bug fix for that problem.

**Comment by KhaledSMQ** [comment]
Thanks bro 👍

**Comment by limonte** [comment]
@KhaledSMQ could you please let me know if `v6.9.1` works fine in IE11, thanks in advance!

**Comment by KhaledSMQ** [comment]
@limonte works fine 💯
