### ISSUE TITLE
Component as html content

### ISSUE THREAD

**Issue by hosseinsalemi** [limonte/sweetalert2#637]
How can I use component as html content like this?

`swal(<AnyComponent/>)`

**Comment by zenflow** [comment]
Is this a React component?

**Comment by hosseinsalemi** [comment]
Yes, `AnyComponent` is a React component.

**Comment by limonte** [comment]
>If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
