### ISSUE TITLE
ReferenceError: text is not defined

### ISSUE THREAD

**Issue by xalexbo** [limonte/sweetalert2#638]
Hi, got this problem: if there is a input element in swal, then I get back the error in subject.
swal is raised only if "input: text" is commented.
It's the first time I see this: probably I am still missing something.
This is the code:

<link href="/dist/sweetalert2.css" rel="stylesheet" type="text/css">
<script src="/dist/sweetalert2.min.js"></script>
<script src="/js/jquery.min.js"></script>
<tr><td colspan='3' align='center'><table><tr>			
	<td align='left'><button id='scanbutton' onclick='click2Scan();'>CLICK HERE</button></td>
	</table></tr>
<script language="javascript">
	function click2Scan() {
		swal({
		  title: 'read code',
		  input: text,
		  focusConfirm: false,
		  showCancelButton: true,
		  cancelButtonText: 'CANCEL',
		  confirmButtonText: 'OK',
		  background: '#e0e4e4',
		  color: '#d0d000',
		  reverseButtons: true,
		  showLoaderOnConfirm: true,
		  allowOutsideClick: false,
		  preConfirm: function (test) {
		    return new Promise(function (resolve, reject) {
		          resolve()
		    })
		  },
		  onOpen: function () {
		  	$('#swal-input1').focus();
		},
		  
		}).then(function (confirm) {
		    },
			function dismiss() {
			}
		)
 	};
</script>

Sweetalert is the latest available.
Please help!

**Comment by limonte** [comment]
`text` => `'text'`
