### ISSUE TITLE
change progressSteps color?

### ISSUE THREAD

**Issue by LuisDiazUgena** [limonte/sweetalert2#639]
Hi!

Is there any option to change the progressSteps color property? I've been looking at the methos at github, and I can not find one.

I'm using a color scheme for a site and it will be a lovely addition.

Thanks.

**Comment by limonte** [comment]
Theming of different parts will be fixed properly in the next major. For now, you can use something like this: https://jsfiddle.net/ad3quksn/129/

**Comment by LuisDiazUgena** [comment]
Thanks!
