### ISSUE TITLE
Issue when using setDefaults

### ISSUE THREAD

**Issue by canfiax** [limonte/sweetalert2#64]
I have set defaults like this:

	swal.setDefaults({
		cancelButtonText: 'Close',
		confirmButtonClass: 'btn btn-primary',
		cancelButtonClass: 'btn btn-secondary',
		buttonsStyling: false
	});

But when I call:

		swal({
			title: 'Some message',
			type: 'success',
			timer: timeout,
			showConfirmButton: false,
			showCancelButton: false,
			cancelButtonText: null,
			confirmButtonClass: null,
			cancelButtonClass: null,
		});

The confirm and cancel buttons are still shown

**Comment by limonte** [comment]
Fixed in https://github.com/limonte/sweetalert2/releases/tag/v0.4.3

Your reports are very useful! 

swal2 celebrates 200 commits! :cake:
