### ISSUE TITLE
onChange option for select input

### ISSUE THREAD

**Issue by f18nfz** [limonte/sweetalert2#641]
I'm using a sweetalert with input: 'select', and want to run the function when the user changes the select option rather than hits OK (i.e. run the function onChange). How can I do this with SweetAlert ...I couldn't see something like onChange that I can use?
(I can see for text boxes I could use onOpen and getInput but what about for changing select options?...)

I want to execute the function onChange....How can I do this?

**Comment by f18nfz** [comment]
Ah silly me, I'll close this myself. I can just use the onOpen and getInput to detect the change in select option. There's no need for an onChange here!

**Comment by yakovcohen4** [comment]
Can you demonstrate with a short code snippet? @f18nfz

**Comment by limonte** [comment]
```js
Swal.fire({
  ...
  didOpen: () => {
    Swal.getInput().addEventListener('change', (event) => {
      console.log(event)
    })
  },
})
```

**Comment by yakovcohen4** [comment]
I don't find this method in the [documentation](https://sweetalert2.github.io/)
