### ISSUE TITLE
Safari 8 on Yosemite

### ISSUE THREAD

**Issue by ChristianLJ** [limonte/sweetalert2#642]
Hi there!

I am using this plugin and testing up against Safari 8 on Yosemite.

Unfortunately the dialog does not close when clicking the close icon.

I am not using any polyfills. Is it necessary for Safari 8?

My code look as follows:
```typescript
swal({
    title: '<b>TITLE</b>',
    html: Templates.variantTemplate(variants),
    showCloseButton: true,
    showCancelButton: false,
    confirmButtonText: "TEXT",
    }).then(function () {
            console.log(1);
});
```

The weird thing is that the console.log(1) prints as expected, the dialog does just not close.
Thank you.

**Comment by limonte** [comment]
Hi @ChristianLJ and thanks for reporting! 

Could you please help me with debugging by trying this snippet with Safari 8 and show me the result in the console: http://jsfiddle.net/xTxBe/145/

**Comment by ChristianLJ** [comment]
Hi @limonte 

I've attached a screenshot from the console after clicking both elements twice.

![image](https://user-images.githubusercontent.com/3056379/31114190-2a69f428-a81d-11e7-846a-5a3165490c50.png)

**Comment by limonte** [comment]
Thank you @ChristianLJ !

So, the `webkitAnimationEnd` is fired. Weird issue. I will try to find Yosemite with Safari 8 to debug this.

If someone is able to debug this and send a PR or just point to the problematic line, please do so. Thanks in advance!

**Comment by ChristianLJ** [comment]
I made two codepens, one which works in Safari 8 on Yosemite and one which doesn't.
I don't know if this is useful but maybe you can help me narrow down the differences and i can continue testing.
**The one that works:**
https://codepen.io/ChristianLJ/pen/gGGooL

**The one that doesn't:**
https://codepen.io/ChristianLJ/pen/YrrYvw

**Comment by ChristianLJ** [comment]
So @limonte, i tried something else. 

When using the script, sweetalert2.all.min.js as standalone it doesn't work in Safari 8 on Yosemite.
By adding a link to the stylesheet, sweetalert2.css, it works.

Maybe this information is useful.

**Comment by limonte** [comment]
Thanks a lot for the feedback @ChristianLJ 

I believe those who are looking for Safari 8 support can use this workaround.
