### ISSUE TITLE
Change min-height of modal

### ISSUE THREAD

**Issue by smachs** [limonte/sweetalert2#643]
Hi, i am try to change `min-height` after modal rendered; I already tried the function `height: 200,` and through custom class using `customClass: 'reciept-print-modal',` without success...

Is there any way to change the height of `swal({ });`?

**Comment by limonte** [comment]
Are you asking about setting `height` or `min-height`?

**Comment by smachs** [comment]
@limonte about `min-height` ckeck my problem

![selecao_001](https://user-images.githubusercontent.com/6456734/31027152-915a4a44-a51f-11e7-969d-2761e4dd75ad.png)
![selecao_002](https://user-images.githubusercontent.com/6456734/31027169-9beb4d1e-a51f-11e7-8b53-81e4f301addd.png)

I'm trying to change by css but without success
`.sweet-alert {
    height: 491px;
    margin-bottom: 5%;
    padding: 20px 20px 0px 20px;
}`

**Comment by limonte** [comment]
> `.sweet-alert`

why don't you inspect the modal for the correct class-name? :) It's `.swal2-modal`, here's the example of setting `min-height`: https://jsfiddle.net/ad3quksn/130/
