### ISSUE TITLE
Outside click on warning message makes action

### ISSUE THREAD

**Issue by believer-ufa** [limonte/sweetalert2#65]
In this example (from docs):

```js
swal({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!',
  closeOnConfirm: false
},
function() {
  swal(
    'Deleted!',
    'Your file has been deleted.',
    'success'
  );
})
```

If you click in outside, delete action will be performed. I think, clicking in outside must just close popup message.

**Comment by limonte** [comment]
Thanks @believer-ufa  for reporting this issue! It's related to https://github.com/limonte/sweetalert2/issues/56

Outside click now triggers callback function, 

`isConfirm` in callback function will be:
- `true` if OK button was clicked
- `false` if Cancel button was clicked
- `undefined` in case of outside click.

I fixed examples in documention.

**Comment by believer-ufa** [comment]
Many thanks, it's really nice library)
