### ISSUE TITLE
placeholder get focus by default

### ISSUE THREAD

**Issue by Orh1989** [limonte/sweetalert2#652]
Hi,
I use sweetAlert2 with input text , with a placeholder - 
but by default, when the alert is pop - the input get focus so the placeholder don't do his job..
When I clicked on the title for example, the placeholder text shown..

Any solution or idea?
my code is:

swal({
title: 'Title?',
type: 'question',
showCancelButton: true,
confirmButtonText: 'Yes',
cancelButtobText: 'No',
input: 'text,
inputPlaceHolder: 'my place holder'
}). then(function(val){
//code..
})

Thanks alot

**Comment by limonte** [comment]
IE11, I guess?

**Comment by limonte** [comment]
https://stackoverflow.com/a/16138480/1331425

**Comment by Orh1989** [comment]
Yep. I have no another option except IE11 (because I work with closed company network)

- I Injected the core.js already
