### ISSUE TITLE
Add css class to modal dialog which denotes if cancel button is displayed.

### ISSUE THREAD

**Issue by TheCelavi** [limonte/sweetalert2#653]
Trivial issue:

- We have a layouts that uses sweet alert for confirm dialogs (only CONFIRM button) and question dialogs (both CONFIRM and CANCEL button)
- Our designer wants to have 100% width button - if it is a single button, or 50% width if there are two buttons.

It would be convenient for customization if div.swal2-buttonswrapper has additional class if both buttons are visible - that would ease up our development and maintenance since we  can use Swal in our project with minimal configuration.

THX!

**Comment by toverux** [comment]
It's doable with flexbox ([basic jsfiddle example](https://jsfiddle.net/u03azjwa/1/)), if that's an option for you. SweetAlert2 supports IE11 at best, [which has partial support](http://caniuse.com/#feat=flexbox) of the flexbox model. But as having two buttons filling an horizontal space is a simple, basic use case of flexbox, I think it could work in IE (can't test it easily as I'm on Linux) :)

**Comment by limonte** [comment]
@toverux Nice fiddle! I think the `display` property for the `buttonswrapper` should be changed from `block` to `flex`  in the next major release, what do you think?

**Comment by limonte** [comment]
btw, @TheCelavi there's a handy `swal.getButtonsWrapper()` which will allow you to depend on our API instead of internal class-names. It was undocumented until now, I just added the missing documentaion https://github.com/limonte/sweetalert2/commit/be80a18fe23ec3eb46a77dbdfd74327245fcd31a

**Comment by toverux** [comment]
@limonte Absolutely no objection on embracing flexbox! - as long as IE compat is preserved (until that day we'll happily drop it)

**Comment by TheCelavi** [comment]
You make me love open source even more:-)

Thanks guys!
