### ISSUE TITLE
Bug in chaining

### ISSUE THREAD

**Issue by ibrahimBeladi** [limonte/sweetalert2#655]
I found a bug in chaining modals, for example, if you have two modals one for username modal chained with password modal and you entered the username and then pressed enter (not clicking the button), the event will be sent to both modals and hence the enter will be pressed for the second modal making it work in a mistaken behaviour. It is also happening in the example, check it out here too.
[Chaining modals (queue) example](https://limonte.github.io/sweetalert2/#chaining-modals)

**Comment by limonte** [comment]
Thanks for reporting @ibrahimBeladi! Which browser and OS are you using?

**Comment by ibrahimBeladi** [comment]
OS: Linux Zorin
Bug in Firefox 56.0 (64-bit) (Ubuntu)
Fine in Chromium (Version 61.0.3163.100 (Official Build) Built on Ubuntu , running on Zorin 12 (64-bit))

**Comment by limonte** [comment]
I can't reproduce the issue with the same configuration (Linux/Firefox). Probably you just holding Enter for too long :) As a solution for this you can use `allowEnterKey: false`, here's the live demo: https://jsfiddle.net/ad3quksn/132/

PS in real-life cases there should be validators preventing submitting empty input values.

**Comment by ibrahimBeladi** [comment]
I am not holding Enter for too long for sure. In Chromium it doesn't happen unless I really hold Enter. But in Firefox it happens even with the fastest presses.

**Comment by limonte** [comment]
Many thanks for the clarification! I just released https://github.com/limonte/sweetalert2/releases/tag/v6.10.2 take another look on https://limonte.github.io/sweetalert2/#chaining-modals, the reported issue should be fixed :+1:

**Comment by limonte** [comment]
@ibrahimBeladi could you please confirm if the issue is fixed in Linux Zorin/Firefox, thanks!

**Comment by ibrahimBeladi** [comment]
Oh I forgot to tell you since the issue is closed. It is working properly, thank you for your effort.

**Comment by limonte** [comment]
Awesome, thank you!
