### ISSUE TITLE
Swal keeps appearing in the bottom of my webpage.

### ISSUE THREAD

**Issue by Martinnord** [limonte/sweetalert2#659]
Hello! Great work with sweetalert2 and sorry if my question is not fitted to be here. However I wonder why my sweetalerts keep appearing at the bottom of my screen (see image: https://imgur.com/a/H8DlM).

I first thought this was some issue with my dependencies, but that was not the case because I created a codesandbox project to check that: https://codesandbox.io/s/k5117qon63

But it keeps appearing at the bottom!

I remeber having this issue with `sweetalert-react` and the fix for that was simply to import the ccs file, like this: `import 'sweetalert-react/node_modules/sweetalert/dist/sweetalert.css'` and I tried ti apply this to sweetalert 2 `import 'sweetalert2/node_modules/sweetalert2/dist/sweetalert2.css'`, but it can't find that file. 

I have no idea how to fix this and all help is appreciated!

**Comment by limonte** [comment]
Hi @Martinnord!

Apparently, styles are missing. 

Good news! We recently released v6.10.0 which contains all-in-one version with JS and CSS in one place.

You can import it this way:

```
import swal from 'sweetalert2/dist/sweetalert2.all.min.js'
```

PS. In the next major version (v7.0.0) the combined JS + CSS version sweetalert2.all.min.js will be the default entry point and it will be possible to import it as usual: `import swal from 'sweetalert2'`

**Comment by Martinnord** [comment]
Oh THANK YOU! Been trying to fix this for hours and now it works! Maybe it would be worth mentioning this in the docs, like a little side note? 

Anyways, thanks a lot @limonte. And great job with sweetalert2. I changed because of the inline-html and I'm exited you use it!

Cheers! :-)

**Comment by janus-reith** [comment]
Im on 7.3.2 ans still have this issue, directly importing sweetalert2.all.min.js also fixed this.
I took a quick look at the package config, and it still defines` "main": "dist/sweetalert2.all.js",`(without `.min`)

**Comment by toverux** [comment]
> and it still defines"main": "dist/sweetalert2.all.js",(without .min

That is expected. `main` entries are generally expected to lead to a non-minified version of the source, it's then up to you to minify it with your build system.
.min.js versions are generally used with CDN when you just put a bunch of `<script src=`s.

> Im on 7.3.2 and still encounter this issue, directly importing sweetalert2.all.min.js

I'm not really sure to understand how that could happen. In your direct import, if you remove the .min suffix, things break?

**Comment by codemaker2015** [comment]
It's due to missing of css file.  Use the following code to import sweetalert in your application
```

import swal from 'sweetalert/dist/sweetalert-dev';
import 'sweetalert/dist/sweetalert.css';
```

**Comment by mdestafadilah** [comment]
> It's due to missing of css file. Use the following code to import sweetalert in your application
> 
> ```js
> import Swal from 'sweetalert2/dist/sweetalert2.js';
> import 'sweetalert/dist/sweetalert.css';
> ```

yest, it's work if you using sass styling file. import css sweetalert it must.
