### ISSUE TITLE
Input select not setting the selected value from inputValue when numeric

### ISSUE THREAD

**Issue by emmanuelballery** [limonte/sweetalert2#662]
Hi!

Because javascript object keys are casted to strings, using numeric keys in `inputOptions` + a numeric `inputValue` will fail to select the corresponding option :

```js
swal({
    title: 'Input something',
    input: 'select',
    inputOptions: {
      15: 'Serbia',
      20: 'Ukraine',
      37: 'Croatia'
    },
    inputValue: 20 // <-----------------------------------
  });
```

https://jsfiddle.net/L87xem1y/67/

Though this one is ok :

```js
swal({
    title: 'Input something',
    input: 'select',
    inputOptions: {
      15: 'Serbia',
      20: 'Ukraine',
      37: 'Croatia'
    },
    inputValue: '20' // <-----------------------------------
  });
```

https://jsfiddle.net/L87xem1y/69/

This is due to the type checking in https://github.com/limonte/sweetalert2/blob/master/src/sweetalert2.js#L926.

This is not really a sweetalert2 problem but I feel like it should be written somewhere in the doc or maybe the `inputOptions` should have a "preserving type form" like for example :

```js
const inputOptions = [
    {value: 15, text: 'Serbia'},
    {value: 20, text: 'Ukraine'},
    {value: 37, text: 'Croatia'},
];
```

Thanks!

**Comment by limonte** [comment]
I wish every issue report would be like this one :)

Should the fix be as simple as:

```js
if (params.inputValue.toString() === optionValue) {
```

?

**Comment by emmanuelballery** [comment]
I wish I thought of this one :+1:

**Comment by limonte** [comment]
Fixed in https://github.com/limonte/sweetalert2/releases/tag/v6.10.3, thanks for reporting!
