### ISSUE TITLE
Enhancement: Allow positioning the popup programatically. 

### ISSUE THREAD

**Issue by roemhildtg** [limonte/sweetalert2#664]
There are times where I don't always want the popup positioned in the center of the screen. Actually, I prefer it to be centered and top, like chrome's default alert. That way it doesn't block whatever is covering the screen. 

Currently, its possible with css, but not practical as you might not _always_ want that:
```css
.swal2-modal {
    margin-top: 0 !important;
}
```

Other possibilities could include: `right` `left` `bottom` `top-right` `top-left` ...etc?

```javascript
swal({
  //....
  position: 'top-left',
});
```

**Comment by toverux** [comment]
I'm somewhat in favor of an option to make the modal appear "more at the top".
But then some users will find it too high, or not enough, etc, that's what makes me think this maybe should stay a CSS problem.

Also, positions like "top-left", "right", etc, seem totally useless to me. Why would you want that?

**Comment by acupajoe** [comment]
@toverux I agree, if the position option was added, it would have to be just for 'top', 'center' and 'bottom'. SWAL2 could provide classes for those positions that a user can more easily customize via css, which I think would fulfill the original issue request.

**Comment by roemhildtg** [comment]
@toverux you're right, I don't see a great use case for top-left, right etc. I guess initially I was thinking it might be beneficial, in cases where you want to position the popup on top of a sidebar on one side of the screen or the other, but for my particular use case, top, center, and bottom will work splendidly.  👍

**Comment by toverux** [comment]
> in cases where you want to position the popup on top of a sidebar on one side of the screen or the other

Aha, that's already possible with the `target` option :)
Pass it the Swal parent container (`body` by default) and the modal will attach itself to it and displayed in the middle of it. So if you screen is divided in two parts for example, give Swal one of the two containers, and the modal will be perfectlty centered in it!

**Comment by limonte** [comment]
Implemented in https://github.com/limonte/sweetalert2/releases/tag/v6.11.0 :rocket:

**Comment by limonte** [comment]
Live example: https://limonte.github.io/sweetalert2/#position

**Comment by Rohit-chapter** [comment]
Hi limonte,
I have tried position tag but it is not working ,it is not showing me "swal2-container **swal2-top-end**" in container div.
Please suggest some solution.

Thanks

**Comment by zenflow** [comment]
@Rohit-chapter Please open an issue with a JSFiddle. There are links to a couple JSFiddle templates in the issue template.

**Comment by resmigenc** [comment]
Hello Limonte. Footer section footer does not work.

**Comment by zenflow** [comment]
@resmigenc Please open an issue with a JSFiddle. There are links to a couple JSFiddle templates in the issue template.

**Comment by Xerotherm1c** [comment]
@limonte In addition to the "quick positioning" you've added, you should also accept x and y offset values from the given position. The default `body.swal2-toast-shown .swal2-container.swal2-[position]` would still have:

`top: 0;
right: 0;`

But now you would have the ability to adjust the position to an exact pixel location if necessary for the given project.

Great plugin! Thanks for your time

**Comment by Franki1986** [comment]
Hello,

Is there any way to position a popup based on an element?
Something like :

```
swal({
  
    // ...
    position: 'top-right',
    popup-target: : document.getElementById('my-div')
    });
```

So that the popup will display at the top-right of my div element?

**Comment by gverni** [comment]
Hi @Franki1986, yes there is. You can use the property `target` to specify which element to put the swal into. Have a look to issue #1244 as well for some more information.

**Comment by Franki1986** [comment]
Hi, thanks for your reply! I have done a quick test, but this seems not to create the expected result.
I thought that the popup would display at the top of my div.

[example](https://jsfiddle.net/franki1986/nxw5Lpac/6/)

**Comment by gverni** [comment]
glad it worked now @Franki1986. I agree we should add an example, but it's not easy with the design of the current documentation page. Let us think about it.
