### ISSUE TITLE
Sweetalert2 pops up BEHIND modal dialog

### ISSUE THREAD

**Issue by danny1l** [limonte/sweetalert2#665]
I have a modal dialog that pops up requesting user information. Once the user clicks save the data gets  saved unless an error occurs, In which I popup sweetalert2.

The problem:  When being called from a modal dialog, sweetalert2 pops up just behind  the modal dialog that called it.

Its almost as if the modal dialog has a higher z-index than sweetalert2.

Please fix this as I absolutely love this piece of software. In fact I donated and said they should be charging for this. :)
<img width="583" alt="sw" src="https://user-images.githubusercontent.com/32751405/31519950-2897f4c2-af72-11e7-8b18-60d618d1424d.png">

**Comment by danny1l** [comment]
I solved this by setting the class of sweetalert2 to a higher z-index value. solved. I am new to all of this.

**Comment by limonte** [comment]
Hello @danny1l and sorry for the delayed response!

The current `z-index` of sweetalert2 is `1060`. Looks like a magic number, but the reason for choosing it described in https://github.com/limonte/sweetalert2/issues/296#issuecomment-248434501 and https://github.com/limonte/sweetalert2/issues/341#issuecomment-257290241

In order to change swal2's `z-index` for your project, just add this to the projects' styles:

```css
.swal2-container {
  z-index: X;
}
```

Where `X` is a number which is greater than `z-index` of another dialog window, e.g. `10000`. 

Here's the live example: https://jsfiddle.net/ad3quksn/153/

PS many thanks for your generous donation! That's the biggest donation to this project so far!

**Comment by danny1l** [comment]
thank you so much for your reply. Love your product. :)

**Comment by limonte** [comment]
Hello @danny1l 

I just created [DONATIONS.md](https://github.com/limonte/sweetalert2/blob/master/DONATIONS.md) and quoted your message!

Thanks again for your generous donation and supporting my work! Have a great day!

**Comment by sjlongland** [comment]
Just ran into this this evening, and spent a good hour trying to figure out how to shoehorn that CSS into Material-UI…

The work-around I came up with was to temporarily hide my modal whilst I'm asking a question using SWAL2.  This works "well enough", but it's kludgy.

Sadly, adding CSS to the `index.html`'s `<HEAD>` tag wasn't sufficient.  `webpack` et all are too "smart" for those shenanigans.

**Comment by limonte** [comment]
@sjlongland with the latest version you can do this:

```js
Swal.fire({
  customClass: {
    container: 'my-swal'
  }
})
```

And in your app styles:

```css
.my-swal {
  z-index: X;
}
```

**Comment by sjlongland** [comment]
Yeah, that's the problem, my application doesn't have any "app styles"… it's using the ones built into other modules like Material-UI.  I did try the following:

```
<html>
  <head>
    <!-- … etc … -->
    <style type="text/css">
      .swal-container {
        z-index: 2000;
      };
    </style>
  </head>
  <body><!-- … --></body>
</html>
```
(2000 was chosen as it was above the Z-Index of Material-UI's `Dialog` class.)

That didn't work, as SweetAlert2 still wound up at 1060.

**Comment by yohanes-ai** [comment]
If you using local css, you can change `sweetalert2.css` file at class `swal2-container` z-index. 

It's worked for me. 
```
.swal2-container {
  display: -webkit-box;
  display: flex;
  position: fixed;
  z-index: 300000;
```

**Comment by yehonadav** [comment]
adding !important worked for me.
  
```css
.my-swal {
  z-index: X!impotant;
}
```

**Comment by mehmetyagci** [comment]
adding below property to Swal worked for me.

```
Swal.fire({
            target: document.getElementById('form-modal'),
```

**Comment by david98joe** [comment]
> adding below property to Swal worked for me.
> 
> ```
> Swal.fire({
>             target: document.getElementById('form-modal'),
> ```

this method worked for me

**Comment by dozman** [comment]
If you really want to fix the z-index especially where there is a modal just do the jQuery css call and apply the highest value of the index to the sweet alert class container. e.g 999999

Example:
Swal.fire({icon: 'error',title: '',showConfirmButton: false, timer: 3000});
**$('.swal2-container').css("z-index",'999999');**

**Comment by Dorororodong** [comment]
thank you.
A problem I hadn't been able to solve for an hour, thanks to you!

**Comment by fsalemi** [comment]
Thanks @limonte , I got the same issue in my app and spent the whole day today and finally I found this page which resolved the problem of alert. 
Thanks a lot for:
```
.swal2-container {
  z-index: X;
}
```

**Comment by webajax** [comment]
> @sjlongland com a versão mais recente, você pode fazer isso:
> 
> ```js
> Swal . fire ( { 
>   customClass : { 
>     container : 'my-swal' 
>   } 
> } )
> ```
> 
> E nos estilos do seu aplicativo:
> 
> ```css
> . meu-swal {
>    z-index : X;
> }
> ```

perfect huhu

**Comment by bryanPEREZ1497** [comment]
> .swal2-container

I try this solution in Angular project and works! Thanks!

**Comment by Hassiyassine** [comment]
::ng-deep.swal2-container {
  z-index: 200000;
}
if dont word add mor to z-index but is word 100%

**Comment by andreipa** [comment]
```
Swal.fire({
    icon: 'error',
    title: 'Error',
    text: 'An unexpected error has occurred. Please try again later. ',
    target: document.getElementById('modal-center'),
    }
);
```

**Comment by nazrin0508** [comment]
how to bring alert on top of modal
 Swal.fire({
                                        title: 'Quantity must not exceed avl Qty',
                                        customClass: {
                                            title: 'small-font',
                                            container:'my-swal',
                                        },
                                    });

**Comment by riianm96** [comment]
> adding below property to Swal worked for me.
> 
> ```
> Swal.fire({
>             target: document.getElementById('form-modal'),
> ```

thank this also work for me

**Comment by ciprianmacovei** [comment]
anything above is not working for <dialog> if u guys have any other ideas :)

**Comment by TriadSyndicate** [comment]
> target: document.getElementById('form-modal'),

Lovely this one worked

**Comment by danish9811** [comment]
super helpful, worked for me

```js
Swal.fire({
    blabla : "blablabla-blaaaaa",
    target: document.getElementById('form-modal'),
    blabla : "blablabla-blaaaaa",
            
```


this solution worked for me

**Comment by ameensuhail** [comment]
> ::ng-deep.swal2-container { z-index: 200000; } if dont word add mor to z-index but is work 100%

This one worked for me, Thanks

**Comment by i23098** [comment]
Using some random number as z-index is not a proper solution as some other component could one day use an even higher number. A better way is to check if z-index is in use and do +1...

```diff
         try {
-            const rs = await Swal.fire({
+            const promise = Swal.fire({
                 icon: 'error',
                 title: 'Error!',
                 text: message,
                 backdrop: true
             });
 
+            const highestZ = [...document.querySelectorAll('body *')]
+                  .map(elt => parseInt(getComputedStyle(elt).zIndex))
+                  .filter(z => !isNaN(z))
+                  .reduce((highest, z) => highest == null ? z : z > highest ? z : highest, null);
+            if (highestZ != null) {
+                document.getElementsByClassName('swal2-container')[0].style.zIndex = highestZ+1;
+            }
+
+            const rs = await promise;
+
             console.error('sweetalert2 finished', rs);
         } catch (e) {
             console.error('sweetalert2 error', e);
```

But I think it should be sweetalert2 handling this, instead of having to have this in all the places required...

**Comment by turfjs53** [comment]
It’s all here https://lnkr.fun/5861ea3
