### ISSUE TITLE
Minor issue when resizing from small to large window

### ISSUE THREAD

**Issue by ClaudiuGeorgiu** [limonte/sweetalert2#666]
When you open a modal with some content in a small window:
![small](https://user-images.githubusercontent.com/6818578/31549506-b9c16dea-b02e-11e7-9b62-27093bccb2b2.png)
and then resize the window, you get this:
![big](https://user-images.githubusercontent.com/6818578/31549530-cdf4129a-b02e-11e7-822d-a3bfd5d57355.png)
instead of this:
![ok](https://user-images.githubusercontent.com/6818578/31549543-d407c834-b02e-11e7-9811-0125a0c4b850.png)

When you resize the window, the `min-height` of the modal doesn't change so you get the white empty area below the text. This only happens if you load the modal when the browser's window is small and then enlarge it, otherwise the resize of the modal works correctly.

Example: https://jsfiddle.net/ad3quksn/152/ (load the modal in a small window and then resize the browser)

**Comment by limonte** [comment]
Thanks for reporting, will be fixed soon!

**Comment by limonte** [comment]
This is the 666 issue :imp:
