### ISSUE TITLE
it is possible use this to make aletrs from electron main proccess? I'm getting some errors about the dom isn't defined.

### ISSUE THREAD

**Issue by rafaelleru** [limonte/sweetalert2#675]

**Comment by limonte** [comment]
>If your issue is focused more on 'is it possible?' rather than 'this is a broken functionality', then either ask on our [Gitter](https://gitter.im/sweetalert2/lobby) or submit it to [StackOverflow](https://stackoverflow.com/questions/ask) instead of GitHub, and make sure you add the [`sweetalert`](https://stackoverflow.com/questions/tagged/sweetalert) tag to the question.

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)
