### ISSUE TITLE
Cannot display image using html tag

### ISSUE THREAD

**Issue by danny1l** [limonte/sweetalert2#677]
Using the html property, I am unable to display an image. Example code...

                      swal({
                            title: 'Record Not Found',
                            text: "Hello",
                            html: "<img src='~/Content/Images/warning.png' alt='dd' />",
                            animation: false,
                            allowEscapeKey: false,
                            allowOutsideClick: false,

                        })

Note: I am aware of the traditional ways of adding images to SA2.

I even tried....
<div class="swal2-icon swal2-warning" style="display: block;">!</div>

Just can't get it to work, please help.

Thank you

**Comment by toverux** [comment]
Hello @danny1l,

I presume that your URL isn't valid. The tilde(`~`) character denotes a filesystem path (relative to your $HOME directory, on Unix systems).
Fix the path and then you'll be able to use the `image*` options from SweetAlert2 (or your <img> tag).

You can probably see a 404 error in your browser's dev tools (Network tabs and/or the console, depending on the browser).

Closing the issue as it's not a SweetAlert2 bug. Please ask a question on StackOverflow if you have trouble to determine the path you should use.
