### ISSUE TITLE
Chaining steps with multiple fields on each step - angularjs

### ISSUE THREAD

**Issue by baigail93** [limonte/sweetalert2#689]
I have 3 steps chaining model and all steps have multiple custom input controls. I used multiple fields as suggested by using HTML/preConfirm. I want to get the results of first step, make an API call and set the api results on $scope of angularjs component. I did it in preConfirm function where the results are being set in the scope after the API call but when I access them in next step, I do not get the results in HTML.

`var steps = [
			{
			  title: 'Name & Destination Number',
			  html: '<input id="swal-tracking-name" class="swal2-input" />' +
			  '<input id="swal-destination-number" class="swal2-input" />',
			  preConfirm: function () {
				return new Promise(function (resolve) {
					$scope.$apply(function(){
						$scope.trackingName = $('#swal-tracking-name').val();
						$scope.destinationNumber = $('#swal-destination-number').val();
					});
					
					var promise = ..service call here that returns the promise..;
					return promise.then(function (data) {
						$scope.availableLocalNumbers = data;
						resolve([
							$('#swal-tracking-name').val(),
							$('#swal-destination-number').val()
						  ]);
					});
				})
			  }
			},
			{
				title: 'Tracking Phone Number',
				html: '<div>' + $scope.destinationNumber + '</div>',	//this is null which is the issue
				preConfirm: function () {
				  return new Promise(function (resolve) {
					console.log($scope.destinationNumber);	//this correctly shows the input by user in step 1
					resolve([
						
					])
				  })
				}
			  }
		  ]
		  
		  swal.queue(steps).then(function (result) {
			swal.resetDefaults()
			swal({
			  title: 'Congratulations!',
			  html:
				'Your answers: <pre>' +
				  JSON.stringify(result) +
				'</pre>',
			  confirmButtonText: 'Go to dashboard!'
			})
		  }, function () {
			swal.resetDefaults()
		  })`

`$scope.destinationNumber` is available in preConfirm of step 1/step 2 but its not available for the HTML attribute which i was expecting it to be.

**Comment by limonte** [comment]
This isn't the right place for Angular- or any other framework related questions. 

https://stackoverflow.com/questions/ask

**Comment by baigail93** [comment]
My bad! I went through the previous closed issues and found few issues with angular! I moved it to stackoverflow! Thanks
