### ISSUE TITLE
Page content scrolls up when swal2 dialog appears

### ISSUE THREAD

**Issue by knagyorg** [limonte/sweetalert2#691]
The problem is that page content scrolls up when swal2 dialog appears.
Imagine you have TOS page with very long text, you have to scroll down, where is Accept button. But when check box "I accept TOS conditions" is not checked, I'd like to show warning dialog. But in that moment page scrolls up and after I close dialog, I have to scroll down again to reach Accept button.
I tested it with sweetalert2 6.11.4.

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by knagyorg** [comment]
It looks like bug when combine Vuetify and Sweetalert2 (don't know in which library).

**Reproduction Link**
https://jsfiddle.net/xvce8r9k/3/
**Expected Behavior**
When click on any button to show swal dialog the page content should stay on the same place
**Actual Behavior**
Page content always scrolls up when swal appears - go to the end of page and click button

**Comment by knagyorg** [comment]
Changed in Vuetify library.
