### ISSUE TITLE
Difference sweetalert2.all.js vs sweetaler2.js

### ISSUE THREAD

**Issue by netbka** [limonte/sweetalert2#695]
Hello,
Could you please clarify what is the difference between the files included in dist folder sweetalert2.all.js vs sweetalert2.js
Thank you!

**Comment by limonte** [comment]
Hello @netbka 

`sweetalert2.all.js` was introduced in [v6.10.0](https://github.com/limonte/sweetalert2/releases/tag/v6.10.0)

It's purpose it to provide a single thing to import/include. It contains both JS and CSS.

`sweetalert2.js`:
```html
<script src="./dist/sweetalert2.js"></script>
<link rel="stylesheet" href="./dist/sweetalert2.css">
```

`sweetalert2.all.js`:
```html
<script src="./dist/sweetalert2.all.js"></script>
```

As you can see, with `sweetalert2.all.js` developers don't need to care about CSS at all, which is handy.

Thanks for using SweetAlert2 and have a good day!
