### ISSUE TITLE
swal popup in IE11 placed in the right side

### ISSUE THREAD

**Issue by seducer0719** [limonte/sweetalert2#698]
using a default swal('Title', 'message', 'error')
in Chrome that was working fine, the popup is in the center of broswer.
but in IE11, popup is in the right side of the broswer.
Any idea about this ?

**Comment by limonte** [comment]
Thanks for reporting @seducer0719, the issue with IE11 positioning was fixed in the latest release https://github.com/limonte/sweetalert2/releases/tag/v6.11.4

You need to update your SweetAlert2 dependency to fix this.
