### ISSUE TITLE
SweetAlert2 confirm doesn't wait for input on form

### ISSUE THREAD

**Issue by n0xic** [limonte/sweetalert2#7]
I am using SweetAlert2 as a confirm dialog before submitting an HTML Form.
The issue is that it sends the request without waiting for input.

With Sweet Alert 2: [JSFiddle](http://jsfiddle.net/b3mhc7o4/)

The normal behavior happens when using a standard "Confirm" html control: [JSFiddle](http://jsfiddle.net/b3mhc7o4/1/)

**Comment by limonte** [comment]
You should use SweetAlert2 this way: http://jsfiddle.net/dhd97qgf/
