### ISSUE TITLE
fix website

### ISSUE THREAD

**Issue by AucT** [limonte/sweetalert2#70]
http://limonte.github.io/dist/sweetalert2.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://limonte.github.io/dist/sweetalert2.css Failed to load resource: the server responded with a status of 404 (Not Found)
(index):572 Uncaught ReferenceError: swal is not defined
http://limonte.github.io/dist/sweetalert2.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by limonte** [comment]
Thanks @AucT for reporting this! Fixed!
