### ISSUE TITLE
Sweetalert2 not working properly on IE11 on Windows 10 Pro v1709

### ISSUE THREAD

**Issue by cmcawood** [limonte/sweetalert2#701]
Fall Creators Update IE dev tools causes browser to crash when sweetalert is loaded.  I was trying to see why sweetalert was not working correctly and cannot because dev tools keeps crashing.

**Comment by limonte** [comment]
- SweetAlert2 version?
- How are you including SweetAlert2?

**Comment by cmcawood** [comment]
Ok some background we developed a system for a client and they are using Windows 7 with IE11 so we had to make a few changes for it to work for them.  I upgraded to v6.11.4 this morning and we added in a polyfill to enable it to work:
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
    <script src="/Scripts/sweetalert2.min.js" type="text/javascript"></script>

So if you go to the site on IE11 on Windows 7 or Win 10 prior to 1709 it randomly doesnt work with the sweetalerts where they are chained (it decides sometimes to work and others not).  On 1709 it does the same behaviour, but if you open the dev tools then IE11 crashes.  If I comment out sweetalert, all works fine.

**Comment by limonte** [comment]
>For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/limon/ad3quksn/

See [Contributing.md](https://github.com/limonte/sweetalert2/blob/master/contributing.md)

**Comment by limonte** [comment]
Add jsfiddle in order to get help.
