### ISSUE TITLE
Textarea always continues when pressing enter key

### ISSUE THREAD

**Issue by Kullersj** [limonte/sweetalert2#702]
In the newest version (6.11.4) when using a textarea input, pressing enter will not bring you to a new line in the text area and will instead proceed as if you hit Confirm. 

This behavior happens when allowEnterKey is set to false and focusConfirm is also set to false

https://jsfiddle.net/t8w2eLma/22/

This is working in an earlier version https://jsfiddle.net/cmqn7s8c/4/

**Comment by limonte** [comment]
Fixed in [v6.11.5](https://github.com/limonte/sweetalert2/releases/tag/v6.11.5), thanks for reporting @Kullersj!
