### ISSUE TITLE
Option to remove grey aria border around button.

### ISSUE THREAD

**Issue by carlosriveros** [limonte/sweetalert2#704]
Currently the confirm button has a grey border when focused.

Can we have an option to remove it?

**Comment by boaticus** [comment]
As a workaround, I removed the gray button border in my app using the following css override:

```
.swal2-modal .swal2-styled:focus {
	outline: 0;
	-webkit-box-shadow: none;
	box-shadow: none;
}
```

**Comment by limonte** [comment]
It's possible to remove the outline from buttons, but **PLEASE DO NOT DO THAT**. 

**[There's a reason for that ugly outline!](https://stackoverflow.com/a/25298082/1331425)**

You're killing the keyboard a11y of your app. People with vision disabilities, as well as keyboard-ninjas, will hate you for that.

This plugin cares about being accessible to all users, by removing buttons outline you simply ruin our effort.

**Comment by poriyaASadi** [comment]
how can hidden border box for sweet alert ? 
i can not display none for button box
