### ISSUE TITLE
Not  issue, just suggestion

### ISSUE THREAD

**Issue by tenzintaschi** [limonte/sweetalert2#705]
Hi Limon Monte,

I have just one more useful example of usage. If need to display alert with custom html content, html attribute can be used but only we content is not too large. If the content is large can load it from external file/url. For example:

            swal({
		  title: "Popup form",
		  showCancelButton: true,
		  confirmButtonColor: "green",
		  confirmButtonText: "Submit",
		  onOpen: function() {
			  $( "#content" ).load("popupFormContent.html");
		  },
		  html: '<div id="content"></div>'

		}).then(function(result) {
			toSubmit=true;
			if(result===false)
				toSubmit=false;
			if(toSubmit){
 
			}
		});

You can also add URL to swal's attributes and program url load to alert'S body. Could be good functionality enhancement.

Regards
TT

**Comment by limonte** [comment]
Thanks for the suggestions, it's out of scope of this plugin.

**Comment by tenzintaschi** [comment]
Ok, no problem.  Anyway I will use it in this way. Thanks for your good job!
