### ISSUE TITLE
Textarea input type newline issue!

### ISSUE THREAD

**Issue by PeymanNaeimi** [limonte/sweetalert2#706]
Hi,
When I try to break line in textarea input type, modal confirmed.

I had added these too, but nothing happen:
allowEnterKey: false,
focusConfirm: false,

any one had advise for my problem?

Check the code here:
https://jsfiddle.net/piman/f28tn8hq/24/

**Comment by limonte** [comment]
My advice is to use latest version: https://jsfiddle.net/f28tn8hq/25/

**Comment by limonte** [comment]
@PeymanNaeimi from your GitHub profile I can see that you're the expert in RTL. I just created an issue related to RTL: https://github.com/limonte/sweetalert2/issues/707 could you please add in comments if I forgot something.

Thanks in advance and have a nice day!
