### ISSUE TITLE
Sweetalert2 breaking my angular build

### ISSUE THREAD

**Issue by tarun29061990** [limonte/sweetalert2#708]
While doing `npm run build`, 

Got this error
`ERROR in vendor.97ddeaba56b47c113f33.bundle.js from UglifyJs`
`Unexpected token: operator (>)`

**Comment by limonte** [comment]
StackOverflow is the right place to ask Angular-related questions: https://stackoverflow.com/questions/ask

**Comment by tarun29061990** [comment]
https://stackoverflow.com/questions/47241748/sweetalert2-breaking-my-angular-build-what-to-do

**Comment by tarun29061990** [comment]
@limonte Can you please share your views on stackoverflow??

**Comment by joshuaalpuerto** [comment]
@tarun29061990, I believe your issue is related with this #647. 

I was able to fix mine by replacing:

```js
import swal from 'sweetalert2'
```
to

```js
import swal from 'sweetalert2/dist/sweetalert2.all.min.js'
```
