### ISSUE TITLE
Modal Window - center y on screen bug

### ISSUE THREAD

**Issue by quma** [limonte/sweetalert2#71]
Hi,

if I use HTML or custom imgages, the modal window is not centered on screen (y- direction)

**Comment by limonte** [comment]
When you're using external content, beside `imageUrl` specify `imageHeight` to fix vertical centering.

**Comment by quma** [comment]
but you have the same problem with html content without images?
But i will test it again.

**Comment by quma** [comment]
I test it and it's not work. If you have html content with images  (not imageUrl)... than the modal window is not centered. I think with a longer html content without a image you have the same problem.

In sweet alert 1 its center correctly

**Comment by quma** [comment]
in your demo (A message with a custom icon and CSS animation disabled)
you can see it ... in Mac OSX Firefox and Mac OSX Chrome the position is different.

[https://limonte.github.io/sweetalert2/](https://limonte.github.io/sweetalert2/)

**Comment by quma** [comment]
I get this work by changing on line 137
this
` padding = parseInt(getComputedStyle(elem).getPropertyValue('padding'), 10);`

to this

` padding = parseInt(getComputedStyle(elem).getPropertyValue('padding-top'), 10);`
