### ISSUE TITLE
Hide cancel button when loader starts loading in place of confirm button

### ISSUE THREAD

**Issue by mateenQureshi** [limonte/sweetalert2#713]
Hello mates,
i would like to request you a feature. i have started using sweetalert2 for my CRUD operations includes ajax, when any operation is performed, i am starting the loader but cancel button is still visible along side it really doesn't cancel the request. So i would like a slight change in the plugin, that if the loader starts on ajax request, please hide all the buttons and just show the loader.

Looking forward!

**Comment by acupajoe** [comment]
@mateenQureshi rather than hiding the buttons, would it not make more sense to disable them?

**Comment by limonte** [comment]
Agree with @acupajoe 

Cancel button gets the disabled state, and it's obvious that it's not clickable because of its color and cursor.

Here's the workaround you can use: https://jsfiddle.net/ad3quksn/191/

**Comment by mateenQureshi** [comment]
also agree with @acupajoe , but it was my client requirement to remove the cancel button on loader start so i have to go with requirement.
Thanks for workaround @limonte . It's exactly what i want

thanks for appreciated response, guyz
