### ISSUE TITLE
There is a small error, when using the timer functionality, to create delays

### ISSUE THREAD

**Issue by julio899** [limonte/sweetalert2#714]
in the console it shows in red like "Uncaught (in promise) timer"

I wanted to correct the failure since the message is uncomfortable, but I do not know how to handle that exception
![image](https://user-images.githubusercontent.com/2575745/32818360-1c056bc2-c999-11e7-98cd-14817245294c.png)

**Comment by julio899** [comment]
I was able to remove the error message.
to visualize what was causing the message.
modify the following way.
`swal({ 
			  type: 'success',
			  title: "Codigo Copiado al Portapapeles",
			  text: "notificación cierra en 2 segundos.",
			  showConfirmButton: false,
			  timer: 2500
			}).then(()=>{},(eception)=>{console.log(eception)});`

**Comment by acupajoe** [comment]
Closing as this issue is handled in the [README#handling-dismissals](https://github.com/limonte/sweetalert2/blob/master/README.md#handling-dismissals). 
Thanks for using swal2!
