### ISSUE TITLE
Argument error in iframes - same error from sweetAlert 1

### ISSUE THREAD

**Issue by psychoPirate** [limonte/sweetalert2#715]
[Issue 722 - sweetAlert 1](https://github.com/t4t5/sweetalert/issues/722)

`Hi, my dear!

I use SweetAlert in a project, but I noticed that there were some changes.

Before, I imported a JS file and a CSS into the body of HTML. I downloaded the latest "sweetalert.min.js" file and imported it as before but I'm having trouble using it.

The call below runs successfully:
swal ("Hello world!");

But this other:
swal ({    title: "Good job!",    text: "You clicked the button!",    icon: "success", });

... the following error occurs:

    Uncaught SweetAlert: 1st argument ('[object Object]') is invalid

I'm doing something wrong?`

- Fix/workaround for this issue?

**Comment by limonte** [comment]
Not related to this repository.

**Comment by psychoPirate** [comment]
So, its to run this code without errors?
`            
		$(parent)[0].swal({
		  title: 'Are you sure?',
		  text: "You won't be able to revert this!",
		  type: 'warning',
		  showCancelButton: true,
		  confirmButtonColor: '#3085d6',
		  cancelButtonColor: '#d33',
		  confirmButtonText: 'Yes, delete it!',
		  cancelButtonText: 'No, cancel!',
		  confirmButtonClass: 'btn btn-success',
		  cancelButtonClass: 'btn btn-danger',
		  buttonsStyling: false
		}).then(function () {
		  swal(
		    'Deleted!',
		    'Your file has been deleted.',
		    'success'
		  )
		}, function (dismiss) {
		  // dismiss can be 'cancel', 'overlay',
		  // 'close', and 'timer'
		  if (dismiss === 'cancel') {
		    swal(
		      'Cancelled',
		      'Your imaginary file is safe :)',
		      'error'
		    )
		  }
		});`


But this one works:
`$(parent)[0].swal("test");`

**Comment by psychoPirate** [comment]
Sorry for the inconvenience, cache problem -.-'  ....  the 2 libraries use the same function name.
