### ISSUE TITLE
Cannot read property 'style' of null

### ISSUE THREAD

**Issue by rain85** [limonte/sweetalert2#716]
Using template: https://jsfiddle.net/ad3quksn/154/

Step1: Enter any text in the inputbox
Step2: Click outside the box to close the sweetalert modal
Step3: Do 'Ctrl+Z'

Result:

Uncaught TypeError: Cannot read property 'style' of null
    at hide (VM110 sweetalert2.js:355)
    at Function.sweetAlert.resetValidationError (VM110 sweetalert2.js:1426)
    at HTMLInputElement.input.oninput (VM110 sweetalert2.js:189)

**Comment by limonte** [comment]
I'll take care of this issue today.

**Comment by limonte** [comment]
Fixed in [v7.0.1](https://github.com/limonte/sweetalert2/releases/tag/v7.0.1)

If you upgrading from v6.x please make sure you read the release notes with some breaking changes for the new major release: [v7.0.0](https://github.com/limonte/sweetalert2/releases/tag/v7.0.0)
