### ISSUE TITLE
Missing Question Mark icon

### ISSUE THREAD

**Issue by sunnybhoy** [limonte/sweetalert2#718]
Hi,

My question icon seems to be broken/missing. I've just updated from sweetalert to sweetalert2 so it's interesting that's the only icon that's been added from 1 to 2.

I tried it on different browsers with the same result so I don't think it's a cache problem.  I've checked my page source and it's pointing to sweetalert2.all.min.js. Everything else seems OK. Any idea what the problem could be?

TIA,

Alan

![screenshot-2017-11-16 user - edm for surveyors](https://user-images.githubusercontent.com/33714292/32879295-2cdd4566-caf5-11e7-9f8d-a040ce8b567f.png)

**Comment by toverux** [comment]
What browser do you use here?

**Comment by sunnybhoy** [comment]
The screenshot is Firefox. Other browsers don't have the broken symbol, just a blank area where the icon should be.

**Comment by sunnybhoy** [comment]
Thanks toverux,

I'm not sure what happened but it has started working. I was testing it with swal('The Internet?','That thing is still around?','question') and got the screenshot. However after messing around I tried another dialog with type: question and noticed that it worked. Then went back to the original code and it seems to have started to work as well.

No idea why but my guess it was something to do with the update from 1 to 2.

Thanks again,

Alan
