### ISSUE TITLE
Fix email validation regex

### ISSUE THREAD

**Issue by virtualtoy** [limonte/sweetalert2#719]
Currently email validation regex is `^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$`. But there's longer top-level domains like `.properties`. Such emails won't be accepted

**Comment by toverux** [comment]
I suggest that we replace `{2,6}` with `{2,}`, so we don't have to choose for an upper bound. Also history has shown that regexes for emails always lead to user frustration without brining any kind of security or anything, so if we can find a simpler regex, why not. For example, I'm unsure that `[a-zA-Z0-9.+_-]` is really good too.

**Comment by virtualtoy** [comment]
`^\S+@\S+\.\S{2,}$`?

**Comment by toverux** [comment]
Yep, looks better.

**Comment by limonte** [comment]
Good catch, thanks @virtualtoy!

According to https://jasontucker.blog/8945/what-is-the-longest-tld-you-can-get-for-a-domain-name the maxlength for TLD is 24 characters.

**Comment by limonte** [comment]
Fixed in [v7.0.1](https://github.com/limonte/sweetalert2/releases/tag/v7.0.1)

:warning:  If you upgrading from v6.x please make sure you read the release notes with some breaking changes for the new major release: [v7.0.0](https://github.com/limonte/sweetalert2/releases/tag/v7.0.0)
