### ISSUE TITLE
Ajax content

### ISSUE THREAD

**Issue by quma** [limonte/sweetalert2#72]
Hi 

is it possible to show the content of a external or html  page in the modal window after click on the confirmation button ?

**Comment by limonte** [comment]
Yes, it's possible.

**Comment by quma** [comment]
ok sounds nice, but can you make me a sample how I get this work ?

thx

**Comment by limonte** [comment]
@quma Nope. All you need to make what you need is here: https://limonte.github.io/sweetalert2/

But I won't do your homework, mate ;)

**Comment by quma** [comment]
thank you, but i read it over and over again but it not helps me to solve the problem :(
