### ISSUE TITLE
allowEnterKey:false is not working for IME keyboard

### ISSUE THREAD

**Issue by kazumanagano** [limonte/sweetalert2#720]
In the IME used for Japanese key input, the user uses the enter key to confirm the input candidate.
Therefore, if you handle a click event depending on whether the contents of e.key is 'Enter' or not, you can not distinguish between character input confirmation operation and Submit.
In addition, users using Japanese input can not prevent Submit by EnterKey even if you use allowEnterKey: false

**Comment by limonte** [comment]
Fixed in [v7.0.1](https://github.com/limonte/sweetalert2/releases/tag/v7.0.1)
