### ISSUE TITLE
Request: Allow only a part of the library to be imported

### ISSUE THREAD

**Issue by StephanBijzitter** [limonte/sweetalert2#728]
Dependabot created a pull request to one of our repositories to update from v6 to v7, and the changes in our output were as follows (as reported by bundlesize):
```
 PASS  ./bundlesize/app.js: 46.65KB < maxSize 75KB gzip (same as master) 

 WARN  ./bundlesize/vendor.js: 289.01KB < maxSize 350KB gzip (5.59KB larger than master, careful!) 

 PASS  ./bundlesize/app.css: 22.66KB < maxSize 50KB gzip (same as master) 

 WARN  ./bundlesize/vendor.css: 3.97KB < maxSize 10KB gzip (864B larger than master, careful!) 
```
This means updating sweetalert2 resulted in 5.59KB additional JS and 864B additional CSS in our build, while we don't use the new features. Granted this is not much on its own, but I do see this increasing over time.

Please allow us to only import a part of the codebase, so that we don't have to include code that we're not going to use.

**Comment by toverux** [comment]
Yep, that recalls me the discussions we've had about ESM and tree-shaking... but that requires important refactor/API changes. I think we, and our users, aren't ready for that, but it's a good thing to take that into consideration more seriously.
I'll try to take a look at the code base at some point to see what could be done with the current state of things.

But also, just to be sure, please check that you don't import the .all.js build of SweetAlert2 (that's the new entry point) and the CSS file at the same time.

**Comment by StephanBijzitter** [comment]
>But also, just to be sure, please check that you don't import the .all.js build of SweetAlert2 (that's the new entry point) and the CSS file at the same time.

That's a good point.
<img width="891" alt="screen shot 2017-11-20 at 12 03 26" src="https://user-images.githubusercontent.com/1649903/33015407-f033fda0-cdea-11e7-8bab-137de0ac3c2f.png">
Changing the imports makes the javascript increase go from +5.59KB to +450B, a tenth of the original change!

Now it looks like this:
```
import 'sweetalert2/src/sweetalert2.scss';
import sweetAlert from 'sweetalert2/dist/sweetalert2.js';
```
I'd prefer to take both from `src`, but doing that would lead to an increased javascript size again. Reason for using src would be that we can run it through our own webpack configuration, which also generated sourcemaps for node_modules.

**Comment by limonte** [comment]
> I'd prefer to take both from src, but doing that would lead to an increased javascript size again. Reason for using src would be that we can run it through our own webpack configuration, which also generates sourcemaps for node_modules.

You should be able to import from `src`:

```js
import 'sweetalert2/src/sweetalert2.scss';
import sweetAlert from 'sweetalert2/src/sweetalert2.js';
```

**Comment by StephanBijzitter** [comment]
When using `src` for the javascript, the css is not extracted correctly in our build which leaves styles inside both the javascript and css bundles. (`var styles = {...}`), so that's why I'm taking dist. It's a bit strange, but it works.

The tool is https://github.com/siddharthkp/bundlesize, and it's quite good but we're working on our own replacement. I just have to convince management to allow us to open source some of our tools :D

**Comment by limonte** [comment]
> When using src for the javascript, the css is not extracted correctly

I wonder why is that? Is that because of SweetAlert2 or your build configuration? There shouldn't be anything CSS-related in the `sweetalert2/src/sweetalert2.js`.

**Comment by limonte** [comment]
> The tool is https://github.com/siddharthkp/bundlesize, and it's quite good but we're working on our own replacement. I just have to convince management to allow us to open source some of our tools :D

Thanks for the link :+1:

**Comment by StephanBijzitter** [comment]
>I wonder why is that? Is that because of SweetAlert2 or your build configuration? There shouldn't be anything CSS-related in the sweetalert2/src/sweetalert2.js.

probably our configuration, it's highly optimised to our usage and sweetalert2 is currently the only dependency that has styles, so it's not worth it at this time to find out where exactly the magic is happening. If it works, it works :-)

**Comment by limonte** [comment]
> If it works, it works :-)

The first rule of sys admins :D But not for JS developers, we are here to BREAK THINGS! :smiling_imp:

**Comment by limonte** [comment]
This issue can be closed I guess, ping @StephanBijzitter

**Comment by StephanBijzitter** [comment]
Well, even though the actual impact was much less than what I first saw, it's still something to consider for the next major version.

I'd prefer to be able to write `import {sweetAlert, sweetToast} from 'sweetalert2'` or  `import sweetAlert from 'sweetalert2/sweetAlert'`, so that I don't have the code for toasts being imported in a project where I'm not using toasts. It could be done in the same major version, but that'd be more work.

**Comment by limonte** [comment]
I'm still not sure if it's worth to split those entities. The difference between alerts and toasts is insignificant: https://github.com/limonte/sweetalert2/pull/672

We will keep this suggestion in mind, but I'll close this issue for now.
