### ISSUE TITLE
Console warnings about deprecated parameters always appear

### ISSUE THREAD

**Issue by dwaxweiler** [limonte/sweetalert2#731]
I have just upgraded sweetalert2 to version 7 for a project. My browser's console shows the warnings about the deprecated parameters although I am not using them. As I understood the discussions in #693 and in #699, they should only appear when the deprecated parameters are actually used. You can easily reproduce this by having a look at your browser's console at the [JSFiddle template](https://jsfiddle.net/ad3quksn/199/).

**Comment by limonte** [comment]
Thanks for reporting @dwaxweiler, I'll handle this issue today.

**Comment by limonte** [comment]
Fixed in [v7.0.3](https://github.com/limonte/sweetalert2/releases/tag/v7.0.3), thanks for reporting!

**Comment by dwaxweiler** [comment]
You are welcome! Thank you for the quick fix!

**Comment by frodeknutsen** [comment]
Has this reappeared? I'm getting the same warning in 7.28.2

**Comment by limonte** [comment]
> Has this reappeared? I'm getting the same warning in 7.28.2

Doesn't look so, please provide the jsfiddle when the excessive warning can be seen.
