### ISSUE TITLE
Issue with the 'ts' task in gulpfile

### ISSUE THREAD

**Issue by limonte** [limonte/sweetalert2#732]
I excluded the `'ts'` task from the default gulp task, it was breaking the build: https://github.com/limonte/sweetalert2/commit/77c6f65f3993a19c792bb58389b6578d1710f2d3

![image](https://user-images.githubusercontent.com/6059356/33071059-d23c4c0c-cec2-11e7-8886-925c962d1256.png)

@toverux is that okay?

**Comment by limonte** [comment]
@toverux the issue is reproducible right now, it seems that `gulp-typescript` is going all the recursive way into `node_modules` which is slow and wrong.

**Comment by toverux** [comment]
Strange! I can't reproduce (even after reinstalling all the devdeps) :/
What surprises me the most is that the task explores that `/home/limon/node_modules` directory (the paths in red). What's that directory exactly?

**Comment by limonte** [comment]
> What surprises me the most is that the task explores that /home/limon/node_modules directory (the paths in red). What's that directory exactly?

Good catch! That's the `node_modules` folder inside my home folder. It's strange that it causes errors, but anyways, [reverted](https://github.com/limonte/sweetalert2/commit/0bebcbb631e30b01c341d15a0ef00dcc12ae5cf3)

**Comment by toverux** [comment]
Hm, I think that this is due to how Node-style module resolution works in general.
Found this in TS docs:

> Node will look for your modules in special folders named node_modules. A node_modules folder can be on the same level as the current file, or higher up in the directory chain. Node will walk up the directory chain, looking through each node_modules until it finds the module you tried to load.

Node resolution doesn't magically know where your project root is. That' why it traverses the filesystem from the file to the root. I think that TS does the same thing here for some reason, so - it's likely a normal behaviour.

**Comment by limonte** [comment]
Thanks @toverux!
