### ISSUE TITLE
Plugin doesn't work in IE 11

### ISSUE THREAD

**Issue by th-m** [limonte/sweetalert2#735]
IE 11 doesn't support promises. 
https://github.com/stefanpenner/es6-promise
I used this polyfill to get promises to work, but the default `confirmButton` in the `swal()` function doesn't resolve the promise when clicked. 
I don't know if IE 11 is something you guys care about, but it would be nice to get some support for it maybe.

**Comment by limonte** [comment]
Plugin does work in IE11: https://jsfiddle.net/ad3quksn/209/

**Comment by ChriStef** [comment]
Please @limonte from IE11 go to your demo page https://sweetalert2.github.io/ even the first demo wont show up. I think is something with the syntax of javascript.. Your demo fiddle pop up ok! 

What do you suggest to change I use promise in my site that works ok with others but not IE

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2.github.io/issues/3
