### ISSUE TITLE
[BUG] "Enter" in Firefox 57 on Windows doesn't work as expected

### ISSUE THREAD

**Issue by bedengler** [limonte/sweetalert2#736]
https://jsfiddle.net/h6vsm880/

works fine on other browsers and worked on Firefox until V56. Stopped working in Firefox 57. 
If you enter a price and press the "Enter" key, nothing happens. It should close the swal.
If you enter a price and press "OK" with the mouse, it closes...

So I assume Firefox interprets the key in another way then anybody else...but how could we solve this?

**Comment by limonte** [comment]
works fine for me:

![recorded](https://user-images.githubusercontent.com/6059356/33129589-108a23ae-cf99-11e7-8eb3-8f7a6e560c37.gif)

**Comment by patrickhlauke** [comment]
seems to work for me (Win 10/Firefox 57)

**Comment by limonte** [comment]
You're using outdated links in your jsfiddle, jsdelivr is :skull:

In future, please pay attention to this link before posting an issue

![image](https://user-images.githubusercontent.com/6059356/33129986-78f1879c-cf9a-11e7-8e83-174b75ce2740.png)

**Comment by bedengler** [comment]
Seems to have solved this issue...but I took the link from you, not the ..../199, but without "/199"...
Btw: is there a way to keep a swal opened, if the value, the user has entered, is not the value we've expected?
This seems not to work:
`swal({
		title: "Enter price",
		text: "do it",
		input: "text",
		showCancelButton: true,
		animation: "slide-from-top",
		inputPlaceholder: "Price",
		allowEnterKey: true
	}).then(
	function(inputValue){
		if (inputValue.value == "") {
			// keep swal opened - need code!!!
		}
		else {
			alert("success");
		}
	});`

**Comment by limonte** [comment]
> Btw: is there a way to keep a swal opened, if the value, the user has entered, is not the value we've expected?

Yes, https://jsfiddle.net/ad3quksn/210/

**Comment by bedengler** [comment]
Thanks! Everything solved for now...
I appreciate your work and your fast reply - keep on going, Sweetalert is great!
