### ISSUE TITLE
How to use SweetAlert2 with Inputmask.js?

### ISSUE THREAD

**Issue by koddr** [limonte/sweetalert2#737]
Hello.

It posible to use [Inputmask.js](https://github.com/RobinHerbots/Inputmask) plugin with SweetAlert2 for `input: 'text'` element? How?

Use cases and/or examples are welcome 👍 Thanks!

**Comment by acupajoe** [comment]
@koddr thanks for using sweetalert! As per our [CONTRIBUTING](https://github.com/limonte/sweetalert2/blob/master/.github/CONTRIBUTING.md)

> If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our Gitter or submit it to StackOverflow instead of GitHub, and make sure you add the sweetalert tag to the question.

But the short answer would be yes, using the `onOpen` option to set your bind to the input.
