### ISSUE TITLE
result.value is undefined

### ISSUE THREAD

**Issue by sal118** [limonte/sweetalert2#739]
This is the code I have for my swal call: 
swal({
                title: 'Are you sure?',
                text: 'Confirm point reset for ' + currentUsers[index].first+'?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, reset points!'
              }).then(function (result) {
                if (result.value) {
                  swal(
                    'Successfully Reset!',
                    'Points reset for '+ currentUsers[index].first+'!',
                    'success'
                  )
              }
              else {
                   console.log("user clicked cancel");
             }
}).catch(swal.noop)

For some reason, every time I try to print what result.value is in the console, it always says undefined. I tried changing it to 'if (result) {...} else{...}' but then nothing in the else statement ever happens. I also tried 'if (result.dismiss === 'cancel') {...}' but that doesn't work when the user presses cancel. I just tried swal two days ago and I'm pretty much a novice at this whole entire thing so I'm having trouble figuring out what the issue may be. I would appreciate any help!

**Comment by limonte** [comment]
make sure you're using **the latest stable version**

https://jsfiddle.net/ad3quksn/211/

**Comment by sal118** [comment]
I have version 7.0.3, but it still doesn't work...

**Comment by limonte** [comment]
it works https://jsfiddle.net/ad3quksn/213/
