### ISSUE TITLE
The documentation talks about modal popups - but they don't seem to be modal

### ISSUE THREAD

**Issue by nickraphael** [limonte/sweetalert2#741]
A modal popup locks the screen behind until the popup is dismissed.  At least that's what 'modal' always used to mean.  But modal examples on the sweetalert2 site don't work like that.  You can click on the page behind and the popup vanishes.  I want to force the user to click a 'close' button on the popup to close it.  Is this possible?

**Comment by acupajoe** [comment]
The option you're looking for is `allowOutsideClick` which defaults to `true`, there are other options in the README that show disabling the escape key, buttons, etc.

**Comment by zenflow** [comment]
@nickraphael 
```js
const myModalMixin = {
  allowOutsideClick: false,
  showCancelButton: false, 
  showConfirmButton: false,
  allowEnterKey: false,
  showCloseButton: true
}

swal(Object.assign({}, myModalMixin, {text: 'Is this more like it?'}))

// or if you're transpiling, use Object Spread (stage 3 proposal)
//   https://github.com/tc39/proposal-object-rest-spread

swal({...myModalMixin, text: 'Is this more like it?'})
```
