### ISSUE TITLE
Handling the result of SweetAlert2 modal on iE11 not works.

### ISSUE THREAD

**Issue by nitrojulia** [limonte/sweetalert2#742]
I try to handling the result of SweetAlert2 modal on iE11 but they never respond...
I using 'npm' version ^7.0.3, on vuejs project.

`        swal({
          title: 'Restart form',
          showCloseButton: true,
          showCancelButton: true,
          focusConfirm: false,
          confirmButtonText:'Restart',
          confirmButtonAriaLabel: 'Restart',
          cancelButtonText:'Close',
          cancelButtonAriaLabel: 'Close',
          confirmButtonColor: '#c8102e',
        }).then(function (result) {
          if (result.value) {
            //confirm and restart
          }else{
            //close modal
          }
        });
`

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/ad3quksn/199/
> 
>IE11 JSFiddle template: https://jsfiddle.net/ad3quksn/209/

See [CONTRIBUTING.md](https://github.com/limonte/sweetalert2/blob/master/.github/CONTRIBUTING.md)

**Comment by nitrojulia** [comment]
Morning, 
I feel my mistake, I've been here for a short time. The error occurs when I use the confirm button in iE11, it never goes into `. then ({function (result) {... }})`. My Modal are:
https://jsfiddle.net/x550z069/9/   

I have seen that by removing the option `focusConfirm: false` the button works well again.

Thx for help.

**Comment by limonte** [comment]
The provided jsfilldle works fine in IE11 :+1:
