### ISSUE TITLE
Remembers previous customClass values

### ISSUE THREAD

**Issue by tombusby** [limonte/sweetalert2#75]
If I try to add a customClass value to a new popup, it adds it along with a customClass value I provided for a previous popup in the flow.

**Comment by limonte** [comment]
Thank you @tombusby for submitting this issue!

Fixed in https://github.com/limonte/sweetalert2/releases/tag/v0.4.5

**Comment by tombusby** [comment]
Wow, the version in use in my client's codebase must be pretty out of date then. Apologies for the duplicate. I should have double checked. All the best.
