### ISSUE TITLE
inputs return as [object Object] in 7.0.x

### ISSUE THREAD

**Issue by Legoman99573** [limonte/sweetalert2#750]
**JSFiddle:** https://jsfiddle.net/78tdrgrn/
**Expected Output:** Suppose to return the value selected but returns as an [object Object]. This wasn't a problem in 6.x as it returned the option selected. I am hoping that this gets fixed as it keeps me from updating as i use it in an Open Source project.

**Comment by acupajoe** [comment]
This is part of the breaking changes of [v7.0.0 release](https://github.com/limonte/sweetalert2/releases/tag/v7.0.0)

@limonte lists available options in the release notes to either use the new syntax or make it backwards compatible with < v7.x
