### ISSUE TITLE
Dynamic Queue Example Won't Work - Two Tiny Bugs

### ISSUE THREAD

**Issue by markgmarkg** [limonte/sweetalert2#752]
Hi,

Two tiny bugs in the **example code** (the code behind works properly) ...
`Promise` in `PreConfirm` handler should contain `Resolve()` call, and curly bracket should be replaced by parenthesis.

```
preConfirm: () => {
    return new Promise((resolve) => {
      return $.get(ipAPI).then((data) => {
        swal.insertQueueStep(data.ip);
        resolve(); // <---- should be resolved
      })
    }) // <---- second parenthesis, not curly bracket
  }

```

**Comment by mattbrunetti** [comment]
Using promises within a Promise constructor is an anti-pattern. Using them in this way makes them basically just a glorified callback system, with the same pyramid of doom possibility, and misses the point of promises.

The Promise constructor should generally only be used for low-level bindings to async operations.

This example should be rewritten without the Promise constructor, and use promise chaining instead:

```js
{
  preConfirm: () => {
    return $.get(ipAPI)
      .then((data) => {
        swal.insertQueueStep(data.ip)
      })
  }
}
```

**Comment by limonte** [comment]
Fixed, thanks @markgmarkg and @mattbrunetti :beers:
