### ISSUE TITLE
Input from `Tab` is stolen while toast is on screen

### ISSUE THREAD

**Issue by acupajoe** [limonte/sweetalert2#753]
**Desired Functionality:**
Pressing tab from an input while a toast is on the screen should navigate to the next available input on the screen.

**Actual Functionality:**
While a toast is on the screen, pressing `tab` will not move the cursor (and further, will produce errors) - interestingly the `shift-tab` combination works.

**Steps to Reproduce:**
See example below - attempt pressing the tab key when it loads.
Example: [https://jsfiddle.net/acupajoe/ad3quksn/233/](https://jsfiddle.net/acupajoe/ad3quksn/233/)

**Comment by limonte** [comment]
Fixed in 7.0.7, thanks for reporting!
