### ISSUE TITLE
Modal type icon is shrinking with toast when providing fixed width

### ISSUE THREAD

**Issue by kgrvr** [limonte/sweetalert2#755]
Modal type icon is shrinking when I'm using toast and providing fixed width.

[Fiddle](https://jsfiddle.net/zvekqkn2/)

**Comment by limonte** [comment]
@acupajoe will you have time to take a look at this issue?

**Comment by limonte** [comment]
Fixed in v7.0.9, thanks for reporting @kgrvr!
