### ISSUE TITLE
Uncaught (in promise): cancel, result.value is undefine, result value is true in confir5m case : angular 5

### ISSUE THREAD

**Issue by imdadturi** [limonte/sweetalert2#756]
i am using sweet alert like below:
`swal({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Yes, delete it!',
      cancelButtonText: 'No, cancel!',
      confirmButtonClass: 'btn btn-success',
      cancelButtonClass: 'btn btn-danger',
      buttonsStyling: false,
      reverseButtons: true
    }).then((result) => {
      console.log(result);
      if (result.value) {
        swal(
          // this.placesService.delete(id).subscribe(
          //   data => {
          //     swal(
          //       'Deleted!',
          //       'Your file has been deleted.',
          //       'success'
          //     )
          //   },
          //   error => {
          //     swal('Error', 'Something went wrong!', 'error');
          //     this.errMessage = "Error: Something went wrong, Please try again";
          //   }
          // )
        )
      // result.dismiss can be 'cancel', 'overlay',
      // 'close', and 'timer'
      } else if (result.dismiss === 'cancel') {        
        swal(
          'Cancelled',
          'Your imaginary file is safe :)',
          'error'
        ).done()
      }
    })`

when i console  > >result  it return true on confirm and uncaught error on cancel, i tried the solution like adding .done() or catch but its not working for me.
My version is 
`"sweetalert2": "^7.0.7"`

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/ad3quksn/199/
> 
>IE11 JSFiddle template: https://jsfiddle.net/ad3quksn/209/

See [CONTRIBUTING.md](https://github.com/limonte/sweetalert2/blob/master/.github/CONTRIBUTING.md)

**Comment by imdadturi** [comment]
@limonte yes, made it work, thank you so much. there was some issue with referencing in my project. 👍

**Comment by limonte** [comment]
@imdadturi thanks for using SweetAlert2! Have a great day!
