### ISSUE TITLE
Comma after div element

### ISSUE THREAD

**Issue by guilherme90** [limonte/sweetalert2#757]
Hi,

I using the `html` property and after the div element, "**,**" is being inserted. How resolve this?

[**JSFiddle**](https://jsfiddle.net/ad3quksn/245/)

Thanks =)

**Comment by limonte** [comment]
>For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/ad3quksn/199/

See [CONTRIBUTING.md](https://github.com/limonte/sweetalert2/blob/master/.github/CONTRIBUTING.md)

**Comment by guilherme90** [comment]
Updating...

https://jsfiddle.net/ad3quksn/242/

**Comment by limonte** [comment]
not related to SweetAlert2, the issue is in the `messageAlert` helper function.

**Comment by guilherme90** [comment]
And how you have certain?

**Comment by guilherme90** [comment]
Thanks.
