### ISSUE TITLE
Bug with inputValidator + preConfirm + radio inputs

### ISSUE THREAD

**Issue by Barterr** [limonte/sweetalert2#758]
If the user tries to confirm without selecting anything and the validator fails, then selects something and tries to confirm again it doesn't work.
If you select a radio and confirm it works as expected.

https://jsfiddle.net/u8g6w00y/

**Comment by limonte** [comment]
@zenflow will you have time to take a look at this issue?

**Comment by zenflow** [comment]
@limonte Unfortunately, not within the next couple of weeks.. I'm leaving my current employer and there's lots of work to do finishing things up, documenting, handing off. On the bright side, after that I'll have much more time to help with this project :)

**Comment by limonte** [comment]
Roger, I'll handle it :+1: Congrats with changes in your life, changes are always for the better!

**Comment by zenflow** [comment]
Thanks :) Yes I am truly very excited for the next stage :D

**Comment by limonte** [comment]
Fixed in v7.0.9, thanks for reporting @Barterr!
