### ISSUE TITLE
typescript defination

### ISSUE THREAD

**Issue by zoinkydoink** [limonte/sweetalert2#76]
I have installed the sweetalert.typescripte.definatelytyped but I get error on cancelButtonColorwhen this is used
`
    swal({
        title: 'Are you sure?',
        text: msg,
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#dd6b55',
        cancelButtonColor: '#d44',
        confirmButtonText: 'Yes, remove it!',
        cancelButtonText: 'No, keep it',
        closeOnConfirm: false
    },
       function (isConfirm) {
           if (isConfirm) {
               callbackFunction(id);
           }

       });`

I assume the typescript i have is for the old sweetalert, but where is one for this one (sweetalert2)?

**Comment by limonte** [comment]
There's no support for this currently in swal2, please feel free to contribute!

PS. in future, please preview your posts and fix mistakes and markdown styling before posting.
