### ISSUE TITLE
Focus on buttons

### ISSUE THREAD

**Issue by KingRial** [limonte/sweetalert2#765]
With the latest version it seems I am unable to use correctly the `focusCancel` and `focusConfirm` options.

Sometimes the popup won't show the focused button.

To reproduce the problem you just need to:
- Access https://limonte.github.io/sweetalert2/
- Open the console
- Launch the following code:
```javascript
swal({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!',
  focusCancel: true
})
```
The Cancel button is never focused.
On previous versions the behaviour was correct.

**Comment by limonte** [comment]
Works fine: https://jsfiddle.net/ad3quksn/263/

Keep in mind that with opened console focus will always be in the console, not in the document.
