### ISSUE TITLE
Strange behavior of buttons

### ISSUE THREAD

**Issue by MSkraburski** [limonte/sweetalert2#768]
I face a strange situation depicted below:

![bez tytulu](https://user-images.githubusercontent.com/31694615/33992890-95e667e6-e0d4-11e7-94b7-f9c3c4ab308d.png)

The button styling is somehow influenced by other part of the code even though I did not apply external CSS or modify it in any way so I wonder what might have caused that issue and how to solve it?

**Comment by limonte** [comment]
>For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/ad3quksn/249/

See [CONTRIBUTING.md](https://github.com/limonte/sweetalert2/blob/master/.github/CONTRIBUTING.md)

**Comment by MSkraburski** [comment]
https://jsfiddle.net/80k8z3sn/4/

**Comment by limonte** [comment]
https://jsfiddle.net/80k8z3sn/5/ works nicely

**Comment by MSkraburski** [comment]
I got 
`.swal2-modal .swal2-styled + .swal2-styled {
    /* margin-top: 15px; */
}`

active from `sweetalert2.scss` and that causes the problem. Is there any other way to overwrite it other then to recompile .scss file? Koala does not compile .scss files on my laptop due to some kind of bug
