### ISSUE TITLE
2 or more modals at the same time

### ISSUE THREAD

**Issue by enforb** [limonte/sweetalert2#770]
Hallo.
Is there any way to open 2 or more swal modals at the same time?

**Comment by toverux** [comment]
Hello @enforb,

No, it is not possible to show more than one modal at a time, by design. See my comment here: https://github.com/limonte/sweetalert2/issues/606#issuecomment-325697220

**Comment by Aldo-f** [comment]
And something like a que? 

We have the possibility to style the alert like a toast..
So displaying multiple toasts would be nice.


![](https://i.imgur.com/ZsVIyf6.gif)

https://codepen.io/AldoF/pen/PoOOpmx
