### ISSUE TITLE
Can't tried

### ISSUE THREAD

**Issue by AchmadGozali8** [limonte/sweetalert2#772]
I try sweetalert from https://limonte.github.io/sweetalert2/ , but i get error on my web console `SyntaxError: missing ) in parenthetical`, i use **Firefox ESR 45.2.0**. thnk u

**Comment by limonte** [comment]
The examples page is using async/await functions which were added to Firefox 52 and greater.

The plugin by itself should work well in Firefox 45, you can check that here: https://jsfiddle.net/ad3quksn/249/
