### ISSUE TITLE
More modal at the same time - FIXED!

### ISSUE THREAD

**Issue by enforb** [limonte/sweetalert2#775]
Really easy fix!!!!

In function **init(params)**
`
var c = getContainer();
if (c) {
//            c.parentNode.removeChild(c); //this row must be disabled
}
`

In function **getContainer()** just **':last-child'** selector was added.
`var getContainer = function getContainer() {
        return document.body.querySelector('.' + swalClasses.container + ':last-child');
    };`

That's all... 

Enjoy :)

**Comment by limonte** [comment]
https://github.com/limonte/sweetalert2/issues/606#issuecomment-325697220

**Comment by RicMBM** [comment]
where's the Init(params)?
Im trying to build 2 modals, 1 for doing a ajax request but if clicked cancel calls a second modal if clicked on Accept close both modals but if clicked cancel call the first modal for continue

**Comment by itorian** [comment]
You don't need that, here's another way:

var modals = [];

// birth modal
if (!validateBirth(data)) {
  modals.push({title: 'title1', text: 'text1', ... });
}

// email modal
if (!validateEmail(email)) {
  modals.push({title: 'title2', text: 'text2', ... });
}

swal.queue(modals);
