### ISSUE TITLE
'target' option not working

### ISSUE THREAD

**Issue by Tsyklop** [limonte/sweetalert2#777]
My code:

```
let types = {
   1: 'qwerty',
   2: 'qwerty1'
}

swal({
      title: 'Select type',
      input: 'select',
      inputOptions: types,
      inputPlaceholder: 'Select type',
      target: $(content),
      showCancelButton: true,
       confirmButtonText: 'Confirm',
      cancelButtonText: 'Cancel',
      reverseButtons: true
}).then((result) => {
      if (result.value) {

      }
})
```

And alrt openned in `body` tag. But i set `target` is `$(content)`

sweetalert2 v7.1.2

**Comment by limonte** [comment]
1. There's a warning in your dev console:

![](https://i.imgur.com/GwUkGoY.png)

2. http://youmightnotneedjquery.com/

3. `target: $(content)` -> `target: content`

4. if you absolutely can't survive w/o jQuery: `target: $(content)` -> `target: $(content)[0]`
