### ISSUE TITLE
a error of webpage index

### ISSUE THREAD

**Issue by zhangenming** [limonte/sweetalert2#778]
Uncaught TypeError: Cannot read property 'slice' of undefined
at HTMLButtonElement.$.on ((index):1777)

  $('.modal-types button').on('click', () => {   //because of arrow function the this value is window
    var type = $(this).attr('class').slice(5)
    swal(type + '!', '', type)
  })

**Comment by limonte** [comment]
Fixed, thanks a lot for reporting @zhangenming!
