### ISSUE TITLE
SweetAlert2 for MeteorJS

### ISSUE THREAD

**Issue by mayvn10** [limonte/sweetalert2#78]
Hi:

Can you port this into a Meteor Package?

Like the original SweetAlert:
https://atmospherejs.com/kevohagan/sweetalert
https://github.com/kevohagan/meteor-sweetalert/

Thanks in advance!

**Comment by limonte** [comment]
I'm not familiar to Meteor. Contributions are welcome!

**Comment by limonte** [comment]
https://github.com/patrickml/swal/

**Comment by limonte** [comment]
Meteor 1.3 now have direct support for npm packages

**Comment by thearabbit** [comment]
I work fine for me
```js
npm install --save sweetalert2

// Import
import swal from 'sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';
```
