### ISSUE TITLE
Adding component in swal body

### ISSUE THREAD

**Issue by m-bryo** [limonte/sweetalert2#790]
I would want to add a component on the swal, but I get a blank display

**Comment by limonte** [comment]
Could you please describe which component you're trying to add?

**Comment by m-bryo** [comment]
I have a component <user-form></user-form> which can be used for creating a new user.

If i do
`this.$swal({
          'title': 'Create new customer ',
          'html': '<user-form></user-form>'
        })`
The swal does not have a body

**Comment by zenflow** [comment]
@m-bryo Is `<user-form>` a [Web Component](https://developer.mozilla.org/en-US/docs/Web/Web_Components)? Or are you using a framework, like Angular, React, etc.?

**Comment by m-bryo** [comment]
I'm using vuejs

**Comment by zenflow** [comment]
@m-bryo That is pretty critical information. 

This project alone will not render Vue components as content. [vue-sweetalert](https://github.com/lishengzxc/vue-sweetalert) might support it, or be willing to support it. Or you could create your own thin wrapper. 

I don't know much about Vue but it should be possible using `swal.getContent` to get the content element, and instantiating your Vue component on it, all inside an `onOpen` handler.

In any case:

>This isn't the right place for Angular- or any other framework related questions.
> https://stackoverflow.com/questions/ask
