### ISSUE TITLE
Feature request: onCloseEnd parameter

### ISSUE THREAD

**Issue by FinesseRus** [limonte/sweetalert2#794]
The `onCloseEnd` parameter should accept a callback. SweetAlert should fire the callback when the close animation finishes and the modal window has become or just about to become not visible.

This parameter can be useful when React is used to render a modal window content. Today we use the `onOpen` callback to render a content and the `onClose` to destroy it. The `onClose` callback is fired when the close animation starts therefore the close animation is not smooth (the content disappears before the animation finishes). [Demo on CodePen](https://codepen.io/TheFinesse/pen/opeNOa?editors=1010). Using `onCloseEnd` could solve it.

**Comment by limonte** [comment]
> SweetAlert should fire the callback when the close animation finishes and the modal window has become or just about to become not visible.

`onClose` actually fires after close animation finishes.

The live example you attached is totally fine, the closing animation is currently broken.

The issue will be fixed in https://github.com/limonte/sweetalert2/issues/761
