### ISSUE TITLE
Sweetalert2 keep adding margin-right to body after closed

### ISSUE THREAD

**Issue by blstechds** [limonte/sweetalert2#797]
Using the following code to show the message after a record is updated but after closing the Sweet Alert dialog/modal, it keeps on adding the "_margin-right_" to _body_.
```
swal({
    title: '',
    text: 'Record updated',
    type: 'success'
});
```

**Comment by limonte** [comment]
>For bug reports, please include a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.

>JSFiddle template: https://jsfiddle.net/ad3quksn/249/

See [CONTRIBUTING.md](https://github.com/limonte/sweetalert2/blob/master/.github/CONTRIBUTING.md)

**Comment by limonte** [comment]
Attach the jsfiddle if you thinks that the issue is valid and should be reopened.
