### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by fcremo** [limonte/sweetalert2#8]
With sweetalert2 it's impossible to use a custom HTML as documented.
Compare 
https://github.com/t4t5/sweetalert/blob/master/lib/sweet-alert.js#L571
https://github.com/limonte/sweetalert2/blob/master/lib/sweetalert2.js#L548
I will try to make a pull request as soon as I can

**Comment by limonte** [comment]
Can you please give an example of using SA2 and custom HTML isn't working as expected.

**Comment by fcremo** [comment]
```js
swal({  title: 'Confirm?',
        text:   '<textarea class="form-control" id="notes" placeholder="Notes"></textarea>',
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        html: true,
        cancelButtonColor: '#d33',
        confirmButtonText: 'Si',
        cancelButtonText: 'No',
    },
    function() {
        alert('other ajax stuff');
    }
);
```

**Comment by limonte** [comment]
You should use SA2 like this:

```js
swal({  title: 'Confirm?',
        html:   '<textarea class="form-control" id="notes" placeholder="Notes"></textarea>',
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Si',
        cancelButtonText: 'No',
    },
    function() {
        alert('other ajax stuff');
    }
);
```

Here's the example from the [documentation](https://limonte.github.io/sweetalert2/):

```js
swal({
            title: 'HTML example',
            html:
              'You can use <b>bold text</b>, ' +
              '<a href="//github.com">links</a> ' +
              'and other HTML tags'
        }); 
```

**Comment by fcremo** [comment]
I see. I realize I filed a non-existing issue because I inadvertently looked at the documentation of t4t5/sweetalert and assumed the intended behavior was the same. I guess I should be dismissed with a RTFM then. I'm sorry :)
