### ISSUE TITLE
Off-placed text on basic swal() - conflict with ...bootstrap or something?

### ISSUE THREAD

**Issue by dylanh724** [limonte/sweetalert2#80]
https://i.imgur.com/4D4NiSI.png

See this screenshot, I just call swal("title", "text"); and the text seems to be floating right. I tried using html instead and center text, but it still wants to stay right. 

Bootstrap conflict or something (exported from Webflow)? I placed the css for swal2 BELOW everything else, though, shouldnt swal override?

**Comment by limonte** [comment]
I have no idea which libraries you're using beside swal2.

In future issues please try to reproduce issues by using jsfiddle.
