### ISSUE TITLE
Buttons are not centered

### ISSUE THREAD

**Issue by jbprat** [limonte/sweetalert2#81]
It seems that line 65 of the scss file need to be changed to center the validation button.
'''
button.styled {
     color: #fff;
     border: 0;
     box-shadow: none;
     font-size: 17px;
     font-weight: 500;
     border-radius: 5px;
     padding: 10px 32px;
-    margin: 0 5px;
+    margin: 0 auto;
     cursor: pointer;
'''

**Comment by limonte** [comment]
what is validation button?

**Comment by jbprat** [comment]
Confirmation buttons.

**Comment by limonte** [comment]
As I can see button are centered corectly. Can you please make jsfiddle with this issue?

**Comment by jbprat** [comment]
I'll check the issue and make a jsfiddle

**Comment by limonte** [comment]
reopen when you make jsfille example

**Comment by jbprat** [comment]
Okay !
