### ISSUE TITLE
Support fot type:checkbox

### ISSUE THREAD

**Issue by jkjha** [limonte/sweetalert2#82]
Hi, I know I can create a model for below requirement but it will be a very nice to have this feature if we can support type: checkbox can be supported. 

I tried adding a checkbox using the HTML tag also but it doesn't displays in pop-up.

Can any one please help me here:

`swal({   
title: "Are you sure?",   
text:" <form><input type='checkbox' name='vehicle' value='Bike'>I have a bike<br></form> 
        Workload will be validated by you for merge! 
       <div class='text-danger'>" +wl_name+ "</div>" ,
showCancelButton: true,  
confirmButtonColor: "#DD6B55",   
confirmButtonText: "Yes, validate it!",   
cancelButtonText: "No, cancel pleaase!", 									 closeOnConfirm: false,   
closeOnCancel: false, 
html:true , 
showLoaderOnConfirm: true}`

**Comment by jkjha** [comment]
I have also stackoverflow question for same, if anyone can help here: http://stackoverflow.com/questions/36400203/input-type-checkbox-in-html-text-not-working

**Comment by limonte** [comment]
@jkjha can you please format the code example so it can be readable for humans? :)

**Comment by jkjha** [comment]
Sorry.. @limonte, I have edited the code now.. but newline not working in the code. Please let me know if I need to format it more.

**Comment by limonte** [comment]
You're using swal2 plugin, not original swal

HTML was introduced here before it was in swal and there's a difference in usage. Instead of

```javascript
  text: "<input type='checkbox' name='vehicle' value='Bike'>",
  html: true
```

you shoud use

`
  html: "<input type='checkbox' name='vehicle' value='Bike'>",
`

**Comment by jkjha** [comment]
ooh yes.. I started with swal and ended to swal2 , so missed that. Anyway I have created a plunkr where I tried to add this and is working fine. But dont know why it is not working with my app. May be some properties are being overwritten. Here is the plunkr. https://plnkr.co/edit/WsCWEFIhRpAkcvRIH0IP?p=preview

Thanks for your prompt response. I will clsoe this ticket in some time.

**Comment by limonte** [comment]
Hi @jkjha I have an update here. I added `input: 'checkbox'` parameter in swal2 to make modal window wich checkbox. Take a look at example: http://limonte.github.io/sweetalert2/#checkbox

**Comment by Arun-Clarisco** [comment]
This is Swal.fire, i am using this code in my react js but checkbox not woking i cant checked and unchecked
any solution for this

import Swal from 'sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';

const { value: confirmDeletion, isConfirmed } = await Swal.fire({
                title: "Confirm Deletion",
                text: "Are you sure you want to delete this user? Doing so will purge this user from DSrummy without any notifications to the user. User’s rewards and achievements will also be permanently deleted",
                input: "checkbox",
                inputValue: 0,
                inputPlaceholder: `I'm sure, delete this user.`,
                confirmButtonText: `Delete&nbsp;<i class="fa fa-trash"></i>`,
                cancelButtonText: `Cancel`,
                showCancelButton: true,
                preConfirm: (result) => {
                    if (!result) {
                        Swal.showValidationMessage("You need to acknowledge this action cannot be undone");
                    }
                    return result;
                }
            });

            if (isConfirmed && confirmDeletion) {
                // Code to delete the item goes here
                Swal.fire("User deleted successfully");
            } else {
                Swal.fire("Action cancelled");
            }
