### ISSUE TITLE
[Suggestion] - Support multi forms

### ISSUE THREAD

**Issue by Silvester20** [limonte/sweetalert2#85]
Is it possible to add mulitple forms in a alert?
So for example: The first form has a text input and 1 button. When you click this button the next form with a another input shows.

**Comment by limonte** [comment]
All custom fucntionality could be done by using `html` parameter and project'related JS scripts.

**Comment by Silvester20** [comment]
Yes I understand that. But my suggestion was if you could add a multi-form alert.For example, I mean something like this: http://thecodeplayer.com/walkthrough/jquery-multi-step-form-with-progress-bar

I think this would be a nice feature to have in SweetAlert 2.

**Comment by dimsav** [comment]
As far as I can see this is now possible. See [here](https://sweetalert2.github.io/) under "Chaining modals (queue) example"
