### ISSUE TITLE
Use better naming in CSS

### ISSUE THREAD

**Issue by grandnasty** [limonte/sweetalert2#86]
Previously Sweetalert used prefixes such as .sa-icon for elements. In Sweetalert2 .icon is used directly.

This is not great since it clashes with a lot of other frameworks that use .icon already.

Would be better to keep SA2 to have a prefix before all CSS elements.

**Comment by limonte** [comment]
Thank you @grandnasty for submitting this issue!

Done in [v1.0.1](https://github.com/limonte/sweetalert2/releases/tag/v1.0.1)

Please pay attention to breaking change in [v1.0.0](https://github.com/limonte/sweetalert2/releases/tag/v1.0.0) before updating swal2 to v1.0.1
