### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by maxicms** [limonte/sweetalert2#87]
I can not understand why there was this error on other sites all running well and one is such a mistake.

**Comment by limonte** [comment]
can you please reproduce this issue in jsfillde?

**Comment by maxicms** [comment]
В этом и проблема на jsfiddle все работает переписал код на  
```
swal({
            title: 'Вы уверены?',
            text: 'Ваша запись будет перемещена в архив!',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#dd6b55',
            cancelButtonColor: '#999',
            confirmButtonText: 'Да, переместить!',
            cancelButtonText: 'Нет, отменить',
            closeOnConfirm: false
        }, function() {
```
now works

**Comment by limonte** [comment]
This issue most probably related to [v1.0.0](https://github.com/limonte/sweetalert2/releases/tag/v1.0.0) release which have a breaking change - from now swal2 is using promise instead of callback:

From v1.0.0 your case should be changed from:

```javascript
swal({
  ...
}, function() {
```

to

```javascript
swal({
  ...
}).then(function() {
```

PS. let's use English on GitHub :)

**Comment by limonte** [comment]
Thank you @maxicms for reporting this!

I finally succeed to reproduce this issue and fixed it in [v1.0.5](https://github.com/limonte/sweetalert2/releases/tag/v1.0.5)

**Comment by ilentt** [comment]
Hi @limonte ,

I have similar this bug too, here is my code

```
function myFunction(parameter)  {
	if (something is true) {
		// to do something
	} else {
		swal({
			// show error popup
			title: 'ERROR',
			text: 'Something went wrong',
			type: 'error',
			confirmButtonColor: '#3085d6',
			confirmButtonText: 'OK'
		}).then(function () {
			// when click ok then redirect back
			location.href = "/";
		})
	}
}
```

I have try to fix by insert lib Polyfill at the header follow [this guide](http://stackoverflow.com/questions/36611575/uncaught-typeerror-cannot-read-property-then-of-undefined-using-sweet-alert) but can not solve this  issue.

I  usage sweetalert2 version 1.1.3, jquery  version 3.1 and mixed all in visualforce page

**Comment by birjolaxew** [comment]
@ilentt Which browser are you testing this on? Your code seems to work fine when I test it (Firefox 51.0.1)

**Comment by ilentt** [comment]
@birjolaxew  I testing on Chrome Version 56.0.2924.87 (64-bit)

**Comment by birjolaxew** [comment]
@ilentt The info you've given seems to suggest you're using SweetAlert, not SweetAlert2. Could you please check to make sure?

**Comment by ilentt** [comment]
@birjolaxew 
Oh! so sorry, Birjolaxew I really using SweetAlert instead of SweetAlert2 as I said. So could you please give me a suggest to solve this issue.
Thank you.

**Comment by limonte** [comment]
https://github.com/t4t5/sweetalert/issues
