### ISSUE TITLE
block process on alert ?

### ISSUE THREAD

**Issue by smolleyes** [limonte/sweetalert2#89]
hi

i use swal in a _.each loop, is it possible to act like a real alert and so block the loop until i clicked the confirm or cancel button ? now it s just replacing the content of the error dialog so i only see the last "error" in my loop not each errors :/

thanks

**Comment by limonte** [comment]
Hi @smolleyes !

Thanks for submitting this issue! After some thinking I'm still not sure if this functionality really needed in swal2. Could you please describe you use case so I can better understand it.

Personally, as user, I'd rather not to have loop of popups. In Chrome for exaple you have `prevent this page from creating additional dialogs` checkbox.

![](https://i.imgur.com/H2Y1PXj.png)

**Comment by limonte** [comment]
reopen if needed
