### ISSUE TITLE
Custom buttons

### ISSUE THREAD

**Issue by xiio** [limonte/sweetalert2#90]
it would be nice to add custom buttons to sweetalert modal. Doing it with HTML not work property with onclick etc. :/ 
ex:
swal({
  ...,
  customButtons: [
    new CustomButton('Google', onClickCallback),
    new CustomButton({ 'text': 'Bing', className: 'bing-btn', onClick: function(ev){  } })
  ]
});

**Comment by limonte** [comment]
> Doing it with HTML not work property with onclick

I'm using swal2 custom HTML modals with onclick handlers on my projects projects and all works fine.

Too custom to be in swal2 by default.
