### ISSUE TITLE
Promise is not resolved if you click confirm button in less than 0.5 seconds

### ISSUE THREAD

**Issue by rokpok** [limonte/sweetalert2#93]
If you click confirm button in less than 0.5 seconds, promise is not resolved. Part of the code that seems to be causing the problem is in function `openModal()`:

`setTimeout(function() {
      addClass(modal, 'visible');
 }, 500);`

Because of that `modalIsVisible` is set to `false` in `onButtonEvent()` and promise is not resolved. Is there any reason to add visible class to the modal only after 500ms?

**Comment by limonte** [comment]
Thank you @rokpok  for reporting this issue!

Fixed in [1.2.1](https://github.com/limonte/sweetalert2/releases/tag/v1.2.1)

**Comment by rokpok** [comment]
No problem. Thank you for quick fix.
