### ISSUE TITLE
jQuery example doesn't work

### ISSUE THREAD

**Issue by jbdemonte** [limonte/sweetalert2#94]
Click on jQuery HTML example on https://limonte.github.io/sweetalert2/

You'll get [object Object]

It would be really useful to be able to provide an HTML element, not just a string of code

**Comment by limonte** [comment]
Nicely done @jbdemonte, thank you!

**Comment by limonte** [comment]
[1.2.2](https://github.com/limonte/sweetalert2/releases/tag/v1.2.2)
