### ISSUE TITLE
'swal' is undefined when shimming the window object

### ISSUE THREAD

**Issue by jdcrensh** [limonte/sweetalert2#97]
When the window object is shimmed for sweetalert2, the `swal` function becomes undefined.

My use case is with Webpack and that I'm importing sweetalert2 in code from multiple modules. After the first module imports it, all following modules that import it get undefined.

My workaround was to use legacy-loader to shim the window object around sweetalert2. This fixed the first problem, but doing so made `swal` references (not `window.swal`) become undefined.

I haven't looked into any solutions for the initial problem I had... but the second problem should be easily fixable by locally scoping the `swal` variable (in addition to the global object).

**Comment by limonte** [comment]
I'm not sure I can help you to fix this issue. Any help would be much appreciated.

**Comment by jdcrensh** [comment]
:+1:
